chanzuckerberg/single-cell-data-portal

- Makefile
- requirements-dev.txt
This is for running the linter and formatter locally
> Adding Makefile to run linter and formatter

- .github/workflows/lint.yml
> rename action to flake8

- infra/envs/test/Makefile
- infra/envs/test/main.tf
- infra/envs/test/terraform.tfvars.example
- infra/envs/test/variables.tf
This is a test environment for running experiments. Initially, @bmccandless will be using this environment to parallelize and speed up the migration script from DCP 1.0 to DCP 2.0
> test terraform env

- README.md
- dcp_prototype/frontend/Makefile
- infra/envs/dev/main.tf
- infra/modules/frontend/browser/static_website.tf
- infra/modules/frontend/browser/variables.tf
- Suggesting we use STAGE environment variables to direct the deployment of code to the correct infra.
- Adding terraform to deploy an s3 bucket for hosting a static website.
closes #67
> Adding deployment for browser frontend.

- dcp_prototype/frontend/src/globals.js
> Change API backend target

- dcp_prototype/backend/browser/Makefile
- dcp_prototype/backend/browser/api/Makefile
- dcp_prototype/backend/ledger/Makefile
- dcp_prototype/frontend/Makefile
- infra/Makefile
- infra/envs/dev/Makefile
- infra/envs/test/Makefile
Context if needed: https://stackoverflow.com/questions/2145590/what-is-the-purpose-of-phony-in-a-makefile
> .PHONY all the Makefiles

- dcp_prototype/frontend/src/components/projectOverview.js
Currently the demo project overview page has this: `Analysis Protocols:smartseq2_v2.3.0smartseq2_v2.4.0`
> Comma separate protocols and species

- dcp_prototype/frontend/src/components/projectsList.js
- dcp_prototype/frontend/src/components/projectsListHeading.js
- added Organ column to project list page
- Assays -> Assay to match design
- Project title -> Project name to match design
> Add organ to project list page

- .github/workflows/push-tests.yml
- Makefile
- README.md
- requirements-dev.txt
To help us keep our code well-tested, report metrics of how well our modules are covered by tests.
**TODO**: Add codecov for javascript. Codecov for node requires a test suite to generate a report and the frontend has no tests, so it's not possible to add them at this time.
> Add codecov for code coverage

- Makefile
- infra/envs/dev/main.tf
- infra/envs/test/main.tf
- infra/modules/backend/browser/rds.tf
- infra/modules/backend/browser/secrets.tf
- infra/modules/backend/ledger/rds.tf
- infra/modules/backend/ledger/secrets.tf
- infra/modules/frontend/browser/static_website.tf
> [EASY] run fmt on terraform directories

- infra/envs/dev/Makefile
- infra/envs/test/Makefile
> [EASY] Using ACCOUNT_ID variable in make file

- dcp_prototype/backend/scripts/convert_metadata.py
- dcp_prototype/backend/scripts/enloom.py
enloom.py converts the GEO GSE60361 matrix to a loom with dcp/2 metadata
convert_metadata.py does the same for dcp/1 matrices from the matrix service.
Partially cłösës #176.
> Add a couple scripts used to prepare demo matrices

- dcp_prototype/frontend/src/components/footer.js
- dcp_prototype/frontend/src/components/header.js
- dcp_prototype/frontend/src/components/layout.css
- dcp_prototype/frontend/src/components/layout.js
- dcp_prototype/frontend/src/components/projectsList.js
- dcp_prototype/frontend/src/components/projectsListHeading.js
- dcp_prototype/frontend/src/components/seo.js
- dcp_prototype/frontend/src/components/theme.js
- dcp_prototype/frontend/src/pages/index.js
I have updated the front-end code to look like the design, for the list-of-projects page.
> Front-end styling code to list-of-projects page

- dcp_prototype/backend/browser/api/app.py
- dcp_prototype/backend/browser/code/common/browser_orm.py
- dcp_prototype/backend/browser/code/common/db_utils.py
- dcp_prototype/backend/browser/scripts/load_artifact.py
- dcp_prototype/backend/browser/scripts/mock.py
- dcp_prototype/frontend/src/components/exploreData.js
- dcp_prototype/frontend/src/components/footer.js
- dcp_prototype/frontend/src/components/header.js
- dcp_prototype/frontend/src/components/layout.css
- dcp_prototype/frontend/src/components/layout.js
- dcp_prototype/frontend/src/components/projectOverview.js
- dcp_prototype/frontend/src/components/projectsList.js
- dcp_prototype/frontend/src/components/projectsListHeading.js
- dcp_prototype/frontend/src/components/seo.js
- dcp_prototype/frontend/src/components/theme.js
- dcp_prototype/frontend/src/globals.js
- dcp_prototype/frontend/src/pages/index.js
These changes:
- point the frontend to the API in the new AWS account
- update the API and UI to reflect the new DB schema
- deliver a [first look](http://dcp-site-deployment-dev.s3-website-us-east-1.amazonaws.com/) at the E2E 3/20 demo
Adding now:
Known bug:
Closes #199
> Update browser API and frontend to reflect new db schema

- dcp_prototype/backend/browser/api/app.py
- dcp_prototype/backend/browser/code/common/browser_orm.py
- dcp_prototype/backend/browser/code/common/db_utils.py
- dcp_prototype/backend/browser/scripts/load_artifact.py
- dcp_prototype/backend/browser/scripts/mock.py
- dcp_prototype/frontend/src/components/exploreData.js
- dcp_prototype/frontend/src/components/footer.js
- dcp_prototype/frontend/src/components/header.js
- dcp_prototype/frontend/src/components/layout.css
- dcp_prototype/frontend/src/components/layout.js
- dcp_prototype/frontend/src/components/projectOverview.js
- dcp_prototype/frontend/src/components/projectsList.js
- dcp_prototype/frontend/src/components/projectsListHeading.js
- dcp_prototype/frontend/src/components/seo.js
- dcp_prototype/frontend/src/components/theme.js
- dcp_prototype/frontend/src/globals.js
- dcp_prototype/frontend/src/pages/index.js
These changes:
1. update the browser ETL to consume a JSON artifact
1. update the browser DB schema in response to the latest [artifact schema](https://github.com/HumanCellAtlas/dcp-prototype/blob/master/dcp_prototype/backend/artifact_manager/schemas/v0.0.0.json)
In future iterations, artifact schema changes will not require a DB schema change (2) as these requirements should be driven by user feedback and browser requirements.
Followed by #210
> Update db schema and browser ETL to consume JSON artifact

- dcp_prototype/frontend/src/components/header.js
> Resize logo in header

- dcp_prototype/frontend/package-lock.json
- dcp_prototype/frontend/package.json
I couldn't start the local dev server, so I upgraded gatsby and refreshed `package-lock.json`.
Seems to work now.
> Upgrade client dependencies

- dcp_prototype/backend/browser/api/app.py
- dcp_prototype/backend/browser/code/common/browser_orm.py
- dcp_prototype/backend/browser/scripts/load_artifact.py
- dcp_prototype/backend/browser/scripts/mock.py
- dcp_prototype/frontend/src/components/exploreData.js
- determines cxg-supported projects via `cxg_enabled` field to be supplied via Artifact (cc @bmccandless)
- fixed broken S3 paths (matrix and cxg objects are identified by the project's `label` name)
- updated DB schema and API accordingly
Fixes #218
> Fix broken cellxgene links

- dcp_prototype/frontend/.env.development
- dcp_prototype/frontend/src/components/exploreData.js
- dcp_prototype/frontend/src/globals.js
- dcp_prototype/frontend/src/pages/index.js
- dcp_prototype/frontend/src/pages/project.js
Also updated `.env.production` in the `dev` S3 bucket
Closes #223
> Parameterize frontend environment specific variables

- Makefile
- dcp_prototype/backend/browser/api/app.py
- dcp_prototype/backend/browser/code/common/db_utils.py
- dcp_prototype/backend/browser/code/common/s3_utils.py
- requirements-dev.txt
- tests/dcp-prototype/__init__.py
- tests/dcp-prototype/backend/browser/code/common/test_db_utils.py
- tests/dcp-prototype/backend/browser/code/common/test_s3_utils.py
- #235 failed on CI
- reverted in #242 
- this PR ships the tests + fix (missing dependencies)
> Fix browser backend unit tests

- dcp_prototype/frontend/src/contexts/auth0Context.js
> User is returned to last page after logout

- dcp_prototype/frontend/.env.development
Using the new auth0 domain. Once this is approved I will update the dev environment to use the new domain.
> new auth0 domain

- dcp_prototype/frontend/src/pages/project.js
> Wait for Auth0 to load before check if authorized

- dcp_prototype/backend/browser/scripts/generate_test_artifact.py
- tests/unit/dcp-prototype/backend/browser/fixtures/test_artifact.json
- simple script to generate a bite-sized JSON artifact from a real one in S3
- generated artifact stored as a test fixture for unit tests
Relates to #237
> Generate test JSON artifact

- dcp_prototype/backend/browser/api/app.py
- dcp_prototype/frontend/src/components/exploreData.js
- dcp_prototype/frontend/src/pages/project.js
We weren't actually sending the token to the backend. This fixes that.
- Also sending the token when we request the actual download
> The Frontend Sends Auth Token to Backend

- dcp_prototype/backend/browser/api/app.py
- dcp_prototype/backend/browser/code/common/db_utils.py
- dcp_prototype/backend/browser/code/common/s3_utils.py
- tests/unit/dcp-prototype/backend/browser/code/common/test_db_utils.py
- Update `db_utils.py` and `test_db_utils.py` to run against the in-memory DB
Closes #237
> Update DB unit tests to hit test DB

- infra/envs/staging/Makefile
- infra/envs/staging/main.tf
- infra/envs/staging/terraform.tfvars.example
- infra/envs/staging/variables.tf
- infra/modules/backend/browser/api-gateway.tf
> Create browser staging deployment via terraform

- README.md
- dcp_prototype/backend/browser/README.md
- dcp_prototype/frontend/README.md
Updated browser frontend and backend READMEs to setup local development environments and to reflect `staging`
Closes #265
> Updated browser frontend and backend READMEs

- cloc/exclude.txt
- cloc/include.txt
- cloc/run.sh
I cherry picked the files and directories that are actually used for the browser frontend and backend. Is that ok?
Generated Report
```
github.com/AlDanial/cloc v 1.84  T=0.16 s (482.0 files/s, 145305.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                             4              0              0          18517
Python                          11            168            124           1131
JavaScript                      26             87             75           1052
HCL                             21            171             99            821
CSS …
```
> Script to generate cloc report

- data_portal_api.yml
> Converting design doc to openapi

- .gitignore
- browser/frontend/README.md
closes #330 
Also created a branch `backup-FE-pages` [here](https://github.com/chanzuckerberg/corpora-data-portal/tree/backup-FE-pages)!
PTAL! Thank you :D
> 330-cleanup-frontend

- browser/backend/Makefile
- browser/backend/README.md
- Adding instruction to README on how to deploy changes the backend.
- Updating the makefile with download-vars
> Updating deployment instructions

- corpora-api.yml
- data_portal_api.yml
Updating the corpora API to match the hight level architecture.
> Update corpora API

- .github/workflows/codeql-analysis.yml
https://securitylab.github.com/tools/codeql. Action automatically generated by GitHub.
> Enable CodeQL Scanning

- tests/unit/backend/corpora/common/test_authorizer.py
The auth0 test will only run when branches are pushed to master.
> Fixing auth tests

- backend/corpora/common/entities/entity.py
We decided that using the ABC doesn't give us much, with a lot of added complexity.
> Removed ABC from entity

- README.md
- backend/chalice/api_server/README.md
- docs/awscli.md
- docs/dev_flags.md
- frontend/README.md
> Clean up and organize existing docs

- Makefile
- backend/corpora/common/entities/entity.py
- backend/corpora/common/entities/project.py
- backend/corpora/common/utils/db_utils.py
- backend/corpora/common/utils/exceptions.py
- backend/scripts/create_db.py
- tests/__init__.py
- tests/unit/__init__.py
- tests/unit/backend/__init__.py
- tests/unit/backend/corpora/common/entities/test_project.py
- tests/unit/backend/corpora/fixtures/database/__init__.py
Closes #392 
New classes:
- `Entity` is an abstract base class that provides an interface for all application objects reading and writing from the DB. Interface overview:
- `get`: Public API to retrieve an object
- `_query`: Sub-routine of `get` - queries the DB
- ~`_parse`: Sub-routine of `get` - parses the db query result~
- `_load`: Sub-routine of `get` - instantiates the Entity from query results
- `list`: Public API to list objects
- `save`: Public API to write an object to the DB
- `Project` inherits from `Entity`
Testing:
- local Postgres instance running in Docker container
- test database is populated in `tests/unit/backend/corpora/fixtures/database/__init__.py`
> Implement Project application-level object

- backend/corpora/common/corpora_orm.py
- backend/corpora/common/entities/dataset.py
- tests/unit/backend/corpora/common/entities/test_dataset.py
- tests/unit/backend/corpora/fixtures/database/__init__.py
- Adding dataset application class
- Adding TransformBase to simplify transforming DBobjects
- Adding custom JSON encoder to handle dateTime object return from DB .
closes #393
> Create dataset application class

- backend/chalice/api_server/requirements.txt
- requirements.txt
This is to ensure the test environment matches actual
> [EASY] import requirements from chalice app

- .github/workflows/push-tests.yml
- backend/chalice/api_server/Makefile
- tests/__init__.py
- tests/unit/backend/__init__.py
- tests/unit/backend/chalice/__init__.py
- tests/unit/backend/chalice/api_server/__init__.py
- tests/unit/backend/chalice/api_server/test_app.py
This is will be used for the testing the corpora API. ChaliceTestHarness is recycled code from [test code](https://github.com/HumanCellAtlas/fusillade/blob/b5ec9ed8fa3a45fc0f449ed01b828c2bbafc80a5/tests/infra/server.py#L9) from Fusillade.
> chalice test harness

- .github/workflows/push-tests.yml
- backend/chalice/api_server/Makefile
- backend/chalice/cloudfront_invalidator/Makefile
- tests/functional/backend/corpora/test_api.py
Fixing tests to run with single-cell-infra assumed roll and module/corpara/cicd 
blocked by https://github.com/chanzuckerberg/single-cell-infra/pull/118
Fixed #438
> Fixing tests

- backend/chalice/api_server/app.py
Need to have a default value when pop from a dictionary otherwise an error is raised if the value is not present.
> [EASY] Fixing request/response logs

- backend/corpora/common/entities/dataset.py
- backend/corpora/common/entities/project.py
They do nothing, and were replaced by add_columns.
> [EASY] remove kwarg from create entity

- backend/config/corpora-api.yml
> Update API to return new schema fields.

- frontend/src/common/localStorage/get.ts
- frontend/src/common/localStorage/set.ts
Tested in prod build! It should work now 🙏 Thanks for flagging this!
> add guard clause for window object since SSR

- frontend/package-lock.json
- frontend/package.json
Per https://github.com/chanzuckerberg/corpora-data-portal/network/alert/frontend/package-lock.json/serialize-javascript/open, we need to update its version via updating `gatsby`
PTAL! Thank you!
> Update serialize javascript

- backend/chalice/api_server/Makefile
- backend/chalice/api_server/README.md
fixes https://github.com/chanzuckerberg/corpora-data-portal/issues/348
> docs: correcting deployment documentation

- .github/workflows/deploy-prod.yml
> ci: automatically deploy prod using github actions

- backend/config/corpora-api.yml
- backend/corpora/common/entities/project.py
- tests/unit/backend/chalice/api_server/test_v1_project.py
- Some the keys in the yaml didn't match the actual response
- links were missing link_name
- The DOI was getting put into a dict with the key 'title', but it is
not a title
- Marked required fields as required
> Fix parts of the API definition

- backend/chalice/api_server/README.md
- backend/config/auth0-secret-template.json
- backend/corpora/common/authorizer.py
- backend/corpora/common/corpora_config.py
- backend/corpora/lambdas/api/v1/authentication.py
- tests/unit/backend/chalice/api_server/test_v1_auth.py
Part of issue chanzuckerberg/corpora-data-portal#481
> Auth:  refresh token handling and test cases

- README.md
- backend/config/corpora-api.yml
- backend/corpora/lambdas/api/v1/authentication.py
- frontend/src/pages/index.tsx
- tests/functional/backend/corpora/test_api.py
- tests/unit/backend/chalice/api_server/test_v1_auth.py
- tests/unit/backend/chalice/api_server/test_v1_dataset.py
- tests/unit/backend/chalice/api_server/test_v1_project.py
- tests/unit/backend/chalice/api_server/test_v1_submission.py
Update path from `/v1/*` to `/dp/v1/*`
1. I just did a global replace lol Hopefully it works 😆
> thuang-593-update-api

- backend/corpora/common/corpora_config.py
some temporary debug code got left in during last commit.
> auth bug fix

- frontend/.prettierrc.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/common/entities.ts
- frontend/src/components/ProjectList/components/Dataset/components/MoreInformation/index.tsx
- frontend/src/components/ProjectList/components/Dataset/components/MoreInformation/style.ts
UPDATE (after deduping links):
> Add more information to corpora data portal.

- frontend/src/components/Footer/index.tsx
- frontend/src/components/Footer/style.ts
- frontend/src/components/ProjectList/components/Dataset/style.ts
- frontend/src/components/ProjectList/components/Heading/style.ts
> Add additional footer information and fix box shadow and remove last line from dataset list

- frontend/src/components/Header/style.ts
- frontend/src/components/Layout/style.ts
- frontend/src/components/ProjectList/common/layout.ts
- frontend/src/components/ProjectList/components/Dataset/components/MoreInformation/style.ts
- frontend/src/components/ProjectList/components/Dataset/components/ViewDataset/style.ts
- frontend/src/components/ProjectList/components/Dataset/index.tsx
- frontend/src/components/ProjectList/components/Dataset/style.ts
- frontend/src/components/ProjectList/components/Heading/style.ts
- frontend/src/components/common/HomepageLink/style.ts
- frontend/src/components/common/Logo/style.ts
- frontend/src/components/layout.css
Hello it's me, your friendly neighborhood moonlighting developer. Made a couple of small UI nits across the primary page, take a look when you get the chance.
Screenshot:
> Couple of UI nits

- frontend/src/configs/prod.js
Point at cloudfront distribution of apis in prod
> update api url

- frontend/src/common/entities.ts
- frontend/src/components/CreateCollectionModal/components/Content/components/AddLink/index.tsx
- frontend/src/components/CreateCollectionModal/components/Content/components/LinkInput/index.tsx
- frontend/src/components/CreateCollectionModal/components/Content/index.tsx
- frontend/src/components/layout.css
- frontend/src/views/Collection/index.tsx
- frontend/src/views/Collection/style.ts
@seve I rebased your commit on top of my latest Create Collection branch, so I was thinking maybe we can just merge your commit into my branch `thuang-651-create-collection-component`, and then `main` will get both once my PR is in?
The rationale is that there are a few things that my branch has that I think your commit can re-use, so it's easier to just cherry pick your commit on top of mine lol
Thank you!
> Thuang seve/649 create collection page

- frontend/src/components/CreateCollectionModal/components/Content/index.tsx
Update collection link keys with prefix `link_`
> thuang-update-collection-link-keys

- frontend/src/common/constants/routes.ts
- frontend/src/components/AppContainer/index.tsx
- frontend/src/components/CreateCollectionModal/components/Content/index.tsx
Proof that `/collections/:id/private` works!
> thuang-update-private-collection-url

- backend/corpora/lambdas/api/v1/authentication.py
> authentication path requires better error handling

- backend/corpora/common/authorizer.py
- backend/corpora/common/corpora_config.py
- oauth/users.json
- scripts/setup_dev_data.sh
We need to disable "verify_at_hash" for local dev.
> Fixes for local development & OAuth

- frontend/src/common/queries/auth.ts
- frontend/src/common/queries/common.ts
Adds cookies to `/userinfo` call. Hopefully this works! 🤞 
If so, I'll apply the same change to other API calls! Thank you!
> fix-fetch-api-cookies

- frontend/.eslintrc.js
- frontend/src/common/queries/common.ts
- frontend/src/components/CreateCollectionModal/components/Content/components/AddLink/index.tsx
- frontend/src/components/CreateCollectionModal/components/Content/components/Policy/components/DirectPersonalIdentifiers/index.tsx
- frontend/src/components/CreateCollectionModal/components/Content/components/Policy/components/DirectPersonalIdentifiers/style.ts
- frontend/src/components/CreateCollectionModal/components/Content/components/Policy/index.tsx
- frontend/src/components/CreateCollectionModal/components/Content/components/Policy/style.ts
- frontend/src/components/common/theme.ts
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/22
Updated the copy per [ticket](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/22) "final policy" items:
UPDATE (11/18):
> thuang-update-create-collection-policy

- backend/chalice/api_server/app.py
- backend/chalice/api_server/requirements.txt
- frontend/src/common/queries/auth.ts
- frontend/src/common/queries/collections.ts
- frontend/src/common/queries/common.ts
Part 2 adds `include` to collections related API calls too! Thank you!
> thuang-fix-fetch-api-cookies PART 2

- backend/corpora/common/entities/dataset.py
- backend/corpora/common/entities/entity.py
- tests/unit/backend/corpora/common/entities/test_dataset.py
- tests/unit/backend/corpora/common/entities/test_entity.py
This is needed to update the dataset row after is has been processed by the upload service.
> Add update to dataset

- backend/corpora/common/entities/dataset.py
- backend/corpora/common/entities/entity.py
- tests/unit/backend/corpora/common/entities/test_collection.py
- tests/unit/backend/corpora/common/entities/test_dataset.py
- tests/unit/backend/corpora/dataset_processing/test_process.py
- tests/unit/backend/utils.py
Also run the docker process tests for the first time.
> Turn entity tests back on and fix them

- frontend/src/components/Collections/components/Dataset/components/ViewDataset/index.tsx
Actually this runtime error is breaking the app completely lol PTAL! Thank you!
> fix-fe-dataset

- frontend/src/configs/staging.js
Remove trailing `/`, since it's not needed 😄 Thank you!
> thuang-fix-staging-config-url

- backend/corpora/common/upload_sfn.py
- modify step function name to be within the 80 character limit.
> shorten the step_function name

- backend/config/corpora-api.yml
- frontend/src/common/API.ts
- tests/unit/backend/chalice/api_server/test_v1_dataset.py
> Pluralize Dataset in api and app

- backend/corpora/lambdas/api/v1/dataset.py
- tests/unit/backend/chalice/api_server/generate_data_mixin.py
- tests/unit/backend/chalice/api_server/test_v1_collection.py
- tests/unit/backend/chalice/api_server/test_v1_dataset.py
**Readability:** @mckinsel 
---
- add the removal of none values from GET dataset/status
- modify data generating code for reusability.
> Remove null json from response

- backend/corpora/common/upload_sfn.py
**Functional:** @tihuan
---
Fixes a bad copy-paste-modify for the stepfunctions client.
> Fix stepfunctions singleton

- backend/config/corpora-api.yml
- add conversion_rds_status to the OpenAPI GET /dp/v1/datasets/{dataset_uuid}/status response
> add conversion_rds_status

- .dockerignore
- Dockerfile.processing_image
- Makefile
- backend/processing_image/Makefile
- docker-compose.yml
The location of the Dockerfile for the processing image has changed, and the Make target for the image needs to be updated as well.
---
- add
- remove
- modify
> Fix processing image build target

- frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/Details/index.tsx
@seve 
@Bento007 
---
- modify
Change the file size calculation to use the correct formula
E.g., `Math.round(402210784 / 2 ** 20)` outputs `384MB`
> thuang-math-file-size

- backend/chalice/upload_failures/app.py
> update import location for lambda

- backend/config/corpora-api.yml
- frontend/src/common/entities.ts
- frontend/src/common/queries/datasets.ts
- frontend/src/components/Collections/components/Grid/common/style.ts
- frontend/src/components/Collections/components/Grid/components/DatasetsGrid/index.tsx
- frontend/src/components/Collections/components/Grid/components/Popover/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/CollectionRow/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/CellCount/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/Popover/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/Tooltip/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/Tooltip/style.ts
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/UploadStatus/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/UploadStatus/style.ts
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/common/Skeleton.tsx
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/style.ts
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/utils.ts
- frontend/src/components/Collections/components/Grid/components/Row/common/style.ts
- frontend/src/components/DropboxChooser/index.tsx
- frontend/src/components/common/theme.ts
- frontend/src/views/Collection/index.tsx
@seve 
@MDunitz 
**UX:**
@hthomas-czi 
---
- add
- remove
- modify
The GIF shows that the app will poll for collection metadata until it's populated!
Also sorting datasets from old to new:
> Thuang feedback 675 frontend dataset view

- scripts/populate_db.py
This fixes a problem with loading up data in the remote dev environment - importing *any* sub-modules from the test module will overwrite the DEPLOYMENT_STAGE env var, so we need to make sure we can import TestDatabase safely.
---
- add
- remove
- modify
> Fix remote dev DB import

- frontend/src/components/Collections/components/Grid/common/utils.ts
@Bento007 
@seve 
---
- modify
1. Quick update to the reduce function !
> thuang-fix-organism

- tests/unit/backend/chalice/api_server/test_v1_dataset.py
> test all upload statuses

- scripts/populate_db.py
> [EASY] fmt populate_db.py

- scripts/rdev
Just a docs update
---
- add
- remove
- modify
> Update help message for rdev script.

- scripts/rdev
* Use boto3 session instead of setting env var
* Instantiate cloudformation client in a single place
* Add ctx as argument of EnvMeta
* Remove unused variables
> Various cleanup of rdev script

- .github/workflows/deploy.yml
- Makefile
- frontend/Makefile
> thuang-github-smoke

- backend/corpora/common/corpora_orm.py
- @Bento007 
- @seve 
---
- modify
- move id onto base class. Move created_at and updated_at onto AuditMixin to dry up code
> move id into base, created_at and updated_at into auditMixin

- backend/config/corpora-api.yml
- frontend/lint-staged.config.js
> fix yaml formatting

- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/UploadStatus/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/index.tsx
#847 
@seve 
@MDunitz 
---
- add
1. When upload status is `WAITING`, we show `Queued...` text 😄 👌 
PTAL thanks all!
> thuang-847-add-queue-text

- backend/corpora/common/entities/collection.py
- tests/unit/backend/chalice/api_server/test_v1_collection.py
---
- add test for tombstoned datasets
- fixing reshape_for_api
> adding test and fixing typoe

- frontend/src/components/Collections/components/DeleteCollection/index.tsx
@seve 
@Bento007 
---
- modify
1. Temporarily disable the delete collection button
> thuang-disable-delete-collection-button

- Makefile
Hopefully fixes https://github.com/chanzuckerberg/corpora-data-portal/actions/runs/535450296
---
- add
- remove
- modify
> Put e2e-dev target back

- .github/workflows/push-tests.yml
**Functional:** @jgadling 
---
- fixing https://github.com/chanzuckerberg/corpora-data-portal/runs/1876381674
> Update push-test with the temporary work around.

- .github/workflows/push-tests.yml
> Upgrade stage after main branch tests succeed.

- scripts/happy
Forgot to include updates to happy script.
---
- add
- remove
- modify
> Fix TFE auth

- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/style.ts
- frontend/src/components/Collections/components/Grid/components/Row/common/style.ts
**Functional:**   @tihuan 
**Readability:**  @MDunitz 
---
- modify Tweak styles for collection visibility tags and dataset titles
----
Broken: 
Fixed:
> style fixes

- frontend/src/views/Collection/index.tsx
- frontend/src/views/MyCollections/index.tsx
@seve 
@Bento007 
---
- add
- remove
Collection page: Share button
- modify
My Collections page: Text to remove wording related to shared collections
PTAL Thank you 😄 !!
> thuang-quick-fix-collection

- .happy/config.json
Upgrade tf version to 0.13.5 and verified new rdev is successfully created.
> upgarde tf version

- Makefile
> Re-enable codecov

- .github/workflows/deploy-prod.yml
- .github/workflows/deploy-staging.yml
- .github/workflows/deploy.yml
- Makefile
- frontend/Makefile
---
-  smoke tests for all deployments
- bump container version
> Fix smoke tests for all deployments

- frontend/tests/common/constants.ts
- frontend/tests/features/collection.test.ts
- frontend/tests/utils/helpers.ts
**Readability:** @Bento007 
---
- add
- remove Helper code associated with auth login/logout
- modify Skip auth related testing
---
#900
> disable auth tests, remove login helper code

- tests/unit/backend/chalice/api_server/test_v1_collection.py
- tests/unit/backend/corpora/common/entities/test_collection.py
- tests/unit/backend/fixtures/test_db.py
---
- add test to verify every link type.
- modify generated test data to include a link of every type.
`make unit-tests`
> Test all link types

- .github/workflows/deploy-happy-stack.yml
- .github/workflows/push-tests.yml
- Makefile
- backend/corpora/common/entities/dataset_asset.py
- backend/corpora/common/upload_sfn.py
- backend/corpora/common/utils/aws.py
- backend/corpora/dataset_processing/process.py
- scripts/happy-deploy
- tests/functional/backend/corpora/test_upload_sfn.py
- tests/unit/backend/corpora/common/utils/test_aws_secret.py
- tests/unit/backend/corpora/common/utils/test_secret_config.py
- tests/unit/backend/corpora/fixtures/existing_aws_secret_test_fixture.py
* Creates separate Github workflow for deploying staging from a Github deployment
* Change push-tests to create a deployment if all tests pass
* Standalone CLI script to create a deployment manually (stopgap)
* Handle BOTO_ENDPOINT_URL empty string correctly (Boto3 does distinguish between
None and empty string)
> Separate workflow for deploying staging

- .github/workflows/push-tests.yml
> update happy deploy script

- .happy/terraform/envs/prod/main.tf
> flip prod urls

- .github/workflows/deploy-happy-stack.yml
Fix permission issues for prod deployment
> fix for prod deploy

- .github/workflows/push-rdev.yml
- REMOTE_DEV.md
> Add GitHub Action to build remote dev for branches prefixed "rdev-"

- .happy/terraform/envs/prod/main.tf
- .happy/terraform/envs/rdev/main.tf
- .happy/terraform/envs/stage/main.tf
- .happy/terraform/modules/batch/main.tf
- .happy/terraform/modules/batch/variables.tf
- .happy/terraform/modules/ecs-stack/main.tf
- .happy/terraform/modules/ecs-stack/variables.tf
- tests/functional/backend/corpora/test_api.py
> increase batch memory

- Dockerfile.processing_image
- Dockerfile.upload_failures
> Add missing __init__.py files from upload Dockerfile

- scripts/happy
> Happy CLI login to multiple ECRs when necessary

- .github/workflows/deploy-happy-stack.yml
Verified this works now that api_signin_url is added to allowed audiences.
> Enable functional tests for staging deploy

- Dockerfile.processing_image
---
- modify Dockerfile for processing image to use correct cellxgene make comands
> update upload processing image for cellxgene refactor

- backend/corpora/dataset_processing/process.py
> remove Flush=true from logs

- frontend/src/components/Collections/components/Grid/common/utils.ts
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/DeleteDataset/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/UploadStatus/style.ts
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/style.ts
- frontend/src/components/Collections/components/Grid/components/Row/common/style.ts
- frontend/src/views/Collection/index.tsx
LIVE URL: https://thuang-ui-revamp-frontend.rdev.single-cell.czi.technology/
@seve 
@Bento007 
---
- modify: Please see DoD for the changes! Thank you!
1. Dataset metadata now updates automatically again without refresh, `<MoreDropdown />` the `...` component is now aligned too, and the processing status indicator and the dataset name now as proper amount of space too:
1. Publish button is disabled properly when a new dataset is added
> Thuang UI revamp updates

- backend/corpora/dataset_processing/download.py
- backend/corpora/dataset_processing/process.py
---
- add file_size to logs for #1013
> logging file size in processing pipeline

- Makefile
> add aws envs to local-e2e

- frontend/next.config.js
This reverts commit c2836ae58bb836e35e6b8169856a23f7fd41a7ac.
---
- add
- remove
- modify
> Revert "thuang-fix-nextjs-multiservers (#1078)"

- frontend/tests/features/collection.test.ts
- frontend/tests/utils/helpers.ts
**Functional:**  @tihuan 
---
- add
- Unique identifier for test collections
- timeout to check for collection to give react query time to clear cache
----
#1106
> bug(fe-tests): reduce flakiness of frontend tests

- scripts/happy-deploy.py
* Use last 50 deployments instead of first 30 deployments
* Do not break prematurely
* Add debug output and more error output
> Fix happy-deploy script

- backend/corpora/dataset_processing/download.py
- tests/unit/backend/corpora/dataset_processing/test_downloader.py
**Readability:**  @MDunitz 
---
- Change download errors to warning
- Catch all error during download
- Upload fails if the downloader has stopped and progress is not 100%
- Check if there is enough disk space to download before starting.
- log status if upload failed
> Processing container file size check

- .happy/terraform/envs/prod/main.tf
---
- modify memory from 230000 -> 250000
> increase container memory

- frontend/src/common/featureFlags/features.ts
- frontend/src/common/featureFlags/index.ts
- frontend/src/common/localStorage/set.ts
- frontend/src/common/utils/removeParams.ts
- frontend/src/components/CreateCollectionModal/components/CTA/index.tsx
- frontend/src/components/CreateCollectionModal/index.tsx
- frontend/src/components/Header/components/AuthButtons/index.tsx
- frontend/src/components/Header/index.tsx
- frontend/src/pages/_app.tsx
**Functional:**  @tihuan 
---
- add
- General remove params util function
- Curator flag (`rubber-chicken`)
- modify
- Check for all feature flags whenever `get()` is called 
- Remove feature flags when read
---
#1062 #983
> feat: create curator flag, always check for flags

- .github/workflows/scale-test.yml
Make output filename match what's read as input below, change step name to match staging.
> Make scale test point at staging

- .happy/terraform/envs/stage/main.tf
> Upgrade memory for staging

- .happy/config.json
---
- modify dev and staging, to automigrate database during deploymentl.
> enable auto migrate for dev and staging database

- .github/workflows/lint-pr.yml
> typo: "ull" -> "pull"

- .github/workflows/standup-assignment-notification.yml
**Functional:** Any engineer. 
---
- Add a GithubAction workflow to automatically assign standup each Sunday at 5pm PT
> feat: Add a GithubAction workflow to automatically assign standup each Sunday at 5pm PT

- scripts/happy-deploy.py
Bug fix to fix name collision.
> fix: Fix prod deploy script to separate read_deployment_stage

- backend/corpora/common/corpora_config.py
---
- modify corpora_config to avoid excessive dictionary lookups for the same variable.
> fix: optimize environment variable lookup in corpora_config

- .happy/config.json
**Functional:** @mbarrien 
**Readability:** @MDunitz 
---
- add auto migration of prod database during deployment.
> ci: enable auto migrate of prod database

- tests/unit/backend/chalice/api_server/test_revisions.py
removing test code that replicated copying the datasets for a revision
> removing test code that replicated copying the datasets for a revision

- backend/corpora/dataset_processing/process.py
- tests/functional/backend/corpora/test_api.py
---
- fix functional tests: test_collection_flow, test_delete_private_collection
> fix:  test_collection_flow, test_delete_private_collection

- tests/functional/backend/corpora/test_api.py
> fix: update response code of functional test "test_delete_private_collection"

- scripts/cxg_admin.py
---
- add script to cxg_admin to update the owner of a collection or to transfer all collections owned by one person to another person
> feat: script to update collection ownership

- tests/unit/backend/chalice/api_server/test_revisions.py
**Functional:* @MDunitz 
---
- moving coming test code into BaseRevisionTest
> refactor: clean up revisions test

- scripts/happy-deploy.py
- @jgadling 
- @Bento007 
---
- modify function checking sha length for deployment
> fix: only check sha length if given

- backend/corpora/dataset_processing/process.py
- scripts/cxg_admin.py
- tests/unit/backend/corpora/dataset_processing/test_process.py
- @maniarathi 
- @seve 
---
- add script to create cxg artifacts from the explorer_url for all datasets in db
- The script was tested on a copy of the prod db
- modify dataset processing to create a cxg artifact
> feat: Dunitz/1223 cxg artifact

- backend/corpora/common/entities/collection.py
- tests/unit/backend/chalice/api_server/test_v1_collection.py
- @maniarathi 
---
- modify also return dataset_deployments field
> fix: missing field breaks dataset uploads page

- frontend/src/views/Collection/utils.tsx
---
- modify
- Cleanup util function and allow additional cxg asset
---
#1233
> fix: clarify getIsPublishable and allow cxg asset

- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/DownloadButton/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/MoreDropdown/components/Menu/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/MoreDropdown/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/index.tsx
- frontend/src/components/CreateCollectionModal/components/Content/index.tsx
- frontend/src/components/common/Form/Input/index.tsx
**Readability:** @Bento007 
---
- modify
- Disable the update dataset button while an upload is in progress
- Remove content validation for link name in create/update collection modal
-  Instead explicitly validate for length where needed
-  Style custom icons properly for blueprint
----
#1163 #1219 #1220
> fix: various collection related bug fixes

- .github/workflows/deploy-happy-stack.yml
> fix: cloudfront invalidation github action

- .github/workflows/deploy-happy-stack.yml
---
- add slack notification when deployment fails
> fix: add slack notification when deployment fails

- backend/corpora/dataset_processing/process.py
- tests/unit/backend/corpora/dataset_processing/test_process.py
---
- add notify_slack_failure when the processing container run into an error.
- A notification appears on slack when the processing container fails.
-
> feat: notify with processing container fails in prod

- backend/corpora/dataset_processing/process.py
> fix: slack notification

- backend/corpora/dataset_processing/process.py
- backend/corpora/dataset_processing/slack.py
- tests/unit/backend/corpora/dataset_processing/test_process.py
- tests/unit/backend/corpora/dataset_processing/test_slack.py
---
- separating slack notification code from the processing code.
> fix: use AWS_DEFAULT_REGION for slack notification.

- backend/chalice/api_server/app.py
This can be removed once clever-canary finishes it's work.
---
- add
- remove
- modify
> fix: add clever canary domain to allowed origins

- backend/chalice/api_server/app.py
This can be removed once clever-canary finishes its work.
---
- add
- remove
- modify
> fix: add clever canary domain to allowed origins, typo

- backend/chalice/api_server/app.py
> fix: hardcode clever canary in allowed_origins

- tests/functional/backend/corpora/test_api.py
---
- a dataset must be present to publish. Uploading a dataset during the test_collection_flow to test collection publishing
> fix: uploading a dataset during test_collection_flow

- backend/corpora/lambdas/api/v1/dataset.py
- tests/unit/backend/chalice/api_server/test_v1_dataset.py
> feat: add collection visibility to dataset identifier api response

- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/utils.ts
- frontend/src/components/Collections/components/PublishCollection/index.tsx
- frontend/src/views/Collection/components/ActionButtons/index.tsx
- frontend/src/views/Collection/components/DatasetTab/index.tsx
- frontend/src/views/Collection/components/Toast/index.tsx
- frontend/src/views/Collection/index.tsx
- frontend/src/views/Collection/utils.tsx
**Functional:**   @MDunitz  
---
- add
- Add alternate text to publish collection modal
- Add toast on successful mutation
- modify
- Make toast name more general
- Check that at least one collection is not tombstoned
> feat(revision): finish style + UX cleanup

- frontend/src/views/Collection/index.tsx
- frontend/src/views/Collection/style.ts
- frontend/src/views/Collection/utils.tsx
---
- add
-  Add callout that shows revision status on collection view
- modify
- Only allow publishing of revision if changes have been made
> feat(revisions): show revision state on collection view

- frontend/src/components/CreateCollectionModal/components/Content/components/LinkInput/index.tsx
@seve 
fixes #1311 
---
- modify
1. Add back `noNameAttr` in Input components
Extra context here:
https://github.com/chanzuckerberg/corpora-data-portal/pull/1103/files#r678794896
> fix: correct create collection payload

- frontend/src/views/Collection/utils.tsx
fixes  #1317 
---
Update conditions to `revisionIsPublishable()`
Repro:
1. Create a new collection
1. Upload a dataset successfully
1. Publish button should be enabled now
> fix: 1317 publish private collection

- frontend/src/common/queries/collections.ts
> fix: tweak queries for instantaneous results

- frontend/src/components/Collections/components/Grid/common/utils.ts
@seve 
---
- add
- remove
- modify
> fix: sort-categoricals-per-collection

- scripts/cxg_admin.py
- @metakuni 
- @seve 
---
- add script to tombsonte datasets
- tested on datasets in staging. Confirmed that they were tombstoned. 
Note we need stop returning tombstoned datasets in the collection/{collection_id}/ response object [ticket](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/1343)
> feat: add tombstone script

- tests/functional/backend/corpora/test_api.py
@MDunitz 
ZenHub Ticket: [#1338](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/1338)
---
- modify `upload_and_wait` function found in `tests/functional/backend/corpora/test_api.py` to use `.get()` when accessing values from dictionary for conversion statuses.
> fix: Flaky functional test

- tests/functional/backend/corpora/test_api.py
@leslieypark 
---
Ticket [#1371 ](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1371)
- Fix a flaky functional test.
> chore: fix flaky functional test

- tests/functional/backend/corpora/test_api.py
@MDunitz 
---
- This functional test didn't support the new authentication mechanism. Now it does.
> fix: API functional test now supports new auth

- frontend/tests/features/collection/revision.test.ts
> chore: tentative fix for revision smoke test

- Dockerfile.processing_image
- backend/corpora/dataset_processing/process.py
- tests/unit/backend/corpora/dataset_processing/test_process.py
- tests/unit/processing_container/test_process.py
@leslieypark @atolopko-czi @pablo-gar 
@seve 
---
- Uses `cellxgene-schema` with `--add-labels` to generate a new h5ad file with labels
- Uses the aforementioned file in the rest of the pipeline
- Cleans up all the old h5ad files
> feat: 1297 use cellxgene-schema with labels

- backend/corpora/dataset_processing/process.py
@leslieypark
---
- `X_approximate_distribution` should be optional.
> fix: make X_approximate_distribution optional

- requirements.txt
@MDunitz 
@ebezzi 
---
- modify: TileDB-Py version 0.9.5 -> 0.10.0
> chore: bumped TileDB-Py version (#1243)

- .happy/terraform/modules/service/variables.tf
- frontend/package.json
> fix: Bump rdev and Next.js build memory to 2048MB

- Makefile
- requirements.txt
- @MDunitz 
- @ebezzi 
---
- modify: upgraded [TileDB-Py to 0.10.1](https://github.com/TileDB-Inc/TileDB-Py/releases/tag/0.10.1) which includes the fix for the [`Array.multi_index` concurrency bug](https://github.com/TileDB-Inc/TileDB-Py/pull/672).
> fix: upgraded TileDB (#1412)

- frontend/src/common/queries/collections.ts
- frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/index.tsx
- frontend/src/components/Collections/components/Grid/components/DatasetsGrid/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/DownloadButton/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/MoreDropdown/components/Menu/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/MoreDropdown/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/index.tsx
- frontend/src/components/DropboxChooser/index.tsx
- frontend/src/components/Header/components/AuthButtons/index.tsx
- frontend/src/components/common/Logo/index.tsx
- frontend/src/components/common/MoreDropdown/index.tsx
- frontend/src/pages/_app.tsx
- frontend/src/pages/collections/[...params].tsx
- frontend/src/pages/index.tsx
- frontend/src/pages/my-collections.tsx
- frontend/src/views/Collection/components/DatasetTab/index.tsx
- frontend/tests/features/collection/revision.test.ts
This PR fixes the broken images after migrating to Next.js, since we no longer needed a dependency for processing images!
Also fixes all the lint errors Next.js caught 🙆‍♂️ 
---
- add
- remove
- modify
> fix: nextjs images and lints

- .pre-commit-config.yaml
- frontend/public/site.webmanifest
> fix: pre-commit config

- tests/functional/backend/corpora/test_revisions.py
@ebezzi 
---
- modify: parametrized the expected S3 URI by `DEPLOYMENT_STAGE`
> chore: parametrized the S3 URI (#1446)

- frontend/src/common/constants/routes.ts
- frontend/src/components/Header/index.tsx
- frontend/src/configs/common.js
> refactor: learn button

- tests/functional/backend/corpora/test_revisions.py
@ebezzi 
---
- add: skipping of `test_revision_flow` functional test
> chore: temporarily skipped test (#1446)

- .happy/terraform/modules/sfn/main.tf
@MDunitz @leslieypark 
---
- Modify timeout for the upload step function to 10 hours
> fix: increase timeout for upload step function

- frontend/src/common/constants/routes.ts
- frontend/src/components/Header/components/AuthButtons/index.tsx
- frontend/src/components/Header/components/LearnButton/index.tsx
- frontend/src/components/Header/index.tsx
- frontend/src/components/Header/style.ts
@seve 
@lesliecodes 
---
- add
Learn More Button
> feat: 1454 add Learn Button Dropdown

- frontend/src/common/featureFlags/features.ts
- frontend/src/views/Collection/index.tsx
- frontend/src/views/MyCollections/index.tsx
**Functional:**  @tihuan 
----
#1062
> chore: merge revision flag into curator flag

- frontend/tests/features/collection/revision.test.ts
@seve 
@leslieypark 
---
- add
- remove
- modify
Reduce flakiness by selecting collection with expected "Published" and "Revision Pending" tags, this way at least we will never pick a private collection that happens to have same name, resulting in false errors
> test: fix revision collection lookup

- frontend/src/views/Collection/components/Banner/constants.ts
@metakuni 
@ebezzi 
---
- remove three collections from `INCOMPLETE_GENE_MIGRATIONS_COLLECTIONS`. These were [updated](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1570).
> chore: Updates to gene migration filter (#1570)

- Dockerfile.processing_image
- backend/corpora/dataset_processing/process.py
- tests/unit/backend/corpora/dataset_processing/test_process.py
> feat: Seurat crash detection (#1579)

- tests/functional/backend/corpora/test_api.py
**Readability:** @ebezzi 
---
-  update functional tests for deleting a collection
> fix: update functional tests for deleting a collection

- frontend/src/common/featureFlags/features.ts
@tihuan 
---
Added `filter` feature flag to facilitate access to filter functionality during its development.
Metadata filter features are only accessible/visible once feature flag has been added to the browser location.
NA
NA
> feat: added filter feature flag. (#1599)

- frontend/src/components/Header/components/AuthButtons/index.tsx
- frontend/src/components/Header/components/LearnButton/index.tsx
- frontend/src/components/Header/index.tsx
- frontend/src/components/Header/style.ts
@tihuan
---
* fixed layout of AuthButton wrapper to handle unauthenticated state
* as per @hthomas:
* updated font size of navigation items
* updated Help & Documentation to include caret
> feat: refine navigation bar UI to match mocks (#1600)

- frontend/src/common/hooks/useFeatureFlag.ts
- frontend/src/components/Header/style.ts
- frontend/src/components/Layout/components/defaultLayout.tsx
- frontend/src/components/Layout/components/sidebarLayout.tsx
- frontend/src/components/Layout/index.tsx
- frontend/src/components/Layout/style.ts
- frontend/src/components/common/layout.ts
- frontend/src/pages/_app.tsx
- frontend/src/pages/index.tsx
- frontend/src/views/Homepage/index.tsx
- frontend/src/views/Homepage/style.ts
@tihuan
---
* Site is left-aligned and has no snap point.
* When feature flag is true:
* Sidebar layout added to accommodate filtering and collections layout; and
* Default layout added for all other pages (collection detail, 404 etc).
* When feature flag is false:
* All pages use added default layout.
> feat: left align site (#1656)

- .happy/terraform/modules/sfn/main.tf
@metakuni 
---
- Adds the Seurat step function, as already defined in [sinle-cell-infra](https://github.com/chanzuckerberg/single-cell-infra/pull/461)
> feat: add Seurat step function

- backend/corpora/dataset_processing/process.py
@metakuni 
---
- Restores exception catching for the process function
> fix: add back try/except to process.py main

- backend/config/corpora-api.yml
- backend/corpora/lambdas/api/v1/wmg.py
> feat: atolopko/thuang-wmg-echarts-backend

- frontend/src/components/Collections/components/PublishCollection/components/Policy/index.tsx
- frontend/src/components/Collections/index.tsx
- frontend/src/views/Collection/index.tsx
**Functional:** @Bento007
---
#1698
> fix: address delete collection QA feedback

- frontend/src/common/constants/metadata.ts
- frontend/src/components/Collections/components/Grid/components/CollectionsGrid/style.ts
- frontend/src/components/Collections/components/Grid/components/Popover/index.tsx
- frontend/src/components/common/Filter/common/entities.ts
- frontend/src/components/common/Grid/components/Cell/index.tsx
- frontend/src/components/common/Grid/components/Hero/index.tsx
- frontend/src/components/common/Grid/components/LinkCell/index.tsx
- frontend/src/components/common/Grid/components/LinkCell/style.ts
- frontend/src/components/common/Grid/components/NTag/index.tsx
- frontend/src/components/common/Grid/components/NTag/style.ts
- frontend/src/components/common/Grid/components/NTagCell/index.tsx
- frontend/src/components/common/Grid/index.tsx
- frontend/src/components/common/Grid/style.ts
- frontend/src/views/Collections/index.tsx
---
- Added basic grid component with grid styles
- Collections UI to match mocks
> feat: collections grid with grid style

- backend/database/versions/22_449eea8f5aeb_remove_loom_enum.py
- backend/database/versions/23_449eea8f5aeb_remove_loom_enum.py
Now owned by @blrnw3 
- @ebezzi 
---
- remove loom enum
loom enum gone
* manually tested migration (bmr)
none
> fix: remove loom enum

- frontend/src/components/common/Grid/components/LinkCell/style.ts
---
- Collections column ui updated
> feat: update collections UI to match mocks; collections link ui updated (#1602)

- frontend/src/components/Categories/index.tsx
- frontend/src/components/Collections/components/Grid/components/CollectionsGrid/style.ts
- frontend/src/components/common/Filter/common/entities.ts
- frontend/src/components/common/Filter/common/style.ts
- frontend/src/components/common/Filter/components/BasicFilter/index.tsx
- frontend/src/components/common/Filter/components/FilterLabel/index.tsx
- frontend/src/components/common/Filter/components/FilterLabel/style.ts
- frontend/src/components/common/Filter/components/FilterMenu/index.tsx
- frontend/src/components/common/Filter/components/FilterMenu/style.ts
- frontend/src/components/common/Filter/components/FilterTags/index.tsx
- frontend/src/components/common/Filter/components/FilterTags/style.ts
- frontend/src/components/common/Filter/index.tsx
- frontend/src/components/common/Grid/components/Hero/index.tsx
- frontend/src/components/common/Grid/index.tsx
- frontend/src/components/common/SideBar/style.ts
- frontend/src/views/Collections/index.tsx
---
- Filter refactored
- Filter menu, tags, and label styles updated
> feat: list basic metadata categories in left sidebar on collections view (#1614)

- frontend/src/common/constants/routes.ts
- frontend/src/components/Header/index.tsx
- frontend/src/components/Header/style.ts
---
- added "Datasets" and "Collections" to navigation bar
> feat: add datasets view; header nav added (#1604)

- frontend/src/common/queries/filter.ts
- frontend/src/views/Collections/index.tsx
- frontend/src/views/Datasets/index.tsx
N/A
---
- Added hook that returns dataset rows for a given collection.
> feat: added collection datasets hook.

- frontend/src/components/Collection/components/CollectionDatasetsGrid/components/DatasetsGrid/index.tsx
- frontend/src/components/Collection/components/CollectionDatasetsGrid/components/Row/DatsetRow/index.tsx
- frontend/src/components/Collection/components/CollectionDatasetsGrid/style.ts
- frontend/src/components/Collections/components/Dataset/components/DownloadDataset/index.tsx
- frontend/src/components/Datasets/components/Grid/common/utils.tsx
- frontend/src/components/Datasets/components/Grid/components/DatasetActionsCell/index.tsx
- frontend/src/components/Datasets/components/Grid/components/DatasetNameCell/index.tsx
- frontend/src/components/common/Filter/common/entities.ts
- frontend/src/components/common/Grid/common/constants.ts
- frontend/src/components/common/Grid/common/utils.ts
- frontend/src/components/common/Grid/components/ActionButton/index.tsx
- frontend/src/components/common/Grid/components/CountCell/index.tsx
- frontend/src/components/common/Grid/components/StatusTags/index.ts
- frontend/src/components/common/MoreDropdown/index.tsx
- frontend/src/views/Collection/components/DatasetTab/index.tsx
- frontend/src/views/Collection/index.tsx
- frontend/src/views/Collections/index.tsx
- frontend/src/views/Datasets/index.tsx
---
- Updated datasets table on collection detail page
> feat: update datasets table on collection detail page (#1605)

- frontend/src/components/Footer/style.ts
- frontend/src/components/Header/style.ts
- frontend/src/components/Layout/style.ts
- frontend/src/components/common/Filter/common/style.ts
- frontend/src/components/common/SideBar/style.ts
- frontend/src/views/Collection/style.ts
- frontend/src/views/Homepage/index.tsx
- frontend/src/views/globalStyle.ts
---
- header font updated to reflect mock; including header link font-weight change from 600 to 500
- horizontal overflow added to content for independent scrolling on filter menu
- minor style adjustments to support horizontal overflow in default view and collections dataset view
> feat: update collections UI to match mocks; header nav font to match spec and content scrolling updates (#1602)

- frontend/src/components/common/Filter/common/entities.ts
- frontend/src/components/common/Filter/components/FilterMenu/index.tsx
- frontend/src/components/common/Filter/index.tsx
---
- Filter category values with a count greater than zero
> feat: implement core facet search module/engine (#1613)

- frontend/src/components/Collections/components/PublishCollection/components/Policy/index.tsx
**Functional:** @Bento007 
---
#1725
> feat: update data submission policy to 2.0

- backend/corpora/lambdas/api/v1/wmg.py
@tihuan 
---
Point WMG prototype at latest data, generated 2021-12-08, which include cell types ordered using Graphviz ontology-based ordering.
Latest data appears, with properly ordered cell types
Wholly untested!
> point wmg at 2012-12-08 data

- .github/workflows/push-tests.yml
@metakuni 
---
- Pushes the `corpora-upload-success` Docker image to ECR.
> ci: add corpora-upload-success docker image push step

- backend/corpora/common/utils/db_helpers.py
- backend/corpora/upload_success/app.py
@ebezzi 
---
- modify: used the proper ID for `processing_status_updater()`
> fix: id bug (#1702)

- .github/workflows/push-tests.yml
- backend/corpora/common/entities/collection.py
- backend/corpora/common/utils/db_helpers.py
- backend/corpora/upload_success/app.py
@ebezzi 
---
- add
- remove
- modify
> chore: staging deployment

- Dockerfile.processing_image
@chanzuckerberg/czi-single-cell-eng 
---
- remove: dead explorer dependency
> chore: removed commented dependency on explorer

- tests/functional/backend/corpora/test_api.py
> chore: change timeout for last functional test to 10m

- Dockerfile.processing_image
@metakuni 
---
- Given that there are issues with [this version of Seurat](https://cran.r-project.org/web/packages/Seurat/index.html), we should force the portal to use the previous published version, which is contained in this (stable) image.
> chore: pin base processing image

- frontend/file_two
> chore: add line to file_two

- backend/corpora/dataset_processing/process_seurat.py
- scripts/cxg_admin.py
@metakuni @danieljhegeman 
---
- Seurat reprocessing script.
> feat: Reprocess Seurat script

- scripts/happy
> fix: Return an error if terraform deploy fails

- scripts/cxg_admin.py
**Readability:** @atolopko-czi 
---
- add function to update curator_name in a collection based on the owner of a collection, and update all published collection to data_submission_policy_version 2.0
- connected to #1745 
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1745
> fix: curator name backfill

- frontend/package-lock.json
- frontend/package.json
- frontend/src/common/queries/README.md
- frontend/src/common/queries/auth.ts
- frontend/src/common/queries/collections.ts
- frontend/src/common/queries/datasets.ts
- frontend/src/common/queries/filter.ts
- frontend/src/components/Collection/components/CollectionDatasetsGrid/components/Row/DatsetRow/index.tsx
- frontend/src/components/Collections/components/DeleteCollection/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/CollectionRow/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/DeleteDataset/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/utils.ts
- frontend/src/components/Collections/components/PublishCollection/index.tsx
- frontend/src/components/CreateCollectionModal/components/Content/index.tsx
- frontend/src/pages/_app.tsx
- frontend/src/views/Collection/components/DatasetTab/index.tsx
- frontend/src/views/Collection/index.tsx
- scripts/cxg_admin.py
- scripts/happy
Deploying:
* #1785
These have no effect on deployed system:
* #1793 
* #1770
> chore: deploy dev -> staging

- backend/corpora/common/entities/dataset_asset.py
- backend/corpora/lambdas/api/v1/collection_uuid/publish.py
- tests/functional/backend/corpora/test_api.py
- tests/unit/backend/corpora/api_server/collection_uuid/test_publish.py
- tests/unit/backend/corpora/api_server/test_revisions.py
- tests/unit/backend/fixtures/generate_data_mixin.py
- tests/unit/backend/utils.py
---
Reverting PRs related to blocking publish of collection with duplicate datasets.
- revert #1784 
- revert #1652
> fix: Revert #1784 and #1652

- backend/corpora/lambdas/api/v1/wmg.py
@tihuan 
@tihuan 
---
update backend data to 20220112, reflecting latest cell_type ordering algo
This has NOT been tested AT ALL.
> data update 20220112

- backend/config/corpora-api.yml
- backend/corpora/lambdas/api/v1/wmg.py
- frontend/next.config.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/common/API.ts
- frontend/src/common/constants/utils.ts
- frontend/src/pages/wmg.tsx
- frontend/src/views/WheresMyGene/common/types.ts
- frontend/src/views/WheresMyGene/components/GeneFetcher/index.tsx
- frontend/src/views/WheresMyGene/components/GeneSearchBar/components/Genesets/index.tsx
- frontend/src/views/WheresMyGene/components/GeneSearchBar/index.tsx
- frontend/src/views/WheresMyGene/components/GeneSearchBar/style.ts
- frontend/src/views/WheresMyGene/components/HeatMap/echarts-gl.d.ts
- frontend/src/views/WheresMyGene/components/HeatMap/index.tsx
- frontend/src/views/WheresMyGene/components/HeatMap/style.ts
- frontend/src/views/WheresMyGene/index.tsx
- frontend/src/views/WheresMyGene/style.ts
Merging Where's My Gene prototype into `main`, so we can conduct UXR with external users 🧪 🔍 ❤️ 
All the Where's My Gene stuff is under URL `domain.org/wmg`, so it shouldn't affect the rest of the site, including the bundle size due to route wise code splitting
The code is in prototype quality, so no need to review thoroughly right now. We'll spend the first a few weeks of Q1 to get it to production quality before we roll out v1!
> feat: Wheres My Gene Prototype

- LICENSE
**Functional:** @metakuni 
**Readability:** N/A
---
- Updating the license year to be a range and also add the year 2022.
> chore: Update license to 2022.

- frontend/src/views/WheresMyGene/common/types.ts
- frontend/src/views/WheresMyGene/components/GeneFetcher/index.tsx
- frontend/src/views/WheresMyGene/components/GeneSearchBar/index.tsx
- frontend/src/views/WheresMyGene/components/HeatMap/index.tsx
- frontend/src/views/WheresMyGene/components/HeatMap/style.ts
- frontend/src/views/WheresMyGene/components/HeatMap/utils.ts
- frontend/src/views/WheresMyGene/index.tsx
@seve 
@MDunitz 
---
- add
1. Add comments to explain things better
2. Clean up `HeatMap` component and extract echarts option creations into their own util functions. Also add type definitions
3. Add x-axis mask:
1. Before:  
2. After:
- remove
- modify
> refactor: wheres my gene

- frontend/src/common/queries/filter.ts
@tihuan 
---
- Modified datasets functionality to use useMemo.
> refactor: no result useMemo for dataserts

- backend/corpora/common/utils/dl_sources/url.py
> fix: change Dropbox content length header (#1905)

- .github/workflows/push-tests.yml
- backend/corpora/dataset_processing/process.py
Reverts chanzuckerberg/single-cell-data-portal#1941
> fix: Revert "fix: copy collections DO NOT PROMOTE TO STAGING/PROD"

- frontend/src/common/entities.ts
- frontend/src/common/hooks/useCategoryFilter.ts
- frontend/src/common/queries/filter.ts
- frontend/src/components/common/Filter/common/entities.ts
- frontend/src/views/Collections/index.tsx
- frontend/src/views/Datasets/index.tsx
- frontend/tests/common/queries/filter.test.ts
@tihuan 
---
- Added filter by publication date to collections and datasets.
- Added filter by publication author to collections and datasets.
> feat: added filter by publication metadata

- frontend/src/components/CreateCollectionModal/components/Content/components/AddLink/index.tsx
- frontend/src/components/CreateCollectionModal/components/Content/components/LinkInput/index.tsx
- frontend/src/components/CreateCollectionModal/components/Content/components/LinkInput/style.ts
- frontend/src/components/CreateCollectionModal/components/Content/index.tsx
- frontend/src/components/CreateCollectionModal/components/Content/style.ts
- frontend/src/components/common/Button/common/style.ts
- frontend/src/components/common/Form/Input/index.tsx
- frontend/src/components/common/Form/Input/style.ts
- frontend/src/components/common/Form/TextArea/index.tsx
- frontend/src/components/common/Form/TextArea/style.ts
- frontend/src/components/common/Form/common/style.ts
@tihuan 
---
- Updated create collection modal UI as per [mock](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=2738%3A29492) and [mock](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=3098%3A31461) (first pass only for the add collection links).
- Submit button text always displayed as "Save".
> feat: Update collection form UI (#1838)

- frontend/src/common/entities.ts
- frontend/src/common/queries/collections.ts
- frontend/src/common/queries/filter.ts
- frontend/src/components/common/Filter/common/entities.ts
- frontend/src/views/Collection/index.tsx
- frontend/src/views/Collection/utils.tsx
- frontend/tests/common/queries/filter.test.ts
@tihuan
---
- Add summary citation to collection detail page ([summary citation mock](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1327%3A8052), [default DOI mock](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1457%3A7365) if publication metadata not found for DOI).
> feat: added summary citation to collection detail.

- backend/open_api_spec.yml
> Add GET curator/collections

- backend/open_api_spec.yml
> Adding API Token endpoints

- backend/open_api_spec.yml
@Bento007 
---
- add
- remove
- modify
> chore: WIP curation API spec

- frontend/src/views/WheresMyGene/common/types.ts
- frontend/src/views/WheresMyGene/components/Filters/index.tsx
- frontend/src/views/WheresMyGene/index.tsx
@seve 
@ebezzi 
---
- add
Use `ComplexFilter` to add filters
- remove
- modify
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1848
1. The filters on the left panel should persist even if you collapse the panel
1. Not hooked up with real API yet. Will be addressed in a different ticket after BE's mock API is merged!
PTAL Thank you!
> feat(wmg): Filters panel

- backend/corpora/common/providers/crossref_provider.py
---
- Remove unnecessary field
> fix: remove dates from crossref metadata

- frontend/src/components/common/Filter/common/entities.ts
- frontend/src/components/common/Filter/common/utils.ts
- frontend/src/components/common/Filter/components/FilterRange/index.tsx
- frontend/src/components/common/Filter/components/FilterRange/style.ts
- frontend/src/components/common/Filter/components/FilterTags/index.tsx
- frontend/src/components/common/Filter/index.tsx
---
- Filter datasets by cell count ui first pass.
> feat: Filter datasets by cell count ui (#1820)

- backend/corpora/common/utils/dl_sources/url.py
- backend/corpora/dataset_processing/download.py
- backend/corpora/lambdas/api/v1/collection_uuid/upload.py
> chore: Dropbox downloader does not depend on content length

- frontend/src/components/Header/components/AuthButtons/index.tsx
- frontend/src/components/Header/components/AuthButtons/style.ts
- frontend/src/components/Header/components/CuratorAPIKeyGenerator/index.tsx
---
1. Use SDS Dialog, Menu, and MenuItem for AuthButton
2. Clicking backdrop doesn't close modal anymore
> refactor: Use SDS Dialog and Menu

- frontend/src/components/Header/components/AuthButtons/index.tsx
Turned out that I took a screenshot but didn't commit 😂
> fix: AuthButton Logout text

- frontend/src/views/WheresMyGene/components/Beta/index.tsx
- frontend/src/views/WheresMyGene/components/Beta/style.ts
- frontend/src/views/WheresMyGene/components/GetStarted/components/Step/index.tsx
- frontend/src/views/WheresMyGene/components/GetStarted/components/Step/style.ts
- frontend/src/views/WheresMyGene/components/GetStarted/index.tsx
- frontend/src/views/WheresMyGene/components/GetStarted/style.ts
- frontend/src/views/WheresMyGene/index.tsx
- frontend/src/views/WheresMyGene/style.ts
---
1. Still need the real link for Step 3's "Learn More". Which is covered in https://app.zenhub.com/workspace/o/chanzuckerberg/single-cell-data-portal/issues/1854
> feat(wmg): Getting Started

- frontend/src/components/common/Filter/common/style.ts
- frontend/src/components/common/Filter/components/FilterMenu/index.tsx
- frontend/src/components/common/Filter/components/FilterMenu/style.ts
- frontend/src/components/common/Filter/components/FilterMultiPanel/components/FilterPanel/index.tsx
- frontend/src/components/common/Filter/components/FilterMultiPanel/components/FilterPanel/style.ts
- frontend/src/components/common/Filter/components/FilterMultiPanel/components/FilterPanelList/index.tsx
- frontend/src/components/common/Filter/components/FilterMultiPanel/components/FilterPanelList/style.ts
- frontend/src/components/common/Filter/components/FilterMultiPanel/index.tsx
- frontend/src/components/common/Filter/components/FilterMultiPanel/style.ts
- frontend/src/components/common/Filter/index.tsx
---
- Filter datasets by development stage ui. First pass.
> feat: Filter datasets by development stage (#1831)

- frontend/src/views/WheresMyGene/components/InfoPanel/common/style.ts
- frontend/src/views/WheresMyGene/components/InfoPanel/components/ExpressedInCells/index.tsx
- frontend/src/views/WheresMyGene/components/InfoPanel/components/ExpressedInCells/style.ts
- frontend/src/views/WheresMyGene/components/InfoPanel/components/Methodology/index.tsx
- frontend/src/views/WheresMyGene/components/InfoPanel/components/Methodology/style.ts
- frontend/src/views/WheresMyGene/components/InfoPanel/components/RelativeGeneExpression/index.tsx
- frontend/src/views/WheresMyGene/components/InfoPanel/components/RelativeGeneExpression/style.ts
- frontend/src/views/WheresMyGene/components/InfoPanel/components/SourceData/index.tsx
- frontend/src/views/WheresMyGene/components/InfoPanel/components/SourceData/style.ts
- frontend/src/views/WheresMyGene/components/InfoPanel/index.tsx
- frontend/src/views/WheresMyGene/index.tsx
---
- add
- remove
- modify
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1849
UPDATE (3/4): After merging latest `main`
1. Dummy data right now, will use API in a later PR
2. Methodology "our documentation" link is not added yet @hthomas-czi @signechambers1 do we know the link we wanna use already? Thank you!
> feat(wmg): Info Panel

- frontend/src/components/common/Filter/index.tsx
---
- Added filter development stage selected tags.
> Added selected tags.

- backend/Makefile
- backend/corpora/common/corpora_orm.py
- backend/database/README.md
- docker-compose.yml
---
- modify:
- update database migration `README.md`
- fixed port assignments in `docker-compose.yml`
> chore: update database migration README.md & fix docker-compose port assignments

- README.md
**Functional:** @atolopko-czi 
**Readability:** N/A 
---
- Change "corpora" to read "Single Cell Data Portal."
- Remove maintainability badge which is broken and unfixable.
- Modify push test and codecov badge to actually use new repo name. Codecov badge was previously broken.
> chore: Fix badges and remove the word corpora in a few locations.

- backend/wmg/cube_creation/wmg_cube.py
- backend/wmg/data/cube_schema.py
@MDunitz 
---
- add
- remove
- modify
> feat: wmg: make cell_type a TileDB Attr instead of Dim

- backend/wmg/cube_creation/load_cube.py
@MDunitz 
---
- add
- remove
- modify
> Add cell ordering to wmg creation script

- frontend/src/components/Footer/style.ts
- frontend/src/components/Header/style.ts
- frontend/src/components/Layout/components/sidebarLayout.tsx
- frontend/src/components/Layout/style.ts
- frontend/src/components/common/SideBar/index.tsx
- frontend/src/components/common/SideBar/style.ts
- frontend/src/pages/wmg.tsx
- frontend/src/views/WheresMyGene/components/HeatMap/components/Chart/index.tsx
- frontend/src/views/WheresMyGene/components/HeatMap/utils.ts
- frontend/src/views/WheresMyGene/index.tsx
- frontend/src/views/WheresMyGene/style.ts
> feat(wmg): cell type truncation

- frontend/src/components/common/Filter/components/FilterRange/style.ts
@tihuan 
---
- Removal of focus border display on range filter.
> fix: Additional focus border displays on range filters in staging (#2069)

- frontend/src/components/Footer/style.ts
- frontend/src/components/Header/style.ts
- frontend/src/components/Layout/components/sidebarLayout.tsx
- frontend/src/components/Layout/style.ts
- frontend/src/components/common/SideBar/index.tsx
- frontend/src/components/common/SideBar/style.ts
- frontend/src/pages/wmg.tsx
- frontend/src/views/WheresMyGene/components/HeatMap/components/Chart/index.tsx
- frontend/src/views/WheresMyGene/components/HeatMap/utils.ts
- frontend/src/views/WheresMyGene/index.tsx
- frontend/src/views/WheresMyGene/style.ts
---
1. Where's My Gene needs footer to be in the viewport, so this PR adds new props on SidebarLayout to allow custom wrappers 👌 
This means that there won't be nested scrollers anymore!
> feat(wmg): Polish layout

- frontend/package.json
- frontend/src/common/constants/routes.ts
- frontend/tests/features/wheresMyGene.test.ts
---
The smoke test currently only tests against `dev` and `staging` and not running locally, because we still need to integrate BE + FE.
After integration is done, I'll update the tests to check organism and cell type selectors too!
Thank you!
> test(wmg): Add basic smoke test

- frontend/src/views/WheresMyGene/components/QuickSelect/index.tsx
> refactor: QuickSelect type

- frontend/package-lock.json
- frontend/package.json
- frontend/src/global.scss
> feat: Change focus outline to focus-visible outline + Upgrade SDS

- backend/corpora/common/authorizer.py
- backend/corpora/lambdas/api/v1/auth/keys.py
- scripts/cxg_admin.py
- tests/unit/backend/corpora/common/utils/test_color_conversion_utils.py
> fix: convert days_to_live to int

- backend/corpora/lambdas/api/v1/auth/keys.py
- backend/corpora/lambdas/api/v1/authentication.py
> fix: use userinfo from authentication in Post auth/keys

- backend/wmg/cube_creation/rankit.py
Makes rankit values positive, addresses #2066
> make rankit values positive

- frontend/package-lock.json
- frontend/package.json
- frontend/src/views/WheresMyGene/common/store/reducer.ts
- frontend/src/views/WheresMyGene/common/types.ts
- frontend/src/views/WheresMyGene/components/Beta/style.ts
- frontend/src/views/WheresMyGene/components/Filters/index.tsx
- frontend/src/views/WheresMyGene/components/Filters/style.ts
- frontend/src/views/WheresMyGene/components/GeneSearchBar/components/Organism/index.tsx
- frontend/src/views/WheresMyGene/components/GeneSearchBar/components/Organism/style.ts
- frontend/src/views/WheresMyGene/components/GeneSearchBar/components/QuickSelect/index.tsx
- frontend/src/views/WheresMyGene/components/GeneSearchBar/components/QuickSelect/style.ts
- frontend/src/views/WheresMyGene/components/GeneSearchBar/index.tsx
- frontend/src/views/WheresMyGene/components/GeneSearchBar/style.ts
- frontend/src/views/WheresMyGene/components/QuickSelect/index.tsx
- frontend/src/views/WheresMyGene/index.tsx
---
1. Update organism, tissues, and genes selectors to match Figma
2. Hook up selectors to the reducer
3. Polish: Fix Filters to be left aligned
> feat(wmg): Organism, Tissues, and Genes selectors

- backend/config/curation-api.yml
- backend/open_api_spec.yml
---
- add: `collection_url` to GET responses of:
- `/curation/collections`
- `/curation/collections/{collection_uuid}`
> feat: add collection url

- backend/corpora/lambdas/api/v1/auth/keys.py
- tests/functional/backend/corpora/test_api_key.py
- tests/unit/backend/corpora/api_server/test_v1_auth_keys.py
---
- add cleanup to api key smoke test
- modify responses code for api key creation and deletion
-
> fix: responses code for api key creation and deletion

- frontend/src/views/WheresMyGene/components/GeneSearchBar/components/Organism/index.tsx
- frontend/src/views/WheresMyGene/components/GeneSearchBar/components/QuickSelect/index.tsx
- frontend/src/views/WheresMyGene/components/GeneSearchBar/index.tsx
- frontend/tests/features/wheresMyGene.test.ts
> test(wmg): Fix smoke test

- frontend/src/components/CreateCollectionModal/components/Content/index.tsx
@tihuan 
---
- Updated invalid DOI error message (see [Slack](https://clevercanary.slack.com/archives/C02CF7MQPGV/p1646692974823789) and [Figma](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=2728%3A31307)).
> refactor: updated invalid DOI error text.

- backend/corpora/common/corpora_orm.py
- backend/database/README.md
- backend/database/versions/27_4d70e8c321e3_add_dataset_curator_tag_column.py
@danieljhegeman @Bento007 
@danieljhegeman @Bento007 
---
- add: database migration to add the `dataset.curator_tag` column
- modify: added the `DbDataset.curator_tag` attribute to the ORM
> chore: add dataset curator tag

- backend/corpora/common/providers/crossref_provider.py
- tests/unit/backend/corpora/api_server/test_v1_collection.py
- tests/unit/backend/corpora/common/providers/test_crossref_provider.py
> chore: add published_at to publisher metadata

- frontend/src/pages/privacy.tsx
Remove summary of key changes, #1542
> feat: update privacy, remove summary of key changes

- frontend/src/pages/privacy.tsx
---
Update to address @brianraymor 's comment in the previous PR here
https://github.com/chanzuckerberg/single-cell-data-portal/pull/2122#discussion_r825163485
> fix: Privacy Page

- requirements.txt
- @Bento007 
- @atolopko-czi 
---
- Merge [prod hotfix](https://github.com/chanzuckerberg/single-cell-data-portal/pull/2184) into main
> chore: apply prod hot fix

- frontend/src/views/WheresMyGene/components/HeatMap/utils.ts
> fix: WMG update dot size

- frontend/tests/features/wheresMyGene.test.ts
> test: skip WMG tests for now

- backend/corpora/lambdas/api/v1/curation/auth/token.py
- tests/unit/backend/corpora/api_server/curator/test_auth_token.py
---
- correctly parsing the users email from identity
> chore: curation access Token generation

- backend/config/curation-api.yml
- backend/corpora/common/auth0_manager.py
- tests/functional/backend/corpora/test_api_key.py
---
generate an API key and use it to generate an access token using this API https://api-key-backend.rdev.single-cell.czi.technology/curation
> fix: token generation

- tests/functional/backend/corpora/common.py
---
- modify audience of the functional tests to match what auth0 expects.
> fix: update audience

- requirements.txt
---
- add: comment in requirements.txt re: `tiledb` version sync requirement between Explorer and Portal
> chore: added comment re: tiledb version sync with Explorer

- backend/wmg/data/extract.py
- @pablo-gar 
- @ebezzi 
---
- modify dict of included assays for single cell expression summary matrix
> chore: update included assays

- backend/Makefile
- backend/config/corpora-api.yml
- backend/corpora/common/corpora_orm.py
- backend/corpora/common/entities/dataset_asset.py
- backend/corpora/dataset_processing/process.py
- backend/database/versions/28_d7976d87cc2f_remove_datasetartifacttype.py
- scripts/cxg_admin.py
- tests/unit/backend/corpora/api_server/test_v1_collection.py
- tests/unit/backend/corpora/api_server/test_v1_dataset.py
- tests/unit/backend/corpora/common/entities/datasets/__init__.py
- tests/unit/backend/corpora/common/entities/datasets/test_create.py
- tests/unit/backend/corpora/common/entities/datasets/test_update.py
- tests/unit/backend/corpora/common/entities/test_dataset_asset.py
- tests/unit/backend/corpora/dataset_processing/test_process.py
- tests/unit/backend/fixtures/mock_aws_test_case.py
- tests/unit/backend/fixtures/test_db.py
@Bento007 
---
- remove: unused `DatasetArtifactType` enum, `dataset_artifact.type` column
> chore: removed DatasetArtifactType

- frontend/src/views/WheresMyGene/components/HeatMap/utils.ts
@seve 
---
Update axis selection style
Polish items added to #1968
> fix(wmg): Update heatmap axis select style

- backend/wmg/data/wmg_cube.py
@MDunitz @atolopko-czi 
---
- add
- remove
- modify
> feat: cell count cube

- frontend/src/common/constants/routes.ts
- frontend/src/views/WheresMyGene/components/GetStarted/index.tsx
- frontend/src/views/WheresMyGene/components/InfoPanel/components/Methodology/index.tsx
> feat(wmg): 1854 Add doc links

- backend/wmg/data/cube_pipeline.py
- backend/wmg/data/schemas/corpus_schema.py
- backend/wmg/data/tiledb.py
- backend/wmg/data/transform.py
- backend/wmg/data/wmg_cube.py
- backend/wmg/requirements.txt
---
- add code to build expression summary cube
- update pipeline to call cell count cube builder function
> feat: scex expression summary cube builder

- .happy/terraform/envs/dev/main.tf
> chore: set backend memory to 4G

- frontend/src/views/WheresMyGene/components/InfoPanel/components/Methodology/index.tsx
@seve 
---
Update text per https://czi-sci.slack.com/archives/C0247APK621/p1649197901759509
> fix(wmg): update info panel text

- frontend/src/common/constants/routes.ts
> fix(wmg): Update doc link

- .happy/terraform/envs/dev/main.tf
@MDunitz 
---
- add
- remove
- modify
> chore: set backend memory to 8G in dev

- .happy/terraform/envs/dev/main.tf
> chore: keep tweaking backend memory

- frontend/src/components/Header/index.tsx
> fix(wmg): Hide scExpression nav

- .happy/terraform/envs/dev/main.tf
> chore: dev backend memory for wmg

- scripts/setup_dev_data.sh
@atolopko-czi
---
Dev data initialization needs to be updated after file renaming.
> fix: update call to test snapshot module in setup_dev_data.sh

- .happy/terraform/envs/dev/main.tf
> fix: decrease mem allocated to backend

- .github/workflows/push-tests.yml
- backend/config/corpora-api.yml
- backend/wmg/api/v1.py
---
- modify dont require failing smoke tests to deploy with dev down
- TODO revert this pr once dev is back up
> chore: remove smoke test revert me

- .github/workflows/push-tests.yml
- backend/config/corpora-api.yml
Reverts chanzuckerberg/single-cell-data-portal#2300
> Revert "chore: remove smoke test revert me"

- .happy/terraform/envs/dev/main.tf
- .happy/terraform/modules/ecs-stack/main.tf
- .happy/terraform/modules/ecs-stack/variables.tf
> chore: set frontend memory to 4G in dev

- Dockerfile
@MDunitz 
---
- add
- remove
- modify
> chore: increase gunicorn timeout for wmg

- .happy/terraform/modules/ecs-stack/main.tf
- Dockerfile
> chore: increase gunicorn timeout for wmg (take 2)

- frontend/src/views/WheresMyGene/components/Beta/index.tsx
@seve 
---
Update beta link! It now links to this [survey](https://docs.google.com/forms/d/e/1FAIpQLSde_zIFZPQD2p0ovaX3Pb7lDOajWJCmOeuX4wQ8Z8Ab5NXUjw/viewform). Such a great idea 💡 🎉 !
> feat(wmg): Update Beta survey link

- .happy/config.json
Make sure we are running Happy migrations in rdev
---
- add
- remove
- modify
> fix: happy rdev auto_run_migrations=true

- .happy/terraform/envs/dev/main.tf
> chore: set backend memory to 50G in dev

- frontend/src/views/WheresMyGene/components/GeneSearchBar/components/Organism/index.tsx
> fix(wmg): Limit organisms

- .pre-commit-config.yaml
- requirements.txt
@metakuni @seve 
**Readability:**
> chore: bump black version in pre commit hook

- .happy/terraform/modules/ecs-stack/variables.tf
> fix(rdev): increase the frontend memory to 4096MB

- backend/wmg/data/wmg_cube.py
@MDunitz @atolopko-czi 
---
- add
- remove
- modify
> fix: wmg var_idx bug

- .happy/terraform/modules/ecs-stack/main.tf
- DEV_ENV.md
- Dockerfile
- docker-compose.yml
- frontend/README.md
- frontend/package.json
- frontend/src/configs/local-docker.js
- frontend/src/configs/local.js
- oauth/clients-config.json
- scripts/login.py
- scripts/setup_dev_data.sh
- tests/functional/backend/corpora/common.py
- tests/unit/backend/corpora/common/test_auth0_manager.py
Reverts chanzuckerberg/single-cell-data-portal#2351
Need to work with the infra team to figure out how to do this gracefully.
> fix(local): Revert Update port to 5005

- backend/wmg/data/cube_pipeline.py
- tests/unit/backend/wmg/fixtures/test_anndata_object.py
- @ebezzi 
- @atolopko-czi 
---
- modify pipeline to log which dataset (out of all datasets being processed) is being loaded
- add flag to extract data
- improve notes for anndata object
> chore: quality of life improvements

- .happy/terraform/envs/prod/main.tf
- .happy/terraform/envs/stage/main.tf
@MDunitz 
---
- add
- remove
- modify
> chore: provision wmg infra to staging and prod

- frontend/src/views/WheresMyGene/components/GeneSearchBar/components/QuickSelect/index.tsx
> fix(wmg): Fix QuickSelect unable to clear search text

- frontend/src/views/WheresMyGene/components/Filters/index.tsx
> fix(wmg): Fix Filter Panel clear selections after closing side panel

- tests/functional/backend/corpora/test_revisions.py
> fix: revision smoke tests

- backend/wmg/data/extract.py
- tests/unit/backend/wmg/data/test_extract.py
> fix: multiple assays support in wmg/extract.py

- .happy/terraform/envs/dev/main.tf
> chore: set batch memory to 120G in dev for wmg

- backend/wmg/data/wmg_cube.py
- backend/wmg/requirements.txt
---
- Also added additional logs
> chore: upgrade tiledb version wmg requirements

- backend/wmg/data/load_corpus.py
- @pablo-gar 
- @ebezzi 
---
- modify RANKIT_RAW_EXPR_COUNT_FILTERING_MIN_THRESHOLD
- Pipeline run on prod data and cube uploaded to staging for QA by @pablo-gar
> chore: update const for rankit filter

- frontend/next.config.js
- frontend/src/common/constants/routes.ts
- frontend/src/components/Header/index.tsx
- frontend/src/components/common/HomepageLink/index.tsx
- frontend/src/pages/index.tsx
- frontend/tests/features/homepage.test.ts
@ebezzi, @tihuan 
---
- Updated `/` to display datasets index page.
- Removed redirect from `/` to `/datasets`.
> fix: updated datasets to display at /. #2401

- frontend/src/pages/datasets.tsx
@ebezzi 
---
- Removed datasets page (located at /datasets).
> fix: removed datasets page. #2401

- frontend/src/views/Collection/components/DatasetTab/index.tsx
@seve 
---
- add
- remove
- modify
> fix: introduce useCallback for query invalidation function

- frontend/src/common/queries/wheresMyGene.ts
- frontend/src/views/WheresMyGene/components/GeneSearchBar/index.tsx
@seve 
---
Address comments from https://github.com/chanzuckerberg/single-cell-data-portal/pull/2382/files
Thank you!
> refactor(wmg): Address PR feedback for tissuesByOrganisms

- frontend/src/views/WheresMyGene/components/GeneSearchBar/index.tsx
> fix(wmg): 2335 Exclude Cell Culture from tissues

- frontend/src/common/queries/wheresMyGene.ts
- frontend/src/views/WheresMyGene/components/GeneSearchBar/index.tsx
> chore: deploy to staging

- frontend/src/views/WheresMyGene/components/HeatMap/components/XAxisChart/index.tsx
- frontend/src/views/WheresMyGene/components/HeatMap/components/YAxisChart/index.tsx
> fix(wmg): Use svg for axis labels, so texts are searchable

- backend/wmg/api/v1.py
- backend/wmg/data/snapshot.py
> feat: 2411 preompute primary

- backend/wmg/data/snapshot.py
> fix: remove open in primary_filter_dimensions

- frontend/tests/features/wheresMyGene.test.ts
> test(wmg): Enable WMG smoke test

- .happy/terraform/envs/rdev/main.tf
- .happy/terraform/modules/sfn/main.tf
- backend/corpora/dataset_processing/process.py
- backend/corpora/dataset_processing/process_download_validate.py
- backend/corpora/dataset_processing/remaster_cxg.py
- scripts/cxg_admin.py
- scripts/cxg_remaster.py
@metakuni @bkmartinjr 
---
- Refactors the script so that the main function body is inside the backend package
- Adds a step function that can be called to trigger the reprocessing
- Builds on top of the existing dataset_processing infra (no new docker images/permissions are needed)
> feat: cxg evolution infra

- .github/workflows/push-tests.yml
---
- add: Docker image build for dataset submission lambda container
> chore: added new image build (#2143)

- backend/corpora/lambdas/api/v1/authorization.py
- backend/corpora/lambdas/api/v1/collection.py
- backend/corpora/lambdas/api/v1/collection_uuid/upload.py
@metakuni @Bento007 
---
- add
- remove
- modify
> fix: addresses import errors

- .happy/terraform/modules/ecs-stack/main.tf
> chore: add permissions to dataset submission lambda policy

- .happy/terraform/modules/ecs-stack/main.tf
- Dockerfile
- docker-compose.yml
> fix: revert port mapping to 5000

- backend/wmg/data/transform.py
> fix: snapshot id is a string

- frontend/src/views/WheresMyGene/components/GeneSearchBar/components/QuickSelect/index.tsx
- frontend/src/views/WheresMyGene/components/GeneSearchBar/index.tsx
> fix(wmg): Gene selector csv paste is now case insensitive

- DEV_ENV.md
There is no functional change. 
@Bento007 @metakuni 
---
A dev doc was updated with an important PSA.
All future attempts to change port 5000 are avoided.
I proofread the text I added.
The English language can be ambiguous.
> docs: add Docker container port 5000 conflict tip

- frontend/src/common/analytics/events.ts
> chore: Add comment for analytics events

- backend/wmg/data/load_corpus.py
- @ebezzi 
- @pablo-gar 
---
- modify RANKIT_RAW_EXPR_COUNT_FILTERING_MIN_THRESHOLD
- add todo to remove code in the future
> chore: rankit min threshold set to 0

- frontend/src/views/Datasets/index.tsx
@tihuan 
---
- Added `isOverMaxCellCount` to list of hidden columns.
> fix: removed additional whitespace from datasets. #2482.

- .happy/terraform/envs/dev/main.tf
> chore: reduce backend memory to fit in new machine

- .happy/terraform/envs/prod/main.tf
- .happy/terraform/envs/stage/main.tf
> chore: reduce memory of dp backend service

- frontend/src/components/common/Grid/components/LinkCell/style.ts
- frontend/src/components/common/theme.ts
@tihuan 
---
- modified Collection and Datasets view title link color to primary blue.
> feat: Inconsistent hints for links that users can click (#2448)

- frontend/src/components/Collection/components/CollectionDatasetsGrid/components/Row/DatsetRow/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/CollectionRow/index.tsx
- frontend/src/components/common/Grid/components/DiseaseCell/index.tsx
- frontend/src/components/common/Grid/components/NTagCell/index.tsx
- frontend/src/views/Collections/index.tsx
- frontend/src/views/Datasets/index.tsx
@tihuan 
---
- the disease value "normal" should always be displayable and not with the +ntag cell values (see [mock](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=3610%3A31868)).
> feat: normal is not a disease (#2457)

- frontend/package-lock.json
- frontend/package.json
- frontend/src/common/queries/wheresMyGene.ts
- frontend/src/components/common/SideBar/index.tsx
- frontend/src/views/WheresMyGene/common/store/actions.ts
- frontend/src/views/WheresMyGene/common/store/reducer.ts
- frontend/src/views/WheresMyGene/common/types.ts
- frontend/src/views/WheresMyGene/components/Filters/components/Sort/index.tsx
- frontend/src/views/WheresMyGene/components/Filters/components/Sort/style.ts
- frontend/src/views/WheresMyGene/components/Filters/index.tsx
- frontend/src/views/WheresMyGene/components/Filters/style.ts
- frontend/src/views/WheresMyGene/components/HeatMap/hooks/useSortedCellTypesByTissueName.ts
- frontend/src/views/WheresMyGene/components/HeatMap/hooks/useSortedGeneNames.ts
- frontend/src/views/WheresMyGene/components/HeatMap/hooks/useTrackHeatMapLoaded.ts
- frontend/src/views/WheresMyGene/components/HeatMap/index.tsx
- frontend/src/views/WheresMyGene/components/Main/index.tsx
- frontend/src/views/WheresMyGene/components/Main/style.ts
---
Try it here 🫱 https://wmg-playground-frontend.rdev.single-cell.czi.technology/scExpression
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2502 #2502 
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2503 #2503
> feat(wmg): H Clustering #2502 #2503

- backend/wmg/requirements.txt
- @ebezzi 
---
- add cellxgene-schema to wmg reqs
> fix: add cellxgene-schema to reqs

- tests/unit/backend/wmg/test_query.py
- @atolopko-czi 
---
- modify test to run now that tiledb no longer throws that error
> fix: failing test

- frontend/next.config.js
- frontend/src/views/WheresMyGene/components/Main/index.tsx
…sion across all cell types + 2544 remove unused CSP sources
- #2544
---
- add
- remove
- modify
> fix(wmg): Column label and dots misalignment when a gene has 0 expression across all cell types + 2544 remove unused CSP sources

- .happy/terraform/envs/dev/main.tf
- @seve 
---
- modify front end memory in dev env
> chore: increase mem

- .github/workflows/push-tests.yml
- .happy/terraform/modules/ecs-stack/main.tf
- CONTRIBUTING.md
- Dockerfile
- Dockerfile.processing_image
- Makefile
- backend/corpora/api_server/README.md
- backend/database/README.md
- docker-compose.yml
- frontend/doc-site/dev/writing-documentation.mdx
- frontend/package.json
- scripts/happy-deploy.py
- #2590
---
- modify references to corpora-data-portal to unblock ontology work
> chore: replace corpora-data-portal with single-cell-data-portal

- Dockerfile.data_cube_creation
Reverts chanzuckerberg/single-cell-data-portal#2602
> Revert: "fix: copy ontology files"

- Dockerfile.data_cube_creation
- backend/wmg/data/ontology_labels.py
- #2549 
---
- add ontology files to image
- modify file access function to use pathlib
> fix: wmg batch process

- frontend/tests/features/wheresMyGene.test.ts
> test(wmg): Simplify test

- .happy/terraform/envs/prod/main.tf
> fix: increase prod memory for fe container

- frontend/src/views/WheresMyGene/style.ts
> fix(wmg): heat map bottom gets cutoff

- frontend/src/common/queries/wheresMyGene.ts
- frontend/src/views/WheresMyGene/components/InfoPanel/components/SourceData/index.tsx
@seve 
---
Datasets are now grouped and sorted by collections!
> fix(wmg): Update datasets dropdown grouped and sorted

- frontend/src/common/theme.ts
- frontend/src/components/common/staticPages/style.ts
- frontend/src/components/common/theme.ts
- frontend/src/layout.css
- frontend/src/pages/_app.tsx
- frontend/src/pages/_document.tsx
> feat: Update SDS theme

- frontend/src/components/Collections/components/Grid/components/Row/CollectionRow/index.tsx
- frontend/src/components/Collections/components/Grid/components/Row/common/style.ts
- #2595 
@tihuan 
---
- fixes disease cell not rendering as expected on my collections page
> fix: Disease cell not rendering correctly on My Collections (#2595)

- tests/performance/test_wmg_apis.py
---
- modify perf test to include reason for skipping
- ran locally with DEPLOYMENT_STAGE set to prod and dev
> fix: add reason to skip perf test

- frontend/src/components/common/Filter/components/FilterMenu/style.ts
- frontend/src/components/common/Filter/components/FilterViews/components/FilterView/index.tsx
- frontend/src/components/common/Filter/components/FilterViews/components/FilterView/style.ts
- frontend/src/components/common/Filter/components/FilterViews/components/FilterViewList/index.tsx
- frontend/src/components/common/Filter/components/FilterViews/components/FilterViewList/style.ts
- #2179 
@tihuan 
---
- modified development stage filter MUI components to SDS
> refactor: Convert development stage List and ListItem to SDS from MUI (#2179)

- frontend/doc-site/07_Join-the-CxG-User-Community.mdx
@seve 
---
- add
- remove
- modify
> fix(docs): 7 images

- scripts/cxg_admin.py
> feat: add admin script to pull s3 uris for wmg

- scripts/cxg_admin.py
- scripts/cxg_admin_scripts/deletions.py
- scripts/cxg_admin_scripts/migrate.py
- scripts/cxg_admin_scripts/reprocess_datafile.py
- scripts/cxg_admin_scripts/tombstones.py
- scripts/cxg_admin_scripts/updates.py
---
- modify cxg_admin scripts moving functions to separate files based on function action. Clean up imports, clean up comments
- ran a few commands in dev (successfully) did not test all
> refactor: cxg_admin scripts for clarity/usability

- frontend/doc-site/03_Download-Published-Data.mdx
- frontend/doc-site/04_Analyze-Public-Data/4_0-Analyze-Public-Data.mdx
- frontend/doc-site/04_Analyze-Public-Data/4_2-scExpression-Tutorials/cell-type-ontology-ordering.mdx
- frontend/doc-site/05_Annotate-and-Analyze-Your-Data/5_0-Annotate-and-Analyze-Your-Data.mdx
- frontend/doc-site/05_Annotate-and-Analyze-Your-Data/5_4-Annotating-Data.mdx
- frontend/doc-site/05_Annotate-and-Analyze-Your-Data/5_6-Analyze-Your-Data.mdx
- frontend/doc-site/07_Join-the-CxG-User-Community.mdx
- frontend/doc-site/dev/writing-documentation.mdx
- frontend/src/pages/docs/[...slug].tsx
> feat(docs): responsive images

- frontend/doc-site/08__Cite cellxgene in your publications.mdx
MLA + APA format
---
- add
- remove
- modify
> fix(docs): add cellxgene citation

- frontend/tests/features/collection/collection.test.ts
- #2551
@seve 
---
- Added skip of collection DOI-related tests.
> fix: added skip of collection DOI tests. #2551.

- backend/corpora/common/corpora_orm.py
- backend/corpora/common/entities/collection.py
---
- add function to_dict_keep. This eliminates the need to loop through the collections and datasets once.
- reducing the number of loops/
> fix: reduce looping

- .github/workflows/deploy-happy-stack.yml
- .github/workflows/push-tests.yml
> chore: add happy go client to push-tests.yml

- .github/workflows/push-tests.yml
> chore: migrate to the Go happy client part 3

- .github/workflows/push-tests.yml
> chore: remove redundant tag from happy push

- backend/wmg/data/validation/validation.py
> fix: update non prod validation numbers to match reality

- frontend/doc-site/05__Annotate and Analyze Your Data/5_6__Community Extensions.mdx
**Functional:**
@seve  
@seve 
---
- add links to community extensions page
> fix(docs): community extensions page 

- frontend/doc-site/07__Join the cxg User Community.mdx
@karenliang0 
@seve 
@karenliang0 
@seve 
---
- add links to cxg community page
> fix(docs): update links - cellxgene community page

- frontend/doc-site/01__CellxGene.mdx
- frontend/next.config.js
> fix(docs): update links on landing page

- backend/wmg/api/v1.py
- backend/wmg/data/query.py
- tests/unit/backend/wmg/api/test_v1.py
- tests/unit/backend/wmg/fixtures/test_snapshot.py
#2338 
---
- modify query api to not filter based on category for secondary filters
> feat: secondary filters

- backend/config/corpora-api.yml
- backend/config/curation-api.yml
---
- modify server names in opneapi spec
> chore: Fix server names in opneapi spec

- backend/corpora/common/utils/regex.py
- backend/corpora/dataset_submissions/app.py
- backend/corpora/lambdas/api/v1/curation/collections/collection_uuid/datasets/actions.py
> refactor: use 'tag_prefix' for tag prefix

- backend/wmg/data/utils.py
- #2409 
- @ebezzi 
---
- add decorator to easily log function run time
- created a test function and successfully called locally
> feat: add decorator to log func runtime in seconds

- backend/corpora/api_server/logger.py
**Readability:** @atolopko-czi 
---
- fix duplicate json logs by setting propagate to 0 for the flask app logger.
- remove funcName from the log message
- all log levels are set to gunicorn_logger.level
> chore: tweak logs

- backend/wmg/api/v1.py
- tests/unit/backend/wmg/api/test_v1.py
- #2774 
---
- modify secondary filters query to avoid queries when secondary filters not set
> fix: avoid unnecessary queries

- frontend/doc-site/01__CellxGene.mdx
- frontend/doc-site/032__Contribute and Publish Data.mdx
- frontend/doc-site/04__Analyze Public Data/4_0__Get Started.mdx
- frontend/doc-site/04__Analyze Public Data/4_2__scExpression Documentation/4_2_1__Get Started.mdx
- frontend/doc-site/04__Analyze Public Data/4_3__Algorithms and Ontologies.mdx
- frontend/doc-site/05__Annotate and Analyze Your Data/5_0__Get Started.mdx
- frontend/doc-site/05__Annotate and Analyze Your Data/5_1__Getting Started: Install, Launch, Quick Start.mdx
- frontend/doc-site/05__Annotate and Analyze Your Data/5_2__Self Host cellxgene.mdx
- frontend/doc-site/05__Annotate and Analyze Your Data/5_4__Annotating Data.mdx
- frontend/doc-site/05__Annotate and Analyze Your Data/5_5__Gene Sets.mdx
- frontend/doc-site/09__Frequently Asked Questions.mdx
- frontend/package-lock.json
- frontend/src/pages/docs/[...slug].tsx
Also adds a page title for docs pages
> fix(docs): fix various broken links

- Dockerfile.data_cube_creation
- #2820 
- @ebezzi 
---
- add
- remove
- modify
> fix: add pipeline code to docker file

- Dockerfile.data_cube_creation
- backend/config/curation-api.yml
- backend/corpora/common/utils/color_conversion_utils.py
- backend/corpora/lambdas/api/v1/auth/keys.py
- backend/corpora/lambdas/api/v1/collection.py
- backend/corpora/lambdas/api/v1/collection_uuid/gene_set.py
- backend/corpora/lambdas/api/v1/collection_uuid/upload.py
- backend/corpora/lambdas/api/v1/common.py
- backend/corpora/lambdas/api/v1/curation/auth/token.py
- backend/corpora/lambdas/api/v1/curation/collections/collection_uuid/actions.py
- backend/corpora/lambdas/api/v1/curation/collections/collection_uuid/assets.py
- backend/corpora/lambdas/api/v1/curation/collections/collection_uuid/datasets/actions.py
- backend/corpora/lambdas/api/v1/dataset.py
- tests/functional/backend/corpora/test_revisions.py
- tests/unit/backend/corpora/api_server/curator/collection/test_curation_collections.py
> chore: deploy staging

- Makefile
---
- Remove host configuration
> chore: remove local-hostconfig

- backend/scripts/mirror_s3_data.sh
- #1735 
@MDunitz 
---
don't copy s3 tags to avoid iam perm error
Running successfully on prod->staging
> fix: s3 object tagging perms

- .github/workflows/push-tests.yml
@tihuan 
---
- add
- remove
- modify
> chore: add git variables to happy push

- .github/workflows/deploy-happy-stack.yml
> chore: set working directory for functional test in deploy-happy action

- .github/workflows/deploy-happy-stack.yml
- .github/workflows/push-tests.yml
> chore: set working directory for smoke test in deploy-happy action

- backend/wmg/data/cube_pipeline.py
---
- modify wmg pipeline slack success (and failure) alert messages to specify `wmg`
> fix: update slack alert message for clarity

- frontend/src/components/LandingFooter/index.module.scss
- frontend/src/components/LandingHeader/index.tsx
- frontend/src/components/LandingHeader/style.ts
- frontend/src/pages/landing-page/index.module.scss
updating hover styles for landing page links
> chore: updating styling for landing links hover states

- Dockerfile
- Dockerfile.processing_image
- backend/Makefile
- backend/corpora/api_server/requirements.txt
- backend/corpora/common/utils/color_conversion_utils.py
- backend/corpora/common/utils/http_exceptions.py
- backend/corpora/dataset_processing/h5ad_data_file.py
- backend/corpora/dataset_processing/requirements.txt
- requirements.txt
- tests/unit/backend/corpora/api_server/test_v1_collection.py
- tests/unit/backend/corpora/common/utils/test_color_conversion_utils.py
Required to fix our builds.
---
- add
- remove
- modify
> chore: upgrade to ubuntu 22.04 LTS + python3.10

- backend/config/curation-api.yml
> fix: Make explorer_url and is_primary_data nullable in dataset response

- Dockerfile.upload_failures
> fix: upload failure docker file
