backend/config/gene-info-api.yml
backend/corpora/api_server/app.py
backend/corpora/common/auth0_manager.py
backend/corpora/common/utils/slack.py
backend/gene_info/api/ensembl_ids.py
backend/gene_info/api/v1.py
backend/wmg/data/cube_pipeline.py
frontend/src/components/LandingFooter/index.module.scss
frontend/src/components/LandingHeader/index.tsx
frontend/src/components/LandingHeader/style.ts
frontend/src/pages/landing-page/index.module.scss
tests/unit/backend/gene_info/test_v1.py

chore: (re)deploy prod <- staging without squashing like I did 20 minutes ago

---

backend/config/corpora-api.yml
frontend/src/common/API.ts

- @seve 
- @atolopko-czi 
---
- remove unused wmg prototype code

chore: remove wmg prototype code

---

.github/workflows/deploy-happy-stack.yml

---
- modify the upgrade Github actions to run the tests in parallel after deployment has finished.

fix(deployment): Run tests in parallel during upgrade

---

backend/corpora/lambdas/api/v1/curation/collections/common.py

---
- Not sure how this snuck in, but it's breaking list collections in the curation API.

fix(GET collection): remove static from add_collection_level_processing_status

---

backend/corpora/dataset_processing/requirements.txt
backend/wmg/data/query.py
requirements.txt

- #2901 
---
- modify tiledb version, update wmg query code

chore: upgrade tiledb, remove pandas filtering

---

backend/corpora/lambdas/api/v1/curation/collections/common.py

- #3105 
---
- modify how the collection id response is built to remove artifacts from the response even if it's an empty list.

fix(curation api): remove artifact from GET collection_id response

---

backend/corpora/common/utils/dl_sources/url.py

- #3122
**Readability:** @ebezzi 
---
- Add support for additional AWS pre-signed URL formats.

fix(curation api):Support more AWS pre-signed url formats

---

backend/config/curation-api.yml

- #2983 
---
- add
- remove
- modify

fix(curation api): organize x_ values in openapi

---

frontend/src/components/common/Filter/components/BasicFilter/index.tsx
frontend/src/components/common/Filter/index.tsx

- #3144
---
- modified Filters to open to right of target.

feat: Open filters to the right of target (#3144)

---

frontend/src/components/common/Filter/components/FilterContent/components/FilterViews/components/FilterSinglePanelCategoryView/index.tsx
frontend/src/components/common/Filter/components/FilterContent/components/FilterViews/components/FilterView/index.tsx
frontend/src/components/common/Filter/components/FilterContent/components/FilterViews/components/FilterView/style.ts

- #3145 
---
- modified filter panel labels to remain sticky on scroll

feat: Freeze filter panel labels on scroll (#3145)

---

frontend/src/components/common/Filter/components/FilterContent/components/FilterViews/components/FilterMultiPanelCategoryView/style.ts
frontend/src/components/common/Filter/components/FilterContent/components/FilterViews/style.ts
frontend/src/components/common/Filter/components/FilterContent/index.tsx
frontend/src/components/common/Filter/components/FilterContent/style.ts

- #2921 
---
- modified FilterContent component to always maintain menu height when filtering.

feat: Add omnisearch to tissue filter (#2921)

---

backend/config/curation-api.yml

- #2793 
---
- remove self example from openapi

fix: remove self example from openapi

---

backend/config/curation-api.yml

- #3122
**Functional:** @nayib-jose-gloria 
---
- modify upload link documentation to include the types of links we currently support.

fix: document upload links that are suported

---

frontend/src/components/common/Filter/components/BasicFilter/index.tsx

- #2921 
---
- modified filter position to top, right.

feat: Top-left align filter menus (#3175)

---

frontend/src/components/common/Filter/components/FilterContent/components/FilterMenu/index.tsx
frontend/src/components/common/Filter/components/FilterContent/components/FilterViews/components/FilterViewList/index.tsx
frontend/src/components/common/Filter/components/FilterContent/index.tsx
frontend/src/components/common/Filter/components/FilterSearch/common/useFilterSearch.ts
frontend/src/components/common/Filter/components/FilterSearch/style.ts
frontend/src/components/common/Filter/index.tsx

- #2929 
---
- removed ui related Filter TODOs.
- refactored FilterViewList component to address typescript TODO.

refactor: Update tissue filter to hierarchical UI (#2929)

---

frontend/src/common/constants/routes.ts

fix: fixing scExpression Help & Documentation link

---

scripts/validate_rds.R

chore: add RDS validation script

---

frontend/src/common/constants/routes.ts

---
This hotfix needs to be merged into main so that it gets included in the Staging deploy on Tuesday. It is already in prod. Normally I would merge back from prod, but I messed up the deploy PR's this week, and it resulted in a totally chaotic diff between prod and staging/main, even though that diff isn't present when viewed locally. I don't get it. A github peculiarity I think. Anyways, let's add this.

fix: sc expression doc link

---

frontend/src/components/common/Filter/components/FilterContent/components/FilterViews/components/FilterMultiPanelCategoryView/index.tsx
frontend/src/components/common/Filter/components/FilterContent/index.tsx
frontend/src/components/common/Filter/components/FilterSearch/common/useFilterSearch.ts

- #3234 
---
- modified ontology multi panel to enable multi select search results.

feat: Enable multiselect search results for tissue (#3234)

---

frontend/src/components/common/Grid/components/HeaderCell/index.tsx
frontend/src/components/common/Grid/components/HeaderCell/style.ts
frontend/src/components/common/Grid/style.ts
frontend/src/views/Collections/index.tsx
frontend/src/views/Datasets/index.tsx

- #3235 
---
- added result set count to datasets and collections

feat: Add result set count to datasets and collections (#3235)

---

backend/config/curation-api.yml

- #2161 
---
- modify "$ref" to $ref in curation_api.yml

fix(curator api): normalize $ref

---

backend/corpora/dataset_submissions/app.py
tests/unit/backend/corpora/api_server/curator/collection/test_assets.py
tests/unit/backend/corpora/api_server/curator/collection/test_curation_collections.py

- remove from lambda code
- remove from tests and refactor to fit unidimensional status
- #3153
@Bento007 
---
- add
- remove
- modify
unit tests are ✅

feat: finish removal of curator_tag

---

backend/corpora/dataset_submissions/app.py
tests/unit/backend/corpora/lambdas/dataset_submissions/test_dataset_submissions.py

- #3153 
@Bento007 
---
- make sure Dataset exists in the correct Collection

fix: submission handler

---

frontend/src/components/common/Grid/components/CountCell/style.ts
frontend/src/components/common/Grid/style.ts

- #3262 
@tihuan
---
- Removed prefixes from font-feature-settings for datasets and collections table.

refactor: Remove prefixes from font-feature-settings (#3262)

---

frontend/src/views/Landing/index.tsx

- modify
- "donors" converted to "cell types" [per discussion](https://czi-sci.slack.com/archives/C039X645880/p1660092739385619?thread_ts=1659554738.891779&cid=C039X645880).
- updated values using today's numbers from superset.

fix(landing): update hero numbers

---

backend/corpora/dataset_processing/process.py

**Functional:** @nayib-jose-gloria 
---
- modify exception handling in the processing container to log the exception first.

fix: log exception before processing futher.

---

scripts/cxg_admin.py

**Functional:** @pablo-gar 
---
- the deployment used for cxg_admin can be specified in DEPLOYMENT_STAGE.

fix(cxg_admin): pass in DEPLOYMENT_STAGE from environment

---

frontend/doc-site/03__Download Published Data.mdx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/DataFormat/index.tsx

- #3290
---
- update doc and UI references from Seurat v3 to v4, since we are now using Seurat/SeuratObject v4 for sceasy conversion

chore: update doc and UI references from Seurat v3 to v4

---

frontend/src/components/common/Filter/components/FilterContent/components/FilterViews/components/FilterMultiPanelCategoryView/index.tsx
frontend/src/components/common/Filter/components/FilterContent/index.tsx

- #3348 
@seve 
---
- Modified omni-search to always show for cell type and tissue filters.

fix: Omni-search disappears on select of cell type filter values (#3348)

---

frontend/src/components/common/Filter/common/style.ts
frontend/src/components/common/Filter/components/FilterContent/components/FilterViews/components/FilterView/style.ts

- #3347 
@seve 
---
- Updated filter menu scrollbar ui hover styles to match [mock](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=4148%3A37736).

feat: Update filter menu scrollbar UI (#3347)

---

frontend/tests/features/wheresMyGene.test.ts

#3361
**Functional:** @atarashansky @seve 
**Readability:** @atarashansky @seve 
---
- add
- remove
- modify
- Updating smoketests for new skeleton wmg landing

fix: smoketests for new skeleton

---

backend/corpora/api_server/app.py
backend/corpora/common/utils/cloudfront.py

**Functional:** @nayib-jose-gloria 
**Readability:** @ebezzi 
---
- fix how we are logging the cloudfront invalidation response.
- Catch and log all exceptions and raise internal error on API.

fix: cloudfront response logging.

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/common/Modal/index.tsx
frontend/src/components/common/Modal/style.ts
frontend/src/views/WheresMyGene/components/GeneSearchBar/components/SaveImage/index.tsx
frontend/src/views/WheresMyGene/components/GeneSearchBar/components/SaveImage/style.ts
frontend/src/views/WheresMyGene/components/GeneSearchBar/index.tsx
frontend/src/views/WheresMyGene/components/GeneSearchBar/style.ts
frontend/src/views/WheresMyGene/components/HeatMap/components/Chart/index.tsx
frontend/src/views/WheresMyGene/components/HeatMap/components/YAxisChart/index.tsx
frontend/src/views/WheresMyGene/components/InfoPanel/components/ColorScale/style.ts
frontend/src/views/WheresMyGene/components/Main/index.tsx
frontend/src/views/globalStyle.ts

- #3243 
**Readability:** @atarashansky 
---
- add
- Add ability to download multiple tissues into a zip  
- modify
- Changed download method

feat(wmg-download): enable downloading of multiple tissues

---

frontend/next.config.js

https://github.com/Touffy/client-zip#webassembly-and-content-security-policy

fix(fe-infra): add 'wasm-unsafe-eval' to CSP to allow for wasm

---

frontend/src/views/WheresMyGene/components/GeneSearchBar/components/SaveImage/index.tsx

fix(GeneExpression): Remove the modal and SVG option for download image

---

frontend/src/views/WheresMyGene/components/GeneSearchBar/components/SaveImage/index.tsx

fix(wmg-download): HOTFIX disable SVG's and set pixel ratio to 4

---

backend/corpora/common/authorizer.py
backend/corpora/common/corpora_config.py
backend/corpora/common/corpora_orm.py
backend/corpora/common/entities/__init__.py
backend/corpora/common/entities/collection.py
backend/corpora/common/entities/dataset.py
backend/corpora/common/entities/dataset_asset.py
backend/corpora/common/entities/entity.py
backend/corpora/common/entities/geneset.py
backend/corpora/common/providers/crossref_provider.py
backend/corpora/common/upload.py
backend/corpora/common/utils/db_session.py
backend/corpora/common/utils/json.py
backend/corpora/common/utils/secret_config.py
backend/corpora/lambdas/api/v1/authentication.py
backend/corpora/lambdas/api/v1/collection.py
backend/corpora/lambdas/api/v1/collection_id/gene_set.py
backend/corpora/lambdas/api/v1/collection_id/publish.py
backend/corpora/lambdas/api/v1/collection_id/upload.py
backend/corpora/lambdas/api/v1/curation/collections/actions.py
backend/corpora/lambdas/api/v1/curation/collections/collection_id/actions.py
backend/corpora/lambdas/api/v1/curation/collections/common.py
backend/corpora/lambdas/api/v1/dataset.py
backend/corpora/lambdas/api/v1/gene_sets.py

- #3394 
---
- modify all imports to be absolute imports.

fix: Remove relative imports

---

backend/corpora/common/upload.py
tests/unit/backend/corpora/dataset_processing/test_common.py

…t (#3459)
* fix: update validation status and message when files exceed size limit
* test: add test for upload of file that exceeds size limit
* fix: specify max file size in GB
---
- add
- remove
- modify

chore: deploy staging <- main -- take ✌️ 

---

DEV_ENV.md

Remove happy from readme as it is not needed for this dev env
- #TICKET_NUMBER 3472
@ebezzi 
@atolopko-czi 
---
- remove old requirement for happy

docs: Clean README to remove happy

---

tests/functional/backend/corpora/test_revisions.py

- #3414
---
- fix typo, passed a positional argument to an inner function that doesn't need any after a refactor

fix: resolve test_revisions helper function TypeError

---

Dockerfile.processing_image
scripts/remaster_cxg_v0.3.0.ipynb

fix: paths for the processing container broken after refactor

---

frontend/src/views/WheresMyGene/components/InfoPanel/components/SourceData/index.tsx

https://github.com/chanzuckerberg/single-cell-data-portal/issues/3503

fix(GeneExpression): source data no longer filtered out when no datasets are selected

---

backend/portal/pipeline/processing/process_download_validate.py

fix: add tolist() to pandas arrays during metadata extraction

---

backend/portal/pipeline/processing/process_download_validate.py
tests/functional/backend/common.py

chore: Staging deploy 2022-11-1

---

frontend/tests/features/collection/collection.test.ts
frontend/tests/features/collection/revision.test.ts
frontend/tests/features/wheresMyGene.test.ts
frontend/tests/utils/helpers.ts

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/3454
- #3454
@seve 
---
1. Update test skipping with Playwright's [test annotation](https://playwright.dev/docs/test-annotations#conditionally-skip-a-test) syntax, so we can document why specific tests are skipped in pre-deployed or post-deployed 
1. Update some tests to run in more deployed environments

test(smoketest): 3454 Update test annotations

---

.github/workflows/deploy-happy-stack.yml
frontend/tests/features/collection/collection.test.ts

- #3454 
---
- add
- remove
- modify

test(smoketest): 3454 update test

---

.github/workflows/deploy-happy-stack.yml
frontend/tests/features/collection/collection.test.ts
frontend/tests/features/collection/revision.test.ts
frontend/tests/features/wheresMyGene.test.ts
frontend/tests/utils/helpers.ts

chore: Staging Deploy

---

.github/workflows/push-tests.yml

- Merging in GHA workflow changes from main; only changes, will be QA tested by the staging deploy itself

chore: staging deploy 11/07

---

Dockerfile.data_cube_creation

- fix cube generation error seen [here](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/$252Fdp$252Fdev$252Fdevstack$252Fwmg-processing/log-events/dp-dev-devstack-wmg-processing$252Fdefault$252F74c4b8fe2143482aa4e372dc2c44428f)

fix: re-add backend.wmg.config module to data cube creation dockerfile

---

backend/wmg/data/tissue_mapper.py

chore: remove 'upper outer quadrant of breast' from hihg-level tissus Gene Expression

---

scripts/thrash_api.py

chore: Add api thrash script

---

backend/wmg/data/rankit.py
backend/wmg/data/tissue_mapper.py

fix(WMG): unblock wmg pipeline by handling edge case where rows are all zeros

---

backend/portal/pipeline/processing/common.py
frontend/tests/utils/helpers.ts
scripts/login.py

- #3598 
@atolopko-czi @tihuan 
---
- add
- remove
- modify

chore: a couple remaining http -> https changes

---

.dockerignore
DEV_ENV.md
Dockerfile.backend
docker-compose.yml

Also: rename Dockerfile to Dockerfile.backend
- #3598 
---
- add
- remove
- modify

fix: add container_init.sh to backend docker container build

---

.github/workflows/push-tests.yml

- https://github.com/chanzuckerberg/single-cell-data-portal/issues/3193
**Functional:** @ashin-czi 
---
-modify the run order for the publish-test-results actions so history is included.

fix: publish test results ordering.

---

frontend/src/views/WheresMyGene/components/GeneSearchBar/components/QuickSelect/index.tsx
frontend/src/views/WheresMyGene/components/HeatMap/index.tsx
frontend/src/views/WheresMyGene/components/Main/index.tsx

- #3652
**Functional:** @atarashansky 
**Readability:** @atarashansky 
---
- add
- remove
- modify
- raising yAxisWrapper zindex after hiding getting started step 1 so that scroll works for the axis

fix: cant scroll after selecting tissue

---

frontend/src/pages/_app.tsx

redirectUri

---

frontend/src/views/WheresMyGene/components/Beta/index.tsx

- #3583
**Functional:** @tihuan @atarashansky @seve 
**Readability:** @tihuan @atarashansky @seve 
---
- add
- remove
- modify
- Change gene expression survey link

feat: new gene expression survey link

---

frontend/src/views/WheresMyGene/components/Beta/index.tsx

- #3569
---
- add
- remove
- modify
- increasing beta message z-index

fix: beta message should always be on top of everything

---

.happy/terraform/modules/ecs-stack/main.tf

chore(wmg): update the compute environment used for wmg processing pipeline

---

frontend/src/components/CreateCollectionModal/components/Content/components/Consortia/index.tsx
frontend/src/components/CreateCollectionModal/components/Content/index.tsx
frontend/src/components/CreateCollectionModal/components/Content/style.ts
frontend/src/components/common/Form/Dropdown/index.tsx
frontend/src/components/common/Form/Dropdown/style.ts
frontend/src/components/common/Form/Input/index.tsx
frontend/src/components/common/Form/common/style.ts

- #3642 
@NoopDog 
---
- added new consortia dropdown in new/edit collection form.

feat: Add optional Consortia dropdown in New and Edit Collection with the required enumeration of approved consortia (#3642)

---

frontend/src/components/common/Form/Dropdown/style.ts
frontend/src/components/common/Form/common/style.ts

- #3642 
@NoopDog 
---
- refactored consortia dropdown style listing.

Add optional Consortia dropdown in New and Edit Collection with the required enumeration of approved consortia. Linting. (#3642)

---

frontend/src/components/Header/index.tsx
frontend/src/components/LandingHeader/index.tsx
frontend/src/views/WheresMyGene/components/Beta/index.tsx

- #3701 
---
- remove 
- Remove Beta chip
- Remove "This feature is in beta" in callout

feat(wmg): Remove beta tag

---

scripts/populate_db.py

@Bento007 
---
- add
- remove
- modify

fix: broken import from recent refactors

---

frontend/src/views/WheresMyGene/components/HeatMap/components/YAxisChart/index.tsx

- #3661
**Functional:** @atarashansky 
**Readability:** @atarashansky 
---
- add
- remove
- modify
- Using regex to find and replace whitespace to hyphens for selectors

fix: Gene Expression Source Data not populating

---

frontend/tests/features/wheresMyGene.test.ts

Tested locally and the E2E tests work now.
The issues were:
1) beta chip was recently removed
2) test ID for y axis charts were appended with tissue ID suffix

chore: fix post-deployment e2e tests

---

frontend/src/components/Header/components/AuthButtons/index.tsx
frontend/src/configs/common.js
frontend/src/configs/dev.js
frontend/src/configs/rdev.js
frontend/src/configs/staging.js

refactor(3598): feedback

---

frontend/tests/features/wheresMyGene.test.ts

fix(WMG): update e2e tests after MUIv5 upgrade

---

frontend/src/views/WheresMyGene/components/InfoPanel/components/SourceData/index.tsx
frontend/tests/features/wheresMyGene.test.ts

test(wmg): Fix Source Data

---

frontend/src/views/WheresMyGene/components/InfoPanel/components/SourceData/index.tsx
frontend/tests/features/wheresMyGene.test.ts

test(wmg): Fix Data Source part 2

---

frontend/src/configs/common.js
frontend/src/configs/dev.js
frontend/src/configs/local.js
frontend/src/configs/prod.js
frontend/src/configs/rdev.js
frontend/src/configs/staging.js
frontend/src/pages/_app.tsx

- #3807 
@tihuan 
---
- add `audience` prop to ensure returned access token contains a payload
- verified in dev

feat: fix jwt payload

---

frontend/src/views/WheresMyGene/components/HeatMap/components/YAxisChart/index.tsx

- #3799
**Functional:** @tihuan @atarashansky @seve 
**Readability:** @tihuan @atarashansky @seve 
---
- add
- Creating list for exclusion of certain tissues from FMG
- remove
- modify

feat: Exclude Blood from FMG

---

frontend/tests/features/wheresMyGene.test.ts

chore(wmg): update e2e y axis text locator to capture buttons instead of text elements.

---

frontend/src/views/WheresMyGene/components/HeatMap/index.tsx

---
alternative to https://github.com/chanzuckerberg/single-cell-data-portal/pull/3882
@atarashansky found that I broke echarts init in this [PR](https://github.com/chanzuckerberg/single-cell-data-portal/pull/3882) (Thanks so much 🙏 !) And this is my proposed fix to avoid adding dependencies we don't use in a hook

fix(wmg): echarts init

---

backend/wmg/data/constants.py
backend/wmg/data/transform.py

[This failed test in wmg-processing-unit-test](https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/3874147388/jobs/6605696195) (see screenshot attached) seems to be due to the ontology site 404-ing.
The culprit: http://purl.obolibrary.org/obo/cl-basic.obo
[Relevant slack thread](https://czi-sci.slack.com/archives/C023Q1APASK/p1673273314865159)

fix(wmg): update cl-basic.obo link

---

frontend/doc-site/04__Analyze Public Data/4_2__Gene Expression Documentation/4_2_5__Find Marker Genes.mdx

chore(fmg): update docs with revised language

---

.github/workflows/push-tests.yml

chore(GHA): Remove feature branch from push_test

---

backend/portal/api/curation/v1/curation/collections/collection_id/datasets/actions.py
tests/unit/backend/layers/api/test_curation_api.py

Tests updated to check for condition

fix: curation post dataset for unpublished collections

---

frontend/src/common/entities.ts
frontend/src/components/CreateCollectionModal/components/Content/common/utils.ts

- #3973 
@tihuan 
---
- modified `consortia` type as per [PR review](https://github.com/chanzuckerberg/single-cell-data-portal/pull/3875/files#r1067566222).

refactor: Refactor consortia type (#3973)

---

.happy/terraform/modules/sfn/main.tf

- #3992 
- 
---
- add retries to dataset pipeline for failure and success handlers.

fix: add retries to dataset pipeline for failure and success handlers.

---

backend/portal/api/app/portal-api.yml
backend/portal/api/curation/curation-api.yml

#3997
@ebezzi 
---
- modify descriptions of the `consortia` field on collections in the swagger docs to document the allowed consortia.

docs: add valid consortia to swagger apis (#3997)

---

backend/wmg/api/wmg-api.yml

chore(fmg): cherry pick hotfix to marker gene api schema into main

---

frontend/src/views/WheresMyGene/components/CellInfoSideBar/index.tsx

feat(fmg): Always send fmg info hover event on doc navigation

---

frontend/src/common/featureFlags/features.ts
frontend/src/common/queries/wheresMyGene.ts
frontend/src/views/WheresMyGene/common/store/reducer.ts
frontend/src/views/WheresMyGene/components/Filters/components/Sort/index.tsx
frontend/src/views/WheresMyGene/components/HeatMap/components/YAxisChart/index.tsx
frontend/src/views/WheresMyGene/components/HeatMap/hooks/useSortedCellTypesByTissueName.ts
frontend/src/views/WheresMyGene/components/HeatMap/index.tsx
frontend/src/views/WheresMyGene/components/Main/index.tsx

Reverts chanzuckerberg/single-cell-data-portal#3906 and adds a feature flag to using hierarchical sort by default

chore(fmg): Add feature flag to default hierarchical sort 

---

backend/portal/api/portal-api.yml
frontend/src/common/queries/common.ts
frontend/src/pages/_app.tsx

- Necessary to support persistent login
- add
- remove
- modify

fix: Support Persistence Login for Auth0 Single Page Application with Refresh Token Rotation

---

backend/wmg/pipeline/summary_cubes/calculate_markers.py
backend/wmg/pipeline/summary_cubes/marker_genes.py

add comments

---

.github/ISSUE_TEMPLATE/tech-issue.md

#4124
see title
not possible to test until it's in main, afaict

chore: add github issue template for tech issues

---

frontend/src/common/featureFlags/features.ts
frontend/src/common/queries/wheresMyGene.ts
frontend/src/views/WheresMyGene/components/HeatMap/components/XAxisChart/index.tsx
frontend/src/views/WheresMyGene/components/HeatMap/components/YAxisChart/index.tsx
frontend/src/views/WheresMyGene/components/HeatMap/utils.ts

- #4168 
- Feature is ready for public consumption.
- removed feature flag and depth from label formatting

chore(wmg): remove feature flag and depth

---

backend/wmg/api/v1.py

- #4115
Changes for compare feature to handle generating compare gene expressions on the backend. Response structure is also changed to:
```json
{
"ENSG00000000003": {
"UBERON:0000178": {
"CL:0000003": {
"aggregated": {
"me": 4.982746259810133,
"n": 1835602,
"pc": 0.986583107819399,
"tpc": 0.015415361059678109
},
"female": {
"me": 4.982746259810133,
"n": 1835602,
"pc": 0.986583107819399,
"tpc": 0.015415361059678109
},
"male": {
"me": 4.982746259810133,
"n": 1835602,
"pc": 0.986583107819399,
"tpc": 0.015415361059678109
}
},
"CL:0000037": {
"aggregated": {
"me": 4.982746259810133,
"n": 1835602,
"pc": 0.986583107819399,
"tpc": 0.015415361059678109
},
"female": {
"me": 4.982746259810133,
"n": 1835602, …
```

feat(wmg): backend compare changes

---

frontend/src/configs/common.js

- #3830 
- add
- remove
- modify

fix: add back configs common.js

---

.github/workflows/push-rdev.yml

I'm sick of grepping the job logs for the sha to use in happy commands, this should make it easier

chore: surface image SHA with happy commands in GH job summary for easy copy + paste

---

frontend/src/views/Landing/index.module.scss
frontend/src/views/Landing/index.tsx

simple update, freethink video section changed from 1-col to 2-col layout

chore: updating freethink video section

---

Dockerfile.upload_failures
backend/curation/api/v1/curation/collections/common.py
backend/layers/business/business.py
backend/layers/persistence/persistence.py
backend/layers/persistence/persistence_mock.py
frontend/package-lock.json
tests/unit/backend/layers/business/test_business.py

chore: Staging Deploy 2-22-2023

---

frontend/src/views/WheresMyGene/components/CellInfoSideBar/index.tsx
frontend/src/views/WheresMyGene/components/CellInfoSideBar/style.ts

…4201)
* feat(wmg): Users need a way to assess the strength of marker genes
* filtering bad genes and limiting marker genes
* marker gene strength in fmg panel thead
* reverting remove bad genes change as it will be another ticket
* removing inline style from td
- add
- remove
- modify

chore: Staging Deploy 2-22-2023 Part 2

---

backend/wmg/data/snapshot.py

This will be removed after prod deploys on Thursday (3/2).

chore(wmg): add backwards compatibility for the performance improvements upgrade

---

frontend/src/views/Landing/index.tsx

Updates the top level metrics in the landing page.

chore: update high-level metrics of landing page

---

frontend/src/views/WheresMyGene/components/GeneSearchBar/components/ShareButton/index.tsx
frontend/src/views/WheresMyGene/components/GeneSearchBar/components/ShareButton/utils.tsx

[Context](https://czi-sci.slack.com/archives/C0247APK621/p1677862105425899?thread_ts=1677860373.890269&cid=C0247APK621)
- change join character from `-` to `,`
- disable share link when tissues or genes not selected
- add versioning

fix(wmg): change join character to comma for shared links

---

backend/wmg/data/snapshot.py

Reverts chanzuckerberg/single-cell-data-portal#4274
#4275

chore(wmg): remove backwards compatibility for the performance improvements upgrade

---

frontend/src/common/constants/routes.ts
frontend/src/components/LandingFooter/index.tsx
frontend/src/pages/sitemap.tsx

- placing sitemap on footer 
- updating sitemap in `routes.ts` 
- updating title tag on sitemap page

chore: sitemap updates

---

frontend/src/views/WheresMyGene/common/constants.ts
frontend/src/views/WheresMyGene/common/store/reducer.ts
frontend/src/views/WheresMyGene/components/GeneSearchBar/components/ShareButton/index.tsx
frontend/src/views/WheresMyGene/components/GeneSearchBar/components/ShareButton/utils.tsx

- #4116 
- add
compare option to share link
also updated share link analytics events to include compare
1. Select a compare option
2. Copy share link
3. Paste share link
4. Observe that compare option is populated

feat(wmg): add compare to share link

---

frontend/src/views/WheresMyGene/common/store/reducer.ts
frontend/src/views/WheresMyGene/components/GeneSearchBar/components/ShareButton/index.tsx
frontend/src/views/WheresMyGene/components/GeneSearchBar/components/ShareButton/utils.tsx

https://github.com/chanzuckerberg/single-cell-data-portal/issues/4285
Adds organism to share URL (version 3)
Also adds organism to analytics payload

fix(wmg): add organism to share url

---

frontend/src/components/common/SideBar/index.tsx
frontend/src/views/WheresMyGene/common/store/reducer.ts
frontend/src/views/WheresMyGene/components/Main/index.tsx

#4281 
Also change some var names for readability

fix(wmg-fmg): reset cell type info value on organism switch

---

backend/wmg/pipeline/cube_pipeline.py

See #4353 for context. This patch unblocks dev pipeline runs.

chore(wmg): disable validation until validation tests are updated to match new schemas

---

backend/wmg/api/v1.py

fix: type error

---

frontend/src/views/Landing/index.tsx

Updates landing page numbers to latest on Mar 20, 2023

chore: update landing page numbers

---

frontend/src/views/WheresMyGene/components/CellInfoSideBar/index.tsx
frontend/src/views/WheresMyGene/components/Filters/components/ColorScale/index.tsx
frontend/src/views/WheresMyGene/components/Filters/index.tsx

- #4210 
- [Slack message with video](https://czi-sci.slack.com/archives/C0247APK621/p1679325493152269)

chore(wmg): update color scale and warning tooltips in filter panel

---

frontend/src/views/WheresMyGene/components/GeneSearchBar/components/SaveImage/utils.ts
frontend/src/views/WheresMyGene/components/HeatMap/components/XAxisChart/style.ts

- #4216 
- add
- remove
- modify

chore(wmg): flip gene and cell count labels 180deg

---

backend/curation/api/curation-api.yml
backend/curation/api/v1/curation/collections/collection_id/actions.py
backend/curation/api/v1/curation/collections/collection_id/datasets/actions.py
backend/curation/api/v1/curation/collections/collection_id/datasets/dataset_id/actions.py
backend/curation/api/v1/curation/collections/collection_id/datasets/dataset_id/assets.py
backend/curation/api/v1/curation/collections/collection_id/s3_upload_credentials.py
backend/curation/api/v1/curation/collections/collection_id/versions.py
backend/curation/api/v1/curation/collections/common.py
backend/layers/business/business.py
backend/portal/api/portal_api.py
tests/unit/backend/layers/api/test_curation_api.py
tests/unit/backend/layers/api/test_portal_api.py

- #4328 
- add: collections 'versions' endpoint
- modify: 
- consolidate "identifier is not uuid format" error-checking code into common function and replace in existing code. 
- Standardize on 403 rather than some 404 and some 403.
- unrelated typo fix for function name
- Unit tested

feat: implement GET /collections/{collection_id}/versions

---

frontend/src/views/WheresMyGene/components/GeneSearchBar/components/SaveImage/utils.ts

chore(wmg): adjust gene label spacing in svg download

---

.github/workflows/push-tests.yml
Makefile

- https://github.com/chanzuckerberg/single-cell-data-portal/issues/4384
- add local-integration-test-backend to coverage report
- Fix uploading of coverage for each github action job.

fix: add coverage to local-integration-test-backend

---

frontend/src/views/WheresMyGene/components/CellInfoSideBar/index.tsx
frontend/src/views/WheresMyGene/components/GeneInfoSideBar/index.tsx
frontend/src/views/WheresMyGene/components/HeatMap/components/XAxisChart/index.tsx
frontend/src/views/WheresMyGene/components/HeatMap/components/YAxisChart/index.tsx
frontend/src/views/WheresMyGene/components/RightSideBar/index.tsx
frontend/tests/features/wheresMyGene.test.ts

add e2e tests for gene info

---

DEV_ENV.md
README.md

Add troubleshooting instructions for dockerized unit test runs

---

backend/layers/processing/logger.py
backend/layers/processing/process_cxg.py
backend/layers/processing/process_download_validate.py
backend/layers/processing/process_logic.py
backend/layers/processing/process_seurat.py

No logs are emitted by the processing container. This makes debugging difficult.
- Add functions to log when a functions started and stopped
- Enable logging in processing container.
- Tested using rdev to make sure logs were emitted.

fix: enable logging for processing jobs

---

frontend/src/views/WheresMyGene/components/Filters/components/Compare/index.tsx

chore(wmg): compare analytics no longer fires when page loads

---

backend/curation/api/curation-api.yml
backend/curation/api/v1/curation/collections/collection_id/datasets/dataset_id/actions.py
backend/curation/api/v1/curation/collections/collection_id/versions.py
backend/curation/api/v1/curation/collections/common.py
backend/curation/api/v1/curation/dataset_versions/dataset_version_id/actions.py
backend/curation/api/v1/curation/datasets/actions.py
backend/layers/business/business.py
backend/layers/business/business_interface.py
backend/layers/business/exceptions.py
backend/layers/common/entities.py
backend/layers/common/helpers.py
backend/layers/persistence/persistence.py
backend/layers/persistence/persistence_interface.py
backend/layers/persistence/persistence_mock.py
tests/unit/backend/layers/api/test_curation_api.py

- #4324 
- Add `published_at` and `collection_version_id` per discussion on the issue for this PR
- Consolidate shared logic
- minor cleanup of unrelated endpoints and tests
- unit tested ✅ 
- rdev tested ✅

feat: add published_at and collection_version_id to Dataset [version] response object

---

frontend/src/layout.css

fix(wmg): Homepage not scrollable

---

Dockerfile.data_cube_creation

#4131 
- Update Docker base image to 3.10
- Run the pipeline in rdev
- Run the pipeline in dev

chore: update Docker base image to python:3.10

---

frontend/tests/features/wheresMyGene/landingPage.test.ts

test(wmg): e2e test feedback

---

backend/wmg/pipeline/integrated_corpus/extract.py
backend/wmg/pipeline/integrated_corpus/job.py
scripts/cxg_admin.py
tests/unit/backend/wmg/pipelines/test_extract.py

in progress

---

frontend/tests/features/home/homePage.test.ts

test(scrollable): patch

---

frontend/playwright.config.ts
frontend/tests/common/context.ts
frontend/tests/features/wheresMyGene/landingPage.test.ts
frontend/tests/features/wheresMyGene/landingPageFilter.test.ts
frontend/tests/features/wheresMyGene/wheresMyGene.test.ts
frontend/tests/utils/wmgUtils.ts

test(e2e): Fix e2e tests

---

frontend/playwright.config.ts

test(e2e): Fix e2e tests increase timeout

---

frontend/tests/features/collection/revision.test.ts

test(e2e): Update revision tests to use locators properly

---

frontend/tests/features/collection/revision.test.ts

chore(deploy): Staging deploy 4-19-2023

---

backend/Makefile
backend/scripts/mirror_s3_data.sh
frontend/src/views/Collection/components/ActionButtons/index.tsx
frontend/tests/features/collection/revision.test.ts

chore(deploy): Staging Deploy 4-19-2023 3:45pm

---

frontend/src/views/WheresMyGene/components/GeneSearchBar/components/ShareButton/utils.tsx
frontend/tests/features/wheresMyGene/shareLink.test.ts

test(4639): feedback

---

tests/unit/backend/wmg/test_marker_gene_calculation.py

- [Slack context](https://czi-sci.slack.com/archives/C0244PQK934/p1682020956304159)
- add
- remove
- modify

chore: fix backend wmg unit test

---

frontend/doc-site/05__Annotate and Analyze Your Data/5_5__Automatic Annotation.mdx

Updated model paths because of MLFlow fix to address some dependency issues, scanpy/leiden lib version also updated in the docs here

chore: Update model paths

---

backend/layers/processing/requirements.txt

feat(large datasets): pin cellxgene-schema version

---

backend/curation/api/v1/curation/collections/common.py
tests/unit/backend/layers/api/test_curation_api.py

- https://github.com/chanzuckerberg/single-cell/issues/445
- add is_published flag to modify the dataset and collection api response. 
- modify tests

fix(445): Only return processing status for unpublished revision or private collection.

---

frontend/tests/features/wheresMyGene/landingPageFilter.test.ts
frontend/tests/features/wheresMyGene/manageGene.test.ts
frontend/tests/features/wheresMyGene/wheresMyGene.test.ts
frontend/tests/utils/wmgUtils.ts

test(wmg): Fix flaky tests

---

frontend/src/common/queries/wheresMyGene.ts

https://github.com/chanzuckerberg/single-cell-data-portal/issues/4348
Removes the following cell types from the y axis and the heatmap:
* native cell
* eukaryotic
* animal cell

feat(wmg): filter out cell types that don't have scientific value

---

frontend/tests/features/wheresMyGene/wheresMyGene.test.ts

Test was targeting a cell type that we're now filtering from gene expression

test(fmg): change test target for no marker gene warning

---

frontend/src/components/Header/components/Nav/index.tsx

Change the census link to the new docpage

chore: change census link

---

frontend/tests/README.md
frontend/tests/utils/wmgUtils.ts

fix: fix WMG tests

---

.github/workflows/push-rdev.yml

- chore: update push-rdev to use only first 7 github sha characters for image tags (#4779)

chore: staging<-main

---

backend/curation/api/curation-api.yml
backend/curation/api/v1/curation/collections/common.py
tests/unit/backend/layers/api/test_curation_api.py

- #4741 
- add
- remove
- modify

feat: remove explorer_url from Dataset version object response

---

.github/workflows/push-rdev.yml

- chore: update push-rdev to use only first 7 github sha characters for image tags (#4779)
- add
- remove
- modify

chore: prod<-staging

---

frontend/src/common/queries/cellCards.ts

feat(wmg): Cell cards hooks refactor

---

frontend/src/views/Landing/index.tsx

Updates landing page numbers to latest

chore: update landing page numbers 

---

frontend/src/views/CellCards/components/CellCard/components/EnrichedGenesTable/index.tsx
frontend/src/views/CellCards/components/CellCard/components/EnrichedGenesTable/style.ts
frontend/src/views/CellCards/components/CellCard/index.tsx
frontend/tests/features/cellCards/cellCards.test.ts

- add enriched genes table and e2e tests
- e2e tests pass

feat(cell-guide): add enriched genes table and e2e tests

---

frontend/src/views/CellCards/components/CellCard/components/SourceDataTable/index.tsx
frontend/src/views/CellCards/components/CellCard/components/SourceDataTable/style.ts
frontend/src/views/CellCards/components/CellCard/index.tsx
frontend/tests/features/cellCards/cellCards.test.ts

- add source data table to cell guide's cell card component
- e2e tests pass

feat(cell-guide): add source data table and e2e tests

---

frontend/doc-site/05__Annotate and Analyze Your Data/5_8__Multimodal Annotations.mdx

docs: update 5_8__Multimodal Annotations.mdx

---

frontend/src/views/CellCards/components/CellCard/components/MarkerGeneTables/index.tsx
frontend/tests/features/cellCards/cellCards.test.ts

- #4936 
- used MUI pagination component to add pages to the tables
- Tests pass

feat(cell-guide): add pages to table

---

.github/workflows/rebuild-processing-image.yml

- #4963
- add slack alert step about job status after prod processing image rebuild + push

feat: add slack ops channel alert after processing image rebuild + push

---

.happy/config.json

- with the introduction of happy slices, we need to include all of the services we want to deploy in the config.json
- add expected services to .happy/config.json- remove
- deployed an rdev

fix(deployment): add expected services to .happy/config.json

---

frontend/src/common/constants/utils.ts
frontend/src/common/queries/wheresMyGene.ts
frontend/src/views/WheresMyGene/common/constants.ts
frontend/src/views/WheresMyGene/components/HeatMap/components/Chart/components/Chart/style.ts
frontend/src/views/WheresMyGene/components/HeatMap/components/Chart/utils.ts
frontend/src/views/WheresMyGene/components/HeatMap/components/XAxisChart/style.ts
frontend/src/views/WheresMyGene/components/HeatMap/components/YAxisChart/style.ts
frontend/src/views/WheresMyGene/components/InfoPanel/components/Legend/index.tsx
frontend/src/views/WheresMyGeneV2/components/GeneSearchBar/components/SaveExport/index.tsx
frontend/src/views/WheresMyGeneV2/components/HeatMap/components/YAxisChart/index.tsx
frontend/src/views/WheresMyGeneV2/components/HeatMap/index.tsx
frontend/src/views/WheresMyGeneV2/components/Main/index.tsx

* feat(wmgv2): expand/collapse with y-axis
* fix spacing and alphabetize tissues
* lint
* use empty set
* lint
* lint
---------
- add
- remove
- modify

chore: Staging Deploy Part 2 6-13-2023

---

frontend/src/common/queries/wheresMyGene.ts

fix(wmg): fix error on selecting tissue on wmg v1

---

frontend/tests/utils/downloadUtils.ts

test(WMG): Fix SVG download tests

---

.happy/terraform/envs/dev/main.tf
frontend/tests/utils/downloadUtils.ts

chore: Staging Deploy Part 4 (6-14-2023)

---

frontend/tests/features/download/downloadSvg.test.ts

test(WMG): Fix skip WMG image download tests

---

backend/schema_migration/migrate.py
tests/unit/schema_migration/pytest_fixtures.py
tests/unit/schema_migration/test_collection_migrate.py
tests/unit/schema_migration/test_dataset_migrate.py
tests/unit/schema_migration/test_gather_collections.py

- #4800
- #5040
- collection migrate + dataset migrate functions for schema migration
- refactor tests + migrate class set-up
- unit tests

feat: add collection migrate + dataset migrate functions for schema migration

---

frontend/playwright-globalSetup.ts
frontend/src/pages/_document.tsx
frontend/tests/features/download/downloadCsv.test.ts
frontend/tests/features/download/downloadSvg.test.ts
frontend/tests/features/wheresMyGene/cellTooltip.test.ts
frontend/tests/features/wheresMyGene/landingPage.test.ts
frontend/tests/features/wheresMyGene/landingPageFilter.test.ts
frontend/tests/features/wheresMyGene/manageGene.test.ts
frontend/tests/features/wheresMyGene/manageTissue.test.ts
frontend/tests/features/wheresMyGene/rightSideBar.test.ts
frontend/tests/features/wheresMyGene/shareLink.test.ts
frontend/tests/features/wheresMyGene/wheresMyGene.test.ts
frontend/tests/utils/helpers.ts
frontend/tests/utils/wmgUtils.ts

- #5050 
- add
- remove
- modify

test(WMG): 5050 Conditionally run WMG e2e tests based on API URL

---

.github/workflows/push-tests.yml
Dockerfile.backend
Makefile
backend/layers/auth/user_info.py
backend/layers/common/entities.py
backend/schema_migration/migrate.py
backend/schema_migration/requirements-dev.txt
frontend/src/common/queries/wheresMyGene.ts
tests/unit/backend/layers/api/test_portal_api.py
tests/unit/backend/layers/business/test_business.py
tests/unit/schema_migration/pytest_fixtures.py
tests/unit/schema_migration/test_collection_migrate.py
tests/unit/schema_migration/test_dataset_migrate.py
tests/unit/schema_migration/test_gather_collections.py

Redeploying to include dataset deployments URL parsing fix for publications filter; the other two commits are not live (backend set-up for future work) and can go into staging safely

chore: staging deploy 2; 06/21/23

---

frontend/src/common/queries/wheresMyGene.ts
frontend/src/views/WheresMyGene/components/Filters/index.tsx

- #4730 
- add code for aggregating no publications' dataset ids 
?? ¯\\_(ツ)_/¯ (seve fixed his arm) (the lil guy thanks you seve)

fix: Adding option for "No Publication" to the secondary filter 

---

frontend/src/components/Header/components/Nav/index.tsx

The Census link should point to the new docsite

chore: update Census link

---

frontend/tests/utils/wmgUtils.ts

REVERT this PR once @carolinechoi 's publication PR is merged!

test: temporarily skip WMG e2e tests

---

.github/workflows/build-images-and-create-deployment.yml

Re-adding merge queue capability by addressing happy bug w/ docker image default tag names

chore: Update happy version in build-images-and-create-deployment.yml

---

.github/workflows/build-images-and-create-deployment.yml

Reverts chanzuckerberg/single-cell-data-portal#5128 to unblock deployments

fix: Revert "chore: Update happy version in build-images-and-create-deployment.yml"

---

.github/workflows/build-images-and-create-deployment.yml
.github/workflows/rebuild-processing-image.yml
.happy/config.json
docker-compose.yml

feat: use slices to build images

---

.github/workflows/build-images-and-create-deployment.yml
.github/workflows/rebuild-processing-image.yml
.happy/config.json
docker-compose.yml

Unblocking dev deployment pipeline while we troubleshoot image push/build timeoouts

fix: Revert "feat: use slices to build images"

---

scripts/generate_realistic_test_snapshot.py

chore(wmg): update script to create the required fixtures for unit tests

---

frontend/src/views/CellCards/components/CellCardSearchBar/index.tsx

chore(cell-guide): reorder cell type and tissue in search bar

---

backend/database/README.md

- #5177 
- add
- remove
- modify

chore: followup on migration instructions

---

frontend/src/components/common/Filter/common/style.ts
frontend/src/views/WheresMyGene/components/HeatMap/components/XAxisChart/style.ts
frontend/src/views/WheresMyGene/components/HeatMap/components/YAxisChart/style.ts
frontend/src/views/WheresMyGene/components/HeatMap/style.ts
frontend/src/views/WheresMyGene/components/HeatMap/utils.ts
frontend/src/views/WheresMyGeneV2/components/HeatMap/components/YAxisChart/index.tsx
frontend/src/views/WheresMyGeneV2/components/HeatMap/index.tsx

feat(wmgv2): cell type filter

---

.happy/terraform/envs/stage/main.tf

temp: increase staging memory 10x

---

.happy/terraform/envs/stage/main.tf
.happy/terraform/modules/ecs-stack/variables.tf

fix: mem config

---

.happy/terraform/envs/prod/main.tf

- Outcome from today's staff meeting (7/13).
- Hotfixing to make sure wmg v2 isn't too unscalable.

chore: increase prod resources

---

frontend/src/common/queries/wheresMyGene.ts

- FMG is broken in WMG v2
- Hardcode useMarkerGenes to use version=2 (later, all versioning should be removed from the hooks module)

fix(wmg): fix find marker genes in wmg v2

---

frontend/src/common/queries/wheresMyGene.ts

- #5233
- add
- remove
- modify

fix(wmg): fix find marker genes in wmg v2 (cherry pick)

---

backend/wmg/api/v2.py

- #5231 
- add
- remove
- modify

fix(wmg): update build_expression_summary to be faster (cherry pick)

---

frontend/src/common/constants/routes.ts
frontend/src/views/CellGuide/components/CellGuideCard/components/MarkerGeneTables/index.tsx

change route

---

frontend/src/views/CellGuide/components/CellGuideCard/components/MarkerGeneTables/index.tsx
frontend/tests/features/cellCards/cellCards.test.ts

- Update wording on tooltip in response to (HUBMAP) katy's feedback

chore(cellguide): small modification to tooltip based on katy's feedback

---

frontend/src/views/CellGuide/components/CellGuideCard/components/Description/index.tsx
frontend/src/views/CellGuide/components/CellGuideCard/components/Description/style.ts

- #5253 
- add
- remove
- modify

chore(cellguide): add experimental description header

---

frontend/src/components/Header/components/Nav/index.tsx

Reverts chanzuckerberg/single-cell-data-portal#5247
We do not want cell guide to be publicly accessible this week

Revert "chore(cell-guide): add cell guide to navbar"

---

backend/wmg/pipeline/summary_cubes/cell_count.py
backend/wmg/pipeline/summary_cubes/expression_summary/load.py

fix(wmg): patch pipeline to be able to handle non-ascii characters

---

backend/wmg/pipeline/summary_cubes/cell_count.py
backend/wmg/pipeline/summary_cubes/expression_summary/load.py
tests/unit/wmg_processing/test_load_corpus.py

- Error in string concatenation due to pre-emptive ascii encoding

fix(wmg): remove preemptive encoding to ascii

---

.github/workflows/schema-migration.yml

- #5099
- add gha to trigger schema migration sfn in AWS in response to webhook trigger from single-cell-curation (see [PR](https://github.com/chanzuckerberg/single-cell-curation/pull/549))

feat: trigger schema migration sfn from single-cell-curation webhook

---

.happy/terraform/envs/stage/main.tf

temp: increase staging resources for debugging

---

.happy/terraform/envs/dev/main.tf
.happy/terraform/envs/prod/main.tf
.happy/terraform/envs/stage/main.tf
.happy/terraform/modules/ecs-stack/main.tf
.happy/terraform/modules/ecs-stack/variables.tf

chore: update num workers for dev, staging, and prod

---

backend/wmg/api/wmg-api-v2.yml

chore(wmg): fix typo in wmg-api-v2.yml for publication citations

---

frontend/tests/features/download/downloadCsv.test.ts

chore: remove .only from e2e test

---

frontend/src/components/Header/components/Nav/index.tsx

Reverts chanzuckerberg/single-cell-data-portal#5264

Revert "Revert "chore(cell-guide): add cell guide to navbar""

---

backend/wmg/api/wmg-api-v2.yml
backend/wmg/data/query.py
backend/wmg/pipeline/summary_cubes/expression_summary/load.py
frontend/src/common/queries/wheresMyGene.ts
frontend/src/views/WheresMyGene/components/Filters/index.tsx
frontend/src/views/WheresMyGeneV2/components/GeneSearchBar/components/SaveExport/csvUtils.ts

- Heatmap needed to be hooked up to secondary filter
- [RDEV LINK](https://pub-test-2-frontend.rdev.single-cell.czi.technology/gene-expression)

feat(wmg): trigger heatmap filtering on publication filter selection

---

frontend/src/views/WheresMyGene/common/constants.ts
frontend/src/views/WheresMyGene/components/Filters/components/Compare/index.tsx
frontend/src/views/WheresMyGene/components/GeneSearchBar/components/SaveExport/index.tsx
frontend/src/views/WheresMyGene/components/GeneSearchBar/components/ShareButton/index.tsx
frontend/src/views/WheresMyGeneV2/components/GeneSearchBar/components/SaveExport/index.tsx
frontend/src/views/WheresMyGeneV2/components/GeneSearchBar/components/ShareButton/index.tsx
frontend/tests/features/wheresMyGene/wheresMyGene.test.ts

- #4955
- adding in filter analytics
- verified groupBy analytics
- modified option in dropdown (UI)

fix: analytics for publications

---

frontend/src/common/queries/wheresMyGene.ts
frontend/src/views/WheresMyGeneV2/components/HeatMap/index.tsx

- #5144
- this lets us sort the compare options by their cell count
- adding this functionality to ALL compare options, not just publications
- local host

feat(wmg): sort compare options by cell count

---

frontend/tests/common/playwright.global.setup.ts
frontend/tests/features/collection/revision.test.ts
frontend/tests/utils/helpers.ts

Don't swallow the error, so it will throw the error and stop the tests

test: fix login swallowing error

---

frontend/tests/common/playwright.global.setup.ts
frontend/tests/features/collection/revision.test.ts
frontend/tests/utils/helpers.ts

Reverts chanzuckerberg/single-cell-data-portal#5337

Revert "test: fix login swallowing error"

---

Dockerfile.backend
backend/api_server/app.py
backend/wmg/data/snapshot.py

This reverts commit abb35242e481a6588a8ddd2b94dd108308528d49.
- Downloading the snapshot at server startup time was causing gunicorn to kill its workers due to some keepalive/timeout settings, though the exact nature of this issue has not been diagnosed and debugged.
- add
- remove
- modify

fix: staging hotfix 7/27 (Revert "feat(wmg): faster queries (#5031)" (#5342))

---

frontend/src/components/GeneInfoSideBar/index.tsx
frontend/src/components/GeneInfoSideBar/style.ts
frontend/src/views/WheresMyGene/components/CellInfoSideBar/index.tsx
frontend/src/views/WheresMyGene/components/CellInfoSideBar/style.ts

- #5236 
- modifying name of GeneInfoSideBar's style constant 'GeneUrl' to 'Link'
- adding 'Link' into CellInfoSideBar
- locally 
https://github.com/chanzuckerberg/single-cell-data-portal/assets/38522055/4a5df690-4655-4bbe-9176-58d91e48851d

feat: cross-linking Gene Expression with Cell Guide

---

frontend/src/common/constants/airtableLinks.ts
frontend/src/components/BottomBanner/index.tsx
frontend/src/components/LandingFooter/index.tsx
frontend/src/views/CellGuide/components/CellGuideBottomBanner/index.tsx
frontend/src/views/CellGuide/components/CellGuideCard/components/Description/index.tsx
frontend/src/views/WheresMyGene/components/Main/index.tsx
frontend/src/views/WheresMyGeneV2/components/Main/index.tsx

- needed to update cellguide banner airtable link to cellguide survey, and update the submit a correction link to the most up-to-date airtable
- add
- remove
- modify

chore(cellguide): update airtable links

---

.happy/terraform/modules/batch/variables.tf
.happy/terraform/modules/schema_migration/main.tf
.happy/terraform/modules/sfn/main.tf
README.md
backend/layers/processing/schema_migration.py
example_dev_notebooks/local_endpoint_runner.ipynb
example_dev_notebooks/local_pipeline_runner.ipynb
frontend/doc-site/04__Analyze Public Data/4_2__Gene Expression Documentation/4_2_6__Gene Expression Source Data.mdx
tests/unit/processing/schema_migration/conftest.py
tests/unit/processing/schema_migration/test_collection_migrate.py
tests/unit/processing/schema_migration/test_publish_and_cleanup.py
tests/unit/processing/schema_migration/test_report.py

chore: Staging deploy part 3

---

backend/layers/processing/upload_failures/app.py
tests/unit/processing/test_handle_error.py

1. Problem: Current slack message doesn't include oncall triage steps, so this PR adds a link to the new triage steps, so oncall engs have action items to do
- add
- remove
- modify

docs: Update dataset processing failure triage steps

---

frontend/tests/common/constants.ts
frontend/tests/features/wheresMyGene/cellTooltip.test.ts
frontend/tests/features/wheresMyGene/landingPage.test.ts
frontend/tests/features/wheresMyGene/landingPageFilter.test.ts
frontend/tests/features/wheresMyGene/manageGene.test.ts
frontend/tests/features/wheresMyGene/manageTissue.test.ts
frontend/tests/features/wheresMyGene/shareLink.test.ts
frontend/tests/features/wheresMyGene/wheresMyGene.test.ts
frontend/tests/utils/geneUtils.ts
frontend/tests/utils/wmgUtils.ts

1. test: Fix wmg e2e manageGene tests
1. test: Fix tooltip
1. test: fix landingPageFilter
1. test: fix WMG shareLink
1. Change share link tissue params to use ids instead of names. There's a ticket to track if this change is intentional
2. Change `ADD_TISSUE_ID` to be `"tissue-filter"`, since we no longer have an add tissue button in the main panel
3. Update `conditionallyRunTests()` to accept `{forceRun: true }`, so we can incrementally add back WMG tests as we go
4. Specific test related changes will be commented inline
1. WMG e2e tests above should pass

fix: e2e WMG tests part 1

---

requirements-upload-failures.txt
requirements-upload-success.txt

Fixes a missing dependency in the lambda docker containers.

fix: missing lambda dependencies

---

.github/workflows/push-tests.yml
frontend/src/pages/cellguide/[cellTypeId].tsx
frontend/src/views/CellGuide/components/CellGuideCard/components/MarkerGeneTables/index.tsx
frontend/src/views/CellGuide/components/CellGuideCard/index.tsx
frontend/tests/features/cellGuide/cellGuide.test.ts

refactor: MarkerGeneTables

---

.happy/config.json

- #5462 
- `cellguide_pipeline` needs to be added to happy config, otherwise happy does not work.
- add
- remove
- modify

fix: cellguide_pipeline happy config error

---

frontend/tests/features/wheresMyGene/landingPage.test.ts

- #5471
This test never worked as intended lol

test: remove  test related to removed "Add Tissue" functionality

---

backend/cellguide/pipeline/utils.py
backend/common/utils/dataclass.py
tests/unit/cellguide_pipeline/test_ontology_tree.py

set default to false

---

frontend/.gitignore

Avoid tracking unzipped fixtures in git
- add
- remove
- modify

chore: Update gitignore to account for unzipped fixtures

---

frontend/src/views/CellGuide/components/CellGuideCard/components/CellGuideCardSidebar/constants.ts
frontend/src/views/CellGuide/components/CellGuideCard/components/CellGuideCardSidebar/index.tsx
frontend/src/views/CellGuide/components/CellGuideCard/components/Description/constants.ts
frontend/src/views/CellGuide/components/CellGuideCard/components/Description/index.tsx
frontend/src/views/CellGuide/components/CellGuideCard/components/MarkerGeneTables/constants.ts
frontend/src/views/CellGuide/components/CellGuideCard/components/MarkerGeneTables/index.tsx
frontend/src/views/CellGuide/components/CellGuideCard/components/SourceDataTable/constants.ts
frontend/src/views/CellGuide/components/CellGuideCard/components/SourceDataTable/index.tsx
frontend/src/views/CellGuide/components/CellGuideCard/constants.ts
frontend/src/views/CellGuide/components/CellGuideCard/index.tsx
frontend/src/views/CellGuide/components/CellGuideCardSearchBar/constants.ts
frontend/src/views/CellGuide/components/CellGuideCardSearchBar/index.tsx
frontend/src/views/CellGuide/components/LandingPage/constants.ts
frontend/src/views/CellGuide/components/LandingPage/index.tsx
frontend/src/views/CellGuide/components/TissueCard/constants.ts
frontend/src/views/CellGuide/components/TissueCard/index.tsx
frontend/src/views/CellGuide/components/common/OntologyDagView/components/Node/components/RectOrCircle/constants.ts
frontend/src/views/CellGuide/components/common/OntologyDagView/components/Node/components/RectOrCircle/index.tsx
frontend/src/views/CellGuide/components/common/OntologyDagView/components/Node/constants.ts
frontend/src/views/CellGuide/components/common/OntologyDagView/components/Node/index.tsx
frontend/src/views/CellGuide/components/common/OntologyDagView/constants.ts
frontend/src/views/CellGuide/components/common/OntologyDagView/index.tsx
frontend/tests/README.md
frontend/tests/features/cellGuide/cellGuide.test.ts

1. @ashin-czi and I both run into issues with Playwright not parsing SVG files correctly, so the temporarily solution is to NOT import .tsx files in test files. I've reached out to Playwright to see why this is happening and will keep you all posted!
- add
- remove
- modify

test: Remove tsx imports

---

backend/cellguide/pipeline/ontology_tree/tree_builder.py
backend/cellguide/pipeline/ontology_tree/types.py
backend/common/utils/dataclass.py

chore(cellguide): small fixes to typing and added safety

---

frontend/playwright.config.ts

test: Update max failure

---

backend/cellguide/pipeline/constants.py
backend/cellguide/pipeline/metadata/__init__.py
backend/cellguide/pipeline/metadata/metadata_generator.py
backend/cellguide/pipeline/metadata/types.py
backend/cellguide/pipeline/ontology_tree/tree_builder.py
tests/unit/cellguide_pipeline/fixtures/tissue_metadata.json
tests/unit/cellguide_pipeline/test_metadata_generator.py

- #5467 
- add
- remove
- modify

feat(cellguide): add tissue metadata pipeline

---

backend/cellguide/pipeline/__init__.py
backend/cellguide/pipeline/canonical_marker_genes/utils.py
backend/cellguide/pipeline/constants.py
backend/cellguide/pipeline/source_collections/__init__.py
backend/cellguide/pipeline/source_collections/source_collections_generator.py
backend/cellguide/pipeline/source_collections/types.py
tests/unit/cellguide_pipeline/test_canonical_marker_genes.py
tests/unit/cellguide_pipeline/test_source_collections_generator.py

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5466
- generates the source collections data artifact
- i added a new citation formatter to format responses from the collections API
- added a test for generating source collections data
- i also added a test for formatting citations from the collections API

feat(cellguide): implement pipeline for the source collections data artifact

---

frontend/playwright.config.ts

Looks like 10 retries was too much that the tests would time out after 1 hr, so hopefully 5 is the sweet spot 🤞 
- add
- remove
- modify

test: Update max failure again

---

.happy/terraform/envs/prod/main.tf
.happy/terraform/envs/stage/main.tf
.happy/terraform/modules/batch/main.tf
backend/layers/processing/schema_migration.py
tests/unit/processing/schema_migration/test_publish_and_cleanup.py

* fix(schema-migration): Pass collection_version to publish_collection_version (#5518)
* reduce memory allocated to prod and staging for upload jobs. (#5510)
- #5555 
- See #5558 
- See #5558

fix: Prod hotfix 08/21/2023 (#5558)

---

.happy/catalog-info.yaml

This PR was created with EngPortal using the "Register Existing Happy App in Software Catalog" software template. It creates a component YAML file and registers the component in the Eng-Portal Software Catalog.

chore: add to software catalog

---

frontend/src/views/CellGuide/components/CellGuideCard/components/MarkerGeneTables/style.ts

fix(cellguide): align tooltip button and text

---

backend/cellguide/pipeline/__init__.py

chore(cellguide): cleanup output files after pipeline run

---

backend/cellguide/pipeline/__init__.py

fix(cellguide): fix cleanup function

---

backend/cellguide/pipeline/__init__.py
frontend/next.config.js
frontend/runtime_configs/rdev.env
frontend/src/common/queries/cellGuide.ts

- add
- remove
- modify
- [Rdev](https://cellguide-test-frontend.rdev.single-cell.czi.technology/cellguide/CL_0000622)

chore(cellguide): add support for rdev

---

.happy/terraform/envs/dev/main.tf
.happy/terraform/envs/prod/main.tf
.happy/terraform/envs/rdev/main.tf
.happy/terraform/envs/stage/main.tf
.happy/terraform/modules/cg-batch/main.tf
.happy/terraform/modules/cg-batch/outputs.tf
.happy/terraform/modules/cg-batch/variables.tf
.happy/terraform/modules/ecs-stack/main.tf
.happy/terraform/modules/ecs-stack/variables.tf

- Set up batch environment for the cellguide pipeline.
- This work is paired with this ticket from single-cell-infra: https://github.com/chanzuckerberg/single-cell-infra/pull/865

feat(cellguide): set up cellguide batch

---

.github/workflows/build-images-and-create-deployment.yml

- Need the create deployment step to wait for image tags to be added

fix: update create deployment to require build frontend/backend/batch images

---

backend/cellguide/pipeline/computational_marker_genes/utils.py

- RDEV pipeline runs have been failing due to JSON decode error after querying gene_info for the computational marker gene pipeline. This is because gene_info is walled behind Auth0. To fix this, we choose the API_URL the same way we are doing it for `get_datasets_from_curation_api` ([here](https://github.com/chanzuckerberg/single-cell-data-portal/blob/fe771acaceaad4950a7d1750ab7861fa83f27316/backend/wmg/data/utils.py#L160)). If DEPLOYMENT_STAGE is rdev, use staging API_URL.
- add
- remove
- modify
- "Unit tested only", "tested in rdev by a, b, c, verifying feature worked by... ", …

fix(cellguide): fix rdev pipeline runs by using staging backend for gene_info

---

frontend/src/views/CellGuide/components/CellGuideCard/index.tsx

fix: Failed to execute insertBefore on Node issue

---

frontend/tests/features/collection/revision.test.ts

test: Skip e2e revision tests

---

frontend/package-lock.json
frontend/package.json
frontend/tests/features/wheresMyGene/manageGene.test.ts

1. Update the test to specifically test gene bulk add, since testing copy/pasting is testing the OS, which is irrelevant

test: Fix e2e test gene bulk add

---

frontend/src/views/CellGuide/components/CellGuideCard/index.tsx
frontend/tests/features/cellGuide/cellGuide.test.ts

- #5670 
- change the global organism and organ filter dropdowns to use SDS components
- E2E tests pass
- manual testing on localhost

feat(cellguide): Use SDS components for organ and organism dropdown

---

frontend/src/views/CellGuide/components/CellGuideCard/components/MarkerGeneTables/hooks/common.ts
frontend/src/views/CellGuide/components/CellGuideCard/index.tsx

Refactor per feedback from here: https://github.com/chanzuckerberg/single-cell-data-portal/pull/5680#pullrequestreview-1607324877

refactor: cell guide - global tissue selector

---

.github/workflows/deploy-happy-stack.yml
.github/workflows/push-tests.yml

1. To shorten feedback loop, decrease max timeout
- add
- remove
- modify

test: lower max time out to 30 mins

---

frontend/src/views/WheresMyGene/components/HeatMap/style.ts
frontend/src/views/WheresMyGene/components/HeatMap/utils.ts
frontend/src/views/WheresMyGeneV2/components/HeatMap/index.tsx
frontend/src/views/WheresMyGeneV2/components/HeatMap/style.ts

I made some changes in the dev console but never committed in the previous PR 🤦‍♂️ 

fix: Heatmap divider

---

frontend/src/common/sitemaps/utils.ts
frontend/src/pages/cellguide-sitemap.xml/index.tsx
frontend/src/pages/collections-sitemap.xml/index.tsx

refactor: cell guide sitemap

---

.github/workflows/deploy-happy-stack.yml
frontend/src/common/queries/cellGuide.ts
frontend/src/pages/cellguide/[cellTypeId].tsx
frontend/src/views/CellGuide/components/CellGuideCard/index.tsx

- Currently, we aren't running post-deployment tests. This PR changes the E2E workflow to require upgrade to complete before running.
- Also, I updated a playwright snapshot as it became out-of-date for a mysterious reason.

fix(e2e): make e2e tests need upgrade and fix seo snapshot

---

frontend/src/views/Landing/constants.ts
frontend/src/views/Landing/index.tsx
frontend/tests/features/home/homePage.test.ts

chore: add landing page hero number e2e test

---

frontend/src/views/WheresMyGene/components/Loader/index.tsx
frontend/src/views/WheresMyGeneV2/components/HeatMap/components/YAxisChart/index.tsx
frontend/src/views/WheresMyGeneV2/components/HeatMap/index.tsx
frontend/tests/features/wheresMyGene/cellTooltip.test.ts
frontend/tests/features/wheresMyGene/landingPageFilter.test.ts
frontend/tests/features/wheresMyGene/manageGene.test.ts
frontend/tests/features/wheresMyGene/wheresMyGene.test.ts
frontend/tests/utils/geneUtils.ts
frontend/tests/utils/helpers.ts
frontend/tests/utils/wmgUtils.ts

…5527)
* test: refactor wheresMyGene.test.ts to capture WMGV2 functionality
* expand not needed
* Update frontend/tests/features/wheresMyGene/wheresMyGene.test.ts
* Update frontend/tests/features/wheresMyGene/wheresMyGene.test.ts
* nits
---------
- add
- remove
- modify

fix: staging hotfix

---

frontend/tests/features/cellGuide/cellGuide.test.ts

- This resolves the [e2e test failure in staging](https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/6100488829).
- This also resolves a source of test flakeyness in the navbar test.
- add
- remove
- modify

chore(cellguide): fix e2e test failing in staging and another flaky test

---

frontend/src/views/WheresMyGeneV2/components/GeneSearchBar/components/SaveExport/svgUtils.ts
frontend/src/views/WheresMyGeneV2/components/HeatMap/components/YAxisChart/constants.ts
frontend/src/views/WheresMyGeneV2/components/HeatMap/components/YAxisChart/index.tsx
frontend/tests/common/constants.ts
frontend/tests/features/wheresMyGene/cellTooltip.test.ts
frontend/tests/features/wheresMyGene/wheresMyGene.test.ts
frontend/tests/utils/downloadUtils.ts
frontend/tests/utils/geneUtils.ts

1. Update css class names to use constants to have single source of truth
2. Update SVG util logic to use the new constants

fix: WMG svg download

---

frontend/src/views/WheresMyGeneV2/components/HeatMap/components/YAxisChart/index.tsx
frontend/tests/features/wheresMyGene/cellTooltip.test.ts
frontend/tests/features/wheresMyGene/wheresMyGene.test.ts
frontend/tests/utils/geneUtils.ts
frontend/tests/utils/helpers.ts

fix: WMG svg download part 2

---

frontend/src/views/WheresMyGene/components/HeatMap/components/Chart/index.tsx
frontend/src/views/WheresMyGeneV2/components/HeatMap/index.tsx

- #5719 #5720
- modify
- Do not modify state in place, create new object and set state instead 
@tihuan is looking into disallowing this behavior via eslint

fix(WMG): correctly update heatmap data when filtering celltypes

---

frontend/src/views/WheresMyGeneV2/components/GeneSearchBar/components/SaveExport/svgUtils.ts
frontend/src/views/WheresMyGeneV2/components/HeatMap/components/YAxisChart/constants.ts
frontend/src/views/WheresMyGeneV2/components/HeatMap/components/YAxisChart/index.tsx
frontend/tests/common/constants.ts
frontend/tests/features/wheresMyGene/cellTooltip.test.ts
frontend/tests/features/wheresMyGene/wheresMyGene.test.ts
frontend/tests/utils/downloadUtils.ts
frontend/tests/utils/geneUtils.ts
frontend/tests/utils/helpers.ts

chore(hotfix): backport staging + prod hotfixes regarding svg downloads

---

.github/workflows/build-images-and-create-deployment.yml
.happy/config.json
docker-compose.yml

When building the docker images in [build-images-and-create-deployment.yml](https://github.com/chanzuckerberg/single-cell-data-portal/pull/5759/files#diff-e0f79301c397cd2b444a586cf77777bfe36bd14722a75aed390bed2d6a6d21bf), all of the images were being built in the jobs `build-frontend-backend-images` and `build-batch-job-images`. This was causing the GHA environment to crash by running out of disk space. This was causing a headache for deployment which would fail due to a lack do disk space. Now the images will be built in their own job, which does not share disk space. This avoid the disk space capacity error. The frontend and backend images are still built in the same job, but that is beyond the scope of this PR to address. 
As an added bonus, this reduces our image build time to under …

fix(cicd): build docker images using matrix strategy

---

frontend/src/views/CellGuide/components/common/OntologyDagView/common/style.ts

[Context](https://czi-sci.slack.com/archives/C023Q1APASK/p1694655891903049) on how this accidental commit occurred.

fix(cellguide): fix error introduced by accidental push into main branch

---

backend/Makefile
backend/scripts/mirror_s3_data.sh
backend/scripts/set_src_dest_envs.sh

unrelated:
- prevent rdev from being used as SRC_ENV
- minor improvement to logs
- #5437 
- add
- remove
- modify

feat: add cellguide mirror option for rdev

---

frontend/src/views/Landing/index.tsx

fix(landing): use default hero numbers if calculated number is 0

---

scripts/populate_rdev_with_wmg_data.sh

- #5603
- Created a script to seed wmg rdev data. Adapted from the script for seeding cellguide rdev data.

chore: add script to seed wmg rdev data

---

.github/workflows/rdev-update-for-pr.yml

A typo was preventing this GHA from running

fix(cicd): rdev-update-for-pr.yml

---

backend/wmg/api/v2.py
backend/wmg/api/wmg_api_config.py
scripts/populate_rdev_with_wmg_data.sh

- Bumping reader snapshot version to v2 now that v2 WMG snapshot exists in all deployments.
- Added server timings for load snapshot

feat(wmg): bump reader snapshot version to v2

---

frontend/src/views/WheresMyGene/common/constants.ts
frontend/src/views/WheresMyGene/common/store/reducer.ts
frontend/src/views/WheresMyGene/components/Filters/components/Compare/connect.ts
frontend/src/views/WheresMyGene/components/Filters/components/Compare/index.tsx
frontend/src/views/WheresMyGeneV2/components/HeatMap/index.tsx
frontend/tests/features/wheresMyGene/downloadCsv.test.ts
frontend/tests/features/wheresMyGene/wheresMyGene.test.ts
frontend/tests/utils/downloadUtils.ts
frontend/tests/utils/wmgUtils.ts

1. Fix a few e2e tests
2. Add temp fix to SDS Dropdown infinite loop
3. Fix tissue expansion not expanding tissues when loading from share link

fix: Fix share link infinite loop + e2e tests + share link tissue expansion 

---

backend/wmg/pipeline/summary_cubes/builder.py

feat: update builder to use pre-calculated nnz per cell

---

.github/workflows/build-images-and-create-deployment.yml
.github/workflows/rdev-update-for-pr.yml
.github/workflows/rebuild-processing-image.yml
.github/workflows/schema-migration.yml

- #5925 
- update happy version in all GHAs to `0.110.1`
- change branch type from `open` to `opened` for GHA trigger (bug that prevents rdev workflow for single-commit PR's?)

fix: update happy version for all GHAs

---

frontend/src/common/featureFlags/features.ts
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/CurlLink/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/index.tsx

- #5589
- Added feature flag to #5589.

feat: added feature flag (#5589)

---

frontend/src/components/common/Filter/components/FilterContent/components/FilterMenu/index.tsx
frontend/src/components/common/Filter/components/FilterContent/components/FilterMenu/style.ts
frontend/src/components/common/Filter/components/FilterContent/components/common/style.ts
frontend/src/components/common/Filter/components/FilterTags/style.ts

- #5915
- Updated filter UI as per [Slack thread](https://clevercanary.slack.com/archives/C02CF7MQPGV/p1696446976678619?thread_ts=1696442917.110609&cid=C02CF7MQPGV).

feat: Polish filter UI (#5915)

---

frontend/src/common/queries/cellGuide.ts

- The computational marker gene table is used to generate the list of valid filter options, but the tissue-to-id  lookup table was being calculated from the source data. The two aren't necessarily overlapping, so there were marker genes being filtered out even though they shouldn't have been (e.g. respiratory system marker genes were being filtered out because source data doesn't contain a tissue label with respiratory system).
- add
- remove
- modify

fix(cellguide): determine tissue label-to-id lookup table based on computational marker gene table

---

frontend/src/views/WheresMyGene/common/store/actions.ts
frontend/src/views/WheresMyGene/common/store/reducer.ts
frontend/src/views/WheresMyGene/components/Main/index.tsx
frontend/src/views/WheresMyGeneV2/components/Main/index.tsx

- #4351
- removed deleteSelectedGenes action, reducer and related backspace event listeners

chore(wmg): removed deleteSelectedGenes and related hooks 4351

---

frontend/src/views/WheresMyGene/components/Filters/components/Compare/connect.ts

Revert temp fix now that SDS has been upgraded thanks to @frano-m 🙏

refactor: Update group by handler

---

frontend/src/common/queries/wheresMyGene.ts
frontend/src/common/utils/formatCitation.ts
frontend/src/views/WheresMyGene/common/types.ts
frontend/src/views/WheresMyGene/components/HeatMap/utils.ts
frontend/src/views/WheresMyGeneV2/components/HeatMap/components/YAxisChart/index.tsx
frontend/src/views/WheresMyGeneV2/components/HeatMap/index.tsx
frontend/tests/features/wheresMyGene/tissueAutoExpand.test.ts

chore(wmg): fix publication format 

---

backend/wmg/pipeline/constants.py
backend/wmg/pipeline/utils.py

implement required constants and utils

---

.github/workflows/test-receiving-repository-dispatch.yml
.github/workflows/test-sending-repository-dispatch.yml

- Continue testing `repository_dispatch` call to trigger workflows
- add
- remove
- modify
Manual testing by pushing to `psridharan/trigger-stage-deploy` feature branch

chore: TEST trigger repository_dispatch on pushes to ANY branch

---

.github/workflows/build-images-and-create-deployment.yml
.github/workflows/deploy-happy-stack.yml
.github/workflows/push-tests.yml

Fix a syntax error in github workflow file
- add
- remove
- modify
Manual testing on `main` branch

fix: Fix syntax error in github workflow

---

frontend/src/views/WheresMyGene/components/Filters/components/ColorScale/index.tsx
frontend/src/views/WheresMyGene/components/Filters/components/Compare/index.tsx
frontend/src/views/WheresMyGene/components/Filters/components/Sort/index.tsx
frontend/src/views/WheresMyGeneV2/components/CellInfoSideBar/index.tsx
frontend/src/views/WheresMyGeneV2/components/CellInfoSideBar/style.ts
frontend/src/views/WheresMyGeneV2/components/HeatMap/components/YAxisChart/index.tsx

- #4821
https://github.com/chanzuckerberg/single-cell-data-portal/assets/7976579/4901bff7-718c-4097-abf7-bb515ab5758e
- replaced table markup with div table
- added striping

chore(wmg): add zebra striping to table

---

frontend/src/common/featureFlags/features.ts
frontend/src/components/Collection/components/CollectionDatasetsGrid/components/Row/DownloadDataset/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/CurlLink/components/CopyMask/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/CurlLink/components/CopyMask/style.ts
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/CurlLink/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/CurlLink/style.ts
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/DataFormat/constants.ts
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/DataFormat/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/Details/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/index.tsx
frontend/src/components/Datasets/components/DownloadDataset/style.ts

- #5566
- Added feature flag to show/hide latest download datasets UI.
- Updated download button styles as per [Slack discussion](https://clevercanary.slack.com/archives/C02CF7MQPGV/p1696962307496509?thread_ts=1696933570.511979&cid=C02CF7MQPGV).
- Feature flag `dux=false` or `dux=true`.

feat: added feature flag (#5566)

---

.happy/terraform/envs/dev/main.tf
.happy/terraform/envs/prod/main.tf
.happy/terraform/envs/stage/main.tf

New marker gene algo requires stronger and faster and smarter machines.

chore: increase resources for cg pipeline

---

backend/wmg/pipeline/__main__.py

fix: fix entrypoint for wmg pipeline

---

frontend/src/views/WheresMyGene/components/InfoPanel/components/RelativeGeneExpression/constants.ts

fix: add constants.ts for pr 6060

---

.github/workflows/deploy-happy-stack.yml
.github/workflows/rdev-update-for-pr.yml
README.md
frontend/package.json
frontend/playwright.config.ts
frontend/src/components/UploadCSV/index.tsx
frontend/tests/README.md
frontend/tests/utils/helpers.ts

Improve e2e test against rdev developer experience 

test: Add RDEV_TOKEN flag

---

frontend/tests/features/cellGuide/cellGuide.test.ts
frontend/tests/features/wheresMyGene/tissueAutoExpand.test.ts
frontend/tests/features/wheresMyGene/wheresMyGene.test.ts

fix(wmg): fix outdated e2e tests due to new wmg snapshot

---

frontend/src/common/constants/routes.ts
frontend/src/common/theme.ts
frontend/src/components/Header/components/Nav/index.tsx
frontend/src/components/Header/components/Nav/style.ts
frontend/src/pages/census-directory/index.tsx
frontend/src/views/CensusDirectory/index.tsx

feat(census-directory): initial style scaffolding for census directory page

---

backend/layers/processing/upload_failures/app.py
tests/unit/processing/test_handle_error.py

- found while working on chanzuckerberg/single-cell#543
- fix log messages to avoid throwing errors.

fix: error handler logging

---

frontend/src/common/featureFlags/features.ts
frontend/src/components/Collection/components/CollectionDatasetsGrid/components/Row/DownloadDataset/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/CurlLink/components/CopyMask/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/CurlLink/components/CopyMask/style.ts
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/CurlLink/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/CurlLink/style.ts
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/DataFormat/constants.ts
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/DataFormat/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/Details/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/index.tsx
frontend/src/components/Datasets/components/DownloadDataset/style.ts

feat: Update UI for "download datasets" (#5566)

---

frontend/tests/features/cellGuide/cellGuide.test.ts

fix(cellguide): updating e2e test for census-based data

---

frontend/src/common/theme.ts
frontend/src/components/Header/components/Nav/constants.ts
frontend/src/components/Header/components/Nav/index.tsx
frontend/src/components/Header/components/Nav/style.ts
frontend/src/components/Header/components/Nav/types.ts
frontend/src/components/Header/style.ts
frontend/src/components/common/Logo/index.tsx
frontend/src/pages/docs/[...slug].tsx
frontend/src/views/CellGuide/components/CellGuideCard/components/MarkerGeneTables/index.tsx
frontend/src/views/CensusDirectory/index.tsx

feat: update navbar to match new design

---

backend/curation/api/curation-api.yml
backend/layers/common/validation.py
backend/portal/api/portal-api.yml
frontend/src/components/CreateCollectionModal/components/Content/common/constants.ts

- #6138
- Added "Human Cell Atlas (HCA)" consortium.

feat: HCA consortium

---

backend/wmg/api/v2.py

Adding more datadog tracing for wmg v2 API
- Passing unit tests

chore: Add more datadog tracing to wmg v2 api

---

Makefile

to make spacing used in the makefile consistent

fix: Clean up format of make file

---

tests/unit/processing/test_process_validate.py

- these tests should not have been deleted
- add tests that were accidentally deleted
- check the unit tests pass

fix: add validation tests that were deleted

---

frontend/src/views/CensusDirectory/index.tsx

chore(census): update copy for spotlight page

---

backend/layers/processing/dataset_metadata_update.py
backend/layers/processing/h5ad_data_file.py

refactor: use common tiledb ctx config for cxg

---

frontend/tests/README.md

i had trouble running e2e tests locally
updates the e2e test docs based on some feedback from @tihuan and @kaloster !
n/a

chore: update e2e test docs

---

frontend/.eslintrc.js
frontend/package-lock.json
frontend/package.json
frontend/src/views/WheresMyGeneV2/components/HeatMap/connect.ts
frontend/src/views/WheresMyGeneV2/components/HeatMap/index.tsx
frontend/src/views/WheresMyGeneV2/components/HeatMap/style.ts

- #5905
- added memoized value to count Total rows
- added Skeleton component and count rows and columns to create loader effect
- utilized `isLoading` and `isLoadingAPI` to hide/show heatmap/loader
- added prop to heat map to hide it using css so `isAnyTissueLoading` can still be utilized
** there are 2 types of animation here - around the 27 second mark this changes into 'wave' animation
https://github.com/chanzuckerberg/single-cell-data-portal/assets/7976579/b7fb292a-d4c2-4d7b-b128-83a0e3d13d5a

feat: add loading state to heatmap

---

backend/layers/business/business.py
backend/layers/business/business_interface.py
backend/layers/business/entities.py
backend/portal/api/portal-api.yml
backend/portal/api/portal_api.py
tests/unit/backend/layers/api/test_portal_api.py
tests/unit/backend/layers/business/test_business.py

- #5697
- Removed POST /datasets/datasetId/asset/assetId endpoint and related test code.

refactor: removed POST asset endpoint

---

backend/wmg/api/common/rollup.py

Since updating this function to optimize its performance, I forgot to also update its docstring. Here I added more detail describing what the function is doing.

chore: improve docstring for rollup function

---

Dockerfile.processing_base
frontend/doc-site/03__Download Published Data.mdx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/DataFormat/constants.ts
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/DataFormat/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/DownloadLink/components/CopyCaption/index.tsx

- #5532 
- build Seurat v5 objects during ingestion
- change v4 references in UI text to v5
- Already tested manually by converting; @jychien confirmed file looked good

feat: upgrade to Seurat v5

---

.github/workflows/build-images-and-create-deployment.yml

as titled, since we've completed the pen test

feat: reenable dev deploys

---

frontend/runtime_configs/dev.env
frontend/runtime_configs/local.env
frontend/runtime_configs/prod.env
frontend/runtime_configs/rdev.env
frontend/runtime_configs/staging.env
package-lock.json

fix(census-spotlight): fix runtime vars

---

frontend/census-projects.json

feat: update mantained projects info

---

backend/layers/common/entities.py
backend/layers/processing/make_seurat.R
backend/layers/processing/reprocess_dataset_metadata.py

- #6345
- Fix logic for assigning new keys to RDS artifacts
- support adding new keys, not just re-assigning values of existing ones 
- rdev

fix: add schema_reference + citation to RDS artifacts

---

frontend/src/views/CensusDirectory/index.tsx

Per @pablo-gar 's punch list. Please review to make sure the email addresses are as desired (`soma@` vs `cellxgene@`). 
NOTE: AUTO MERGE IS ON because I am working asynchronously and this is a small and safe PR.

chore(): Copy updates

---

frontend/census-projects.json

feat(census-models): fix Geneformer description

---

frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/DownloadLink/components/CopyButton/index.tsx
frontend/src/views/CensusDirectory/components/Project/ProjectButtons/components/EmbeddingButton/connect.ts
frontend/src/views/CensusDirectory/components/Project/ProjectButtons/components/EmbeddingButton/index.tsx
frontend/src/views/CensusDirectory/components/Project/index.tsx

fix: small changes

---

.github/workflows/build-images.yml

- the sha should be the first 8 digits to align with what upgrade expected

fix: fix upgrade during deployment

---

backend/wmg/data/snapshot.py

Fix bug in `_local_disk_snapshot_is_valid()` implementation such that it checks if `latest_snapshot_identifier` file exists before executing other validity checks.
- modify `_local_disk_snapshot_is_valid()` implementation
- Unit tests
- Manual test on rdev

fix: Fix bug in _local_disk_snapshot_is_valid implementation

---

.github/workflows/build-images-and-create-deployment.yml
.github/workflows/promote-staging-to-prod.yml
.github/workflows/schema-migration.yml
.github/workflows/trigger-release-candidate-build-and-deploy.yml

- #5482 
- add
- remove
- modify

fix: re-add repository_dispatch and fix processing image workflow ref

---

frontend/src/views/WheresMyGeneV2/components/InfoPanel/components/SourceData/constants.ts
frontend/src/views/WheresMyGeneV2/components/InfoPanel/components/SourceData/index.tsx

- #6285
- added constant for disclaimer text
- added disclaimer to datasource panel

chore: add disclaimer to source data panel

---

frontend/doc-site/04__Analyze Public Data/4_2__Gene Expression Documentation/4_2_3__Gene Expression Data Processing.mdx

- #4935
- added link as per ticket

chore: add documentation update

---

python_dependencies/backend/requirements.txt

- knock out a few requirements at once.
- update backend requirements

chore: Update backend dependencies

---

frontend/doc-site/04__Analyze Public Data/4_2__Gene Expression Documentation/4_2_6__Gene Expression Source Data.mdx

- #6318
- uploaded new compressed data snapshots to assets bucket
- fixed links and updated date in docs

fix: data snapshots provided in docs

---

frontend/src/common/queries/collections.ts

#6508
- Updated published counterpart (used when diff'ing revisions) to be built from its own datasets and not the revision's datasets.
- Tested manually in rdev.
- ~~Added e2e test~~. I am experiencing flakiness in the e2e test and have created [Add e2e test exercising dataset diff functionality](https://github.com/chanzuckerberg/single-cell-data-portal/issues/6561) to address this separately.

fix: dataset diff

---

PULL_REQUEST_TEMPLATE.md

- #6417
1. Add a new checklist item in the PR template to remind people to verify analytics events still work

docs: 6417 Update PR template to remind UI changes to check analytics

---

frontend/src/views/CellGuide/components/CellGuideCard/components/MarkerGeneTables/index.tsx
frontend/tests/features/cellGuide/cellGuide.test.ts

chore: update tooltip for canonical marker genes in cellguide

---

Dockerfile.wmg_pipeline

#6626 
- add
- remove
- modify

fix: Update awscli library for wmg pipeline

---

frontend/tests/features/collection/revision.test.ts

- #6561 
- Added test for exercising frontend dataset diff/publish button functionality.

feat: dataset diff test

---

.github/dependabot.yml

since i'm not on applications anymore 💔 
changes the WMG owner from me to prathap
n/a
n/a

chore: update WMG owner to prathap :D

---

frontend/src/views/CensusDirectory/components/DetailItem.tsx
frontend/src/views/CensusDirectory/components/Project/ProjectButtons/index.tsx
frontend/src/views/CensusDirectory/components/Project/index.tsx

fix(models): add differentiation label for embedding axis and possible hydration error fix

---

frontend/src/common/queries/filter.ts
frontend/src/components/Collection/components/CollectionDatasetsGrid/components/Row/DatsetRow/components/ReorderModeRow/index.tsx
frontend/src/components/Collection/components/CollectionDatasetsGrid/components/Row/DatsetRow/index.tsx
frontend/src/components/Collections/components/ReorderDatasets/index.tsx
frontend/src/views/Collection/components/CollectionActions/components/MoreDropdown/components/Menu/index.tsx
frontend/tests/features/collection/revision.test.ts

test: reorder E2E

---

python_dependencies/wmg/requirements.txt

Updating dependencies for WMG pipeline - `coverage` and `owlready2` python packages
- update requirements.txt file for WMG pipeline
- Passing automated tests

chore: Update wmg dependencies

---

.github/workflows/build-images-and-create-deployment.yml

fix: add quotes around refs/heads/<env>

---

frontend/doc-site/04__Analyze Public Data/4_2__Gene Expression Documentation/4_2_6__Gene Expression Source Data.mdx

- Update source data for GE
- Tested a few queries in the UI and found that the results match in the source data

chore: update links to ge data in documentation

---

frontend/doc-site/04__Analyze Public Data/4_2__Gene Expression Documentation/4_2_6__Gene Expression Source Data.mdx

chore: update documentation text for ge source data snapshot

---

.github/workflows/build-images-and-create-deployment.yml

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/6718
adds dev in as an environment that we deploy to
n/a

chore: unfreeze deploys to dev

---

.github/dependabot.yml

fix: enable dependabot.yml

---

backend/wmg/api/wmg_api_config.py
container_init.sh

feat: download only the latest snapshot on wmg container init

---

python_dependencies/cellguide_pipeline/requirements.txt

chore: update cellguide pipeline dependencies

---

backend/layers/thirdparty/crossref_provider.py
tests/unit/backend/layers/thirdparty/test_crossref_provider.py

- #6558
- Modified Crossref response to remove duped authors.
- Added unit tests.
- Tested in rdev.

feat: remove duped Crossref authors

---

Makefile
backend/Makefile

See https://github.com/orgs/community/discussions/116610

ci: switch to docker-compose v2

---

backend/wmg/data/constants.py

feat: update wmg pinned schema version to v5.0.0

---

backend/wmg/pipeline/validation/validation.py

chore: update wmg validation constant for xist test

---

scripts/populate_rdev_with_wmg_data.sh

chore: update snapshot version for rdev seeding

---

backend/cellguide/pipeline/constants.py

chore: reduce number of cpus for the cellguide pipeline

---

frontend/tests/features/cellGuide/cellGuide.test.ts

chore: fix e2e test after COG integration

---

frontend/tests/features/cellGuide/cellGuide.test.ts

chore: fix flakey e2e test

---

.github/dependabot.yml

- engineer left team
- 
- modify owner of requirements of processing container

chore: reassign processing requirements.txt

---

frontend/src/components/CreateCollectionModal/components/Content/index.tsx
frontend/src/components/Header/components/CuratorAPIKeyGenerator/index.tsx
frontend/src/components/common/Form/Dropdown/index.tsx
frontend/src/components/common/Form/Dropdown/style.ts
frontend/src/components/common/MoreDropdown/index.tsx
frontend/src/views/CellGuide/components/CellGuideCard/index.tsx
frontend/src/views/CellGuide/components/TissueCard/index.tsx
frontend/src/views/WheresMyGeneV2/components/Filters/components/ColorScale/connect.ts
frontend/src/views/WheresMyGeneV2/components/Filters/components/ColorScale/index.tsx
frontend/src/views/WheresMyGeneV2/components/Filters/components/ColorScale/types.ts
frontend/src/views/WheresMyGeneV2/components/Filters/components/Compare/connect.ts
frontend/src/views/WheresMyGeneV2/components/Filters/components/Compare/index.tsx
frontend/src/views/WheresMyGeneV2/components/Filters/components/Organism/connect.ts
frontend/src/views/WheresMyGeneV2/components/Filters/components/Organism/index.tsx
frontend/src/views/WheresMyGeneV2/components/Filters/components/Sort/connect.ts
frontend/src/views/WheresMyGeneV2/components/Filters/components/Sort/index.tsx
frontend/src/views/WheresMyGeneV2/components/Filters/components/Sort/types.ts

Fix migration bugs

---

frontend/doc-site/032__Contribute and Publish Data.mdx

- #6673
- Updated docs to include link to accepted assays.
- Tested locally, and on rdev.

feat: accepted assays docs

---

Dockerfile.wmg_pipeline

chore(fix): wmg dockerfile

---

frontend/tests/features/cellGuide/cellGuide.test.ts

chore: remove test for cl description

---

frontend/tests/features/cellGuide/cellGuide.test.ts

chore: skip vestigial e2e test

---

frontend/tests/features/cellGuide/cellGuide.test.ts

chore: update vestigial e2e test

---

.github/workflows/push-tests.yml
.github/workflows/rdev-delete-for-pr.yml
.github/workflows/rdev-update-for-pr.yml

chore: fix yaml parsing issue on gha

---

.github/workflows/push-tests.yml
.github/workflows/rdev-delete-for-pr.yml
.github/workflows/rdev-update-for-pr.yml

chore: try three, maybe this works

---

backend/wmg/pipeline/load_cube.py
tests/unit/wmg_processing/test_cube_pipeline.py

chore: fix accidentally refactored wmg bucket name

---

frontend/src/views/CensusDirectory/components/Project/ProjectButtons/style.tsx

chore: fix census model buttons

---

backend/common/census_cube/data/ontology_labels.py

- Publication group-by
- added exception handling

chore: publication group-by fix

---

.github/workflows/build-images-and-create-deployment.yml

Unfreezing since cellxgene schema 5.1 migration is complete

chore: unfreeze dev

---

frontend/tests/features/differentialExpression/differentialExpression.test.ts

chore: fix de e2e test by reloading when running new DE queries

---

frontend/src/views/CellGuide/components/CellGuideCard/components/common/Table/index.tsx
frontend/src/views/DifferentialExpression/components/Main/components/DeResults/components/DifferentialExpressionResults/index.tsx

chore(de): truncate genes longer than 8 characters and display tooltip

---

frontend/src/views/DifferentialExpression/components/Main/components/DeResults/components/DifferentialExpressionResults/connect.ts
frontend/src/views/DifferentialExpression/components/Main/components/DeResults/components/DifferentialExpressionResults/index.tsx
frontend/src/views/DifferentialExpression/components/Main/components/DeResults/components/DifferentialExpressionResults/style.ts

chore(de): add datasets to group indicators

---

frontend/src/views/DifferentialExpression/common/constants.ts
frontend/src/views/DifferentialExpression/components/Main/connect.ts
frontend/src/views/DifferentialExpression/components/Main/index.tsx
frontend/src/views/DifferentialExpression/components/Main/style.ts
frontend/tests/features/differentialExpression/differentialExpression.test.ts

feat(de): clear all button can clear query groups

---

frontend/src/views/DifferentialExpression/components/Main/components/Filters/components/FilterDropdown/index.tsx
frontend/src/views/DifferentialExpression/components/Main/components/Filters/components/FilterDropdown/style.ts

feat(de): add no options callout text

---

frontend/src/views/DifferentialExpression/components/Main/components/DeResults/components/DifferentialExpressionResults/style.ts
frontend/src/views/DifferentialExpression/components/Main/components/DeResults/style.ts
frontend/src/views/DifferentialExpression/components/Main/components/Filters/components/FilterDropdown/style.ts
frontend/src/views/DifferentialExpression/components/Main/components/Filters/style.ts
frontend/src/views/DifferentialExpression/components/Main/index.tsx
frontend/src/views/DifferentialExpression/components/Main/style.ts

feat(de): add responsiveness to two panels (query builders not responsive)

---

frontend/src/views/DifferentialExpression/components/Main/components/Filters/components/FilterDropdown/connect.ts
frontend/src/views/DifferentialExpression/components/Main/components/Filters/components/FilterDropdown/index.tsx
frontend/src/views/DifferentialExpression/components/Main/components/Filters/components/FilterDropdown/utils.ts

feat(de): update dropdown selection visual behavior in the query selectors

---

frontend/src/views/DifferentialExpression/components/Main/components/DeResults/components/DifferentialExpressionResults/components/QueryGroupTags/constants.ts
frontend/src/views/DifferentialExpression/components/Main/components/DeResults/components/DifferentialExpressionResults/components/QueryGroupTags/index.tsx
frontend/src/views/DifferentialExpression/components/Main/components/DeResults/components/DifferentialExpressionResults/components/QueryGroupTags/style.ts
frontend/src/views/DifferentialExpression/components/Main/components/DeResults/components/DifferentialExpressionResults/index.tsx

chore(de): add effect size tooltip and hyperlinks to cell type tags

---

frontend/tests/features/differentialExpression/differentialExpression.test.ts

chore: fix de e2e tests

---

backend/layers/business/business.py
backend/layers/common/cleanup.py
backend/layers/common/validation.py
backend/portal/api/portal-api.yml
backend/portal/api/portal_api.py
tests/unit/backend/layers/api/test_portal_api.py
tests/unit/backend/layers/business/test_business.py

- #7063 
- Added update dataset logic to business layer.
- Added update dataset endpoint to DP API.
- DP API unit tests 
- Business layer unit tests
- rdev

feat: update dataset title DP endpoint

---

backend/de/api/v1.py
frontend/src/views/CellGuide/components/CellGuideCard/components/Description/index.tsx
frontend/src/views/CellGuide/components/common/OntologyDagView/index.tsx

chore(de): add de filter rollup

---

backend/curation/api/curation-api.yml
backend/curation/api/v1/curation/collections/collection_id/datasets/dataset_id/actions.py
tests/unit/backend/layers/api/test_curation_api.py

- #7062 
- Added update dataset endpoint to Discover API.
* Discover API unit tests
* rdev

feat: update dataset title Curation endpoint

---

Dockerfile.backend
Dockerfile.backend_de
Dockerfile.backend_wmg
Dockerfile.cellguide_pipeline
Dockerfile.dataset_submissions
Dockerfile.processing
Dockerfile.upload_failures
Dockerfile.upload_success
Dockerfile.wmg_pipeline

- https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/zh/19
- add AWS Root CA to all docker images
- functional and end2end tests must pass

fix(RDS CA): Install the update AWS root CA in docker images

---

.github/dependabot.yml

chore: comment out dependabot

---

.github/dependabot.yml

chore: set pull request limit to 0

---

frontend/src/views/CellGuide/components/CellGuideCard/components/Description/index.tsx
frontend/src/views/DifferentialExpression/common/constants.ts
frontend/src/views/WheresMyGeneV2/components/CellInfoSideBar/index.tsx

Hide open in DE links because DE is not launched yet.

chore: hide open in DE links

---

scripts/smoke_tests/setup.py

- add required parameters to upload_and_wait
- verify that e2e_login_tests pass

fix: smoke test setup

---

backend/common/census_cube/data/query.py
backend/de/api/v1.py
frontend/src/views/CellGuide/components/CellGuideCard/components/common/HelpTooltip/index.tsx
frontend/src/views/DifferentialExpression/common/store/reducer.ts
frontend/src/views/DifferentialExpression/components/Main/components/DeResults/components/DifferentialExpressionResults/components/QueryGroupTags/index.tsx
frontend/src/views/DifferentialExpression/components/Main/components/DeResults/components/DifferentialExpressionResults/connect.ts
frontend/src/views/DifferentialExpression/components/Main/components/DeResults/components/DifferentialExpressionResults/index.tsx
frontend/src/views/DifferentialExpression/components/Main/components/DeResults/components/DifferentialExpressionResults/style.ts
frontend/src/views/DifferentialExpression/components/Main/components/DeResults/style.ts
frontend/src/views/DifferentialExpression/components/Main/components/Filters/components/FilterDropdown/connect.ts
frontend/src/views/DifferentialExpression/components/Main/components/Method/index.tsx
frontend/src/views/DifferentialExpression/components/Main/components/Method/style.ts
frontend/src/views/DifferentialExpression/components/Main/components/OverlapBehavior/index.tsx
frontend/src/views/DifferentialExpression/components/Main/index.tsx
frontend/src/views/DifferentialExpression/components/Main/style.ts
frontend/tests/features/differentialExpression/differentialExpression.test.ts

- Final changes noted as required during internal QA for launching DE
- added method tooltip and updated background text on main page
- updated ordering and wording of overlap behavior icons
- updated behavior of results panel when changing filter tags. previously, results panel tags were updating when updating the filter dropdown. the query group tags are now determined from the SUBMITTED query groups.
- Rdev, manual QA

chore(de): final polish for launch

---

backend/common/census_cube/data/constants.py
backend/common/census_cube/utils.py

- Fix post-deploy e2e tests in dev/staging

fix(e2e tests): use 5.1.0 ontology parser

---

frontend/src/common/analytics/events.ts
frontend/src/views/DifferentialExpression/components/Main/components/DeResults/components/DifferentialExpressionResults/index.tsx
frontend/src/views/DifferentialExpression/components/Main/components/DeResults/connect.ts
frontend/src/views/DifferentialExpression/components/Main/connect.ts
frontend/src/views/DifferentialExpression/components/Main/utils.ts

chore(de): final updates to analytics

---

backend/curation/api/curation-api.yml
backend/layers/common/validation.py
backend/portal/api/portal-api.yml
frontend/doc-site/032__Contribute and Publish Data.mdx
frontend/src/components/CreateCollectionModal/components/Content/common/constants.ts

feat: add Pediatric Center of Excellence in Nephrology (PCEN) to valid consortia

---

.happy/terraform/modules/wmg-batch/main.tf
.happy/terraform/modules/wmg-batch/variables.tf

- #7298 
- Added env var to wmg-batch where census package is being used

chore: add census user agent env var

---

.github/workflows/build-images-and-create-deployment.yml

- Isolating dev env for use in schema 5.2 test migration

chore: isolate dev env for schema 5.2 test migration

---

frontend/src/components/common/Filter/common/constants.ts
frontend/tests/features/filter/constants.ts
frontend/tests/features/filter/useCategoryFilter.test.ts
frontend/tests/features/filter/utils.test.ts

- #6994 
- Updated development stage constants.
- Manually test.

feat: 5.2.0 dev stage UI

---

frontend/src/components/BottomBanner/constants.ts
frontend/src/components/Layout/index.tsx

- Add `BottomBanner` to landing to keep it consistent with other CxG apps

chore: add bottom banner to landing

---

frontend/src/components/LandingFooter/index.tsx
frontend/src/components/Layout/index.tsx

- Move bottom banner out of layout and into landing footer

chore: move bottom banner to landing footer

---

frontend/doc-site/032__Contribute and Publish Data.mdx

- More thorough, complete summary of the submission requirements. Goal is to make this doc more comprehensive & user friendly so that curators can reply to submission requests with a link to this doc rather than copy/paste the summary into an email.
- bold property names & add nested notes
- clarify accepted assays that aren't on Census list
- specify a _single_ contact is required
- link to current schema doc for specs
- consistent phrasing/grammar where possible

docs: refactor contribute doc

---

.github/workflows/push-tests.yml
tests/test_utils/__init__.py

- #7438 
- Updated Coverage to always upload a report - `if: always()`
- Updated `compare_dict()` to handle lists of dictionaries (sort by keys before comparing) to ensure tests are deterministic

fix: CellGuide flakey test and coverage

---

tests/functional/backend/constants.py
tests/functional/backend/utils.py

looks like this url disappeared somehow. i updated this to be the 5.0 "visium small" artifact in dropbox

fix: visium test url in main

---

backend/layers/processing/process_logic.py
tests/functional/backend/constants.py
tests/functional/backend/utils.py

as titled. updates the asset url to the 5.3 visium dataset

fix: visium test in schema 5.3 branch

---

frontend/package-lock.json
frontend/package.json

Hotfix for prod - updating `next` to the latest patch version

fix: Next critical update

---

frontend/package-lock.json
frontend/package.json

New PR based on prod + main with resolved conflicts - approved [here](https://github.com/chanzuckerberg/single-cell-data-portal/pull/7502)

chore: Prod to main to add Nextjs hotfix

---

.happy/terraform/modules/batch/main.tf

chore: increase memory for processing atac fragments

---

.happy/terraform/envs/rdev/main.tf

- Increase resources for rdev instance to see if it helps with failing tests

fix: rdev resources

---

.github/workflows/rdev-tests.yml
frontend/tests/features/cellGuide/cellGuide.test.ts
frontend/tests/features/collection/collection.test.ts
frontend/tests/features/collection/revision.test.ts

- Identify offending tests and de-flake
- Seed db workflow - explicitly define python
- Collections
- CellGuide
- Logged in DOI tests
- Logged in Edit

fix: various e2e improvements

---

frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/utils.ts

- Added timeout to allow multiple downloads on Multiome. 
- Final change than should be ready to promote staging to prod.

fix: allow multiple downloads by adding a slight timeout

---

.github/workflows/deploy-happy-stack.yml
.github/workflows/rdev-tests.yml

chore: migrate to standard runners

---

.github/workflows/deploy-happy-stack.yml

fix: Slack notification logic

---

.happy/terraform/modules/sfn/main.tf

fixes this issue: https://si.prod.tfe.czi.technology/app/happy-singlecell/workspaces/stage-stagestack/runs/run-YF55EWq4CdmeACx2

fix: invalid json in SFN

---

frontend/doc-site/032__Contribute and Publish Data.mdx

- Update the Contribute documentation to reflect the updated submission criteria & requirements for schema 6.0.0

docs: refactor contribute doc for schema 6.0.0

---

frontend/doc-site/032__Contribute and Publish Data.mdx

- add
1. Actual code block to preserve the surrounding spaces ` || `
1. Correct typo
- remove
- modify
BEFORE:
AFTER:

docs: Fix prettier error

---

python_dependencies/processing/requirements.txt

related to this [bug](https://czi.atlassian.net/browse/VC-4234)

fix: update cellxgene-schema version in requirements.txt

---

frontend/src/components/common/Filter/common/entities.ts
frontend/tests/features/filter/filter.test.ts

- https://czi.atlassian.net/browse/VC-3364
- Update Cell Culture enum and associated test
- Added Cell Line to enum and test case

chore: Update Cell Culture enum

---

python_dependencies/processing/requirements.txt

https://czi.atlassian.net/jira/software/c/projects/VC/boards/2818?selectedIssue=VC-4254

chore: bump cellxgene-schema version to 6.2.2

---

.gitignore
.mcp.json
CLAUDE.md
frontend/census-notebook-links.json
frontend/src/common/featureFlags/features.ts
frontend/src/components/BYODModal/constants.ts
frontend/src/components/BYODModal/index.tsx
frontend/src/components/BYODModal/style.ts
frontend/src/components/Collection/components/CollectionDatasetsGrid/components/DatasetsGrid/style.ts
frontend/src/components/Header/index.tsx
frontend/src/components/MobileFriendlyHeader/index.tsx
frontend/src/pages/tos.tsx
frontend/tsconfig.json

Add button and modal to connect CxG and BYOD
- https://czi.atlassian.net/browse/UW-9
add
- Claude.md file and .mcp.json
- Feature flag "byod" to hide until launch
- button to top nav
- BYODModal

feat: UW-9 addition of byod entry point from cxg top nav

---

frontend/src/components/Layout/index.tsx

feat: Update benchmark banner date
