chanzuckerberg/single-cell-data-portal

infra/envs/test/main.tf
infra/envs/test/terraform.tfvars.example
infra/envs/test/variables.tf
infra/modules/backend/browser/rds.tf
infra/modules/backend/browser/variables.tf

Creates an RDS Aurora MySQL cluster via terraform in the `test` env for the browser database layer. MySQL is favored over PostgreSQL to optimize for simple query/read performance to support the web app. Version `5.7.mysql_aurora.2.07.1` (latest) is configured, however, due to [limited SQL 5.7 feature support in Aurora](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Updates.20180206.html), it isn't clear at this point that this is the right version. Moving forward with latest version, may re-evaluate in the future.
Closes #77

Create browser RDS terraform resources in test env

---

dcp_prototype/backend/wrangling/migrations/metadata_schema_representation/old_entities/old_dataset_metadata.py
dcp_prototype/backend/wrangling/migrations/scripts/migrate_dcp_one_to_dcp_two.py
dcp_prototype/backend/wrangling/migrations/utils/constants.py

First pass:
1. thread the portion that reads and processes the json files from s3.
2. add a filter to the paginator to only return json files
3. avoid O(n^2) algorithm in order_file_list (there could be 100000s of files)
The number of threads can be selected at runtime.
In the example with 2500 bundles, the time went down from 2-3 hours to a little under 15 minutes
That was with 16 threads

Parallelize script to read in metadata files for a project and transform the metadata graph into entities to submit to the Ledger DB. (#85)

---

dcp_prototype/backend/wrangling/README.md
dcp_prototype/backend/wrangling/migrations/scripts/migrate_dcp_one_to_dcp_two.py

Improve the performance of the migration_dcp_one_to_dcp_two,py script.
And start a readme to document how to use this script.

Improve the migrate_dcp_one_to_dcp_two.py and add a README #136

---

dcp_prototype/backend/wrangling/README.md
dcp_prototype/backend/wrangling/migrations/scripts/metadata_aggregator.py
dcp_prototype/backend/wrangling/migrations/scripts/migrate_dcp_one_to_dcp_two.py

The format on s3 for dcp metadata has changed.  so the tool needed to be updated.
For example, the object names do not indicate the entity type.  This can be determined
by processing the text of the file.
The whole script has been refactored:
1. There was code to upload data to s3.  This has been removed.
2. A new feature to read the metadata from a tar.gz file has been implemented.  It can
read the tar.gz file inplace (without having to extract the contents as files).
3. The script can first download the .tar.gz file from s3 and then process it.  
Add a new script called metadata_aggregator.py:
1. downloads all the metadata for a project from s3
2. tar/gz the contents
3. push the tar.gz file back up to s3
All 29 projects have been processed with the metadata_aggregator.py script. …

refactor dcp1 to dcp2 migration tool (#165)

---

dcp_prototype/backend/wrangling/migrations/common/dataset_metadata.py
dcp_prototype/backend/wrangling/migrations/common/metadata.py
requirements-dev.txt
tests/dcp-prototype/backend/wrangling/fixtures/WongAdultRetina.json

1. fix biosample_names and biosample_categories
2. fix bug in handing of enrichment_protocol
3. workaround for missing donor species in one of the datasets
The biosample_categories may not be correct.  This is the part
that chooses between primary, cell line and organoid.
Issue #176

Updates and fixes to the dcp1 migration script

---

dcp_prototype/backend/browser/api/Makefile
dcp_prototype/backend/browser/iam/policy-templates/browser-api-lambda.json
dcp_prototype/frontend/Makefile
infra/envs/dev/main.tf
infra/envs/dev/terraform.tfvars.example
infra/envs/dev/variables.tf
infra/modules/frontend/browser/static_website.tf

These changes create terraform resources for the browser's `dev` environment. These changes coincide with the AWS account migration from `856863240400` (czi-hca-dev) to `699936264352` (single-cell-dev). As we spin up in the new account, the browser infrastructure will deprecate the `test` environment in favor of per-developer test environments, `dev` and `prod`.
The account migration for the browser is complete with the site running at: http://dcp-site-deployment-dev.s3-website-us-east-1.amazonaws.com/ . Since its bucket hosted, we can preserve the old URL (dcp-static-site) after destroying resources in the old account.
Note:
Ledger resources have been commented out in terraform (`main.tf`) for the time being.
Closes #198

Create dev deployment for browser

---

dcp_prototype/backend/browser/api/app.py
dcp_prototype/backend/browser/code/common/db_utils.py
dcp_prototype/backend/browser/code/common/s3_utils.py
dcp_prototype/backend/browser/iam/policy-templates/browser-api-lambda.json
infra/modules/backend/browser/s3.tf

These changes enable downloading of project loom files via presigned S3 URLs. Download URLs are currently set to expire in 24 hours.
Closes #130 
Closes #148

Implement file download API

---

dcp_prototype/frontend/src/components/authenticate.js
dcp_prototype/frontend/src/components/exploreData.js
dcp_prototype/frontend/src/components/footer.js
dcp_prototype/frontend/src/components/header.js
dcp_prototype/frontend/src/components/layout.js
dcp_prototype/frontend/src/components/login-signup.js
dcp_prototype/frontend/src/components/projectOverview.js
dcp_prototype/frontend/src/components/projectsList.js
dcp_prototype/frontend/src/components/projectsListHeading.js
dcp_prototype/frontend/src/components/styledButton.js
dcp_prototype/frontend/src/components/theme.js
dcp_prototype/frontend/src/pages/project.js

Updated browser front-end to improve aesthetics and file download user experience:
- styled project page
- updated button styles
- updated logo to CZI logo
- surfaced data access to top of page
- implemented user flows for unauthenticated and unavailable data scenarios
Closes #35
Closes #200 
Projects list page (PLP):
Project page (PP):
Unauthenticated data view:
Unavailable data view:

update styles: project page, button styles, logo, file download ux

---

dcp_prototype/frontend/.env.development
dcp_prototype/frontend/Makefile
dcp_prototype/frontend/src/contexts/auth0Context.js
infra/envs/dev/main.tf
infra/envs/test/main.tf

- Adding terraform to host the single-cell browser from s3 behind cloudfront and over https. This will allow us to securely deploy the site using CZI-INFRA best practices. 
- This PR also adds the gastby env.production file that will be will be uploaded to the gatsby site bucket and downloaded and used during the deployment of the site. This allows us to store the configuration of the each deployment environment easier.
- There were conflict with the existing dcp site bucket name so I created a new bucket with appends the aws_account_id to the end of the bucket.
- Changed the AUTH0_CLIENT_ID for env.develop. This will allow us to continue to test gatsby locally while the old AUTH0_CLIENT_ID will be used for the host site. There is no security risk in reusing the client ids.

Gatsby Site Deployment With Authentication

---

dcp_prototype/frontend/src/components/projectsList.js

- Refreshing on a project page, does not return the user to the index page.
- The url in the browser window of a project page will correctly link back to the project page.
Fixes #217 
Fixes #215

Refresh on project page and deep linking fix

---

Makefile
dcp_prototype/backend/browser/api/app.py
dcp_prototype/backend/browser/code/common/db_utils.py
dcp_prototype/backend/browser/code/common/s3_utils.py
dcp_prototype/backend/browser/scripts/load_artifact.py
requirements-dev.txt
tests/dcp-prototype/backend/browser/code/common/test_db_utils.py
tests/dcp-prototype/backend/browser/code/common/test_s3_utils.py

- covers `db_utils.py` and `s3_utils.py`
- refactors `db_utils.py` and `s3_utils.py` to be more testable
- E2E functionality (`api/app.py`, SQL queries) covered in functional tests in a separate PR
Closes #219

Add browser backend unit tests

---

.github/workflows/push-tests.yml
README.md
dcp_prototype/backend/browser/README.md

Functional tests require an E2E deployment which is either not possible or overly complicated to perform for every development branch. These tests will be reintroduced in CI/CD as smoketests following a merge and deployment to `dev`, `staging` and `prod`. Until then, they will remain a useful tool to use on developer environments.

Remove functional tests from push tests

---

dcp_prototype/backend/browser/api/app.py

- modified chalice application to Allowing Origin "*" using chalice.CORSConfig
- this will allow us to send the auth token to the backend

Authorization header allowed

---

dcp_prototype/backend/browser/code/common/browser_orm.py
dcp_prototype/backend/browser/scripts/create_db.py
dcp_prototype/backend/browser/scripts/load_artifact.py
dcp_prototype/backend/browser/scripts/mock.py

- When `DEPLOYMENT_STAGE` is set to `test`, an in-memory SQLite database will service all database connections
- These changes propose the deprecation of the deployed `test` environment in favor of [`dev`, `staging`, and `prod`] environments. The `test` moniker will then be reserved for the local environment and unit testing
- [TODO](https://app.zenhub.com/workspaces/dcp2-5e2a191dad828d52cc78b028/issues/chanzuckerberg/dcp-prototype/262): deprecate and shut down deployed `test` environment via Terraform if this proposal sounds good @Bento007 
- Tests covered in #256 
Related to #237

Use in-memory SQLite db for testing

---

dcp_prototype/frontend/src/components/exploreData.js
dcp_prototype/frontend/src/components/footer.js
dcp_prototype/frontend/src/components/header.js
dcp_prototype/frontend/src/components/layout.js
dcp_prototype/frontend/src/components/projectOverview.js
dcp_prototype/frontend/src/components/projectsList.js
dcp_prototype/frontend/src/components/theme.js
dcp_prototype/frontend/src/pages/project.js

Better legibility for organ and assay names that run over one line (also increased table max width to make this happen less often) + fixing spacing issues for "Diabetic Nephropathy..." project page. I also added a bit of styling to the project page to differentiate the labels from their values.

Fixes for #246 and #249

---

dcp_prototype/backend/browser/Makefile
dcp_prototype/backend/browser/api/Makefile
dcp_prototype/backend/browser/api/local_server.py
dcp_prototype/backend/browser/requirements-dev.txt
dcp_prototype/frontend/.env.development
requirements-dev.txt

Adding local-server make recipe to simplify testing of the frontend with a local browser backend.

Adding local-server make recipe 

---

.github/workflows/push-tests.yml
dcp_prototype/backend/browser/api/app.py
dcp_prototype/backend/browser/api/requirements.txt
dcp_prototype/backend/browser/code/common/authorizer.py
dcp_prototype/backend/browser/requirements.txt
dcp_prototype/frontend/.env.development
dcp_prototype/frontend/src/contexts/auth0Context.js
infra/modules/backend/cicd/github_actions_unittests.tf
tests/dcp-prototype/__init__.py
tests/functional/dcp-prototype/backend/browser/test_api.py
tests/unit/dcp-prototype/backend/browser/code/common/test_auth.py
tests/unit/dcp-prototype/backend/browser/code/common/test_authorizer.py

* The frontend gets a token for the browser-api audience. The new AUDIENCE environment variable for the frontend is used to retrieve a token for the browser-api.
* The JWT is verified by the backend using the flow recommended by auth0 https://auth0.com/docs/quickstart/backend/python
* Testing tokens are generated using a secret stored in AWS dcp/backend/browser/test/auth0-secret. These test secret is only used for the DEPLOYMENT_STAGEs "dev", and "test". Auth tests do not run when DEPLOYMENT_STAGE is not "dev, or "test". The secret used to generate the tokens is not linked to a user, therefore the auth0 userinfo endpoint does not work and is skipped when using the test key.
* The JWT is verified for correctness and the public key from auth0 is used to verify the tokens authenticity. …

Adding JWT Token verify to browser backend

---

tests/unit/dcp-prototype/backend/browser/code/common/test_authorizer.py

- Fixing a flaky test with generating an invalid hash
- adding tests for wrong header and wrong message

Adding additional test for invalid token

---

.github/workflows/deploy.yml
browser/backend/chalice/Makefile
browser/backend/requirements-dev.txt
infra/envs/dev/main.tf
infra/envs/dev/terraform.tfvars.example
infra/envs/dev/variables.tf
infra/modules/backend/cicd/github_actions_unittests.tf
infra/modules/backend/cicd/variables.tf

- Adding github actions to automate the deployment of the browser backend when the `master` branch changes.
- A new file is uploaded to the infra s3 bucket. This files contains the current configuration for the chalice deployment. This make it easier to reuse the existing deployed chalice app rather than creating a new chalice app in AWS. A deployment file is stored for each deployment stage. 
- The IAM policy for github_actions has been update to allow github to deploy chalice apps. If a new deployment stage is created, the policy will need to be updated.
- Chalice apps for new stage must still be deployed from a local machine first before github can automate the deployment.
- Only the `dev` environment is automatically deployed.

Github Action to Automated Browser Backend Deployment

---

.github/workflows/deploy.yml
infra/envs/dev/main.tf
infra/modules/backend/cicd/github_actions_unittests.tf
infra/modules/backend/cicd/variables.tf

Deploy the frontend to dev whenever master is updated. This will still require us to invalid the cloudfront cache before the changes are seen. This will be automated in the future.

Continuous Deploy Frontend

---

README.md
browser/backend/README.md
browser/backend/scripts/generate_test_artifact.py
browser/frontend/README.md
browser/lambdas/chalice/cloudfront-invalidator/README.md

Closes #299
Nt: `codecov` badge still points to `dcp-prototype`. This will be addressed in #314

Update dcp-prototype references to corpora-data-portal

---

backend/corpora/common/authorizer.py
tests/__init__.py
tests/functional/backend/corpora/test_api.py
tests/unit/__init__.py
tests/unit/backend/__init__.py
tests/unit/backend/corpora/common/test_authorizer.py

* If a different DEPLOYMENT_STAGE is set in the environment, that value is used.
* Adding documentation for why certain DEPLOYMENT_STAGEs are used.

Default DEPLOYMENT_STAGE for tests=='test'

---

backend/corpora/common/corpora_orm.py
backend/corpora/common/entities/dataset.py
backend/corpora/common/entities/entity.py
backend/corpora/common/entities/project.py
tests/unit/backend/corpora/common/entities/test_project.py
tests/unit/backend/corpora/fixtures/database/__init__.py

By utilizing SQLAlchemy Object Relationship Mapping, CRUD operations will be easier to manage across the various tables.
- Adding more shared code to Entity
- Using SQLAlchemy relationships to query for values in other tables for DBProject
- Factoring out common code from Dataset

Refactor project to match dataset

---

backend/chalice/api_server/app.py

- Do not log the body of the request or the response in the logs. It will take up a lot of storage and can contain sensitive information.

[EASY] Remove body from app logs

---

backend/Makefile
backend/config/database.ini
backend/database/README
backend/database/env.py
backend/database/script.py.mako
requirements.txt

Couple notes: much of this code is generated by running `alembic init alembic` and I left most of it as is except for a few formatting things that black decided to change. The main changes here are the `run_migrations_online` function in `env.py` and the scripts for migration which were pulled from the original dcp 2.0 code (which were pulled from upload-service). They provide some nice sugar around being able to execute migrations cleanly.
One thing I'd love to get feedback on is the location of the files. Currently I renamed the `alembic` directory that was created to `database` to more clearly elucidate what the contents are related to and I put the `database.ini` file in the config directory (it was floating in the top level `backend` directory when originally generated). The Makefile …

Add initial alembic migration framework.

---

docs/psycopg2_binary.md

This documentation provides context and instructions for how to retrieve and/or recompile the `psycopg2` binary currently used to deploy the API in the event it is lost, corrupt or needs to be updated. The binary at the moment is stored at `corpora-data-portal/backend/chalice/api_server/vendor/psycopg2`.

Document psycopg2 binary build process

---

.github/workflows/deploy.yml
backend/chalice/cloudfront_invalidator/Makefile

- Assume AWS role for deployment
- Cloudfront-invalidator lambda pulls deployment from the correct s3 bucket

CICD for dev deployment

---

backend/schema/corpora_schema_h5ad_implementation.md

AnnData does not allow a list of dicts, so we have to convert them to json strings.

Add note about converting list of dicts to json

---

backend/corpora/common/corpora_orm.py
backend/corpora/common/entities/dataset.py
backend/corpora/common/entities/entity.py
backend/corpora/common/utils/db_utils.py
tests/unit/backend/corpora/common/entities/test_dataset.py
tests/unit/backend/corpora/common/entities/test_project.py
tests/unit/backend/corpora/common/entities/utils.py
tests/unit/backend/utils.py

Linking objects in corpora_orm to clean up when the parent is deleted.
Contributors are not delete when their dataset is deleted unless they are not connect to any other datasets.

Cascade update and delete of row in the database

---

backend/chalice/api_server/Makefile

Adding DEPLOYMENT_STAGE as a variable when retrieving VPC_ID during the deployment process.
partial fix for #338

Fixing api-server to deploy to multiple stages

---

frontend/gatsby-config.js
frontend/package-lock.json
frontend/package.json

Changes:
1. Adds `gatsby-plugin-asset-path` plugin to serve our static assets from `/dp/*` than root `/*`
2. Update `npm run build` command to add flag `--prefix-paths` as required by the plugin
3. Proof below that prod build now serves static assets from `/dp/*` namespace 🎉 
PTAL! Thank you!
closes #496

496-DP-serve-static-assets

---

requirements.txt

This mirrors a change in cellxgene. The latest s3fs creates a bunch of errors in aiobotocore.

Pin s3fs dependency

---

.github/workflows/push-tests.yml
.gitignore
frontend/.env.development
frontend/.gitignore
frontend/Makefile
frontend/README.md
frontend/src/configs/dev.js
frontend/src/configs/local.js
frontend/src/configs/prod.js
frontend/src/configs/staging.js
frontend/src/globals.ts
frontend/src/pages/index.tsx

This PR moves away from using `.env.[ENV]` to define non-sensitive app configurations to just copy the variables from `src/configs/[ENV].js` to `src/configs/configs.js`.
This way we decouple build env with config env, in order to allow Gatsby prod build to still hit local API endpoint (will be part 2 smoke test PR)
Changes:
1. Update README to reflect the new setup
2. Update deployment yml accordingly
3. Remove `.env.development`
4. Update `.gitignore`
5. Update the app to use the new config file to get `API_URL`
QA steps:
1. Copy `src/configs/dev.js` to `src/configs/configs.js` (please create the file if not available)
2. Run `npm run develop`
3. Browse `http://localhost:8000/` and you should see a list of datasets that match the `dev` env DB

thuang-499-smoke-test-part-1

---

backend/corpora/common/authorizer.py
backend/corpora/common/entities/dataset.py
backend/corpora/lambdas/api/v1/authentication.py
tests/unit/backend/chalice/api_server/__init__.py
tests/unit/backend/chalice/api_server/test_v1_auth.py

Importing the CorpaAuthConfig used by the chalice app to ensure the same class is used in the test. Otherwise there are two CorpaAuthConfig class. One is defined in backend/chalice/api_server/chalicelib/corpora, the other is defined in backend/corpora. We are interested in testing the former.

Fix local library imports to be relative

---

frontend/src/components/ProjectList/common/layout.ts
frontend/src/components/ProjectList/components/Dataset/common/style.ts
frontend/src/components/ProjectList/components/Dataset/components/DownloadDataset/index.tsx
frontend/src/components/ProjectList/components/Dataset/components/DownloadDataset/style.ts
frontend/src/components/ProjectList/components/Dataset/components/MoreInformation/index.tsx
frontend/src/components/ProjectList/components/Dataset/components/MoreInformation/style.ts
frontend/src/components/ProjectList/components/Dataset/components/ViewDataset/index.tsx
frontend/src/components/ProjectList/components/Dataset/components/ViewDataset/style.ts
frontend/src/components/ProjectList/components/Dataset/style.ts
frontend/src/components/ProjectList/components/Heading/index.tsx
frontend/src/components/ProjectList/components/Heading/style.ts

I updated the column to use `flex-grow` instead of percentage, since flex-grow is easier to use and less brittle, as shown below in OLD, where the percentage is consistent between the header and the column below, but somehow it's still not aligned
NEW:
OLD:

thuang-download-buttons-feedback

---

frontend/Makefile

https://stackoverflow.com/questions/20389064/using-gnu-make-functions-to-check-if-variables-are-defined explains why `define ifndef` doesn't work with `$(call)`, and it's easier to just do `check-var-defined = $(if $(1),,$(error $(1) is not defined))`

thuang-fix-FE-makefile

---

frontend/src/components/ProjectList/components/Dataset/components/MoreInformation/index.tsx
frontend/src/components/ProjectList/components/Dataset/components/MoreInformation/style.ts
frontend/src/components/ProjectList/components/Dataset/style.ts
frontend/src/components/ProjectList/index.tsx
frontend/src/components/common/Modal/index.tsx
frontend/stylelint.config.js

Tiny updates:
1. Add a space between "please let us know at" and "cellxgene@chanzuckerberg.com"
2. Add max-width to name column, otherwise it could take up more space than intended (I missed that 😆 )
3. Change "More Information" column to stack links vertically 
For #3, I don't know if that's the best solution, so would love input from @pdugan20 🙏  One thing I was debating with myself is whether we could sort the link by text length, so at least shorter ones are on top and can take a tiny pyramid 🔺 But also unsure if the info links are already sorted by importance? CC: @maniarathi @mckinsel 
Thanks all!
BEFORE:
AFTER:

thuang-download-feedback

---

frontend/src/configs/dev.js
frontend/src/configs/staging.js

- as a user I want data portal to load in under 1 second
- we set up a cloudfront distribution to cache the api content this pr will point the data portal frontend at the cached version of the api
- deployed to dev and saw a significant speed up in load time

Point to cloudfront distribution of apis

---

frontend/gatsby-config.js
frontend/src/components/ProjectList/components/Dataset/components/DownloadDataset/components/Content/components/CurlLink/style.ts
frontend/src/components/ProjectList/components/Dataset/components/DownloadDataset/components/Content/components/DataFormat/index.tsx
frontend/src/components/ProjectList/components/Dataset/components/DownloadDataset/components/Content/components/Details/index.tsx
frontend/src/components/ProjectList/index.tsx
frontend/tests/features/homepage.test.ts

Ticket: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/622
QA checks:
1. Hide scroll bar in Chrome, FF, and Safari
1. Change download prompt text to: Select one of the data formats to view its download details
1. Update .anndata to .h5ad (AnnData v0.7)
1. Update Data Portal description to:
> The cellxgene data portal is a repository of public, explorable single-cell datasets. If you have a public dataset that you would like hosted on this site, please let us know at cellxgene@chanzuckerberg.com.
Thank you!
Proof:

thuang-622-download-ux-fixes

---

frontend/src/components/ProjectList/components/Dataset/style.ts
frontend/src/components/ProjectList/components/Heading/style.ts

Looks like we just needed to add `min-width` and `max-width` as lower and upper bounds for `flex` CSS property!
The reason we can't just use `width: 620px;` is because `width` is ignored when `flex-basis` is set, in this case, `flex: 2` will automatically sets `flex-basis` to `auto`.
Resources:
1. https://mastery.games/post/the-difference-between-width-and-flex-basis/
2. https://css-tricks.com/snippets/css/a-guide-to-flexbox/
AFTER in Chrome:
BEFORE and AFTER in Safari:

thuang-621-dataset-column-fix

---

frontend/src/components/Collections/components/Collection/index.tsx

Doing a better response check to avoid runtime error! 
I forgot BE would return error response like the following, so I need to update how I check for empty datasets:
```ts
{
detail: "None is not of type 'string'↵↵Failed validating 'type' in schema['properties']['obfuscated_uuid']:↵    {'type': 'string'}↵↵On instance['obfuscated_uuid']:↵    None",
status: 500,
title: "Response body does not conform to specification",
type: "about:blank"
}
```
Thank you!

fix FE collection runtime error

---

backend/config/corpora-api.yml

due to migration, there are empty fields that are returned. Changing the openapi spec to accommodate these empty fields.

allow empty fields

---

frontend/src/common/queries/collections.ts
frontend/src/components/Collections/components/Collection/index.tsx
frontend/src/components/Collections/index.tsx
frontend/src/components/CreateCollectionModal/components/Content/index.tsx
frontend/src/components/CreateCollectionModal/index.tsx

Changelog from `thuang-651-part2`:
1. Hard code an existing POST response, since BE endpoint is WIP `frontend/src/common/queries/collections.ts`
1. Code split Create Collection modal's Content component to only download the component when the button is hovered
Changelog from `thuang-651-create-collection-component`:
1. Add `gatsby-plugin-sass` to allow Blueprint.js scss overwrite
1. Add `@blueprintjs/icons`
1. Add `lodash-es` for ES6 module version of lodash, which is tree shaking friendly and, in theory, reduces js bundle size
1. Introduce @hthomas-czi 's design system by adding standardized colors in `frontend/src/components/common/theme.ts` and Blueprint style overwrite in `frontend/src/global.scss`
1. Add `CreateCollectionModal`, which is hidden behind URL param feature flag: …

thuang-651-part2

---

frontend/src/views/Collection/style.ts

fix-collection-page-margin

---

docker-compose.yml
frontend/Dockerfile

NPM in the nodejs:15 docker image has a bug that causes it to OOM. This should fix problems with launching the local dev environment using `make dev-init`

Pin nodejs to version 14

---

frontend/src/configs/dev.js

Seems like we need to remove the `/` at the end of the API URL, otherwise we get `//` in the API request! E.g., 
This somehow prevents Auth cookies from being sent to BE on Dev now

thuang-update-dev-API-url

---

backend/corpora/lambdas/api/v1/authentication.py
tests/unit/backend/chalice/api_server/mock_auth.py
tests/unit/backend/chalice/api_server/test_v1_auth.py
tests/unit/backend/chalice/api_server/test_v1_collection.py

It can now be used simultaneously by multiple tests, and the
port used by the mock server can be immediately reused.
This should avoid the flaky tests.
#719

Improve the mock oauth server tests

---

frontend/src/common/queries/collections.ts
frontend/src/common/utils/getUrlHost.ts
frontend/src/components/Collections/components/Collection/index.tsx
frontend/src/components/Collections/components/Dataset/components/MoreInformation/index.tsx
frontend/src/components/Collections/index.tsx
frontend/src/components/CreateCollectionModal/components/Content/common/constants.ts
frontend/src/components/CreateCollectionModal/components/Content/index.tsx
frontend/src/views/Collection/index.tsx

1. Updates collection link object keys to add `link_` prefix
1. Adds link name display support to fall back to showing the URL host when `link_name` is not available.
1. Create collection flow now works end to end!
QA Steps:
1. Pull the branch `thuang-create-collection-integration`
1. Make sure your `frontend/src/configs/configs.js` points to Dev: `API_URL: "https://api.cellxgene.dev.single-cell.czi.technology",`
1. Make sure you use Requestly Chrome Extension to hard code your `cxguser` and `session` cookies from Dev env
1. Fire up `npm start`
1. Navigate to `http://localhost:8000/?auth=true&cc=true`
1. Click on "Create Collection" button
1. Fill in the form
1. Click "Create"
1. You should now land on your newly created private collection page!
NOTE: You might be able to get this to work …

thuang-create-collection-integration

---

frontend/src/components/CreateCollectionModal/index.tsx
frontend/src/components/Header/components/AuthButtons/index.tsx

This PR fixes the edge case where a user logs out from another tab, the current tab will still be logged in
The issue was that React Query caches the successful response, so even if subsequent calls fail (since the user has logged out from another tab) React Query will still return cached successful response.
The solution is to detect when there's both `userInfo` and `error`, and force refresh the page to log the user out!
closes #517

thuang-517-AuthN-bugfix

---

frontend/src/common/constants/queryParameters.ts
frontend/src/components/CreateCollectionModal/components/CTA/index.tsx
frontend/src/components/CreateCollectionModal/index.tsx

Passed query param to auth backend which is sent with redirect.
Front end reads query param and resumes the user's state in the collection creation  flow.
---
QA:
Navigate to `http://localhost:8000/?showCCModule&auth=true&cc=true`
_also_
On unauthenticated session, authenticating after attempting to create a collection should redirect to:
`https://cellxgene.dev.single-cell.czi.technology/?showCCModule` (redirect is only available on dev as of now)

auth to collection creation flow

---

frontend/src/components/CreateCollectionModal/components/CTA/index.tsx

Query param wasn't assigned a value to reflect when we changed the param digest to operate only on true values

add true value to redirect query param

---

backend/corpora/common/entities/collection.py
tests/unit/backend/corpora/common/entities/test_collection.py

(cherry picked from commit b351c8436819698c1fdfc136b0366762a12133aa)
**Functional:** @MDunitz  
**Readability:** @tihuan 
---
- Change dataset field to empty list from GET collection response when no datasets are present.

Change dataset field to empty list from GET collection response when no datasets are present.

---

scripts/rdev

This adds a "--reset" flag to `./scripts/rdev migrate` that drops the rdev database and then recreates it from the S3 snapshot and any db migrations.
I also cleaned up some duplicate code and ran the python `black` utility on the script.
---
- add
- remove
- modify

Support a wipe/recreate of rdev db's

---

frontend/src/components/Collections/components/Grid/components/DatasetsGrid/index.tsx
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/index.tsx
frontend/src/views/Collection/index.tsx

thuang-radio-useState

---

backend/chalice/api_server/requirements.txt
backend/chalice/upload_failures/requirements.txt

---
- Pin requirement for  rsa>=4.7 in lambda

pin rsa>=4.7 in lambda requirements

---

oauth/clients-config.json

This change (after a `docker-compose restart oidc` and a logout/login) will make sure the local-dev OIDC service returns email and name as part of the ID token.
---
- add
- remove
- modify

Make sure name and email are part of ID token

---

backend/config/corpora-api.yml

---
- modify  GET /dp/v1/datasets/{dataset_uuid}/status to return CANCEL_PENDING rather than CANCEL PENDING

Fix cancel_pending enum

---

backend/config/corpora-api.yml
frontend/src/common/queries/datasets.ts
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/DataFormat/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/style.ts
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/index.tsx
frontend/src/components/Collections/components/Grid/components/DatasetsGrid/index.tsx
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/DeleteDataset/index.tsx
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/DeleteDataset/style.ts
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/Popover/index.tsx
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/Tooltip/index.tsx
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/UploadStatus/index.tsx
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/UploadStatus/style.ts
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/index.tsx
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/utils.ts
frontend/src/components/common/theme.ts
frontend/src/views/Collection/index.tsx
frontend/src/views/Collection/style.ts
frontend/tests/features/homepage.test.ts
frontend/tests/utils/helpers.ts

**Readability:** @Bento007 (was thinking about Madison too, but eyes are important 👀 !!)
---
- add
- remove
- modify
1. FE will poll dataset status endpoint for conversion status until all formats either become `CONVERTED` or `FAILED`. When CXG file becomes available, we also show the `Explore` button that takes users to its Explorer page
1. Download dataset + cancel prompt
@hthomas-czi @brianraymor : I didn't have time to implement the dropdown menu for downloading the files, because I realized last night that it would take maybe 2 more points to refactor the old code to play well with the new feature. 
In the meantime, clicking on the "Download" button will trigger the existing download modal with unavailable formats disabled. If we need to implement the download …

thuang-705-upload-datasets-part-3

---

frontend/src/common/modules/datasets/selectors.ts
frontend/src/components/Collections/components/Dataset/common/style.ts
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/style.ts
frontend/src/components/Collections/components/Dataset/index.tsx
frontend/src/views/Collection/index.tsx

#850 
@seve 
@MDunitz 
---
- add
- Add selector `hasAssets()` to only enable the Download button if `true`
- Add new folder and file `frontend/src/common/modules/datasets/selectors.ts `
- modify
- Disable download button if no asset is available for download
Homepage:
Collection Page:
UPDATE (1/26):
New disabled style:

thuang-850-fix-download-button

---

frontend/package-lock.json
frontend/package.json
frontend/src/common/API.ts
frontend/src/common/queries/collections.ts
frontend/src/components/Alert/index.ts
frontend/src/components/Collections/components/DeleteCollection/index.tsx
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/DeleteDataset/index.tsx
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/index.tsx
frontend/src/components/Collections/components/PublishCollection/index.tsx
frontend/src/views/Collection/index.tsx
frontend/src/views/Collection/utils.tsx
frontend/tests/features/collection.test.ts
frontend/tests/features/homepage.test.ts
frontend/tests/utils/helpers.ts

#804 
@seve 
@Bento007 
---
- add
1. `COLLECTION_PUBLISH` API
2. `publishCollection()` and `usePublishCollection()`
3. Add `<PublishCollection />`
4. Add "Publish a collection" test 
- modify
1. Upgrade BlueprintJS, so the Alert modal gets a `loading` state
2. Update `<Alert />` component styling to show Primary button properly 
3. Code split `<Alert />` from `<DeleteCollection />`, `<DeleteDataset />`, and `<DatasetRow />`
4. Move some `views/Collection`'s helper functions into `frontend/src/views/Collection/utils.tsx`
5. Refactor some shared helper functions into `frontend/tests/utils/helpers.ts`
1. **Published collection is showing the green tag:**
1. **Empty dataset Publish button is disabled:**
1. **Public collection Publish button is hidden:**
1. …

Thuang 804 publish private collection

---

backend/corpora/common/entities/collection.py
tests/unit/backend/chalice/api_server/test_v1_collection.py

---
- modify how collection link names are populated in API responses.

link_name is blank if not populated in DB

---

.gitignore
README.md
backend/Makefile
backend/database/README.md
docker-compose.yml

**Functional:** @jgadling 
**Readability:** @MDunitz 
---
- Modify documentation to work with the current architecture.
- Add explicit instruction for testing a migration locally. 
- Modify database make recipes to work with database docker container
- Add an additional volume to the database container so we can import a *.sqlc into the database docker container using make db/import.

Improving database migration documentation

---

backend/corpora/common/corpora_orm.py
backend/database/versions/5a363594dd06_tombstone_false.py

**Readability:** @tihuan 
---
- add tombstone false to all existing datasets and collections.
- modify tombstone in datasets and collection to be required and defaulted to false

Add Default False to tombstones

---

Dockerfile.processing_image

@Bento007 
---
We can't have the tiledb of the processing image creep ahead of what's deployed in hosted cellxgene, or we create cxgs that can't be read. So, pin to the version used in hosted cellxgene, which is 0.7.4

Pin tiledb to version 0.7.4

---

backend/corpora/common/utils/db_session.py

create_engine() is being called as soon as this module is imported. Is this intentional?
---
- add
- remove
- modify

Don't do work on module import

---

backend/corpora/lambdas/api/v1/collection.py
tests/unit/backend/chalice/api_server/test_v1_collection.py

- @Bento007 
- @seve 
---
- modify collections endpoint to allow non owners to have read access 
When a non-owner visits a private collection link, they should still see the page, even though they don't have WRITE access. But they shouldn't see WRITE access related actions, such as Publish

allow non owners to access private collections

---

frontend/tests/features/collection.test.ts
frontend/tests/utils/helpers.ts

@seve 
@Bento007 
---
- add
- remove
- modify
1. Update test code to prevent race condition
The problem we had before is that right after clicking on the delete button, we immediately navigate to the private collection page without waiting for the success API callback. This means the collection page sometimes will still be there, since the BE hasn't deleted the collection yet, thus failing the test.
The solution is to wait for navigations!

thuang-fix-collection-test

---

.happy/terraform/envs/prod/main.tf
.happy/terraform/envs/prod/variables.tf
.happy/terraform/envs/rdev/main.tf
.happy/terraform/envs/rdev/variables.tf
.happy/terraform/envs/stage/main.tf
.happy/terraform/envs/stage/variables.tf
.happy/terraform/modules/ecs-stack/main.tf
.happy/terraform/modules/ecs-stack/variables.tf
.happy/terraform/modules/lambda/main.tf
.happy/terraform/modules/lambda/outputs.tf
.happy/terraform/modules/lambda/variables.tf
.happy/terraform/modules/service/main.tf
.happy/terraform/modules/service/variables.tf
backend/chalice/api_server/app.py

1. Fixes an s3 bucket naming mismatch
2. Makes sure error handler lambdas execute in our VPC network
2. Updates the prod & staging configuration so Terraform will [wait for ECS services to be healthy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service#wait_for_steady_state) before exiting. This means that when we run integration tests after a deployment, we'll know that those tests are running against our upgraded services.
3. Support passing in valid CORS domains via env variables, even in production
---
- add
- remove
- modify

Wait for ECS upgrades to complete in CI

---

frontend/src/components/common/staticPages/style.ts
frontend/src/pages/previewpolicies.tsx

---
- add
- remove unneeded logos!
- modify
AND:

thuang-126-policy-change-logo-removal

---

frontend/src/views/Collection/utils.tsx

@Bento007 
@MDunitz 
---
- add
- remove
- modify
Hide contact field when unavailable
BEFORE:
AFTER:
1. Pull branch
2. `npm i && npm start`
3. Visit: `http://localhost:8000/collections/18e6337b-8c36-4977-9ac8-ca8aa5494481`
4. You should not see an empty Contact field anymore!

thuang-959-hide-contact-when-unavailable

---

.happy/terraform/envs/stage/main.tf

Flipping URLs to use the staging URLs that are set up in single-cell-infra, instead of the URLs used internally by happy path.

Set stage urls to be live staging

---

frontend/jest/featureFlags.js
frontend/src/common/localStorage/set.ts

---
- add
- remove
- modify
- `localStorage` values are changed from "`true"` and "`false"` to `"yes"` and `"no"` to match Explorer's convention
Note that feature flags will use `"yes"` and `"no"` from now on too, so please add the relevant feature flags in the URL params to overwrite the values again! E.g., `?auth=true&cc=true` (this part stays the same)
1. Clear your localStorage for the site and try setting feature flags and cookie banner again!

thuang-update-localStorage-boolean-values

---

DEV_ENV.md
Makefile
backend/chalice/api_server/app.py
backend/config/database.ini
backend/corpora/lambdas/api/v1/authentication.py
docker-compose.yml
frontend/Makefile
frontend/README.md
frontend/src/configs/local.js
oauth/clients-config.json
oauth/pkcs12/generate_cert.sh
scripts/happy
scripts/login.py
scripts/setup_dev_data.sh

** Experimental! **
This is a draft PR to get some feedback from the team about usability.
We've been having some trouble getting playwright to work properly when run against local dev due to some inconsistencies in the way DNS works inside a docker network, and on our laptops.
When containers connect to each other, they use service names defined in docker-compose.yml (for example, "backend", and "database"), but when we connect to the containers from our laptops, we use the 'localhost' name with different ports for each container. This means that OAuth redirects inside the docker network need to be different than redirects for browsers running on our laptops.
This PR makes the container names consistent inside and outside of the docker network by adding /etc/hosts entries to our systems …

Unify DNS for local dev

---

.github/workflows/deploy-happy-stack.yml
Makefile
frontend/Makefile
frontend/README.md
frontend/package.json
frontend/tests/common/constants.ts

* Remove unused smoke-test-with-local-backend-ci, @tihuan said it was dead
* Make TEST_ENV=local default for e2e tests, since dev environments going away with happy path
* Frontend make e2e now allows TEST_ENV environment variable to be passed through, without forcing to local
* Enable functional tests for staging deploys; added test passwords to staging
* Add e2e tests for staging deploys

Add tests to run before deploys

---

.happy/terraform/modules/ecs-stack/main.tf
.happy/terraform/modules/service/main.tf
.happy/terraform/modules/service/variables.tf

This doubles the memory allocated to backend API containers. We were seeing some memory allocation failures in the prod container logs.
This has been tested in the jgadling2 rdev stack, all backend tasks now have 1536mb memory, and frontend tasks have 768m
---
- add
- remove
- modify

Double memory for backend containers.

---

docker-compose.yml

This makes the OIDC app run natively on port 8443 instead of mapping the container's internal port 443 to the OSX hosts's port 8443. This makes it possible for other containers to reach the oidc service on port 8443 as well as engineers' web browsers
---
- add
- remove
- modify

Fix: oidc runs on port 8443 rather than portmapping

---

scripts/happy

The happy path script breaks if a previous run created a stack's workspace
without actually creating any workspace state or workspace config versions,
and you try to delete that workspace.
This PR prevents us from crashing in these cases, instead printing a warning
that the workspace is empty. Since the workspace is empty, this should not
be harmful.

Handle workspaces without any latest config version

---

.github/workflows/deploy-prod.yml
.github/workflows/deploy-staging.yml
.github/workflows/deploy.yml

Smoke test jobs now require AWS log in, this adds credentials to all smoke test jobs that we run.
Just one review for merge

fix: add aws credentials to smoke test

---

frontend/next.config.js

@seve 
@maniarathi 
---
Fixes deployed FE containers sometimes not being able to resolve static files such as `/_ssgManifest.js` and `buildManifest.js`, returning 404
The root cause is that every Nextjs prod build has a unique build id for their static assets, which means if we have multiple FE instances running in a cluster, load balancer will sometimes route a static asset request to a different instance, which won't have the static asset with that build id.
The solution is to have build id based on the last commit hash, so the build id is the same across different FE instances!
Sources:
https://github.com/vercel/next.js/issues/18389
https://nextjs.org/docs/api-reference/next.config.js/configuring-the-build-id
After deploying to staging and prod, we …

thuang-fix-nextjs-multiservers

---

.github/workflows/deploy-happy-stack.yml
Makefile

Allows passing BOTO_ENDPOINT_URL when running frontend smoke tests,
so that it can access the AWS secrets. Also modifies the Happy CI
deploy script to set BOTO_ENDPOINT_URL to empty.
Gets us past the localstack issue, but unclear if it fixes everything;
Playwright still complains about being unable to access websocket on
127.0.0.1. However this at the minimum is part of the ultimate fix.

Pass BOTO_ENDPOINT_URL when running smoke tests

---

frontend/src/components/common/Form/Input/index.tsx
frontend/src/components/common/Form/Input/style.ts

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/988
#988 
Related to https://github.com/chanzuckerberg/corpora-data-portal/pull/1033
@seve 
@Bento007 
---
Following https://stackoverflow.com/a/30873633 to add `type="search"` and `autocompete="off"` to each input field. This seems to stop autocomplete for me!
Seems like Chrome (and any browser) has the right to ignore `autocomplete="off"` for user protection, so the latest workaround is the combination above 🤞 
Another backup option is https://flaviocopes.com/react-form-browser-autofill/, which is not ideal, since it touches things that should be controlled by React, but should reliably work. Definitely the last resort and not a scalable …

thuang-988-disable-autocomplete

---

backend/corpora/common/corpora_config.py

**Functional:**  @mbarrien 
----
Smoke tests were failing because OIDC was failing to read the redirect URI sent from the backend (recieving  localhost instead of backend.corporanet.local)

fix: remove incorrect redirect uri and outdated oauth config code

---

.github/workflows/deploy-happy-stack.yml
.github/workflows/push-tests.yml

Fixes deployment issues for smoke tests on staging, where it
lack permissions to read the staging secrets because the
normal dev IAM role does not have permissions. We use the
existing unused staging IAM role, and store its ARN in a new
Github Actions secret AWS_STAGING_ROLE_TO_ASSUME. (Already
added manually to the repo.)
The IAM user used in CI already has permissions to
assume the existing CI IAM role.
While here, remove some code that isn't used during push tests;
the push tests are not run as part of a deployment workflow, so
it will never need to use the prod IAM role.

Fix staging deploy IAM role assume

---

.happy/terraform/envs/prod/main.tf
.happy/terraform/modules/ecs-stack/main.tf
.happy/terraform/modules/ecs-stack/variables.tf

This increases the number of backend workers available to service requests. Each backend container can process a max of 40 parallel requests, and prod is regularly exceeding our available worker count. We should look into adding an autoscaling policy for these services, but this PR will reduce errors in the meantime.
---
- add
- remove
- modify

Run more backend containers in prod.

---

backend/corpora/common/corpora_orm.py
backend/corpora/common/entities/geneset.py
backend/corpora/lambdas/api/v1/collection_uuid/gene_set.py
backend/corpora/lambdas/api/v1/dataset.py
backend/database/versions/7685265932f6_rename_gene_symbols_field_to_genes.py
tests/unit/backend/chalice/api_server/collection_uuid/test_create_genesets.py
tests/unit/backend/corpora/common/entities/test_genesets.py
tests/unit/backend/utils.py

- @Bento007 
---
- add test to ensure gene order is maintained
- modify gene_symbols to be genes for naming consistency.
Closes [957](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/957)
- geneset.genes returns a list of genes in the same order it was submitted

rename gene_symbols in db, add test for order

---

Dockerfile
Dockerfile.processing_image
Dockerfile.upload_failures
docker-compose.yml
frontend/Dockerfile
frontend/next.config.js
scripts/happy

* Make the current Git branch, commit hash, and tag description be
added as Docker build-time arguments.
* Modify containers to add those as labels embedded within the image
* Override next.js build ID to use the commit hash, falling back to
default random ID behavior if commit hash not provided.
Ideally we'd rather build the next build artifact right into the
container image, so a 2nd container using the same image would have
the same build ID for free (and there's no build time at startup).
However, we cannot run `npm run build` on the bare image because
even running this requires a configs/config.js file to be present,
which it isn't at the time we initially build the Dockerfile.

Pass git commit at container build time, use a next.js build id

---

Makefile
frontend/jest/playwright-globalSetup.js
tests/functional/backend/corpora/test_api.py

* Move the test_account_username into a secret, even for test stage
* Modify the playwright global setup to dynamically change secret
name to read based on deployment stage

e2e tests use secret for current deployment stage

---

.github/workflows/push-tests.yml

With the dev environment gone, there is no more need to separately upload the corpora-upload container to dev.

Remove use of dead corpora-upload-dev ECR repo

---

backend/corpora/common/entities/collection.py
frontend/src/common/queries/collections.ts
frontend/src/common/queries/common.ts
frontend/src/components/CreateCollectionModal/components/Content/components/AddLink/index.tsx
frontend/src/components/CreateCollectionModal/components/Content/components/LinkInput/index.tsx
frontend/src/components/CreateCollectionModal/components/Content/components/LinkInput/style.ts
frontend/src/components/CreateCollectionModal/components/Content/index.tsx
frontend/src/components/CreateCollectionModal/index.tsx
frontend/src/components/common/Form/Input/index.tsx
frontend/src/components/common/Form/Input/style.ts
frontend/src/views/Collection/components/ActionButtons/components/MoreDropdown/components/Menu/index.tsx
frontend/src/views/Collection/utils.tsx
tests/unit/backend/chalice/api_server/test_v1_collection.py

**Readability:** @MDunitz 
---
- add
- Mutation query to edit collections
- remove
- modify
- Change LinkInput to allow for changing of link type and for adding a link name
- Alter create collection modal content to allow for fetching collection information and prepopulating fields
- Display link names on collection page
#952 
1. Navigate to a private collection
2. Click on edit
3. Update input fields
4. Click update
5. The collection page should now reflect the new changes
#955
- The MyCollections page will display the links in a collection using the link_name if present, otherwise the raw link will be shown.
-  Must also address Incorrect DOI format in Collection Dataset view. Closing the original issue and referencing here.
#1102

feat: Allow for users to update their collections and add names to links

---

Makefile

For local development, instead of bringing up "long-lived" containers then "SSH-ing" into them to run unit tests, init, or local upload jobs, this commit changes it to run temporary containers. These containers are deleted right after the job runs, and run parallel to any backend/frontend/processing containers.
For running the local unit tests, we move the reporting of any code coverage to be done within the same run as the unit test, to avoid needing to have a container that persists between the 2 commands.
This should set us up to better run the processing unit tests of @Bento007 without needing to have the processor container booted up before running the test (which is why that branch is failing).

Run unittests with docker-compose run instead of exec

---

backend/corpora/common/utils/db_session.py
scripts/cxg_admin.py
scripts/delete_dataset.py

**Functional:** @mbarrien 
---
- Add script to delete a dataset from cellxgene. 
- Modify Database Session Engine to accept a databaser_uri as a parameter. This makes it easier to supply a database_uri to the ORM code.
- #1066
- Manually delete duplicate Lung dataset in Tabula Muris Senis
- Set DEPLOYMENT_STAGE, connect to the database using `make db/tunnel`. Run "script/delete_dataset.py"

Adding Script to delete datasets

---

frontend/src/common/featureFlags/features.ts
frontend/src/common/featureFlags/index.ts
frontend/src/common/localStorage/set.ts
frontend/src/common/utils/removeParams.ts
frontend/src/components/CreateCollectionModal/components/CTA/index.tsx
frontend/src/components/CreateCollectionModal/index.tsx
frontend/src/components/Header/components/AuthButtons/index.tsx
frontend/src/components/Header/index.tsx
frontend/src/pages/_app.tsx

@seve 
---
1. Update `removeParams()` function to use web API more
2. Add collection `CURATOR_FEATURES` to host all feature flags we want to enable for curators
3. Split featureFlags/index.ts to have getter and setter (`checkFeatureFlags()`)
4. Check for feature flags at app initiation time `checkFeatureFlags()` in `_app.tsx`. The setter will NOT set `rubber-chicken` to `true` in localStorage, so other feature flags remain the single source of truth. This is to prevent the weird state where in localStorage `cc=true` and `rubber-chicken=false`
5. Remove removing the feature flag params, since getter and setter are now separated
1. feature flags should work -- TESTED
2. Redirect after login should work -- NOT TESTED PLEASE HELP 😆 
N/A

thuang-feedback-1062

---

frontend/tests/features/collection.test.ts

**Functional:** @Bento007 
---
- add
- Wait for automatic navigation
- remove
- no more manual navigation
- modify
- more attempts to check that collection is gone 
We were navigating the collection page before the browser could send out the delete collection request

fix(fe-e2e): wait to see collection on my collections page don't do manual navigation

---

.github/workflows/push-tests.yml

When running smoke tests, make local-sync starts up a temporary local frontend container from scratch. When the frontend container starts, it runs the npm build step, which takes some time to finish. Before this change, make local-smoke-test would start immediately, before the npm build step had finished, and the tests would fail since the server it is testing is not ready for testing.
This PR does a crude hack to wait 30 seconds after the local-sync, which has proven to be sufficient so far. If we want something a little bit faster, we could add a curl loop that checks a frontend health endpoint before continuing on (with appropriate timeout in case frontend build fails), but this seems to be unnecessary for now.

smoke-test add sleep to allow time for frontend to finish build

---

backend/corpora/lambdas/api/v1/dataset.py

---
- modify deleting a published dataset in a revision to set the tombstone flag rather than delete the dataset children. This makes it easier for the frontend to track if the datasets have been deleted. It also avoids making refactoring changes to handle cases where the datasets do not have any assets or processing status.

fix: deleting a dataset during a revision crashes collection page

---

scripts/happy-deploy.py

Changes in this PR:
- Script exits immediately with an error message if the specified github SHA is < 8 characters long
- Change CLI flags to use dashes, which is more standard than underscores.
---
- add
- remove
- modify

Raise error if github sha is too short

---

backend/corpora/common/utils/db_session.py
tests/unit/backend/corpora/common/test_corpora_orm.py

---
Before we were using the same SQLAlchemy Base for corpora_orm and the tests. This cause tests tabled to be added to the staging and production databases. To fix this, the tests now create their own database and use their own SQLAlchmey base when running the tests. The database and data are cleaned up after the test.
- add Test_Base to avoid confusion with corpora_orm.Base 
- add DBSessionMaker.reset to reset the DBSessionMaker
- Create a new database to run corpora_orm tests on.
- related to #1214. It prevents the tables from being created in the future.
-

fix: use a different database for testing corpora_orm

---

.github/workflows/deploy-happy-stack.yml

Restore previous functionality to invalidate CloudFront on deployment.
Looks up the cellxgene CloudFront distribution ID by matching on
the domain name and alias (assumes a specific naming pattern),
then invalidates index.html only.

feat: Cloudfront invalidation on deploy

---

backend/corpora/common/entities/dataset.py
tests/unit/backend/chalice/api_server/test_revisions.py

- not replacing the explorer_url when publishing a dataset revision. This will preserve URL reference to the explorer once the updated dataset is published.

fix: the explorer url is not replaced when publishing a dataset revision

---

backend/corpora/lambdas/upload_failures/upload.py
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/Tooltip/index.tsx
tests/unit/backend/corpora/api_server/test_v1_auth.py
tests/unit/backend/corpora/common/entities/datasets/test_update.py

remove message telling users to try again
- @seve 
---
- remove message telling users to try again on upload failure
- modify upload failure lambda to update the processing status instead of the upload status

fix: update processing status instead of upload status on failure

---

frontend/src/common/entities.ts
frontend/src/common/queries/collections.ts
frontend/src/common/utils/checkForRevisionChange.ts
frontend/src/components/Collections/components/Grid/components/Row/CollectionRow/index.tsx
frontend/src/views/Collection/index.tsx

**Functional:**  @tihuan 
---
- modify
-  actually check if a collection **is** a revision when showing revision state
- rename `is_revision1 to `has_revision` to better communicate boolean state

fix: only show revision state on the revision, rename confusing field

---

frontend/src/common/queries/collections.ts

fix: check collections map presence when computing revision state

---

.github/workflows/standup-assignment-notification.yml
backend/corpora/common/utils/cxg_generation_utils.py
backend/corpora/common/utils/type_conversion_utils.py
requirements.txt
tests/unit/backend/corpora/common/utils/test_type_conversion_utils.py

This PR makes the same fixes as chanzuckerberg/cellxgene#2332
In particular:
* type inferencing from H5AD is clarified, most specifically in cases where casts are required
* add tests to confirm proper behavior
This code is _duplicated_ in this repo from the cellxgene repo.  The cellxgene repo should be considered authoratative, as CXG is a cellxgene-private data structure, and many additional tests are performed in that repo.

fix: type inferencing

---

frontend/src/components/Collections/components/Dataset/components/DownloadDataset/index.tsx
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/MoreDropdown/index.tsx
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/index.tsx

fixes: #1306 
---
- add
- add disabled props to buttons which are enabled by tombstone status

fix: disable buttons on deleted dataset

---

frontend/src/common/queries/collections.ts
frontend/src/components/Collections/components/Grid/components/Row/CollectionRow/index.tsx
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/DeleteDataset/index.tsx

fixes #1313  #1309
---
1. We just need to wait for cache invalidation promises to resolve before navigating to the collection
2. Added loading state on "Start Revision" click

fix: 1313 revision delete last dataset

---

frontend/src/views/Collection/components/Toast/index.tsx

fixes: #1310 
@seve 
---
1. We can't lazy-load toaster via `.create()` on the first `.show()` call anymore, because sometimes `.show()` is called inside React lifecycle hooks, which doesn't work with React 16+. The solution is to instantiate a Toaster instance on the client side when the file is first loaded
1. Upload a dataset
2. Wait till you see the first toaster then refresh the page
3. Wait till you see the second toaster (it should no longer crashes)

fix: 1310 Add dataset refresh unexpected error

---

backend/corpora/dataset_processing/process.py
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/Tooltip/index.tsx
tests/unit/backend/corpora/dataset_processing/test_process.py

- @danieljhegeman 
---
- modify processing script to extract metadata before creating the cxg file
rdev - https://dunitz-example-frontend.rdev.single-cell.czi.technology/?curator=true
dataset known to fail - https://www.dropbox.com/s/ccnukp6ehra5vei/dead_small_dataset.h5ad?dl=0

fix: create cxg after extracting metadata

---

frontend/jest/featureFlags.js
frontend/src/common/featureFlags/features.ts
frontend/src/components/CreateCollectionModal/index.tsx
frontend/src/components/Header/components/AuthButtons/index.tsx
frontend/src/components/Header/index.tsx

@seve 
- remove `CREATE_COLLECTION` and `AUTH` feature flag and code references
- Still need to try `rdev`
- Ran locally and checked if buttons are displayed when deprecated feature flags are turned on:
**CREATE_COLLECTIONS ("cc")**
**AUTH ("auth")**
**Curator flag works as it should:**

chore: Deprecate CREATE_COLLECTION and AUTH feature flags

---

frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/utils.ts

RDEV: https://thuang-stale-download-frontend.rdev.single-cell.czi.technology/?rc=true&curator=true
@seve 
---
- modify
Looks like CXG is now part of `dataset.dataset_assets`, so we no longer need to rely on `dataset.dataset_deployments` to infer `CXG` has been converted. This is the root cause of the off by one issue that causes the bug!
1. Upload a dataset
2. Wait till the process completes
3. Click download icon to see if all three formats are available (should be)
4. Upload another dataset
5. Wait till the process completes
6. Click download icon to see if all three formats are available <--- this is where the bug was. But now all 3 formats should  be available!
N/A

fix: upload dataset stale download

---

frontend/src/common/queries/collections.ts

---
- modify
Disable refetch after invalidating collection with id, since the private collection is no longer available!

fix: thuang-1308-delete-revision-is-slow

---

backend/corpora/dataset_processing/process.py
tests/unit/backend/corpora/dataset_processing/test_h5ad_data_file.py

@MDunitz 
@seve 
@leslieypark 
---
Specify `feature_name` as the `var` index column when creating the H5AD object file.
- H5ADDataFile is called with var_index arg when converting H5AD to CXG
- Test that var_index is correctly set on resulting H5ADDataFile obj
Run this on a real, 2.0.0 compliant H5AD file and inspect the resulting cxg.
N/A

feat: 1298 use feature_name column as var_index

---

requirements.txt

@MDunitz 
---
`numba` (which is at least used by `scanpy`) requires `numpy` to be of version `<= 1.20`. On my dev environment 1.21 gets pulled and this causes the app to malfunction. This pins it to a safe version.

chore: pin numpy and numba to consistent versions

---

backend/config/corpora-api.yml
backend/corpora/lambdas/api/v1/authentication.py
backend/corpora/lambdas/api/v1/authorization.py
backend/corpora/lambdas/api/v1/collection.py
tests/unit/backend/corpora/api_server/base_api_test.py
tests/unit/backend/corpora/api_server/mock_auth.py
tests/unit/backend/corpora/api_server/test_v1_collection.py

@MDunitz 
@seve 
---
Ticket [#1368 ](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1368)
- Changes all the collections endpoints to behave differently depending on the user's permissions
- Curators can view all the private collections, even if they belong to other users
- Curators can delete any private collection
- Curators can update any private collection
- Curators can start revisions on every private collection.
Verify if this doesn't introduce new authentication issues that might impact non logged in users.

feat: 1368 authorization for curators

---

backend/config/corpora-api.yml
backend/corpora/api_server/app.py
backend/corpora/common/authorizer.py
backend/corpora/lambdas/api/v1/authentication.py
backend/corpora/lambdas/api/v1/authorization.py
backend/corpora/lambdas/api/v1/collection.py
oauth/api_scopes.json
oauth/clients-config.json
scripts/setup_dev_data.sh
tests/unit/backend/corpora/api_server/base_api_test.py
tests/unit/backend/corpora/api_server/mock_auth.py
tests/unit/backend/corpora/api_server/test_v1_collection.py

@MDunitz 
---
Issue [1368](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1368)
Implements token based authorization. Adds a `requires_auth` and `requires_scope` decorators that can be used to restrict APIs. 
Notes: 
1. The current authentication flow isn't ideal. The proper Oauth2 flow requires the token not to be stored in the cookie, but rather in the FE local storage/memory and sent via the `Authorization` header to each request. The `id_token` is also probably useless for this application and should be replaced with a call to `userinfo`
2. `connexion` (which is currently use to manage secured access to the APIs via the swagger yaml file) does not support scopes unless you use the …

feat: 1368 authorization

---

requirements.txt

@MDunitz 
@ebezzi 
---
- modify: tiledb version: `<0.9` -> `==0.9.5`
- verified on rdev that CXG conversion of an h5ad file with slashes was successful
- N/A

fix: upgraded TileDB to 0.9+ (#1243)

---

.pre-commit-config.yaml
README.md

I removed `https://github.com/awslabs/git-secrets` from the config, since it keeps failing at pre-commit installing stage
And also added a line in the README to remind people to run `pre-commit install` to add precommit hook, such as prettier!
PTAL thank you 🙆‍♂️ 
---
- add
- remove
- modify

fix: remove git-secrets from pre-commit

---

frontend/.eslintrc.js
frontend/package-lock.json
frontend/package.json
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/utils.ts
frontend/src/views/Collection/index.tsx

@tihuan 
@seve
---
- Add withdrawn dataset toast to collections page. When a user goes to an explorer link for a tombstoned dataset, the explorer will redirect the user back to the parent collections page with the URL query param of `tombstoned_dataset_id`.
Navigating to a tombstoned dataset result in a withdrawn dataset toast.
Run data portal locally and go to a collection. Add `?tombstoned_dataset_id=asdfasdf` to the URL and press enter. You should see the toast.
The explorer side of this ticket (redirection) is being completed by @MDunitz.

feat: Add withdrawn dataset toast (#1237)

---

.pre-commit-config.yaml
frontend/tests/features/collection/revision.test.ts

This PR updates pre-commit black version and fix FE E2E revision test that was flaky when FE had to fetch lots of collections

fix: fix-flaky-revision-test

---

backend/corpora/common/utils/corpora_constants.py
frontend/src/common/entities.ts

@leslieypark 
---
- More requirements to make `X_approximate_distribution` optional

fix: make X_approximate_distribution optional in h5ad_data_file.py

---

frontend/package-lock.json

Ran `npm audit fix` and `npm dedupe` to fix some vulnerabilities. `node-sass` fix is not included, since we still need Next.js to fix on their end!
Note that this is only patching `package-lock.json`, because `npm audit fix` only handles non breaking changes. `node-sass` upgrade to v6 is a breaking change, and Next.js' peerDependencies requires `4.x || 5.x` or `dart-sass`. But Blueprint is not compatible with `dart-sass`(they plan to [fix in v4](https://github.com/palantir/blueprint/pull/4820), so we're stuck on `node-sass` v5 until either Next.js updates its peer dependency or upgrade to Blueprint 4.x when it comes out
Also tested `npm run build && npm run serve` to make sure prod build works as expected 😆 
---
- add
- remove
- modify

fix: patch FE vulnerabilities

---

backend/config/corpora-api.yml
backend/corpora/dataset_processing/process.py
tests/functional/backend/corpora/test_api.py

@ebezzi 
@leslieypark 
---
- modify: relaxed the assertion for expected conversion status since we can hit the status endoint too early which was resulting in the test flakiness

chore: relaxed assertion for expected conversion status

---

backend/corpora/dataset_processing/process.py
tests/unit/backend/corpora/dataset_processing/test_process.py
tests/unit/processing_container/test_process.py

@MDunitz 
@leslieypark 
Ticket [#1432](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1432)
---
Since `cellxgene-schema` now ouputs a file, the final h5ad file that gets uploaded was renamed. This reverts it back to `local.h5ad`

fix: rename final h5ad file to local.h5ad

---

Dockerfile.processing_image
requirements.txt
tests/unit/backend/corpora/dataset_processing/test_h5ad_data_file.py

@bkmartinjr @MDunitz 
@leslieypark 
---
- add: tiledb regression test
- remove: superfluous tiledb version spec in `Dockerfile.processing_image`
* ran `test__slash_in_attribute_name` locally using a known version of tiledb that would fail (tiledb==0.8.0)
* also ran via CI to demonstrate: https://github.com/chanzuckerberg/single-cell-data-portal/pull/1434/checks?check_run_id=3678016085#step:5:3314
* This added unit test is a regression test of tiledb and contains no cellxgene code, so arguably doesn't belong in our unit tests, but it was requested, so here it is 😄

test: add tiledb regression test

---

scripts/happy

@ebezzi @MDunitz 
@blrnw3 
---
- add: skip ECR repos/images that don't exist, but log that we're skipping it.
- ran successfully locally
- on merge, check that the `push-image` job succeeds and Portal deployments work again

fix: skip tagging of non-existent images (#1475)

---

backend/corpora/common/entities/dataset.py

@MDunitz 
Ticket [#1472 ](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1472)
---
- If `explorer_url` is None on the cloned dataset, the revision will break. This will just keep the url as None.

fix: safely handle explorer_url=None in revisions

---

backend/corpora/common/corpora_orm.py
backend/database/versions/23bade351f23_update_data_submission_policy_version.py

@MDunitz 
@MDunitz 
---
- modify
Adding migration to change `data_submission_policy_version` to nullable.

feat: migrate data_submission_policy_version to be nullable

---

frontend/src/common/utils/checkForRevisionChange.ts

---
There were two bugs, last PR only caught the returning true in `Array.forEach()` this catches the `object === object`

fix: use list diffing instead of incorrect object equality check

---

frontend/src/pages/privacy.tsx
frontend/src/pages/tos.tsx

@brianraymor 
@seve 
---
- add
- remove
- modify
1. Update Privacy and ToS copy
Privacy: https://thuang-new-privacy-tos-frontend.rdev.single-cell.czi.technology/privacy
ToS: https://thuang-new-privacy-tos-frontend.rdev.single-cell.czi.technology/tos
[Source of truth gDoc](https://docs.google.com/document/d/1yr_ouJKZBn9R6EcMAKzNOOBzklStBETJzyp4Wd9ZNF4/edit#)

fix: update privacy and tos

---

Dockerfile.processing_image

---
This is the original failing [smoke test](https://github.com/chanzuckerberg/single-cell-data-portal/runs/4072903438?check_suite_focus=true#step:5:339). Here is the error in our smoke test.
> ERROR: packaging 21.2 has requirement pyparsing<3,>=2.0.2, but you'll have pyparsing 3.0.4 which is incompatible.
The python library Packaging is failing during install do to conflicting requirements. Packaging's version 21.2 locks down the version of pyparsing to resolve this https://github.com/pypa/packaging/pull/471. 
There is also an error installing the requirements for Owlready2==0.34. This is pinned in [chanzuckerberg/single-cell-curation](https://github.com/chanzuckerberg/single-cell-curation/blob/37d8a199c4017d743694ad9ff47f8ccca555efd0/cellxgene_schema_c …

fix: pin packaging version in dockerfile.processing_image to fix smoke tests

---

backend/config/corpora-api.yml
backend/corpora/lambdas/api/v1/collection.py
tests/unit/backend/corpora/api_server/test_v1_collection.py

---
- modify DELETE collection/{collection_uuid} endpoint to allow the owner of a collection to tombstone a published collection. If an active revision exists for the collection, it will be deleted.
- modified GET collection/{collection_uuid} to return a gone<410> response with the contact_name and contact_email in the response body.
https://github.com/chanzuckerberg/single-cell-data-portal/issues/1577

feat: delete published collection

---

backend/corpora/dataset_processing/make_seurat.R

@pablo-gar @maniarathi 
Ticket [#1657](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1657)
---
- Pins `SeuratObject` to version 4.0.2. The latest version (4.0.3) is causing the issue documented in the ticket.

fix: pin SeuratObject to version 4.0.2

---

frontend/src/views/Collection/utils.tsx

@metakuni @danieljhegeman @seve 
---
- Removes `RDS` from the required asset conditions to publish a dataset.

fix: relax RDS requirement in datasets for publishing a collection

---

backend/corpora/common/entities/dataset.py
tests/unit/backend/corpora/api_server/test_v1_dataset.py

N/A
---
- Add `is_primary_data` to `datasets/index` endpoint

feat: add is_primary_data to datasets/index endpoint

---

frontend/src/common/constants/metadata.ts
frontend/src/components/Collections/components/Grid/components/Popover/index.tsx
frontend/src/components/Collections/components/Grid/components/Row/CollectionRow/index.tsx
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/Popover/index.tsx
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/index.tsx
frontend/src/components/Collections/components/Grid/components/Row/common/style.ts

@tihuan 
---
Updated n+ tag to render only when there are 2 or more field values. The first two values are no longer displayed alongside the tag.  Pluralized metadata name is added to tag and + is removed (see [mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1670%3A25035)).

feat: update +n tag to include all values (#1603)

---

frontend/src/components/CreateCollectionModal/components/Content/index.tsx

**Readability:** @tihuan 
---
- add curator name from id_token when creating or updating a collection
- related to #1683 
1. `make local-start`
1. open frontend
1. login
1. create a collection
1. Retrieve the collection. The curators name will appear in the response under curator_name

feat: add curator name from id_token when creating or updating a colllection

---

.happy/terraform/modules/batch/main.tf
.happy/terraform/modules/batch/outputs.tf
.happy/terraform/modules/ecs-stack/main.tf

@metakuni 
Companion PR: https://github.com/chanzuckerberg/single-cell-infra/pull/472
---
- Removes the revision from the batch job definitions used by the step function. This is useful because if a deployment happens, the definition will be marked as INACTIVE, causing existing jobs to fail. This should allow to always pick up the latest revision available.

chore: Remove revision from batch job definitions

---

frontend/src/components/Collections/index.tsx
frontend/src/views/Collection/index.tsx

**Readability:** @atolopko-czi / @Bento007 
---
React Router was preserving the query param even though we were deleting it off the URL.  The collection object would change, triggering a call of the effect hook which would pop the toast again.

fix: add display state to prevent multiple renders of toast

---

frontend/src/common/hooks/useCategoryFilter.ts
frontend/src/common/queries/filter.ts
frontend/src/views/Collections/index.tsx
frontend/src/views/Datasets/index.tsx

* Added react-query-based fetch of datasets from `datasets/index`.
* Added react-query-based fetch of collections from `collections/index`.
* Hooked up responses to filter view model builder functionality.
* Set of datasets, joined with collection information, sorted by publication date is available to display components.
* Set of collections, with rolled up dataset metadata, sorted by recency is available to display components.
* A possible improvement would be to cache the built view models via react-query rather than just the response themselves. Alternatively, built view models could be cached at the application level.
* There is some duplication between the sequencing of the fetch and build of datasets and the fetch and build of collections. This could be possibly refactored into a …

feat: hooked up /datasets/index and collections/index. (#1609)

---

Makefile
backend/Makefile

This commit makes some of the local dev commands more flexible to allow
'rdev' as an acceptable DEPLOYMENT_STAGE variable (for the purposes of
using an rdev database during local development). It also preserves env
variables for sudo commands in local dev Make targets which is necessary
in order to be compatible with some developers' virtual environment
configurations.
@ebezzi @atolopko-czi 
@chanzuckerberg/czi-single-cell-eng 
---
- add
- remove
- modify

fix: Improve local dev compatibilities

---

backend/corpora/common/entities/dataset.py
tests/unit/backend/corpora/api_server/test_v1_dataset.py

Ticket [#1721](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1721)
---
- Adds `explorer_url` to the `dataset/index` endpoint

feat: add explorer_url to dataset/index

---

frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/DataFormat/index.tsx

This commit rearranges the rendering logic for the DataFormat component
so that the Tooltip, which breaks the radio button grouping
functionality, only renders when the rds radio button is not needed.
@seve 
@tihuan 
---
- add
- remove
- modify

fix: behavior of download radio buttons

---

backend/corpora/common/entities/collection.py

This commit fixes a bug that allowed the revised_at column to sometimes
not be updated even when there were changes (revisions) to a
Collection's datasets.
@ebezzi 
@metakuni 
---
- add
- remove
- modify

fix: Correctly update revised_at when publishing Collection revision

---

.happy/terraform/modules/sfn/main.tf
backend/corpora/dataset_processing/process.py
backend/corpora/dataset_processing/process_seurat.py

@metakuni 
Ticket [#1761](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1761)
---
- Enhances the Seurat reprocessing logic so that it will work for every type of dataset. In particular:
1. Datasets that are revised will not have their RDS artifact in a bucket with a matching name, therefore we need to read the S3 path from the database.
2. Datasets with an existing RDS artifact should not create a new database record, but they should replace the S3 file in place.

fix: seurat reprocessing change

---

frontend/src/components/CreateCollectionModal/components/Content/index.tsx

@Bento007 
@seve 
---
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1748
- delete `curator_name` from list of attributes sent from FE to BE when editing the details for a private collection

fix: do not update curator_name when revising a collection

---

backend/corpora/lambdas/api/v1/collection_uuid/publish.py
tests/functional/backend/corpora/test_api.py
tests/unit/backend/corpora/api_server/collection_uuid/test_publish.py

Only check h5ad File for duplication across datasets in a collection. Don't check derived files for duplication. This was added because smoke tests were failing with a 500 error when publishing a collection. This was caused by the way were are retrieving metadata from S3. When parsing the file name from the S3 URI we were not taking into account that the URI for the CXG artifact was to a directory. Thus when requesting metadata for a directory, S3 return 404. Rather than retrieving all of the files from the CXG directory and check for duplication it's faster and easier to check if the source H5AD file is duplicated across the datasets in the collection. Since the H5AD file is used to generate the other artifacts, it's safe to assume if the H5AD file are unique, then the derived artifacts …

fix: detect duplicate H5AD files

---

frontend/package-lock.json
frontend/package.json
frontend/src/common/queries/README.md
frontend/src/common/queries/auth.ts
frontend/src/common/queries/collections.ts
frontend/src/common/queries/datasets.ts
frontend/src/common/queries/filter.ts
frontend/src/components/Collection/components/CollectionDatasetsGrid/components/Row/DatsetRow/index.tsx
frontend/src/components/Collections/components/DeleteCollection/index.tsx
frontend/src/components/Collections/components/Grid/components/Row/CollectionRow/index.tsx
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/components/DeleteDataset/index.tsx
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/index.tsx
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/utils.ts
frontend/src/components/Collections/components/PublishCollection/index.tsx
frontend/src/components/CreateCollectionModal/components/Content/index.tsx
frontend/src/pages/_app.tsx
frontend/src/views/Collection/components/DatasetTab/index.tsx
frontend/src/views/Collection/index.tsx

@seve 
@frano-m @MillenniumFalconMechanic 
---
- add
Upgrade `react-query` to v3!
Some breaking changes that affect us:
Source: https://react-query.tanstack.com/guides/migrating-to-react-query-3
1. useQuery:
1. https://react-query.tanstack.com/guides/migrating-to-react-query-3#query-key-partspieces-are-no-longer-automatically-spread-to-the-query-function
1. https://react-query.tanstack.com/guides/migrating-to-react-query-3#the-object-syntax-for-usequery-now-uses-a-collapsed-config
1. Mutation:
1. https://react-query.tanstack.com/guides/migrating-to-react-query-3#usemutation-now-returns-an-object-instead-of-an-array
1. https://react-query.tanstack.com/guides/migrating-to-react-query-3#mutationmutate-no-longer-return-a-promise. Use mutate for callback, and …

chore: upgrade react-query

---

.github/workflows/push-rdev.yml
scripts/happy

---
Add explicit --stack-name option for GHA-based builds of docker images. Replaces the use of --extra-tag to pass in the stack name. This allows the script to work in non-GHA build usages.
Tested:
* single-cell-infra happy explorer + data portal rdev *local* create
* single-cell-infra happy explorer + data portal rdev *GHA* create
* single-cell-data-portal happy *local* create

fix: rdev non-GHA builds

---

frontend/src/common/queries/filter.ts

@tihuan 
---
* Updated `stateTime` of filter-related queries to never expire.
* Note: data refresh-management will not be handled in Q1 2022. `staleTime` could be replaced with `refetchOnWindowFocus` during update of filter state management in _[Remember filter while navigating within the Portal](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1811)_ (if data re-fetching without clearing selected filters is supported).
* Any selected filters remain selected on blur and refocus of browser tab.
1. View collections page.
1. Select at least one category value from the filter sidebar.
1. Click to different browser tab.
1. Click back to tab containing collections page.
=> Selected filter should still be …

fix: updated staleTime for filter queries. (#1773)

---

backend/corpora/common/entities/collection.py
tests/unit/backend/corpora/common/entities/test_collection.py

@MDunitz 
Ticket [#1803](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1803)
---
- Adds a function that returns a normalized DOI for a collection. This DOI doesn't have an URL format and will be used to call the Crossref API to retrieve the metadata.

feat: create DOI normalization function

---

.happy/terraform/envs/rdev/main.tf
.happy/terraform/modules/ecs-stack/variables.tf

@metakuni 
---
- Set rdev instance_count to 1. This will help us save some memory and avoid adding EC2 machines.

chore: set rdev instance_count to 1

---

.github/workflows/lint-pr.yml
frontend/src/components/Collection/components/CollectionDatasetsGrid/components/Row/DatsetRow/index.tsx
frontend/src/components/Collection/components/CollectionDatasetsGrid/components/Row/DownloadDataset/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/DataFormat/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/index.tsx
frontend/src/components/Collections/components/Grid/components/Row/DatasetRow/index.tsx
frontend/src/components/Datasets/components/Grid/components/DatasetActionsCell/index.tsx
frontend/src/views/Datasets/index.tsx

This commit simplifies the previous logic for determining whether or not
to display a message to the user telling them that rds is unavailable
specifically when it is due to the conversation status being set to
SKIPPED. This change makes the code more blunt -- now the message is
displayed whenever rds is unavailable, regardless of whether the
conversion status is SKIPPED. This helps address a bug where the status
is not updated to SKIPPED after dataset processor (?) crash.
@seve 
---
- add
- remove all instances of isRDSSkipped flag and simply go by presence/absence of rds asset
- modify

fix: ensure toast about rds incompatibility is presented

---

frontend/src/components/Collection/components/CollectionDatasetsGrid/style.ts
frontend/src/components/Collections/components/Grid/components/CollectionsGrid/style.ts
frontend/src/components/Datasets/components/Grid/components/DatasetsGrid/style.ts
frontend/src/components/common/Grid/components/ActionButton/style.ts
frontend/src/components/common/Grid/components/ActionsCell/style.ts
frontend/src/views/Collection/index.tsx
frontend/src/views/Collection/style.ts
frontend/src/views/globalStyle.ts

**Functional:**
@tihuan
---
- Modified collections, datasets and collection datasets grids to match mocks ([here](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=2667%3A29344), [here](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=2667%3A29372) and [here](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=2805%3A29708)) in order to prevent horizontal scroll.

fix: Datasets tab requires horizontal scrolling (#1771)

---

backend/corpora/common/utils/dl_sources/url.py

@seve @Bento007 
---
Changes the Dropbox content length header. This is currently broken in all environments and causes the dataset upload to fail. Note that there is no documentation around these headers, so this might change any time. I can't think of a better solution though. We could make the size check optional but as @maniarathi pointed out, that would still break one of our features (block datasets that are too big) and it will do so silently.

fix: change Dropbox content length header

---

frontend/src/pages/_app.tsx
frontend/src/pages/index.tsx

@seve 
@frano-m 
---
Since Where's My Gene page also needs a custom layout that doesn't depend on the feature flag, this PR moves the homepage's layout logic to homepage's view file!
PTAL thank you 🙏 
1. Homepage layout with feature flag on off should work as expected
2. WMG page layout should be 3 panels regardless of feature flag status

feat(layout): Update optional layout logic

---

frontend/src/views/WheresMyGene/common/store/actions.ts
frontend/src/views/WheresMyGene/common/store/index.ts
frontend/src/views/WheresMyGene/common/store/reducer.ts
frontend/src/views/WheresMyGene/components/GeneFetcher/index.tsx
frontend/src/views/WheresMyGene/components/HeatMap/hooks/useDeleteGenesAndCellTypes.ts
frontend/src/views/WheresMyGene/components/HeatMap/index.tsx
frontend/src/views/WheresMyGene/components/HeatMap/utils.ts
frontend/src/views/WheresMyGene/index.tsx

@seve 
@MDunitz 
---
- add
1. `src/views/WheresMyGene/common/store` for `useReducer` to centralize heat map state, since many values change together in various events
2. The reducer/actions pattern follows closely to how [Redux Toolkit](https://redux-toolkit.js.org/usage/usage-with-typescript#createslice) structures the code to reduce boilerplate. I didn't dynamically generate actions like RTK does because the TS overhead involved to type things properly would take a lot more time for me to figure out 😆 And I don't think the app is global/heavy enough to justify adding RTK, so hopefully the current approach is a good balance
3. Add `useDeleteGenesAndCellTypes()` hook to encapsulate business logic, which internally uses the reducer and dispatch relevant …

feat: Delete rows and columns infrastructure

---

requirements.txt

@atolopko-czi @metakuni 
---
- Pins `scipy` to version 1.7.3. The newer version (1.8.0) isn't compatible with the Seurat conversion script and will cause it to crash.

fix: pin scipy to version 1.7.3

---

backend/corpora/common/providers/crossref_provider.py
tests/unit/backend/corpora/common/providers/test_crossref_provider.py

@metakuni
@MDunitz 
---
- Use the Crossref API key to call their API.
- If a key isn't found in the secret, just skip the call. This is useful for pre-staging environments if we want to avoid Crossref calls.
- Move the URL into the code. There is arguably no need to configure it since it's an immutable URI which is provided by Crossref.

feat: use Crossref API key

---

.github/workflows/push-tests.yml
backend/corpora/dataset_processing/process.py

- @ebezzi 
- @Bento007 
---
- modify dataset processing to skip validation step
DO NOT MERGE
DO NOT PROMOTE TO STAGING/PROD
This will allow us to copy collections from prod to dev for testing and should be reverted as soon as that process is complete. This PR should NOT be pushed to staging/prod

fix: copy collections DO NOT PROMOTE TO STAGING/PROD

---

requirements.txt

fix: pin scipy to version 1.7.3 (#1931)

---

frontend/src/common/queries/filter.ts
frontend/src/components/common/Filter/common/entities.ts
frontend/src/views/Collections/index.tsx
frontend/src/views/Datasets/index.tsx
frontend/tests/common/queries/filter.test.ts

@tihuan!
---
- Updated recency sort order of collections and datasets to use (collection) publisher metadata, revised_at, published_at.

feat: updated collections and datasets sort by recency.

---

frontend/src/components/Collections/components/Grid/components/CollectionsGrid/style.ts
frontend/src/views/Collections/index.tsx

@tihuan 
---
- Added the publication column to the collections index ([mock](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1509%3A19110), [redlines](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=2667%3A29344)).
- Added the summary citation displayed for collections with corresponding publication metadata.
- Shows "No publication" for collections with no corresponding publication metadata.

feat: Add publication column to collections index (#1912)

---

frontend/package-lock.json
frontend/src/views/WheresMyGene/components/HeatMap/components/Chart/index.tsx
frontend/src/views/WheresMyGene/components/HeatMap/utils.ts

Instead of hard coding a set debounce time, we apply a sliding scale depending on how many genes are selected. So the long debounce time is only applied on large gene selection. This way for small amount of genes, we get snappy interaction like the users expect!

feat(wmg): Incremental debounce

---

backend/open_api_spec.yml

---
- add empty security for fields that can be accessed with or without authentication.
- add securitySchema curatorAccess to allow curators to pass their access token in a header field. This is easier to do than passing as a cookie.
- remove cxguserCookieLenient because it is not used.
- remove ApiKey from Post /token since we are passing the API key in the request body and don't want connexion to automagically try to handle it.

curation api spec

---

backend/config/corpora-api.yml
backend/corpora/common/entities/dataset.py
tests/unit/backend/corpora/api_server/test_v1_dataset.py

---
- Adds `mean_genes_per_cell` to the `dataset/index` endpoint

chore: add mean_genes_per_cell field to dataset/index

---

backend/corpora/common/providers/crossref_provider.py

---
- Add an explicit exception raising if either date or journal aren't found in the Crossref metadata

chore: Crossref parsing fails if date or journal are not found

---

backend/corpora/common/utils/dl_sources/url.py

@metakuni @atolopko-czi 
---
- Bypass content length for dropbox downloads
- Sets a default of 100MB.

chore: bypass content length for dropbox downloads

---

frontend/src/common/hooks/useCategoryFilter.ts
frontend/src/common/queries/filter.ts
frontend/src/components/common/Filter/common/entities.ts
frontend/src/components/common/Filter/common/utils.ts
frontend/src/components/common/Filter/components/FilterMenu/index.tsx
frontend/src/components/common/Filter/components/FilterRange/index.tsx
frontend/src/components/common/Filter/components/FilterRange/style.ts
frontend/src/components/common/Filter/components/FilterTags/index.tsx
frontend/src/components/common/Filter/index.tsx
frontend/src/components/common/Grid/components/ActionButton/index.tsx
frontend/src/views/Collections/index.tsx
frontend/src/views/Datasets/index.tsx
frontend/src/views/WheresMyGene/components/GeneSearchBar/index.tsx
frontend/tests/features/filter/utils.test.ts

@tihuan 
---
- Added filter by cell count ([mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1468%3A9713)).
- Added filter by gene count ([mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1468%3A9713)).
* Cell count filter displayed in datasets filter sidebar.
* Slider UI matches [mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1468%3A9713).
* Selected state matches [mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=2681%3A31105).
* Selecting min and max cell count values filters corresponding datasets result set.
* Gene count filter displayed in datasets filter sidebar.
* Slider UI matches [mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1468% …

feat: added filter by cell and gene count. #1820, #1823

---

frontend/src/views/WheresMyGene/components/HeatMap/components/Chart/index.tsx
frontend/src/views/WheresMyGene/components/HeatMap/components/Chart/style.ts
frontend/src/views/WheresMyGene/components/HeatMap/index.tsx
frontend/src/views/WheresMyGene/components/HeatMap/utils.ts

---
1. Tooltip is now triggered by table cell, not actual dot
2. Highlight gene and cell rows on hover rather than click
3. Update tooltip to match Figma design
4. Update heatmap to match design
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1852
https://app.zenhub.com/workspace/o/chanzuckerberg/single-cell-data-portal/issues/1856
1. Tooltip data is not complete. Will fill that out after connecting to API next week!
2. Not truncating gene names yet. Will leave it for the [polish ticket](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1968)

feat(wmg): Update Heatmap design

---

frontend/src/components/CreateCollectionModal/components/Content/index.tsx

@tihuan 
---
- Updated create of link view model to only convert DOI URLs to path if filter state is enabled.
1. Remove filter feature flag.
2. Edit collection that has a DOI specified.
DOI form field displays a DOI path (e.g. `/123/123`).
DOI form field displays the full DOI URL (e.g. `https://doi.org/123/123`).

fix: updated DOI form field value on edit.

---

backend/corpora/common/auth0_manager.py

**Functional:** @metakuni  
---
- remove mgmt_client and use the existing client in secrets manager
- change api_client for a more descriptive curator_api_client
-

fix: auth0sessionmanagement secret names

---

tests/functional/backend/corpora/common.py
tests/functional/backend/corpora/test_api.py
tests/functional/backend/corpora/test_api_key.py
tests/functional/backend/corpora/test_collection_access.py
tests/functional/backend/corpora/test_revisions.py

**Readability:** @tihuan 
---
- change r/self.cookie/self.curator_cookie.
- add auth0 user supercurator@example.com who has super curator permission.
- added auth0 user nocollection@example.com who is a curator with no collections.
- Add test to verify only a super curator can use the `write:collections` claim
- Add test to verify users can view only their private collections unless they are a super curator.
- moved access token generation to the class method for functional tests. This prevents creating excessive auth0 tokens.
Run functional tests again the dev deployment to test

fix: Add tests for collection access control

---

frontend/src/common/hooks/useCategoryFilter.ts
frontend/src/common/queries/filter.ts
frontend/src/components/common/Filter/common/entities.ts
frontend/src/views/Collections/index.tsx
frontend/src/views/Datasets/index.tsx

@tihuan 
---
- Added filter datasets by ethnicity (#1833).
- Added filter collections by ethnicity (#1860).
- This is PR 1 of 2 and covers just the addition of the ethnicity filter. A second PR will be created at a later point to cover the disabled/tooltip functionality (see [mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=1670%3A50787)).
~~- I am seeing a couple of linting errors that I have suppressed in the previous [filter by development stage PR](https://github.com/chanzuckerberg/single-cell-data-portal/pull/2166). I have left the linting errors in this PR and am expecting the development stage PR to resolve these errors. Please let me know if you would prefer a different approach!~~ Linting issues resolved with `npm ci`.

feat: added filter by ethnicity. #1833. #1860.

---

backend/config/corpora-api.yml

**Functional:** @Bento007
**Readability:** N/A
---
- Remove parenthesis from error code in OpenAPI spec.

chore: Remove parenthesis from OpenAPI spec for error code 413.

---

backend/corpora/common/utils/api_key.py

The attribute for the Issued At claim on the Curator API Key jwt was
misspelled and would not be recognized as a result.
@Bento007 
---
- fix the attribute typo for "iat"

fix: correct jwt attr spelling "ait" => "iat"

---

backend/corpora/common/utils/cxg_generation_utils.py
backend/corpora/dataset_processing/h5ad_data_file.py
tests/unit/backend/corpora/dataset_processing/test_h5ad_data_file.py

---
- modify: unified code to always use `tiledb.open()` to open TileDB arrays regardless of type (`DenseArray`, `SparseArray`), 
to use context managers

chore: use tiledb.open to open sparse and dense arrays

---

frontend/src/common/queries/collections.ts
frontend/src/components/CreateCollectionModal/components/Content/index.tsx

@seve 
---
- Added `refetchOnWindowFocus: false` for collection detail-related React Query fetches. The general approach for handling of stale data on the FE is currently being reviewed (see [Determine approach for updating search results when backend data changes](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1809) and [Add Cloudfront caching+invalidation for datasets/index and collections/index endpoints](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1899).

fix: set refetch to false for collection detail. #2204

---

frontend/src/common/utils/checkForRevisionChange.ts

@seve 
---
- add `id` (collections) and `collection_id` (datasets) to the ignored fields so that they don't erroneously cause the Collection to be marked as changed when it isn't (during revision).

fix: add `id` to ignored fields

---

frontend/src/views/WheresMyGene/components/HeatMap/utils.ts
frontend/src/views/WheresMyGene/components/InfoPanel/components/ExpressedInCells/index.tsx

@seve 
---
Update dot size to use Pablo's formula
The percentages used in the legend are: `0.0, 0.25, 0.50, 0.75, 1.0`

fix(wmg): Update heatmap dot size

---

backend/wmg/config.py
backend/wmg/data/snapshot.py
backend/wmg/data/tiledb.py

@ebezzi 
@MDunitz 
---
- WmgConfig() accepts a `tiledb_config_overrides` JSON object
- WmgSnapshot uses all tiledb config overrides for TileDB init
- removed support for `tiledb_mem` config param, replaced by lower-level `py.init_buffer_bytes` setting in config overrides.
rdev verified

feat: support tiledb config overrides for WMG

---

frontend/src/views/WheresMyGene/components/GeneSearchBar/components/QuickSelect/index.tsx

@seve 
---
Update dropdown height based on the number of options available with a max of 9.5 options tall

fix(wmg): Update dropdown height

---

backend/Makefile
requirements.txt

---
currently `db/init_remote_dev` and `db/delete_remote_dev` are failing because we aren't installing the requirements needed to run `scripts.populate_db`. This is causing 500 errors on the backend because the database is not created. It's also causing issues when tearing down an rdev because the database is not deleted.
- removed extra click
- install requirements for scripts.populate_db
- `happy` correctly sets up and tears down the databases used by rdev environments

fix: database setup for rdev

---

frontend/src/common/queries/wheresMyGene.ts

---
This doesn't include an error message if any condition causes this conditional to return true. We could split this conditional in to the expected, often, trues (loading), and the error states. Returning a broad warning for the others. Cut this PR now immediately  so we can unblock.

fix: check if expression summary is already an empty object

---

.pre-commit-config.yaml
requirements.txt

@Bento007 @tihuan 
---
need to update flake8 pre-commit version in order to not have disparities in linting demands from pre-commit hook vs GHA hook

chore: bump flake8 pre-commit version

---

frontend/src/views/WheresMyGene/components/GeneSearchBar/components/QuickSelect/index.tsx
frontend/src/views/WheresMyGene/components/HeatMap/components/Chart/index.tsx
frontend/src/views/WheresMyGene/components/HeatMap/utils.ts

@pablo-gar @hthomas-czi 
---
1. Selected state background color to `LIGHT_GRAY.D` (⚠️ : This seems to be the only place not using `theme.ts` for color. If there are other things, please help point them out for me 🙏 Thank you!):
1. Tooltip placement:
1. Don't clear text:

fix(wmg): 2272 tooltip placement FE polish

---

.happy/terraform/modules/ecs-stack/main.tf
DEV_ENV.md
Dockerfile
docker-compose.yml
frontend/README.md
frontend/package.json
frontend/src/configs/local-docker.js
frontend/src/configs/local.js
oauth/clients-config.json
scripts/login.py
scripts/setup_dev_data.sh
tests/functional/backend/corpora/common.py
tests/unit/backend/corpora/common/test_auth0_manager.py

**Functional:** @metakuni 
---
- modify the port used by dataportal backend from 5000 to 5005
- able to make a local deployment
- able to make an rdev
- `make local-rebuild` and verify you can access the backend and the frontend can access the backend.

fix(local): Update port to 5005

---

.pre-commit-config.yaml
requirements.txt

@seve @tihuan 
---
- Recent update of click version causes problems for older black version. Updated.

fix: black version bump to be compatible with click

---

frontend/src/views/WheresMyGene/components/HeatMap/components/Chart/index.tsx
frontend/src/views/WheresMyGene/components/HeatMap/components/Chart/style.ts
frontend/src/views/WheresMyGene/components/InfoPanel/components/RelativeGeneExpression/index.tsx
frontend/src/views/WheresMyGene/components/InfoPanel/components/RelativeGeneExpression/style.ts

@hthomas-czi 
---
- Tooltip labels should be `fontWeight: 400` and values should be `foregroundColor: .secondary`
- Less spacing between sections in the tooltip
- Add question mark icon next to Scaled, on hover add definition: "Expression is scaled to the range [0,1]. Scaling is done by assigning the minimum value in the current view to 0 and the max is assigned to 1." **<--- ⚠️ NOTE: Instead of question mark, I use info circle, since that's the closest available in SDS. Hopefully that's okay!**

fix(wmg): 2272 FE Polish

---

frontend/src/common/queries/datasets.ts
frontend/src/views/Collection/components/DatasetTab/index.tsx

The usage of memoization for this particular function call appears to be
incorrect. Also, 'visibility' should have been removed from the key
array for the query invalidation call as part of the original primary
key migration.
@seve @tihuan 
---
- remove visibility from query invalidations, an instance of memoization

fix: remove memoization, remove visibility from query invalidations

---

frontend/src/components/Header/index.tsx
frontend/src/views/WheresMyGene/components/GeneSearchBar/index.tsx

⚠️ ⚠️ ⚠️ ⚠️ ⚠️  
BACK MERGE TO MAIN AND PROMOTE STAGING 
⚠️ ⚠️ ⚠️ ⚠️ ⚠️ 
1. Add back scExpression
2. I also missed that FE tissue selector was showing duplicate tissue entries from different organisms (thought it was a BE dev cube issue 🤦 ), so this PR also fixes that!
Before:
After:

fix(wmg): Add scExpression nav button + fix tissue selector

---

frontend/src/components/common/SideBar/index.tsx
frontend/src/views/WheresMyGene/components/Main/index.tsx
frontend/tests/features/wheresMyGene.test.ts

Seems like `return page.$("*css=div >> text=Filters");` is picking up the `Beta` tag on the new nav button, so I'm changing the selector to narrow it down to the left panel only!

test(wmg): Fix smoke test sex filter tags

---

.happy/terraform/modules/ecs-stack/main.tf
scripts/cxg_admin.py

@metakuni 
---
- Uses `stack_name` in place of `deployment_stage` in IAMs, to avoid rdev duplication.

chore: use stack_name in submission lambda IAMs

---

backend/corpora/lambdas/api/v1/curation/collection/dataset.py

This reverts commit ffe1ef8768ab4cb666bd92e41e780ed203ee9e23.
@Bento007 
---
- Trying to exceed 1 hr causes failure; no way to get around it due to container's assumed role (role chaining issue).

revert: "fix: up s3 credential duration from 1 hr to 12 hrs (#2482)"

---

frontend/src/common/hooks/useResizeObserver.ts
frontend/src/components/Collection/components/CollectionDescription/index.tsx
frontend/src/components/Collection/components/CollectionDescription/style.ts
frontend/src/views/Collection/index.tsx
frontend/src/views/Collection/style.ts

@tihuan 
---
- added to long collection descriptions a button to toggle between [Show More](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=2988%3A31078) and [Show Less](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=3584%3A31174) views.

feat: Truncate long collection descriptions and display a 'read more' link (#1938)

---

frontend/src/common/queries/wheresMyGene.ts
frontend/src/views/WheresMyGene/common/store/actions.ts
frontend/src/views/WheresMyGene/common/store/reducer.ts
frontend/src/views/WheresMyGene/components/GeneSearchBar/components/Organism/index.tsx

1. This PR automatically refetches both `/primary_filter_dimensions` and `/query` when `snapshotId` changes!

fix(wmg): Refresh when snapshot changes

---

frontend/src/views/WheresMyGene/components/HeatMap/hooks/useUpdateXAxisChart.ts
frontend/src/views/WheresMyGene/components/HeatMap/hooks/useUpdateYAxisChart.ts
frontend/src/views/WheresMyGene/components/HeatMap/index.tsx

---
1. Seems like #2500 is caused by accidental guard clauses 🤦 
1. #2521 is fixed using @frano-m 's brand new `useResizeObserver` hook 🤩 👏 Thanks so much for making it reusable 🔥 !!
1. https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2500
1. https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2521

fix(wmg): 2500 and 2521 scExpr rendering bugs

---

backend/wmg/data/extract.py
tests/unit/backend/wmg/data/test_extract.py

---
- modify dataset selection function to exclude datasets with multiple organisms

fix: exclude datasets with multiple organisms

---

backend/config/curation-api.yml
backend/corpora/lambdas/api/v1/curation/collection/dataset.py
tests/unit/backend/corpora/api_server/curator/collection/test_collections.py

We were referring to what is techically a 'key prefix' as a 'path'.
Changing because it is surfaced to users as an attribute in the response
body.
@Bento007 
---
- modify var name

style: use proper terminology for s3 upload key prefix

---

backend/wmg/api/v1.py
backend/wmg/data/transform.py
tests/unit/backend/wmg/api/test_v1.py
tests/unit/backend/wmg/fixtures/test_snapshot.py

- #2501
- modify backend to create a tree structure for cell type ordering of scExpression
- update `generate_cell_ordering` from `transform.py` to write a pandas dataframe into a json file with the following columns `"tissue_ontology_term_id", "cell_type_ontology_term_id", "depth", "order"]`. The column `depth` encodes the level in the tree where a cell type is
- update `build_ordered_cell_types_by_tissue` of `v1.py` to work with the file mentioned above, the api request now returns a json file of the following structure `{tissue_id : [{id = "", name = "", depth = 10}, ... ], ...} `

feat: Add depths to cell types for dot plot

---

backend/corpora/common/corpora_orm.py
backend/corpora/common/entities/collection.py
backend/corpora/common/entities/dataset.py
backend/corpora/common/entities/entity.py
tests/unit/backend/corpora/api_server/collection_uuid/test_publish.py
tests/unit/backend/corpora/api_server/test_revisions.py
tests/unit/backend/fixtures/test_db.py

---
- Reorganize publish logic.
- Add __repr__ to make debugging easier
- Add additional publish revision test with refreshed dataset and new links.
- don't change published_at if tombstoned

fix: streamline publish function to prevent loss of links

---

frontend/src/components/EmbeddedGoogleSlides/index.tsx
frontend/src/components/Header/index.tsx
frontend/src/components/Header/style.ts
frontend/src/pages/landing-page/index.module.scss

---
1. Tweak CSS to fix header issue
2. Remove `"allow-scripts"` attribute
Before:
After:

fix(layout): Fix header

---

backend/corpora/dataset_submissions/app.py
tests/unit/backend/corpora/lambdas/dataset_submissions/test_dataset_submissions.py

**Readability:** @metakuni 
---
- add support for processing super curator submissions

feat(curation API): support processing s3 uploads from a super curator

---

backend/wmg/data/load_corpus.py

- @pablo-gar 
---
- modify rankit low expression filter to be 2
- generated full cube for filter of 0, 1, 2, and 3. @pablo-gar inspected all of the above via the scex feature and determined that 2 and 3 give the best results. We decided to go with 2 to reduce the amount of data removed.

chore: set rankit filter to 2

---

Dockerfile.data_cube_creation

Rebuilding the stack took forever because any changes to the backend code triggers the reinstallation of all the requirements in the `wmg_processing` image. We can fix this by moving the `pip3 install` further up in the `data_cube_creation` Dockerfile. This also means we don't need to push the bulky python dependency layer every time.
@MDunitz

chore: reordered dockerfile to improve rebuild speed

---

tests/performance/test_wmg_apis.py

cc: @MDunitz 
---
- modify: temporarily skipping [failing WMG performance unit test](https://github.com/chanzuckerberg/single-cell-data-portal/runs/7047210237?check_suite_focus=true) to get prod deployed before HCA

chore: skip failing perf test

---

backend/config/curation-api.yml
backend/corpora/common/entities/collection.py
backend/corpora/lambdas/api/v1/curation/collections/common.py

Apparently there exists some data corruption in deployed envs. Allow processing status
entity to be null in response for flexibility. Handle key error.
@Bento007 
---
A number of small tweaks need to be made to make sure the API response schema matches up with the db schema and with the data that actually exist in the deployed environments.

fix: update API response schema for Datasets

---

tests/performance/test_wmg_apis.py

(cherry picked from commit ad2430b524af56135a1d41282e060caf8e521612)
---
- add
- remove
- modify

chore: cherrypick prod hot fix to temporarily skip failing performance test

---

backend/corpora/dataset_processing/process.py
tests/unit/backend/corpora/dataset_processing/test_process.py

- #2770 
**Readability:** @atolopko-czi 
---
- new cxg files are upload to the cxg bucket with a unique UUID. This UUID changes whenever ever the dataset is reuploaded.
- The `s3_uri` and the `explorer_url` have been updated to use their own unique UUID.
1. Create a collection
2. upload a dataset
3. open the explorer and look at the resulting URL path.
dataset:  https://t2770-explorer.rdev.single-cell.czi.technology/e/391f6c86-950e-49e4-b51c-02e1aaede204.cxg/
4. publish
5. start a revision
dataset-R: https://t2770-explorer.rdev.single-cell.czi.technology/e/3ee1fa9f-ae40-4662-adad-c1c041a54be1.cxg/
6. update dataset.
dataset-R':https://t2770-explorer.rdev.single-cell.czi.technology/e/a3053715-359c-4417-bebc-e765ca2f9c68.cxg/
7. update again
dataset-R'': …

fix(2770): Generate a unique s3_uri for cxg files add to the cellxgene bucket.

---

tests/functional/backend/corpora/test_revisions.py

**Readability:** @MDunitz 
---
fixing test_revision to match the behavior introduced by https://github.com/chanzuckerberg/single-cell-data-portal/commit/8575f2e3cd1bc3e8356a0af269b666ac0a44c99e. The ID in the S3_URI is independently generated from the ID of the original dataset and the revision.

chore: updating functional tests

---

.happy/terraform/envs/rdev/main.tf
.happy/terraform/modules/ecs-stack/main.tf
.happy/terraform/modules/ecs-stack/variables.tf
.happy/terraform/modules/service/main.tf
.happy/terraform/modules/service/variables.tf

Reverts chanzuckerberg/single-cell-data-portal#2522
- causing issues with deploying happy environments. https://si.prod.tfe.czi.technology/app/happy-singlecell/workspaces/dev-devstack/runs
- `launch_type` does not appear to be used or defined in "./modules/ecs-stack"
- `execution_role_arn` roles for use_fargate aren't yet defined.

Revert "feat: Optionally use FARGATE; use FARGATE in rdev"

---

.github/workflows/push-tests.yml
frontend/jest-playwright.config.js

This speeds up smoke test runs for push-tests from ~20 minutes to <5.
We're also experiencing issues with our frontend docker container running smoke tests, so this will both unblock merges to main and allow for deployments.
We'll be attempting to address containerized smoke test runs in a separate PR.

fix(workflow): don't run push-tests smoke tests in happy container 

---

frontend/src/components/Layout/style.ts

- #2827
**Functional:** @MillenniumFalconMechanic 
---
Moves doc specific styling to the appropriate layout

fix(styles): move centering responsive pages to doc layout

---

tests/performance/test_wmg_apis.py

- #2774 
- @metakuni 
---
- modify perf tests to run in prod and log run times
- ran against prod locally. Tests ran within desired time limits

fix: reimplement all perf tests in prod

---

frontend/tests/features/wheresMyGene.test.ts

---
1. The cell type name comparison got thrown off a bit with the introduction of cell count because we were grabbing all `text` elements within the y-axis `g` element. Halving the count fixes it!
2. Update to only select one tissue instead of 3 tissues to limit flakiness -- it feels that sometimes the test code will grab cell type counts from different tissues, thus causing false negative
3. Extract reused constants
NOTE:
1. This bug only got discovered in dev smoke test because we are NOT running scExpression smoke test in PRs due to related API being unavailable in the container. Not sure if this is still true today? If so, we'll need to run scExpression tests locally ourselves! 
Thank you!

test(wmg): Fix cell type name count

---

backend/corpora/common/utils/slack.py

- #2406 
---
- modify slack alert to only retrieve webhook in prod env

fix: only pull slack webhook in prod

---

tests/unit/backend/corpora/api_server/test_v1_collection_upload_link.py
tests/unit/backend/corpora/common/utils/test_dropbox.py

- unit tests updated
- Dropbox now returns 200 in response to a HEAD request for a resource
that does not exist.
https://czi-sci.slack.com/archives/C023Q1APASK/p1659053375076559
@atolopko-czi @ebezzi 
---
- add
- remove
- modify

fix: Handle Dropbox 200 for head req for nonexistent resources

---

tests/unit/backend/corpora/api_server/test_v1_collection_upload_link.py

This is nuts but this is the only reasonable solution I can come up with for this situation, the situation being that Dropbox seems to oscillate randomly between two different possible error messages for a nonexistent resource link.
---
- add
- remove
- modify

fix: handle both possible types of error responses from Dropbox

---

backend/corpora/lambdas/api/v1/curation/collections/common.py

- #2978 
@Bento007 
---
- modify algorithm for determining which datasets should be returned. Previous logic had a mistake because it was mutating the list while iterating over it, allowing possibility for datasets to sneak through without being reshaped if tombstoned datasets exist within the collection. cc @brianraymor

fix: track active vs tombstoned datasets correctly for API response

---

backend/config/curation-api.yml
tests/unit/backend/corpora/api_server/curator/collection/test_curation_collections.py

- move 'required' attributes to request body for POST /collections
- add test for partial attribute update for PATCH /collections
- #3010 
@Bento007 
---
- add
- remove
- modify

fix: allow partial field updates to Collection metadata

---

.github/workflows/deploy-happy-stack.yml

---
- re-added aws cred set-up to deployment smoke tests job, to resolve tests failing due to undefined test account secrets to be fetched from AWS
- See failing tests at https://github.com/chanzuckerberg/single-cell-data-portal/runs/7675953815?check_suite_focus=true

fix(smoke tests): add aws creds to post-deployment smoke tests step, needed to fetch test account creds

---

backend/corpora/common/utils/json.py
tests/unit/backend/corpora/common/utils/test_json.py

- Add time zone info to responses.
- Generally useful
- Required for 'Expiration' on s3 upload credentials
- Update unit test to test against hardcoded isoformat with tzinfo
- Testing environment must be UTC for unit test to pass (this is good)
- #3051 
@Bento007 
**Readability:**

fix: Curation API - add time zone info to JSON-encoded timestamps

---

backend/config/curation-api.yml
backend/corpora/lambdas/api/v1/curation/collections/actions.py
backend/corpora/lambdas/api/v1/curation/collections/common.py
tests/unit/backend/corpora/api_server/curator/collection/test_curation_collections.py

- #2793 
---
- Move list_collections_curation, because it's only used in one place.
- Add query parameter `owned` to get collections to allow filtering collections by the owner. The access token is used to determine the owner.
- Add a test case to only retrieve the collections owned by a user.
- The test leaves something to be desired. Since the owner is not in the collection data returned there is no definitive way to show the collection belongs to the user. Instead, I retrieve all the collections owned by a user and check that they have WRITE permission. In the same test, we retrieve all of the collections owned by the super curator, which should be 0 since the super-curator doesn't own any collection because none were created by the.

fix(GET Collections): Add filter by owner

---

frontend/src/components/Collections/components/PublishCollection/components/Policy/components/DirectPersonalIdentifiers/index.tsx
frontend/src/components/Collections/components/PublishCollection/components/Policy/components/DirectPersonalIdentifiers/style.ts

- #2944 
@seve 
@hthomas-czi 
---
Update PII popover height to be 50vh + scroll overflow, so it works with different zoom levels and viewport heights
1. Invoke the publish collection modal and hover over the PII target
2. Play with different viewport heights and zoom levels, the content should no longer be cutoff

fix(collection): 2944 Publish Collection PII cutoff

---

backend/corpora/lambdas/api/v1/collection.py
backend/corpora/lambdas/api/v1/curation/collections/collection_id/actions.py
tests/unit/backend/corpora/api_server/curator/collection/test_curation_collections.py
tests/unit/backend/corpora/api_server/test_v1_collection.py

- #3118
---
- modify the code that verifies the collection body. Required fields cannot be blank, but they can be missing from the response body.

fix(curation api): If fields are included they cannot be blank for required fields

---

requirements.txt

This is likely used by tests (since the dependency is transitively pulled in by the validator), but we should update it regardless.

chore: upgrade to anndata 0.8

---

backend/config/curation-api.yml
backend/corpora/lambdas/api/v1/collection.py
tests/unit/backend/corpora/api_server/test_revisions.py

- #3116 
---
- modify the error message returned when a revision already exists.

fix(curation api): fix error returned when a revision already exists

---

backend/config/curation-api.yml
tests/unit/backend/corpora/api_server/curator/collection/test_curation_collections.py

- #2983 
- #3162
**Functional:** @atarashansky 
**Readability:** @danieljhegeman 
---
- modify allow x_approximate_distribution to be None. If the field is not provided by the user, we want to return it as None in the API request.

fix: x_approximate_distribution can be None

---

Dockerfile.processing_image
backend/config/curation-api.yml
backend/corpora/lambdas/api/v1/curation/collections/common.py
tests/unit/backend/corpora/api_server/curator/collection/test_curation_collections.py

- #1461 
@ebezzi 
---
- surface batch_condition in dataset response object in curation API (scope does NOT include dataset preview object)
- update test
- minor refactor of curation API spec to organize + add descriptions/examples
- unit tests + rdev
- batch_condition metadata is already extracted from dataset submissions and persisted in the db (see #1459 ). Test changes were also made as part of that previous PR. This simply surfaces it in curation API endpoints that return full dataset metadata.

feat: surface dataset batch_condition in curation API

---

backend/config/curation-api.yml
backend/corpora/lambdas/api/v1/curation/collections/common.py
tests/unit/backend/corpora/api_server/curator/collection/test_curation_collections.py

- #1461 
@ebezzi 
---
- surface batch_condition in dataset response object in curation API (scope does NOT include dataset preview object)
update test
- unit tests and rdev
- Cherry picked from [PR merged into feature/schema-3-0-0.](https://github.com/chanzuckerberg/single-cell-data-portal/pull/3172) Can be released outside of schema 3.0.0 release cycle

chore: cherry pick changes from #3172 surface dataset batch_condition in curation API

---

scripts/smoke_tests/setup.py
tests/functional/backend/corpora/test_api.py
tests/functional/backend/corpora/test_revisions.py

- #3182 
---
- updated dropbox links to public schema 3.0.0 compliant h5ad, for functional and smoke test uploads
- There is another h5ad test fixture in the data portal, pbmc3k.h5ad, that I did not update. It does not go through the upload pipeline--it is used for a unit test for convert_anndata_category_colors_to_cxg_category_colors, so it should not need to be updated. Unit tests pass, so it should be fine, but let me know if you'd rather I update for consistency's sake. 
- There are also dropbox links for a test.h5ad, but these are exclusively used to unit test functions related to making dropbox requests, and do not process or upload the h5ad.

chore: use 3.0.0 compliant h5ads for functional and smoke tests

---

backend/corpus_asset_pipelines/integrated_corpus/job.py
backend/corpus_asset_pipelines/integrated_corpus/transform.py
backend/corpus_asset_pipelines/summary_cubes/cell_count.py
backend/corpus_asset_pipelines/summary_cubes/expression_summary/load.py
backend/wmg/data/query.py
backend/wmg/data/schemas/corpus_schema.py
backend/wmg/data/schemas/cube_schema.py
backend/wmg/data/validation/validation.py
tests/unit/backend/wmg/fixtures/test_snapshot.py
tests/unit/backend/wmg/test_query.py

Addresses #3084 
@ebezzi (?) Let me know if I should choose someone else
@atarashansky 
---
- renames integrated corpus and wmg cube **dimension** `tissue_ontology_term_id` to `tissue_original_ontology_term_id`
- renames integrated corpus and wmg cube **attribute** `tissue` to `tissue_original`
- the steps above results in an added dimension and attribute to integrated corpus and cubes 
- `tissue_ontology_term_id` and `tissue` will contain the high-level tissues. For now, only children of `lung` are mapped to `lung`, everything else is untouched, another PR will be submitted for mapping all tissues
- modify querying to snapshot to handle extra dimension and attribute and send correct information to frontend
- update unit tests of querying to account for …

feat: Add extra dimension to integrated corpus, summary cubes, and snapshot of scExpression

---

backend/config/curation-api.yml
backend/corpora/common/utils/regex.py
tests/unit/backend/corpora/api_server/curator/collection/test_dataset.py

- #3102 
@Bento007 
---
- remove unused regex
- enforce non-empty curator tag in backend validator code
- do not prohibit uuid shape _within_ a curator tag; only prohibit uuid _as_ tag.

style: remove unused regex and consolidate curator tag logic

---

frontend/src/views/WheresMyGene/components/Filters/index.tsx

- [#339
](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/339)
---
- renamed ethnicity on the WMG Filter Tab
- just going to rename the frontend label for now, leaving var names the same for brevity and consistency with the backend

chore: rename ethnicity to self-reported ethnicity in wmg frontend

---

backend/config/curation-api.yml
backend/corpora/lambdas/api/v1/curation/collections/actions.py
tests/unit/backend/corpora/api_server/curator/collection/test_curation_collections.py

This commit returns the array of Collections directly rather than
nesting it under a '.collections' attribute.
- #3203 
@Bento007 
---
- add
- remove
- modify

feat: remove '.collections' attribute from GET /collections response

---

backend/corpus_asset_pipelines/integrated_corpus/transform.py
backend/wmg/data/tissue_mapper.py
backend/wmg/data/transform.py
backend/wmg/data/validation/fixtures.py
tests/unit/backend/wmg/test_tissue_mapper.py

- #3099 
@ebezzi 
@MillenniumFalconMechanic please review [backend/wmg/data/tissue_mapper.py](https://github.com/chanzuckerberg/single-cell-data-portal/pull/3198/files#diff-40380a401959bb1235f5f11926bb4745053bd377049a825cb21615de34ea916e)
@atarashansky 
---
- add Class `TissueMapper` with all assets necessary for mapping any tissue to its high-level equivalent
- modify Creation of integrated corpus to use the Class above to add the high-level tissue to dimension `tissue_ontology_term_id` and to attribute `tissue`
- modify Order of tissues that are passed to the FE for better usability, the order is the same as the list of high-level tissues defined in the class `TissueMapper`
- Integrated corpus and cubes were manually created with small sets of data AND …

feat: Implement tissue mapper function for getting high-level tissues in scExpression

---

frontend/src/components/common/Filter/common/entities.ts
frontend/src/components/common/Grid/common/utils.ts
frontend/src/components/common/Grid/components/HeaderCell/index.tsx
frontend/src/components/common/Grid/index.tsx
frontend/src/views/Collections/index.tsx
frontend/src/views/Datasets/index.tsx

- #3235 
---
- Modified column config to with new header prop `tableCountSummary` for display of result set count to datasets and collections.
- Fixes unwanted rerender of column config.

fix: Add result set count to datasets and collections (#3235)

---

Dockerfile.processing_image
backend/corpora/dataset_processing/requirements.txt
backend/wmg/requirements.txt
requirements.txt

- [#328](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/328)
---
- updated numpy, pandas and numba dependencies to match those in cellxgene-schema 3.0.0 (see [PR](https://github.com/chanzuckerberg/single-cell-curation/pull/339) in single-cell-curation)
- tests and rdev upload
- merging into 3.0.0 feature branch
- any particular known risks with updating the same dependencies for WMG?

chore: update dependencies to match cellxgene-schema 3.0.0 dependencies

---

frontend/doc-site/.dev/01__writing-documentation.mdx

Setting the config is not optional. 
```bash
ambrose@ambrose-MS-7C59:~/projects/single-cell-data-portal/frontend$ npm run dev
> cellxgene-data-portal@0.1.0 dev
> next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
Error: Cannot find module '/home/ambrose/projects/single-cell-data-portal/frontend/src/configs/configs.js'
Require stack:
- /home/ambrose/projects/single-cell-data-portal/frontend/next.config.js
at Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
at mod._resolveFilename (/home/ambrose/projects/single-cell-data-portal/frontend/node_modules/next/dist/build/webpack/require-hook.js:27:32)
at mod._resolveFilename …
```

docs: setting a config is required to run the docs server

---

backend/config/curation-api.yml

This commit also changes the example code for using bearer tokens to be prefaced with "Bearer" instead of "bearer"
- #3277 
@Bento007 
---
- improve description for s3-upload-credentials endpoint to allow a user to comfortably perform a local datafile upload without having to reference code or instructions in our notebooks.
- change `bearer` to `Bearer`

docs: improve description for s3 upload protocol

---

backend/corpora/dataset_processing/process.py
tests/unit/processing_container/test_process.py

- removed extraneous logic, and associated test
- reviewed processing code and confirmed that all status-bearing exceptions would be named exceptions (e.g. ProcessingFailed, etc.). Also confirmed that all validation-level errors will be caught and named, so we can safely assume only upload errors would fail with unnamed exceptions.

chore: remove extraneous logic checking for processing status in unexpected pipeline errors

---

backend/wmg/data/constants.py

fixes: typo in list of assays to include in gene expression. 
About 400K cells from "10x 3' transcription profiling" are currently not included because of this typo.

fix: typo in list of assays to include in gene expression

---

backend/corpora/common/upload.py

This commit ensures that INITIALIZED Datasets -- those created using the Curation API -- will proceed with processing rather than erroneously throwing an InvalidProcessingStateException
@Bento007 
---
- add
- remove
- modify

fix: proceed with processing if status is INITIALIZED

---

backend/corpora/common/utils/regex.py
backend/corpora/lambdas/api/v1/collection.py
tests/unit/backend/corpora/api_server/curator/collection/test_curation_collections.py
tests/unit/backend/corpora/api_server/test_v1_collection.py

- Undo previous solution which was applied to `contact_name` and `description` as well; these fields should permit such characters
- Primary focus was to disallow characters that did not get a valid grapheme representation *when used for a hyperlink*, which is important for Collection names
- #3134 
@Bento007
---
- add
- remove
- modify

fix: prevent nonprintable chars in Collection name

---

backend/config/curation-api.yml

- #3212 
@Bento007 
---
- add note in description for `POST /datasets` per @brianraymor 's [mention in the issue](https://github.com/chanzuckerberg/single-cell-data-portal/issues/3212#issuecomment-1254306628)

docs: access token required for POST /datasets

---

backend/corpora/common/utils/slack.py

Alright, here it is. After countless hours of untangling our pipeline and re-deriving various fundamentals of binary-encoded data theory, this is what I've come up with for this previously-thought-to-be-unsolvable ticket. Even [Emanuele was stumped](https://github.com/chanzuckerberg/single-cell-data-portal/issues/2031#issuecomment-1224093938) by this one.
- #2031 
@Bento007 @seve @metakuni 
---
- add
- remove
- modify

fix: remove '/private' from Collection url in Slack notification

---

.github/workflows/push-tests.yml
docker-compose.yml

Currently, there is a bug in Docker Compose where the latest version (2.11, which Github has automatically upgraded to in our Github Actions) requires that the service.build.platforms argument be provided in the docker-compose.yml. Github autopopulates this field with "linux/arm64". This is normally fine by default because we specify the service.platform attribute in each of our images. However, there is another Docker Compose bug that is not properly picking up these platform attributes. Due to that, our Github Action is failing because it doesn't think a platform matches the list of provided platforms. To make things worse, this latest version of Docker Compose is not available on Mac yet. Ideally, we'd add the service.build.platforms attribute, such as in [this test …

fix: Remove platform references, and use DOCKER_DEFAULT_PLATFORM env

---

backend/config/curation-api.yml

- #3345 
The `dataset_id` is in the url of the request. Returning it in the response is redundant.
@nayib-jose-gloria @Bento007 
---
- remove `dataset_id` from the `GET /{dataset_id}/assets` response

feat: remove dataset_id from /{dataset_id}/assets response

---

scripts/remaster_cxg_v0.3.0.ipynb

Adds the remastering notebook used to update the CXGs from v0.2.0 to v0.3.0 to `scripts/`.

chore: add remastering jupyter notebook

---

backend/corpora/lambdas/api/v1/curation/collections/common.py
tests/unit/backend/corpora/api_server/curation/collection/test_curation_collections.py

- #3366 
@Bento007 
---
- modify logic for Collection-level processing status so that `PENDING` is returned if the Collection contains any Datasets with a status of `INITIALIZED` (new, empty Datasets).

fix: report Collection status as PENDING with INITIALIZED Datasets

---

backend/corpora/common/utils/cloudfront.py

---
fixing this error
```{
"levelname": "ERROR",
"asctime": "2022-10-04T20:30:27.004Z",
"name": "corpora-api-dev",
"message": "InternalServerError",
"lineno": 184,
"pathname": "/single-cell-data-portal/backend/corpora/api_server/app.py",
"request_id": "fe85c64d-c218-432c-8323-5df61ccbbd8b",
"exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/flask/app.py\", line 1820, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/local/lib/python3.10/dist-packages/flask/app.py\", line 1796, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/usr/local/lib/python3.10/dist-packages/connexion/decorators/decorator.py\", line 68, …
```

fix: cloudfront log message

---

backend/corpora/lambdas/api/v1/curation/collections/collection_id/assets.py
tests/unit/backend/corpora/api_server/curation/collection/test_assets.py

- #3345 
@Bento007 
---
This PR actually makes the necessary code changes to remove `dataset_id` from the `GET /assets` response.

fix: remove dataset_id from 'GET /assets' response

---

backend/config/curation-api.yml
backend/corpora/lambdas/api/v1/curation/collections/collection_id/assets.py
tests/unit/backend/corpora/api_server/curation/collection/test_assets.py

- #3392 
@Bento007 
---
- instead of nesting under `.assets` in a top-level object, simply return assets array directly (since `dataset_id` is no longer included as a sibling top-level attr)

refactor: return list of assets for 'GET /assets'

---

frontend/src/views/WheresMyGene/components/GetStarted/index.tsx
frontend/src/views/WheresMyGene/components/HeatMap/index.tsx
frontend/src/views/WheresMyGene/components/Main/index.tsx

Fixes #3398 
I also adjusted the landing page behavior such that if genes are selected first, Step 3 does not disappear until both tissues and genes are selected.

fix: Genes display properly if selected first

---

backend/corpora/common/utils/cxg_generation_utils.py
tests/unit/backend/corpora/common/utils/test_cxg_generation_utils.py

https://github.com/chanzuckerberg/single-cell-data-portal/issues/3461

fix: Cast categorical values to strings before generating cxg_schema type hints.

---

backend/corpora/common/upload.py
tests/unit/backend/corpora/dataset_processing/test_common.py

- #3451 
@Bento007 
---
Populate the `dataset_processing_status.validation_status` and `dataset_processing_status.validation_message` when a file is encountered that is too large for processing.

fix: update validation status and message when files exceed size limit

---

frontend/playwright.config.ts
frontend/tests/features/collection/collection.test.ts

- #3412
---
- Made default # of workers for local e2e test runs 1, to more closely match CI pipeline post-deployment test environment when testing locally
- Updated Invalid DOI tests to wait for specific response (URL, status code) they want to evaluate against, they were previously evaluating after the first response event on the page, which is not necessarily always the response they are actually testing (led to flakiness)
- Locally ran e2e tests against dev env
- On true failures, invalid DOI tests will now timeout waiting for a 400 response (3 min) rather than fail quickly on evaluation like before. This is a trade-off, however, I find it preferable to quicker tests with a larger chance …

fix(Invalid DOI e2e tests): e2e test specifies which response it is waiting for before evaluating test assertions

---

tests/functional/backend/common.py

- #3490
- Updated Retry config object in BaseFunctionalTest class to apply retry logic on POST requests
By default, the Retry config object we pass into the requests.Session for our functional tests only applies towards a limited set of HTTP methods (see docs [here](https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html#module-urllib3.util.retry)), which does not include 'POST' requests because they are not idempotent by default. As a result, we are not retrying POST requests in our functional tests, which increases flakiness on transient server/gateway errors and/or busy queues. Because our solution in these cases of false negatives is to retry the entire functional test suite anyway until it works, it should be …

fix: apply functional test retry config towards POST requests

---

backend/layers/business/business.py
backend/layers/business/exceptions.py
backend/layers/persistence/persistence.py
tests/unit/backend/layers/business/test_business.py
tests/unit/backend/layers/persistence/persistence_mock.py

CR feedback, as code change suggestions, for PR https://github.com/chanzuckerberg/single-cell-data-portal/pull/3463
- suggest replacing "visibility" terminology with published/unpublished, since I think it's clearer and reduces number of business layer concepts by 1; API layer can keep "visibility" concept, as needed
- suggest keeping unit test setup state inlined for get_collection w/filtering tests
- a couple method name rename suggestions and a doc comment or two.
- adds business layer exceptions stub classes
- minor formatting (newlines mostly, to keep my IDE happy)

business layer unit tests PR suggestions as code changes

---

.github/workflows/deploy-happy-stack.yml
frontend/tests/features/collection/collection.test.ts

@tihuan  
---
- copy config.js over from <deployment_stage>.js before running post-deploy e2e tests
- post deploy e2e [tests failed](https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/3386128595) due to imported dependency on API_URL from config.js, which we removed in [this commit](https://github.com/chanzuckerberg/single-cell-data-portal/commit/e1a2d7487a2a1d05e6567f87f981f0b3def4c39d). 
- Re-adding config.js for simplicity, it doesn't really affect clarity or performance so I think we should just add it back in vs. trying to remove dependency on it entirely. If you disagree however, let me know

fix: re-add config.js copy before running post-deploy e2e tests

---

.github/workflows/push-tests.yml

- #3509
- wait until prod image is pushed/tagged before creating deployment, as it was consistently causing the first prod upgrade attempt to fail + require a manual retry 
- rename push-images step to add-image-tags to better reflect what its actually doing (adding branch-<main/staging/prod> tag to latest pushed docker images)
- update push-prod-images to only push prod images for prod branch merges. Still runs in dev/staging as a no-op due to limitations with GHA workflow conditional statements
- Unfortunately, GHA does not support conditional "needs" statements, so I chose to implement this wait for all environments. Alternatively, I can make a separate, duplicate 'create_deployment' job called "create_prod_deployment" and …

fix: wait until prod image tag is pushed before creating deployment

---

backend/wmg/data/schemas/marker_genes_cube_schema.py
tests/unit/wmg_processing/test_schemas.py

- 'ethnicity' -> self_reported_ethnicity to be schema 3.0.0 compliant

fix: update FMG cube schema to be schema 3.0.0 compliant

---

frontend/src/views/WheresMyGene/components/GeneSearchBar/components/SaveImage/index.tsx

- #3486
Added 'tissues' and 'genes' to analytics upon image download in WMG for better understanding of usefulness.
I printed out to console while locally testing - on image download, this is now what is being sent to plausible:
`WMG_DOWNLOAD_COMPLETE {file_type: 'png', tissues: 'blood,lung,spleen', genes: 'TSPAN6,TNMD,DPM1'}`

feat: Track Tissues and Genes in Image Download

---

backend/common/entities/dataset_asset.py
backend/wmg/pipeline/integrated_corpus/extract.py
tests/unit/backend/wmg/pipelines/test_extract.py

- add optional arg to filter dataset assets by filename when mapping dataset assets in db to s3_uri, in order to filter out raw.h5ads (originally uploaded, non-labeled h5ads) from wmg cube processing. raw.h5ads should not be included in wmg cube, only the processed local.h5ads

fix: filter out raw.h5ad from wmg cube dataset processing

---

Makefile
frontend/Makefile
frontend/package.json

@seve 
---
1. Remove commands we don't use
2. Originally I added a few test commands to build the FE app in prod mode and run tests against it, but since we don't have Server Side Rendering (SSR) like CZ Meta, we don't really need to run e2e tests against prod mode FE. Will probably need to revisit if we start having SSR

test(smoketest): 3466-clean-up-e2e-test-commands

---

backend/common/utils/exceptions.py
backend/wmg/data/load_cube.py
backend/wmg/data/validation/validation.py
backend/wmg/pipeline/cube_pipeline.py
backend/wmg/pipeline/summary_cubes/__init__.py

Ticket: #3427
Changes:
- Force indices to match when comparing single gene expression expected vs. cube actual datasets in validation.py
- Add logic to upload snapshots to s3 that 1) create cubes then 2) fail validation. This will help with future debugging, as generating a cube takes a long time and we'll be able to debug validation failures faster with the failed cube to inspect.

fix: unblock wmg pipeline by forcing validation series to have same indices

---

backend/wmg/pipeline/cube_pipeline.py

`stats` is a dictionary of dataset count, gene count, and cell count. It was previously passed as a single argument by mistake. It should be `**stats` .

fix: Fix final wmg processing pipeline success message function

---

frontend/src/components/common/Filter/components/FilterContent/components/FilterViews/components/FilterMultiPanelCategoryView/style.ts
frontend/src/components/common/Filter/components/FilterSearch/index.tsx
frontend/src/components/common/Filter/components/FilterSearch/style.ts

- #3612 
@tihuan 
---
- Added clear button to filter search as per [mock](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=4261%3A37785&t=BHyMIN9m4P1kvKj6-4) and implemented as per [slack discussion](https://clevercanary.slack.com/archives/C02CF7MQPGV/p1669055439987369?thread_ts=1668452415.971099&cid=C02CF7MQPGV).

feat: add button to easily clear filter search bars (#3612)

---

DEV_ENV.md
Dockerfile
backend/api_server/app.py
backend/common/corpora_config.py
container_init.sh
docker-compose.yml
frontend/container_init.sh
frontend/package-lock.json
frontend/package.json
frontend/src/configs/local.js
frontend/tests/README.md
frontend/tests/common/constants.ts
oauth/clients-config.json
oauth/pkcs12/generate_cert.sh
scripts/setup_dev_data.sh
tests/functional/backend/common.py
tests/unit/backend/api_server/curation/collection/test_curation_collections.py

- #3598 
@tihuan @Bento007 
@atarashansky 
---
- Introduce [next-dev-https](https://www.npmjs.com/package/next-dev-https) for our local dev server for serving the FE
- Move BE to HTTPS as well (required for compatibility)
- Share cert/key generated by the oidc container (legacy code from Jessica) with the FE and the BE containers so that (it continues to be true that) **only one** cert has to be added to the local keychain.

chore: move local FE and BE servers to HTTPS

---

frontend/doc-site/04__Analyze Public Data/4_2__Gene Expression Documentation/4_2_1__Get Started.mdx

fix: Links in Gene Expression documentation

---

frontend/src/views/WheresMyGene/components/InfoPanel/components/SourceData/index.tsx

Fixing this for the second time...somehow the previous fix got reverted, though I'm not sure how.

fix: source datasets filter appropriately when no datasets selected

---

frontend/playwright-globalSetup.ts
frontend/playwright.config.ts
frontend/tests/common/context.ts

This PR fixes HTTPS error when running smoke test against https localhost, because the global setup playwright context didn't have config option `ignoreHTTPSErrors: true`
---
- add
- remove
- modify

test(smoketest): Extract common shared Playwright context options

---

backend/wmg/data/snapshot.py

To prevent outages when deploying the FMG changes to prod (as snapshot will need to be updated by wmg processing pipeline to generate `marker_genes` cube), a temporary backwards compatibility patch is added.

chore: add backwards compatibility to prevent transient outages (will be reverted after prod deployment)

---

frontend/package-lock.json
frontend/src/components/Header/index.tsx

- #3688 
**Functional:** @tihuan @seve @atarashansky 
**Readability:** @tihuan @seve @atarashansky 
---
- add
- remove
- modify
- Help and Documentation dropdown closes when clicked out

fix: help and documentation dropdown hides on blur

---

frontend/src/components/Collection/components/CollectionMetadata/index.tsx

- #3713 
@tihuan 
---
- modified `CollectionMetadata` component to map over metadata with unique key value.

fix: Dataset collection metadata emits 'two children with the same key' warning (#3713)

---

.github/workflows/push-tests.yml

Fixes the following error in Docker re-tag:
```
[ERROR]: error getting Image: operation error ECR: BatchGetImage, https response error StatusCode: 400, RequestID: f00322e8-7a33-4e28-a07f-93f2bdaa25bb, InvalidParameterException: Invalid parameter at 'registryId' failed to satisfy constraint: 'must satisfy regular expression [0-9]{12}'
```

fix: Fix the re-tagging issue due to invalid registryId

---

frontend/.gitignore
frontend/next-sitemap.config.js
frontend/package-lock.json
frontend/package.json
frontend/src/common/theme.ts
frontend/src/components/Header/index.tsx
frontend/src/pages/collections-sitemap.xml/index.tsx
frontend/src/views/WheresMyGene/components/GeneSearchBar/components/QuickSelect/index.tsx

This uses the [next-sitemap package](https://www.npmjs.com/package/next-sitemap) in order to add a dynamic xml sitemap and accompanying robots.txt file for SEO purposes as a post-build process.
- Edits can be made in the `next-sitemap.config.js` file in order to exclude pages or directories from the generated sitemap.xml file and/or robots.txt file (I've included comments for clarity)
- sitemap size has been set to 50,000 max entries as specified in the task requirements
- `pages/collections-sitemap.xml` has been excluded from the sitemap itself. The purpose of this page is to generate a sitemap of each collection based on the ID's and "revised_at" dates (or "published_at" date if revision is not present) that are returned from the …

feat: dynamic sitemap and robots.txt file

---

backend/layers/api/portal_api.py
tests/unit/backend/layers/api/test_portal_api.py

Even if partial updates aren't currently used by the FE, the endpoint supports it. This fixes an issue where links would not be updated correctly in case of a partial update.

fix: support for collection partial updates

---

Makefile
README.md
backend/layers/api/portal_api.py
backend/portal/api/app/portal-api.yml
tests/functional/backend/corpora/test_api.py
tests/functional/backend/corpora/test_revisions.py
tests/unit/backend/layers/api/test_portal_api.py

- re-introduced 'original_id' to datasets API response object, using canonical dataset id. Needed to access the original dataset associated with a private revision of a published dataset 
- remove duplicated 'delete' path in portal-api definition yaml
- raise a descriptive error if curator_name is not provided for a collection

fix: functional tests portal redesign compatibility

---

backend/layers/api/portal_api.py
tests/unit/backend/layers/api/test_portal_api.py
tests/unit/backend/layers/common/base_test.py

- modified logic to add original ids onto dataset API response objects--now, we add original IDs when the dataset is part of an unpublished collection revision, and its canonical dataset has been published before.
- minor type hinting fixes to test methods
- added assert for original ID logic in revisions unit test
- locally ran functional tests
- Named Original ID to map to existing API, but points to the canonical dataset ID. Used for building explorer URL perma link

fix: only add original_ids on unpublished revisions of published datasets

---

backend/layers/api/portal_api.py
tests/functional/backend/corpora/test_revisions.py

- we have existing portal API endpoints that only provide a dataset_id; however, in our data model, dataset_ids can belong to both 1 published collection version and 1 unpublished revision of that collection version. We need to fetch the collection version associated with a dataset for these actions in order to determine 1) ownership and 2) for deletes, which to delete from. By default, we were fetching the published collection version in all cases and then enforcing a rule that datasets in published collections cannot be deleted, which was blocking deletes of those datasets from the private revisions they were also associated with. As a quick fix without changing the API contract, I've updated the dataset ID endpoint logic to fetch the latest collection version (either an unpublished …

fix: for portal API dataset status and delete endpoints, fetch latest collection version

---

backend/layers/api/portal_api.py
backend/portal/api/app/portal-api.yml
tests/functional/backend/corpora/test_revisions.py
tests/unit/backend/layers/api/test_portal_api.py

-  remove original_id, deprecated use case given our new data model (revised datasets keep the original dataset version id as their id)

fix: remove original_id and fix post-deploy tests

---

.github/workflows/push-tests.yml
Dockerfile.data_cube_creation
Makefile
backend/wmg/api/v1.py
backend/wmg/pipeline/integrated_corpus/extract.py
backend/wmg/pipeline/requirements.txt
tests/unit/backend/layers/common/base_test.py
tests/unit/backend/wmg/pipelines/test_extract.py

1. Migrate the WMG functions to the redesign
2. Reintroduce WMG API tests (accidentally dropped)
3. Create a new `backend-wmg-unit-test` GHA action for it

chore: reintroduce wmg unit tests + migrate to redesign

---

frontend/src/views/WheresMyGene/components/CellInfoSideBar/index.tsx

- #3853
This changes the effect size label in the marker gene panel to "Marker Score" which is a more accurate description of the numbers being shown.
A separate PR will add the tooltip next week.

chore(FMG): change the effect size label in the marker gene panel to "marker score"

---

backend/portal/api/app/portal-api.yml
backend/portal/api/curation/v1/curation/collections/collection_id/datasets/dataset_id/assets.py
backend/portal/api/curation/v1/curation/collections/common.py
tests/unit/backend/layers/api/test_curation_api.py

---
- In Portal API layer, accept RAW_H5AD (original, unlabeled H5AD we store) as an acceptable filetype
- In Curation API layer, filter out RAW_H5AD from API responses by using a whitelist of allowed API response filetypes (since CXG is already filtered out, whitelist already existed in common class)
- Added to curation API tests

fix(portal redesign): handle raw h5ads at api layer in portal and curation API

---

frontend/src/views/WheresMyGene/common/store/reducer.ts

https://github.com/chanzuckerberg/single-cell-data-portal/issues/3802
Changed reducer logic to filter out existing genes and then insert all at front when adding marker genes to the heatmap
https://user-images.githubusercontent.com/8716829/210895827-63e94b90-f113-4e7b-88f4-3df2c988f694.mov

feat(fmg): shift marker genes to front if already selected when adding

---

frontend/src/views/WheresMyGene/components/GeneSearchBar/components/SaveImage/index.tsx
frontend/src/views/globalStyle.ts

---
- add
- remove
- remove `width: fit-content;` in `globalStyles.ts` as it makes the chart jump/disappear on download and not show up in the generated image
- modify
- increasing hardcoded width to not make legend be cut off

fix: downloaded image being cut off

---

frontend/src/views/WheresMyGene/components/HeatMap/index.tsx
frontend/src/views/WheresMyGene/components/HeatMap/style.ts

Y axis stopped being sticky when scrolling horizontally on a very large heatmap. The fix involved (a) changing the y axis/chart container to be inline instead of flex and (b) ensuring that both y axis and chart had the same height.

fix(wmg): y axis is now properly sticky

---

frontend/src/views/WheresMyGene/components/GeneSearchBar/components/SaveImage/index.tsx
frontend/src/views/WheresMyGene/components/HeatMap/components/Chart/index.tsx

The image download was including tissue charts from other tissues because the tissue id was accidentally deleted from [this PR](https://github.com/chanzuckerberg/single-cell-data-portal/pull/3811/files). Thus adding it back!
---
- add
- remove
- modify

fix(wmg): image download

---

frontend/src/views/WheresMyGene/components/Filters/index.tsx
frontend/src/views/WheresMyGene/components/GeneSearchBar/components/QuickSelect/index.tsx
frontend/src/views/WheresMyGene/components/HeatMap/components/Chart/index.tsx

@atarashansky 
@ainfeld 
---
This triggers the onClick analytics event when selecting a previously unselected option again
How it broke:
After migrating to MUIv5, MUI adds their own `onClick()` handler now, which overrides our custom one, thus the need to merge the two now
1. Select a tissue option, you should see a Plausible response
2. In the GIF below, you can see that the warning message count is incrementing, which is a warning that Plausible received the event but is not reporting it to the server because this is a local dev environment

fix(wmg): Select Tissues/Genes dropdown not triggering onClick event

---

frontend/src/common/queries/wheresMyGene.ts

- #3883 
Was naively returning true for all filter attributes that weren't being checked, we still needed to check to see if equality was there.

fix(wmg): still check for equality on non-checked filters when checking to clobber queries

---

backend/layers/api/portal_api.py
tests/unit/backend/layers/api/test_portal_api.py

---
Allows lookup by canonical `collection_id` for unpublished collections.

feat: unpublished collections can be looked up by canonical id

---

backend/layers/api/portal_api.py
tests/unit/backend/layers/api/test_portal_api.py

@nayib-jose-gloria @Bento007 
---
With this change, newly unpublished collections will work with canonical ids rather than version ids. Also introduces double lookups for all update operations, since they will need to work with collection_ids as well.

feat: newly unpublished collections return canonical collection_id in API

---

backend/portal/api/curation/v1/curation/collections/actions.py
tests/unit/backend/layers/api/test_curation_api.py

feat(curation API): newly unpublished collections return canonical collection_id in API

---

backend/layers/api/portal_api.py
backend/layers/business/business.py
backend/layers/business/entities.py
backend/layers/business/exceptions.py
backend/layers/common/entities.py
backend/layers/common/validation.py
backend/portal/api/app/portal-api.yml
backend/portal/api/curation/curation-api.yml
backend/portal/api/curation/v1/curation/collections/actions.py
backend/portal/api/curation/v1/curation/collections/collection_id/actions.py
backend/portal/api/curation/v1/curation/collections/common.py
frontend/src/common/entities.ts
frontend/src/components/CreateCollectionModal/components/Content/common/constants.ts
frontend/src/components/CreateCollectionModal/components/Content/common/utils.ts
frontend/src/components/CreateCollectionModal/components/Content/index.tsx
frontend/src/components/CreateCollectionModal/components/Content/style.ts
frontend/src/components/common/Form/Dropdown/index.tsx
frontend/src/components/common/Form/Dropdown/style.ts
frontend/src/components/common/Form/Input/index.tsx
frontend/src/components/common/Form/common/style.ts
frontend/src/views/Collection/index.tsx
frontend/src/views/Collection/style.ts
tests/unit/backend/layers/api/test_curation_api.py
tests/unit/backend/layers/api/test_portal_api.py
tests/unit/backend/layers/business/test_business.py
tests/unit/backend/layers/common/base_test.py

- chanzuckerberg/single-cell#348
@ebezzi 
@tihuan 
---
- added consortia dropdown to create/edit collection form as per [mocks](https://www.figma.com/file/5X1Y2CHUjLOIu6MiuMsut1/Consortia-Collection?node-id=11%3A31594). Includes some minor modifications to existing collection form input styles for consistency.
- added consortia to collection/dataset detail page as per [mock](https://www.figma.com/file/5X1Y2CHUjLOIu6MiuMsut1/Consortia-Collection?node-id=11%3A31357&t=BhpIM6NAjhrowUse-4).

feat: data submitters want collections to document their consortia

---

backend/layers/api/portal_api.py
backend/portal/api/curation/v1/curation/collections/collection_id/datasets/dataset_id/actions.py
backend/portal/api/curation/v1/curation/collections/common.py
tests/unit/backend/layers/api/test_curation_api.py

CXG links are using canonical dataset ids for collections that are unpublished but not revisions.
@Bento007 
---
- add
- remove
- modify

chore: cxg links are permalinks for new unpublished collections

---

backend/portal/api/curation/v1/curation/collections/common.py
tests/unit/backend/layers/api/test_curation_api.py

Curation API only returns version_id for collections that are revisions.
@Bento007 
---
- add
- remove
- modify

chore: use canonical collection_id in curation API responses

---

backend/layers/business/business_interface.py
backend/portal/api/curation/v1/curation/collections/collection_id/datasets/dataset_id/actions.py
backend/portal/api/curation/v1/curation/collections/common.py
tests/unit/backend/layers/api/test_curation_api.py

@Bento007 
---
1. In Curation API's `GET collection`, support the case where `metadata = None`. This is necessary if the endpoint is queried before the dataset is fully ingested
2. Add support for double lookup in operations that involve updating datasets: PUT and DELETE. Previously this wasn't required as they were only accessed via the version_id. The double lookup here isn't ideal but it will work since the only change is for unpublished, not revised collection, for which only a version exists.

fix: support null metadata and double lookup for write datasets

---

backend/layers/api/portal_api.py
tests/unit/backend/layers/api/test_portal_api.py
tests/unit/backend/layers/common/base_test.py

Improves the `dataset_identifiers` endpoint (aka the meta endpoint). This was previously failing when viewing a replaced dataset in a revision. Also add unit tests to explicitly test the hard-to-test portal <-> explorer integration workflow.

fix: improve dataset identifiers

---

oauth/mock_auth0_pkce.py

- #3945 
@tihuan @Bento007 
---
- use a real key pair (this may actually not be necessary but it is nice to have in place for future-proofing)
- use nonce claim, pulled from header in initial authorize request (required)
- use client id as audience claim value (required)
- rebuild oidc container `docker-compose build oidc`
- run local dev mode
- click 'Log In' in top right; should see `Fake User` appear as logged-in user.

fix: valid id token

---

Makefile
README.md
backend/common/corpora_config.py
backend/database/README.md

Recent commit 4e6c4e2876 simplified the '../database_local' secret name to '../database'. However, local dev case exceptions still caused the database config to look for a '../database_local' secret.
- #3984 
@Bento007 
@ebezzi 
---
- add
- remove
- modify

fix: local dev database config / secret name

---

backend/portal/api/curation/v1/curation/collections/common.py
scripts/setup_dev_data.sh
tests/unit/backend/layers/api/test_curation_api.py

@Bento007 
---
- In the `GET /collections/:collection_id` endpoint, handle additional cases where the endpoint breaks when the metadata is null
- Add a unit test for this case

fix: handle null metadata in curation API GET collection (take 2)

---

backend/layers/api/portal_api.py
backend/layers/common/entities.py
tests/unit/backend/layers/api/test_portal_api.py

---
- We need to return the canonical collection_id for a new unpublished collections when list all the collections. This technically isn't user facing problem but it would mean we no longer have working functional test if we don't fix this way. Since we do not openly disclose the version ID we wont be able to determine if a collection was successfully listed by get collection since creating a collection only return the canonical collection ID.
Updated the unit test to reflect the ID that should be returned when listing collections.

fix: Portal Get /collections

---

backend/layers/business/business.py
backend/layers/processing/submissions/app.py
tests/unit/processing/test_dataset_submissions.py

@Bento007 
---
- Add double lookup for both collection and version id in the dataset submissions lambda. This is required since for non-revisions, the curation API will use the canonical ids now.
Cannot be easily be tested in rdev. The unit test should suffice, but this should be retested using the local upload notebook once in dev.

fix: add double lookup in dataset submissions lambda

---

backend/portal/api/curation/v1/curation/collections/collection_id/datasets/actions.py
tests/unit/backend/layers/api/test_curation_api.py

**Functional:**
@Bento007 @nayib-jose-gloria  
---
- `POST /datasets` returns the canonical dataset id instead of the dataset version_id

chore: POST /datasets returns the canonical dataset_id

---

backend/portal/api/curation/v1/curation/collections/collection_id/datasets/actions.py
backend/portal/api/curation/v1/curation/collections/collection_id/datasets/dataset_id/actions.py
backend/portal/api/curation/v1/curation/collections/common.py
tests/unit/backend/layers/api/test_curation_api.py
tests/unit/backend/layers/common/base_test.py

---
- added tests for revision_of in GET /collections/{collection_id}/datasets/{dataset_id}
- revision_of only refers to the published dataset when revising a dataset. Otherwise it is NULL.
- fix typing in test code

fix(curation api): GET /collections/{collection_id}/datasets/{dataset_id}

---

frontend/src/common/utils/checkForRevisionChange.ts

- update checkRevisionForChanges function that runs when fetching a revision. 'consortia' field check was triggering 'updated' messages on all revisions because the comparison between revision vs. published collection was treating it as a scalar (rather than a list). Now, it checks it as a list and returns an accurate check on whether the revision has changes, which is used by the frontend to notify the end users. 
- Ran failing e2e test locally with the fix
- Implementation follows established pattern for checking list fields (put on ignore list for scalar check, then check separately)

fix: check whether revision's consortia list has changed when determining whether collection has updates

---

backend/portal/api/curation/v1/curation/collections/common.py

@Bento007 @nayib-jose-gloria 
---
- When calling `GET /collections/:collection_id`, the dataset id should only be a version_id if the collection is a revision. This is consistent with the `explorer_url` and the general behavior of the curation API
- Rename `use_canonical_url` to `use_canonical_id` for additional clarity

chore: GET /collections/:collection_id should return the correct dataset_id

---

.github/workflows/clean_happy_rdev.yml

This PR adds a CI GIthub Action that runs on a schedule (every hour) and removes old rdev stacks. An old rdev stack, by default, is a stack that has not been updated in two weeks. This stale period is configurable. If you'd like to update the cronjob period, simply change the schedule at the top of this action. This should help clean up unused stacks over time.
---
- add
- remove
- modify

feat: cronjob to remove old rdev stacks

---

backend/layers/api/explorer_url.py
backend/layers/api/portal_api.py
backend/portal/api/curation/v1/curation/collections/common.py
frontend/src/common/entities.ts
frontend/src/components/Collection/components/CollectionDatasetsGrid/components/Row/DatsetRow/components/RevisionStatusTag/index.tsx

- #4007
---
-  implement logic to determine 'published' field in portal API response  
-  update dataset portal API response translator method to optionally accept arg for collection revision created timestamp (logic: if dataset is in an unpublished revision and its created time is after the revision created time, it is also unpublished even if the canonical dataset has been published before). 
- add optional 'updated' boolean in portal API dataset response, to share with frontend whether a dataset in a revision is updated from its published counterpart or not 
- update Frontend to use new data model to interpret whether revised datasets need a NEW, UPDATED, or DELETED RevisionStatusTag (this …

fix: Adapt RevisionStatusTag to use redesigned data model

---

backend/layers/business/business.py
backend/layers/common/entities.py
tests/unit/backend/layers/api/test_curation_api.py
tests/unit/backend/layers/api/test_portal_api.py

#3996 
@ebezzi 
---
- sorted collection during creation and edit of consortia
- added tests for portal and curation APIs

fix: sort consortia on collection create or edit (#3996)

---

backend/layers/api/portal_api.py
tests/unit/backend/layers/api/test_portal_api.py

@nayib-jose-gloria @Bento007 
---
- Fixes an issue where update collection in the portal API doesn't handle DOIs correctly
- Current Portal tests (both pre and post redesign) assume that the payload will contain DOIs that start with https://doi.org, and are not necessarily valid (e.g. http://doi.org/123). This isn't the case as the FE sends Curie DOIs (i.e. with only the trailing part). We should change them to reflect this behavior

fix: update collection handles DOI correctly

---

frontend/src/common/utils/checkForRevisionChange.ts

Bug: Certain revisions were not rendering in the UI even though backend updates went through and curation API worked for equivalent endpoints
- check for revision changes at Collection-level in same way as Datasets (dependent on data field type) to avoid edge case bugs when adding new fields 
- update dataset-level changes check to return True when revision datasets are missing a published dataset (i.e. mark collection as changed if dataset from published is deleted in revision).
- checked revisions failing to render in dev in local frontend (pointed at dev backend). Renders correctly locally w/ changes
- The discovered issue was that, before the redesign, deleted datasets in revisions were simply marked as tombstoned but still …

fix: check for Revision Changes accounts for deleted datasets in new data model + refactor Collection checks

---

backend/wmg/api/wmg-api.yml

- #4035
Previously, negative effect size was not allowed, but in the latest version we decided to not zero out negative values. The api spec wasn't updated, so any response that yields negative effect size was treated as malformed. This PR removes the api spec requirement for effectsize >0

hotfix(fmg): update api schema effect size

---

backend/curation/api/curation-api.yml
backend/curation/api/v1/curation/collections/common.py
tests/unit/backend/layers/api/test_curation_api.py

- re-add original_id to curation API--it points to the canonical dataset ID for datasets in private revisions that have counterparts in the published Collection. Otherwise, it is None for newly added datasets in a revision Collection and not returned at all for non-revision collections. 
- tests
- Will unblock "replace second dataset" step in [curator example workflow notebook](https://github.com/chanzuckerberg/single-cell-curation/blob/main/notebooks/curation_api/python/example_workflow.ipynb)
- Achieves parity with existing curator use

fix: reintroduce original_id to curation API for revisions

---

backend/layers/business/business_interface.py
backend/layers/processing/process.py
backend/layers/processing/process_logic.py
backend/layers/thirdparty/schema_validator_provider.py
tests/unit/processing/test_processing.py

**Functional:**
@nayib-jose-gloria  
---
- Restores `validation_message` for uploaded artifacts that fail validation
- Unit tests
- [rdev stack pointed to a collection with failed upload](https://ebezzi-redesign-frontend.rdev.single-cell.czi.technology/collections/2514cd5a-e87e-42a3-bab8-c77303c9a801). Note that the `validation_message` can only be viewed in the database.

fix: add validation_message back to the pipeline

---

backend/wmg/pipeline/summary_cubes/expression_summary_fmg/transform.py

I updated the expression summary fmg data artifact in a PR that was meant to only update the gene expression heatmap, _not_ the calculated marker genes. This reverts this change. This change will be re-applied in this PR: #3955

chore(dag): revert update to expression summary fmg and put it in a different PR

---

backend/layers/business/business.py
backend/layers/common/cleanup.py
backend/layers/common/entities.py
tests/unit/backend/layers/api/test_curation_api.py
tests/unit/backend/layers/api/test_portal_api.py

#4032
---
- Added tests to validate that collection metadata is sanitized on update for both the Discover and Portal APIs and that in the put response:
- consortia are sorted
- leading/trailing whitespace is removed
- Modified the collection metadata "sanitize" to be a function in its own file rather than be on the CollectionMetadata class so that the same code can be used to sanitize the "CollectionMetadataUpdate" class.

fix(apis): sanitize collection metadata on update (#4032)

---

backend/wmg/pipeline/summary_cubes/expression_summary_fmg/load.py
backend/wmg/pipeline/summary_cubes/expression_summary_fmg/transform.py
backend/wmg/pipeline/summary_cubes/rollup.py

- #4057
This PR fixes two bugs:
- Expression roll-up was unexpectedly computationally intensive. It added 4 hours to the processing pipeline. Here, I re-implemented the rollup function in parallelized numba to get a 20x speedup.
- The way the healthy cell filter was implemented resulted in the `reduce_X` operation seg-faulting. It probably has something to do with misaligned cube indices, but I'm not exactly sure what the problem was. I fixed this issue by moving the filter to _after_ the reduction in `build_in_mem_cube`.
- The expression rollup tests pass using the numba implementation.
- Healthy cells are properly filtered out from the expression summary cube and no segfault occurs (tested locally)

fix: used numba to achieve 20x speedup for expression roll-up and fix seg-fault due to healthy cell filter

---

frontend/src/views/WheresMyGene/components/CellInfoSideBar/index.tsx

- #3853 
- #4074 
- Update analytics on marker score and marker genes tooltips.
- added new payload to the tooltip hover and documentation clicked events indicating which tooltip was used.
- Tested with a local instance pointing to dev.

chore(fmg): add tooltip to marker score and update analytics for info tooltips

---

frontend/src/views/WheresMyGene/components/CellInfoSideBar/index.tsx

- Analytics were broken after CR in #4090 (oops!)
- wrap useCallback in a function so it properly behaves as an event
- replace onMouseEnter/Leave logic with onOpen/Close of the tooltip itself. That way mouse doesn't need to hover over the question mark button specifically.
- Tested locally and console.log'd the events firing with the appropriate payloads.

fix(fmg): update analytics on tooltips to fire properly

---

backend/scripts/mirror_s3_data.sh

Do not mirror WMG data, since that will conflict with dev's weekly build.

chore: do not mirror WMG data

---

.happy/terraform/modules/service/main.tf

Currently we are unable to use `happy shell` to get inside the backend containers. This would be very helpful for debugging certain issues.

chore: enable happy shell into the backend container

---

backend/wmg/api/v1.py
backend/wmg/data/snapshot.py

- #4119 
There are now 145 datasets for brain tissue in the WMG snapshot. The `fetch_dataset_metadata` logic was getting dataset metadata one at a time from the RDS database. This makes any query for brain tissue take >2 minutes which times out the query and eventually crashes the server forcing a restart of the ECS task.
The proposed solution is to fetch the dataset and collection metadata from the data portal endpoints and parse them to get all the metadata we'd need. This would happen every time a snapshot loads for the first time. 
This will also greatly improve the query response times for pretty much all tissues.
- added dataset metadata builder to WmgSnapshot
- remove previous logic for `fetch_dataset_metadata`
RDEV STACK

fix(wmg): rewrite the dataset metadata logic to eliminate performance bottleneck for tissues with many datasets

---

backend/wmg/api/v1.py

This ensures that the behavior of `fetch_dataset_metadata` perfectly matches what it was before #4133

chore: update default dataset metadata response when dataset ID is not found

---

frontend/src/views/WheresMyGene/components/HeatMap/index.tsx

This is a small bug-fix. For the rollup work, we set cell types to be sorted hierarchically by default. If no genes are selected, the original ordering is used instead. When genes are first selected, there is a transient period where genes are selected but no data is present, which clears the cell type information transiently. This PR fixes that issue.
- #4138 
- add nullish coalescence to set sorted cell types = to default sorting if sorted cell types are still null during data loading

fix(wmg): fix transient tissue clearing due to default hierarchical sorting 

---

frontend/src/common/queries/filter.ts
frontend/src/components/common/Filter/common/constants.ts

- #2622
- Remove "na" option from suspension type filter as per [Slack](https://clevercanary.slack.com/archives/C02CF7MQPGV/p1675267437217269).
- Removed "na" option from suspension type filter values.
- For both collections and datasets, verify there is no "na" option in the suspension type filter.

fix: removed na from suspension type filter. #2622

---

frontend/src/pages/html-sitemap.tsx

this PR fixes `yarn build` error due to invalid React multi root caused by having `console.log()` in the render function
Thanks!

fix(sitemap): build error

---

frontend/src/common/hooks/useCategoryFilter/common/selectUtils.ts
frontend/tests/features/filter/selectUtils.test.ts

- #4176
- Corrected payload key for select filters to use the text "payload" if a payload key is not specified.
- Added tests to check generating the analytics event payload with and without a payload key.
- "Existing" filters such as assay and author should send a payload in the format `{payload: ${value}}`.
- New filters such as suspension type should send a payload in the format `{suspension_type: ${value}}`.

fix: corrected filter payload field. #4176.

---

backend/wmg/data/load_cube.py

- #4170 
- Snapshot size is getting unwieldy to download and upload. The bulkiest files are not used for anything.
- remove integrated, obs, and var arrays before uploading to s3
- Tested remove function (`shutil.rmtree`) locally

chore(wmg): clean up data artifacts we don't wish to upload

---

frontend/src/views/WheresMyGene/components/GeneSearchBar/components/SaveImage/index.tsx
frontend/src/views/WheresMyGene/components/GeneSearchBar/components/SaveImage/utils.ts
frontend/src/views/WheresMyGene/components/HeatMap/components/Chart/index.tsx

- #3991 
1. Interactive heatmap is in canvas mode, which is NOT suitable for downloads, so we need to re-render heatmap in SVG before triggering the download. However, if we trigger download before the heatmap is done rendering, we'll miss elements in the downloaded files, thus the need to add MutationObserver to ensure the heatmap is done rendering before triggering download
1. Add MutationObserver to check if the heatmap is done rendering SVG elements before downloading images
2. Move SVG render functions into `util.ts`
3. Re-enable canvas mode for interactive heatmap
4. Minor TS fixes to avoid using `!`
1. Go to GE
2. In Genes selector, paste and enter the following to populate many genes:
``` …
```

feat(wmg): 3991 SVG download with MutationObserver

---

Dockerfile.processing_image
backend/layers/processing/requirements.txt
frontend/src/views/Landing/index.tsx

Required due to https://github.com/scverse/scanpy/issues/2411
Also pins scapy to 1.6.0 (the version currently used) since this is likely a library that will introduce potential breaking updates.
- See if unit tests pass
- Do an upload in dev

chore: pin scanpy and matplotlib dependencies

---

backend/portal/api/portal_api.py

This endpoint is currently used by Amanda for analytics. Even if she should probably migrate to a different approach, this fix is still valuable.
Note that the field isn't currently used by the website so this is not a regression outside of analytics.
No ticket.
- `published_at` in the collections detail endpoint should point to the original publishing date, not to the collection version's publication date.

chore: update published_at in the collection details endpoint

---

backend/api_server/requirements.txt

See https://github.com/chanzuckerberg/single-cell-data-portal/pull/4195/files. This is required in the backend container as well due to WMG using scanpy.

chore: pin scanpy and matplotlib dependencies in backend

---

frontend/src/configs/dev.js
frontend/src/configs/prod.js
frontend/src/configs/staging.js

https://github.com/chanzuckerberg/single-cell-data-portal/issues/3830
- Reintroduce the configuration js files. This is necessary in order for the e2e tests to work. This introduces some config duplication, but I think it's acceptable. As an alternative, the file would have to be written at line 144 in deploy-happy-stack.yml based on the .env files, but that will require a new script since the tests are run outside Docker.

chore: restore js env files

---

frontend/tests/features/wheresMyGene.test.ts

Update test to wait for `canvas` element instead of SVG, since we've switched back to use canvas now!
Fixes failing tests in dev

test(wmg): Fix heatmap await

---

Dockerfile.upload_failures

Due to a rename, the handle failures lambda was broken because of a missing import. This fixes it.
- Adds a missing directory in the handle_failures Dockerfile
1. Deploy
2. Upload a failing h5ad (e.g. a 2.0.0 schema)
3. Go to our step functions page (devstack)
4. Find the failed pipeline
5. Ensure that the HandleFailures lambda is being called and it's green.

fix: handle_failures lambda import error

---

backend/layers/thirdparty/uri_provider.py

[#4244](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4244)
- Add exception details for Dropbox failures

chore: add exception details for Dropbox failures

---

backend/common/utils/dl_sources/url.py

- #4245 and #4244
- dropbox HEAD request on download links are not officially supported/maintained by dropbox API, and transient errors are causing flakiness in our functional tests
- trade-off: links to files larger than our max supported filesize will fail slower, more downstream in the process than currently. However, failing on transient errors is also causing issues and that occurs more often than overly large uploads. Further, those will still fail gracefully. 
- add try/except block around HEAD request
- processing unit tests

fix: wrap try/except around dropbox download link HEAD request

---

.github/workflows/push-rdev.yml

Back ticks need to be escaped to properly be echo'ed into the markdown file

fix(workflows): escape backticks in echo string

---

frontend/src/views/WheresMyGene/components/Filters/components/Sort/index.tsx
frontend/src/views/WheresMyGene/components/Filters/index.tsx
frontend/src/views/WheresMyGene/components/GeneSearchBar/components/Organism/index.tsx
frontend/src/views/WheresMyGene/components/InfoPanel/components/ColorScale/index.tsx

- #4211 @ashin-czi please help add the ticket number thank you!
1. The filters are not showing the selected item as active state, because every time we change an option, React destroys all the children of `<TooltipWrapper />` and re-create new instances of them. This results in calculating memoized values for the first time, thus breaking active select state
1. The root cause is because we're re-generating `TooltipWrapper` component in each render, thus all its children are considered first time showing up in the DOM tree, thus triggering useMemo() every time `TooltipWrapper`'s parent re-renders. The solution is simply removing the `TooltipWrapper` component and use the hidden API `disableHoverListener` and `disableFocusListener` to decide whether to show tooltip or not instead of relying …

fix(wmg): Filters selected options not showing active state

---

frontend/tests/features/wheresMyGene.test.ts

Fixes playwright test
selectNthOption from 1 to 2 because of new offset logic

fix(wmg): fixing selectNthOption from 1 to 2

---

frontend/src/views/WheresMyGene/components/GeneSearchBar/components/SaveImage/utils.ts

Fixes erroneous label names from displaying on SVG download
- add
- remove
- modify
- Query selectors for retrieving label text for svg generation
1. Fill tissue and genes
2. Select Download
3. Select SVG
4. Press Download

fix(wmg): Fix SVG Download

---

frontend/src/components/Layout/style.ts
frontend/src/views/globalStyle.ts

The dataset download button, when actioned, causes the datasets table to scroll back to the top of the table. It is desirable to maintain the scroll position when downloading any dataset.
- #4300
- Overflow styles on the datasets/collections table are relocated to an ancestor element.
- Navigate to the Datasets view.
- Scroll down the page.
- Download any dataset.
- The table view should remain at the current scroll position.

fix: Clicking Download resets the Datasets view to the top (#4300)

---

frontend/.eslintrc.js
frontend/src/components/common/Filter/common/constants.ts
frontend/src/components/common/Filter/components/FilterContent/components/FilterRange/style.ts

Based on conversation during HQ week. Removing sort-keys as mental models of key order usually trump alphabetical ordering

chore(fe-lint): remove sort-keys

---

frontend/src/views/WheresMyGene/components/GeneSearchBar/components/QuickSelect/index.tsx

- #4209
- added a useMemo hook to make it so item options update only when the dropdown closes and opens.

chore(wmg): selected items in quick select pin after reopen

---

backend/wmg/api/v1.py

- We want invalid IDs to not be `null` and just return the ID instead

chore(wmg+compare): return name as ID when no label is found in ontology

---

.happy/terraform/modules/ecs-stack/main.tf

This allows us to output the stack URLs in the latest version of Terraform.
-  The TFE workspaces Terraform version has been updated to 1.3.0. This version checks for the senitivity of values and disallows certain actions based on them. We want to be able to display information about the integration secret, so this change marks it nonsensitive.
- modify sensitivity of integration secret

fix: make the integration secret nonsensitive

---

.github/workflows/build-images-and-create-deployment.yml
.github/workflows/deploy-happy-stack.yml
.github/workflows/push-rdev.yml
.github/workflows/push-tests.yml

Updates github actions for installing happy and deploying stacks to the latest available versions. This causes the actions to use the latest version of happy CLI which fixes some recent stacklist issues.

chore: update happy actions to latest

---

.github/workflows/build-images-and-create-deployment.yml
.github/workflows/deploy-happy-stack.yml
.github/workflows/push-rdev.yml
.github/workflows/push-tests.yml

Follow-up to https://github.com/chanzuckerberg/single-cell-data-portal/pull/4376
Bumping past happy version 0.59.0 introduces a breaking change (autocreation of ECR, which we don't want to do here)

chore: re-pin happy version

---

frontend/package-lock.json
frontend/package.json

Unnecessary dependency, which causes false security warning [here](https://github.com/chanzuckerberg/single-cell-data-portal/pull/4346)
Remove `webpack` -- we use `next` for everything, so no longer needs Webpack at all!
App should not be affected by this change at all

chore: Remove unneeded FE dep

---

docker-compose.yml

Reverts chanzuckerberg/single-cell-data-portal#3351
This fix no longer required as macs support latest version of docker-compose.

chore: Revert "fix: Remove platform references, and use DOCKER_DEFAULT_PLATFORM env"

---

DEV_ENV.md
docker-compose.yml

Local dev environment setup was broken and needed a fix.
- add
- remove
- modify
Please follow these steps on your local machine to check that it works for your machine platform
1. `make local-clean`
2. `docker images -a` # lists the images you have
3. If you are ok deleting all the images then run: `docker rmi $(docker images -a -q)`. If not, at least delete all images generated by this repo
4. `unset DOCKER_DEFAULT_PLATFORM`
5. `rm .env.ecr`
1. Follow instructions in the **Development quickstart** heading of `DEV_ENV.md` file to setup a local dev
1. `AWS_PROFILE=single-cell-dev make unit-test`
1. Please run functional test per [these instructions in the …

fix: update instructions to create local dev stack

---

backend/wmg/api/v1.py
tests/functional/backend/wmg/fixtures.py

- #4396
- update `/query` to return empty response if tiledb query returns empty dataframes
- remove `self_reported_ethnicity_ids` from the secondary filter common case request fixture
- tests pass

fix(wmg): fix failing functional test by updating invalid request fixture

---

backend/wmg/api/v1.py

- [This PR](https://github.com/chanzuckerberg/single-cell-data-portal/pull/4397) was merged into main to fix a failing functional test. It was hotfixed into staging, but the PR failed to take into account the edge case where no genes are selected. In that particular case, `expression_summary` is an empty dataframe which defaults the endpoint to returning an empty response.
- modify `and` to `or`
- test will be added https://github.com/chanzuckerberg/single-cell-data-portal/issues/4406

fix(WMG): no genes selected should not return empty response

---

backend/curation/api/curation-api.yml
backend/curation/api/v1/curation/datasets/dataset_id/versions/actions.py
tests/unit/backend/layers/api/test_curation_api.py

- #4329 
- modify endpoint response to return an array of dataset versions rather than an object with a nested array
- unit tested
- notebooks do NOT need updates for this change

feat: return dataset versions as array

---

backend/wmg/api/v1.py
frontend/tests/features/wheresMyGene.test.ts
tests/unit/backend/wmg/api/test_v1.py

- #4406
- added api tests to cover the edge case where no genes are selected.
- one for 1 tissue
- one for multiple tissues
- added an e2e test to cover the same edge case from the FE perspective
- Tests pass
I confirmed that these tests fail as expected when the bug fixed by #4405 is introduced.

chore(wmg): add unit test for no gene query edge case

---

frontend/src/views/WheresMyGene/components/HeatMap/components/Chart/style.ts

- #4213
- shrink left column of tooltip to 30% width
- make left column text not wrap
- vertical alignment baseline so word-wrap is easier to read
- tested on the longest cell type name in the corpus (below screenshot)

chore(wmg): prevent majority of word-wrap by expanding right column of tooltip

---

backend/wmg/api/v1.py
tests/unit/backend/wmg/api/test_expression_rollup.py

- [Context](https://czi-sci.slack.com/archives/C0247APK621/p1680121082202219?thread_ts=1680118996.135129&cid=C0247APK621)
- The rollup operation only applied to (gene, cell type, tissue) combinations for which we had data. For example, if a gene isn't expressed in `native cell` pre-rollup, then the rollup operation would not be able to rescue its expression as there is nothing to rollup into.
- For each gene, identify the missing combinations in `dot_plot_matrix_df` (the expression dataframe) based on the available combinations in `cell_counts_cell_type_agg` (the cell counts dataframe) and add them as zero's to `dot_plot_matrix_df` before rollup. Here, "combinations" refers to `<tissue, cell type, compare dimension if selected>`. Rolling up the dataframe can now potentially add expression …

fix(wmg): rollup now applies to genes+cell types that have no data

---

frontend/src/pages/collections-sitemap.xml/index.tsx

@tihuan not sure if this is able to get deployed straight to prod as a hotfix but the team is still receiving Google Search Console errors, I believe this lastmod formatting is the culprit.

chore: updating lastmod to fix google search console errors

---

frontend/next.config.js
frontend/src/views/Landing/index.tsx

- #4514 
Temporarily remove Twitter and Wistia until in #4513 we figure out a way to add them back in a compliant way
**RDEV link incoming**
1. Navigate to homepage
2. Scroll down and you should no longer see embedded video and twitter timelines
3. You should also no longer see cookies for both Wistia and Twitter domains
https://user-images.githubusercontent.com/6309723/230915967-85775f4e-cee1-499c-8682-a3650420ce93.mov

fix(homepage): 4514-temp-remove-twitter-wistia

---

frontend/src/components/common/Grid/common/constants.ts

Exploration of datasets of up to 4.3 million cells is now possible. Datasets with a cell count exceeding 4.3 million cells will not be explorable; the "Explore" button will be disabled with a corresponding updated tooltip message "Exploration is currently unavailable for datasets with more than 4.3 million cells".
- #4510 
- Modified the `DATASET_MAX_CELL_COUNT` to be `4,300,000` and the corresponding hover message to be `Exploration is currently unavailable for datasets with more than 4.3 million cells`.
- Any dataset with a cell count greater than 4.3 million cells will not be explorable; the "Explore" button will be disabled and the tooltip message should show "Exploration is currently unavailable for datasets with more than 4.3 million cells".
- It has been confirmed that this feature …

feat: Allow exploration of datasets up to 4.3 million cells (#4510)

---

frontend/src/components/common/Grid/components/NTag/index.tsx
frontend/src/components/common/Grid/components/NTag/style.ts

- The collections and datasets index NTag UI has been updated.
- #4556
- Modified the NTag to use `czifui` Tag component instead of `blueprintjs` and updated the style to match the [mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=4626-40099&t=fyFhxksWKZ4mSlsA-0) .e.g  padding, colour, font styles.
- Go to collections index, the NTag UI should be updated.

feat: Update NTag UI to match mocks (#4556)

---

backend/curation/api/v1/curation/collections/common.py
tests/unit/backend/layers/api/test_curation_api.py

Previously, all pre-redesign datasets lived under a key in the public-access datasets bucket that was different from their dataset version ids. Now, all past and future assets live under their dataset version id.
- #4621 
- modify asset uri to reflect dataset version id, and not the uuid that is part of the corpora prod asset
- unit tested

feat: always return dataset_version_id dataset permalink

---

frontend/src/components/CreateCollectionModal/index.tsx
frontend/src/components/CreateCollectionModal/style.ts
frontend/src/views/Collections/common/constants.ts
frontend/src/views/Collections/index.tsx
frontend/src/views/Collections/style.ts

Curators are able to create a collection from the collections index.
- #4560
- Added Create Collection button to collections index, for curators only.
- Updated Create Collection button from `blueprint` to `czifui`, and styles to match [mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=4626-40099&t=0WAYPzpZ8eh7QPpT-0).
- Go to collections index, the "Create Collection" button should not be visible.
- Use the curator feature flag, the "Create Collection" button should not be visible.
- Log in, the "Create Collection" button should be visible.
- Click on the "Create Collection" button and add a new collection. Flow should be unchanged i.e. when a new private collection is created the page should route to the private collection.
- Cancelling the "Create Collection" …

feat: Add create collection button to collections list for curators (#4560)

---

backend/layers/business/business.py
backend/layers/business/exceptions.py
backend/layers/processing/requirements.txt
backend/layers/thirdparty/s3_exceptions.py
backend/layers/thirdparty/s3_provider.py
backend/portal/api/portal_api.py
backend/wmg/pipeline/requirements.txt
tests/unit/backend/layers/thirdparty/test_s3_provider.py

- #4641 
- decouple s3 layer from api layer
- remove unnecessary imports that were imperfectly bandaiding dependency hell
- import s3 *interface* in business logic, not s3 *provider*
- Tests updated

fix: make s3 layer throw its own exceptions

---

frontend/src/pages/_document.tsx

- #4617 
- added font-weight `300`, `600` and `800` to Inter import.
- Review all elements using a font-weight of `300`, or `600` or `800` (`light`, `semibold`, or `medium`) to confirm correct rendering of the specified font-weight.
- See https://github.com/chanzuckerberg/single-cell-data-portal/issues/4207 and https://github.com/chanzuckerberg/single-cell-data-portal/pull/4562

feat: Update inter font weights to match app theme requirements (#4617)

---

frontend/src/views/Collection/components/ActionButtons/index.tsx
frontend/tests/features/collection/revision.test.ts

Adding a test-id to avoid Playwright locator matching two elements and throwing error

test(e2e): Update revision test to add a test-id

---

frontend/src/components/Collections/components/Grid/components/CollectionsGrid/style.ts
frontend/src/components/Datasets/components/Grid/components/DatasetsGrid/style.ts
frontend/src/components/common/Filter/common/entities.ts
frontend/src/components/common/Grid/common/entities.ts
frontend/src/components/common/Grid/components/ActionsCell/style.ts
frontend/src/components/common/Grid/components/HeaderCell/components/CountAndTotal/index.tsx
frontend/src/components/common/Grid/components/HeaderCell/components/CountAndTotal/style.ts
frontend/src/components/common/Grid/components/HeaderCell/index.tsx
frontend/src/components/common/Grid/components/HeaderCell/style.ts
frontend/src/components/common/Grid/components/LinkCell/style.ts
frontend/src/components/common/Grid/index.tsx
frontend/src/components/common/Grid/style.ts
frontend/src/types/react-table-config.d.ts
frontend/src/views/Collections/index.tsx
frontend/src/views/Datasets/index.tsx

- Collections and Datasets index table ui updated to match [mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=4626-40099&t=0WAYPzpZ8eh7QPpT-0).
- #4557
- modified collections and datasets table ui to match the [mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?node-id=4626-40099&t=0WAYPzpZ8eh7QPpT-0).
- added a new header component with updated styles, in preparation for [sorting](https://github.com/chanzuckerberg/single-cell-data-portal/issues/4559).
- Go to collections page and review:
- header and cell spacing, font styles, colour, and
- collection cell font styles and colour, and
- collection and datasets heading count tag, and
- table spacing and borders.
- Update: font-weight specification import resolved by #4617. Commentary below is out of …

feat: Update collection and datasets tables to match mocks (#4557)

---

.github/workflows/deploy-happy-stack.yml

Necessary to fix cloudfront invalidation; fix is the only commit since last staging deploy so hot fix not necessary

chore: 2nd staging deploy of 4/26/23

---

backend/curation/api/curation-api.yml

- #4386 
- add clear description of how the concept of 'version' impinges on Collections/Datasets and interacting with them via the Discover API.
- https://dan-docs-backend.rdev.single-cell.czi.technology/curation/ui/#/

docs: introduce Collection versions and Dataset versions

---

backend/api_server/requirements.txt

Pins Flask to be less than 2.3.0.
This is to avoid the `AttributeError: module 'flask.json' has no attribute 'JSONEncoder'` issue.

chore: pin Flask to be less than 2.3.0

---

.github/workflows/build-images-and-create-deployment.yml

Required to restore the deployment pipeline.

chore: skip unnecessary steps in push-prod-images

---

frontend/tests/features/wheresMyGene/shareLink.test.ts

@charles-testco I updated the `initialState` to use `TEST_URL`, so the tests won't fail in `dev`, `staging`, and `prod`!
Thank you!

test(wmg): Fix wmg e2e tests

---

.github/workflows/push-tests.yml

1. Currently we're getting 403 when trying to create test report page. 
[Example](https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/4917592967/jobs/8783425751)
[Log link](https://pipelines.actions.githubusercontent.com/serviceHosts/78ca9276-3e2b-466e-90c0-b7f09d6f2881/_apis/pipelines/1/runs/47296/signedlogcontent/111?urlExpires=2023-05-08T18%3A09%3A04.8265171Z&urlSigningMethod=HMACV1&urlSignature=kgsyDCNGbS1Cro%2F4WHtq6Ozdc3q2G1oRGR8oKdetjKE%3D)
3. According to [this instruction](https://github.com/marketplace/actions/github-pages-action#%EF%B8%8F-first-deployment-with-github_token), we need to specify `permissions write` for the job to make it work
- add
- remove
- modify
- Describe how you made sure to …

chore: Fix test report GH page

---

backend/layers/business/business.py
backend/portal/api/portal-api.yml
backend/portal/api/portal_api.py
tests/unit/backend/layers/api/test_portal_api.py

#4577,
#4578
- adds API endpoints for /user-collections/index and /user-datasets/index
- Could you describe how you made sure to know that your changes worked? Should allow someone else to go verify your code without in depth knowledge.

feat: user and dataset collections (#4577, #4578)

---

frontend/src/common/utils/checkForRevisionChange.ts

- #4775
- add ignore `revising_in` when comparing collections 
I have not been able to test this yet as I can't create an rdev

fix: ignore revising_in when comparing collections (#4775)

---

backend/portal/api/portal_api.py

- #4775
- I reverted a change that set `is_in_revision` dynamically based on the value of `revising_in` for collections in `_collection_to_response.`  I mistakenly thought `is_in_revision` applied to the original public collection (canonical); instead, it seems `is_in_revision` applies to the actual revisions themselves.  The incorrect value for `is_in_revision` for the canonical collection was causing datasets to be marked as `published = false` on the canonical collection and making the front-end code think the collection had been modified since it was last published. 
- I ran the back-end tests
- I validated the functionality first broken, then fixed on [cc-rdev-2](https://cc-rdev-2-frontend.rdev.single-cell.czi.technology/)
#4766 is still required to fix this bug so I have not …

fix: set is_in_revision false for collections with revisions (#4775)

---

backend/wmg/api/v1.py
backend/wmg/data/rollup.py
tests/unit/backend/wmg/api/test_expression_rollup.py

- #4575 
Modified the gene expression rollup code to also rollup the compare dimension cell counts correctly. Particularly, the change is in computation for set of ancestor cell types that should included rolled up numeric values from its descendant cell types.
- Visual inspection of the dot plot and cell counts in [rdev](https://rdev-ps-fix-rollup2-frontend.rdev.single-cell.czi.technology/gene-expression) based on manual testing.
- Added unit tests for the top level rollup functionality which is public function
- Added unit tests for the private functions that the public rollup function calls

fix: Fix rollup implementation to include compare dimension

---

frontend/src/common/queries/cellCards.ts
frontend/src/views/CellCards/components/CellCardSearchBar/index.tsx
frontend/src/views/CellCards/components/CellCardSearchBar/style.ts
frontend/src/views/CellCards/components/LandingPage/index.tsx
frontend/tests/features/cellCards/cellCards.test.ts

- Add cell type search bar feature to Cell Guide landing page.
- added cell type search bar 
- added e2e tests for landing page and search bar
- modified the `useCellCardQuery` hook to use generics
- added `use<Endpoint>` wrapper hooks for convenience.
- e2e tests pass

feat(cell-guide): cell type search bar added

---

backend/wmg/api/v1.py
tests/unit/backend/wmg/api/test_expression_rollup.py

- #4867 
When the query API gets a list of tissues and genes, and it is the case that one of the tissues in the query arguments does not express any of the genes in the query argument, the rollup function would throw a KeyError when looking up the "gene expression free" tissue in one of the data structures.
The fix is to prevent this look up by filtering these "expression free tissues".
- Follow reproduction steps in the ticket on rdev
- Added unit tests to verify the fix at the function level

fix: Fix rollup bug when selected tissue has no gene expressions

---

backend/wmg/api/v2.py
backend/wmg/data/query.py
tests/unit/backend/wmg/api/test_v2.py

- #4863
- This ticket requires multiple commits. This commit **addresses steps 1 to 3** as described in the ticket. _**Specifically, this commit versions the WMG API (make a `v2` version) instead of making changes in the existing API version (`v1`) so as to prevent backward incompatible changes in the API (ex: structure of payload sent back to the frontend) from breaking the current production version of frontend rendering code.**_
- add v2 version of the WMG query API and accompanying unit test file
- add v2 version of the `WMGQueryCriteria` class called `WMGQueryCriteriaV2` to isolate the WMG V2 requirement of querying without specifying `tissue_ontology_term_id`
- Currently has no tests since this is effectively unreachable code. Moreover it is effectively prototype code meant to …

refactor: Create a strawman V2 version of the WMG API

---

backend/api_server/app.py
backend/wmg/api/wmg-api-v2.yml

- #4863 
- _This ticket requires multiple commits_. **This commit addresses step 4 as described in the ticket**. Specifically, this commit hooks up WMG V2 API endpoints to the application router so that the frontend can hit the V2 api by using the url `/wmg/v2/<endpoint-name>`
- add `wmg-api-v2.yml` api spec file
- add call to route `/wmg/v2/<end-point>` calls to the correct functions in `v2.py`
**Checked the url routes to the correct version of the API and endpoint in the [rdev](https://rdev-ps-wmgv2-wired-backend.rdev.single-cell.czi.technology/) associated with this branch**
- Here is the request body that was tested for the `query` endpoint. _Notice that `tissue_ontology_term_ids` has value `[]`, that is, `tissue_ontology_term_ids` are not being sent in the request body per WMG V2 …

feat: Wire up WMG V2 API into the app's url router

---

frontend/src/pages/docs/[...slug].tsx

ticket:
https://github.com/chanzuckerberg/single-cell-data-portal/issues/4729
- sets the `isExpanded` state to 1 if `directory.files.includes(activeFile)` using the react hook `useMemo`
- after doing some reading + consulting chatGPT, i believe a react hook is necessary because the values `directory.files` and `activeFile` may not be set when the component is first rendered. the `useMemo` hook will ensure that the state is set if the data is updated asynchronously
- i think `useMemo` is preferred over `useEffect` since this component doesn't rely on any external dependencies
- recursively checks the directory as well as any child subdirectories to see if the activeFile is in there, and sets the expansion state as necessary
- i also included some aesthetic changes to declare …

fix: documentation outline when you enter from an external source

---

frontend/tests/features/cellCards/cellCards.test.ts

- This test is flakey and also testing native NavBar functionality, something that we are not accountable for.
- We also cover basic scroll functionality via the navbar in another test.
- Remove the flakey and redundant test.

fix(cell-guide): remove redundant and flakey e2e test

---

frontend/src/views/CellCards/components/CellCard/components/EnrichedGenesTable/index.tsx

- The version on the share URL wasn't set for the enriched genes Open in Gene Expression link, so the WMG client expected commas that weren't URL encoded.
- add ver=2 to the end of the share URL link.

fix(cell-guide): set share URL to version 2 for enriched genes share link

---

frontend/src/views/CellCards/components/CellCard/components/CanonicalMarkerGeneTable/index.tsx

- The tooltip was pointing to ASCT+B v1.2 but we are using v1.3.

chore(cell-guide): update canonical marker gene tooltip to point to latest ASCT+B version

---

frontend/src/views/CellCards/components/CellCard/components/CanonicalMarkerGeneTable/index.tsx
frontend/tests/features/cellCards/cellCards.test.ts

- To be consistent with CCF nomenclature

chore(cell-guide): rename publication to references for canonical marker gene table

---

frontend/src/views/CellCards/components/CellCard/components/OntologyDagView/index.tsx

- Update the DAG tooltip to remove descendant # cells indicator for leaf nodes
- Leaf nodes have no descendants so this information isn't meaningful.

chore(cell-guide): update dag tooltip to remove descendent cells for leaf nodes

---

frontend/src/views/CellCards/components/CellCard/components/OntologyDagView/common/constants.ts
frontend/tests/features/cellCards/cellCards.test.ts

-There was overlap between 2 square nodes:
- Increase vertical spacing from 15 to 18

chore(cell-guide): increase vertical spacing between nodes in ontology view

---

backend/wmg/api/wmg-api-v2.yml
backend/wmg/data/query.py
tests/unit/backend/wmg/api/test_v2.py

- #4863 
- This PR addresses step 5 in the ticket above - specifically creating unit test coverage for the WMG V2 API where the `query` endpoint expects request bodies without `tissue_ontology_term_ids` key.
- add unit tests
- Make api more secure by making strict the schema of the request body on `HTTP POST`. Specifically, the openApi spec is modified such that properties not specified in the request body schema are rejected. This prevents potential injection attacks that could lead to a denial of service or worse things.
- Unit tests

feat: Unit tests and security for WMG V2 API

---

frontend/tests/common/context.ts

Failing locator actions resulted in tests taking the full 5 min to time out.

fix: set action timeout to 10s

---

frontend/package-lock.json
frontend/package.json

- The AWS SDK version was uncapped and `npm i` automatically installed a backwards-incompatible version, which prevented the testrunner from being able to log in.
-

fix: revert aws-sdk dependency upgrade

---

frontend/tests/common/context.ts

Reverts chanzuckerberg/single-cell-data-portal#4917
The action timeout being set to 10s triggered errors when waiting for a button for longer than 10s because the page was taking long to navigate to the desired URL. Errors were also being triggered because waiting for a download took longer than 10s.

Revert "fix: set action timeout to 10s"

---

backend/wmg/api/wmg-api-v2.yml

`development_stage_ontology_term_ids` key was misspelled causing WMG V2 API to break.
- `development_stage_ontology_term_id` key in the WMG V2 API was misspelled as `development_ontology_stage_term_id` causing the WMG V2 API to fail while parsing the request body.
- Change `development_ontology_stage_term_id` key to `development_stage_ontology_term_id` in the openapi spec file.
- unit tests

fix: Fix typo in request body schema for WMG V2 API

---

backend/wmg/data/validation/validation.py

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4529
i pulled the cell counts data frame in locally, and ran the following commands
```
In [3]: cell_counts_df["dataset_id"].nunique()
Out[3]: 283
In [5]: cell_counts_df["tissue_original_ontology_term_id"].nunique()
Out[5]: 190
In [4]: cell_counts_df["tissue_ontology_term_id"].nunique()
Out[4]: 61
In [6]: cell_counts_df["organism_ontology_term_id"].nunique()
Out[6]: 4
```
i also found the total size of the expression summary cube by running this command from the `snapshot/expression_summary` directory:
```
find . -type f -name '*.tdb' -exec du -ch {} + | grep total$
2.6G	total
```
the constants were then set as roughly 90% of what the current values are in the expression …

chore: update constants in validation file

---

backend/layers/processing/process_cxg.py
tests/unit/processing/test_processing.py

- #4855
- Necessary because local h5ad / cxg filename do not have a consistent s3_uri naming convention across all datasets, meaning it's easiest to fetch the old path + update in-place when re-processing rather than try to reverse engineer how each dataset at different points in time mapped from dataset ID -> labeled h5ad s3_uri -> cxg s3_uri 
- when reprocessing cxgs, updates cxg artifact in-place based on reprocessing previous labeled h5ad
- rdev + unit tests

fix: refactor cxg reprocessing such that original cxg uri is retained and updated in-place

---

backend/layers/processing/process_cxg.py
backend/layers/thirdparty/s3_provider.py
backend/layers/thirdparty/s3_provider_mock.py
tests/unit/processing/test_processing.py

- #4856
- refactor cxg reprocessing path to fetch current local h5ad s3_uri rather than assume ID (issue: inconsistent whether local.h5ad location uses dataset ID or dataset version ID)
- rdev

fix: reprocess needs to fetch current local h5ad s3_uri

---

backend/wmg/data/tissue_mapper.py

Fixes an issue where the tissue mapper is unable to download the UBERON ontology file.
- Updates the uberon.owl file to a different location (which is the redirect target for the old URI).
- Unit tests should cover the update.

fix: update ontology file location in tissue_mapper

---

backend/wmg/data/query.py
requirements.txt

- Fixes #4893 
- Upgrades tiledb to 0.21.1, which is the version pinned in Explorer.
- Run tests in GHA, see if they pass
- Run this in rdev, upload a dataset, see if it can be opened by the Explorer
- For WMG, need to figure out a testing strategy w/ data-vis team

chore: upgrade tiledb to 0.21.4

---

frontend/src/components/common/Grid/components/HeaderCell/index.tsx
frontend/src/components/common/Grid/components/HeaderCell/style.ts

- #4905 
- Modified column header sort ui as per [mocks](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filtering?type=design&node-id=4846-40544&t=FWVYJSodTiqZD6vk-4).
- Log in as a curator and on the Collections page, click on the "Status" header.

feat: UI Updates to sortable column headers (#4905)

---

backend/common/utils/result_notification.py

- Fixes #4959 
- Fixes WMG pipeline slack notifications. Those were broken because Slack only accepts up to 150 characters in a `header` block. I changed this to that the header is now a fixed size.
- Modifies the wmg slack messages.
-  Testing the pipeline success is easy - we'll do a test run in dev anyway
- Testing failures is more difficult. I will try to do that using rdev.

fix: WMG slack notifications

---

backend/wmg/api/v2.py
backend/wmg/api/wmg-api-v2.yml
tests/unit/backend/wmg/api/test_v2.py

- #4863 
- This PR addresses *step 6* in the ticket referenced. This PR concludes the work needed to make `\query` endpoint for WMG V2 functional (but not necessarily performant)
- add aggregate gene expression stats to the response object returned by `\query` endpoint
- add aggregate cell counts stats to the response object returned by `\query` endpoint
- add unit tests to cover changes to the response object returned by `\query` endpoint
- Unit tests
1. Go to rdev for `/wmg/v2/query` endpoint: https://rdev-ps-wmg-v2-query-backend.rdev.single-cell.czi.technology/wmg/v2/ui/#/wmg/backend.wmg.api.v2.query
2. Paste in the following request body to the end point:
```
{"filter":{"dataset_ids":[],"development_stage_ontology_term_ids":[],"disease_ontology_term_ids":[],"gene_ontology_term_ids":["E …
```

feat: Add aggregate gene expression and cell counts for WMG V2 response

---

frontend/src/pages/cell-guide/[cellTypeId].tsx
frontend/src/views/CellCards/components/CellCard/index.tsx
frontend/src/views/CellCards/components/CellCard/style.ts
frontend/src/views/CellCards/components/common/OntologyDagView/index.tsx

- #4931 
Add "Suggest Change" button and link out to the form
1. RDEV: https://thuang-cell-feedback-frontend.rdev.single-cell.czi.technology/cell-guide/CL_0000115
2. Go to rdev link above to view a cell card
3. Click on "Suggest Change"
4. It should open the form in a new tab
5. Resize window to skinny mode
6. The Search box should move above the card title
7. That's it!
Regular mode Figma:
Skinny mode Figma:
ACTUAL:
https://github.com/chanzuckerberg/single-cell-data-portal/assets/6309723/a81ab7a1-9edd-4002-ad6c-77e6ae6e2c19

feat(cellcard): Add suggest change

---

frontend/src/common/entities.ts
frontend/src/components/Collection/components/CollectionDatasetsGrid/components/Row/DatsetRow/components/MoreDropdown/components/Menu/index.tsx
frontend/src/components/Collection/components/CollectionDatasetsGrid/components/Row/DatsetRow/components/MoreDropdown/index.tsx
frontend/src/components/Collection/components/CollectionDatasetsGrid/components/Row/DatsetRow/index.tsx

- #3037 
- Curators are no longer able to delete a dataset in the private revision of a published collection i.e. if a dataset has been previously published, then it may not be deleted. For clarification see [slack thread](https://clevercanary.slack.com/archives/C02CF7MQPGV/p1685602748854589?thread_ts=1685602175.729339&cid=C02CF7MQPGV).
- Curator may delete a dataset from a private collection.
- Curator may NOT delete a dataset from a published revision collection.
- Curator may add a new dataset to a published revision collection, and is able to delete the newly added dataset.

feat: Deletion of published datasets in the Curation UX must be removed (#3037)

---

backend/wmg/api/common/expression_dotplot.py
backend/wmg/api/v2.py
tests/unit/backend/wmg/api/test_v2.py

- #4971 
Currently, the calculation of tpc involves summing up gene expression values in the rolled-up gene expression dataframe over groups keyed by (gene_ontology_term_id, tissue_ontology_term_id) pairs.
Since rolled-up values are calculated over the cell-type ontology inheritance graph, any aggregation functions grouped by composite keys that DO NOT include `cell_type_ontology_term_id` will aggregate duplicate values.
Since the grouping key (gene_ontology_term_id, tissue_ontology_term_id) does not contain `cell_type_ontology_term_id`, the aggregation CANNOT happen over the rolled-up gene expression dataframe. Instead, the aggregation should be computed over the original gene expression dataframe containing raw gene expression values.
See heading above
- Unit tests
- rdev manual test …

fix: Fix tpc gene expression statistic calculation

---

frontend/src/components/Collection/components/CollectionDatasetsGrid/components/Row/DownloadDataset/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/index.tsx

- #4179
- Removed `x` button from datasets download dialog (both datasets index and detail pages).

feat: Remove 'X' icon from Datasets Download Dialog (#4179)

---

tests/unit/backend/wmg/fixtures/test_anndata_object.py
tests/unit/wmg_processing/test_load_corpus.py

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4519
- Implements some basic sanity checks for verifying the snapshot of our cell corpus works as expected. Since I believe the input dataset that is generated for this test includes some amount of randomness (see all usages of `np.random.choice` [here](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/tests/unit/backend/wmg/fixtures/test_anndata_object.py)), I don't think it would be possible to create this test with a static cube fixture.
- Instead, this does some basic sanity check assertions on mostly the `obs` matrix to verify that the size is roughly correct, the number of unique values is roughly what we expect, and basic assertions when the …

feat: Implement the high-level snapshot creation unit test in TestCorpusLoad

---

frontend/src/common/queries/filter.ts
frontend/src/components/common/Grid/components/Loader/index.tsx
frontend/src/components/common/Grid/components/Loader/style.ts
frontend/src/views/Collections/index.tsx
frontend/src/views/Datasets/index.tsx
frontend/src/views/Datasets/style.ts

- #4908 
- The Collections and Datasets index has been modified to display only the filter sidebar and list upon successful execution of the collections and datasets query, resolving the issue of unwanted and premature display of "No Results".
- A loading indicator has been implemented specifically for curator mode to provide a visual representation of the pending collections and datasets query.
- A curator should see on page refresh, *a loading indicator*, followed by the display of the side bar filters and list.
- A non-curator should see on page refresh, *no loading indicator*, followed by the display of the side bar filters and list.
- Both curator and non-curator should not see a flash of "No Results" during loading.

fix: Bug(curation) Flash of "No Results" when refreshing the collections page / No loading indicator (#4908)

---

Dockerfile.backend

isn't allowing backend docker container to start-up

fix: typo in Dockerfile.backend

---

frontend/src/common/queries/wheresMyGene.ts

- The URL-to-dataset ID parser was hard-coded for the dev API URL. 

fix: fix url parsing in publication filter

---

frontend/src/views/Collection/components/DatasetTab/index.tsx
frontend/src/views/Collection/components/EmptyModal/index.tsx

- #4491
- Modified the private collections "No Datasets Uploaded" modal to optionally render text and button. The uploading of private collection datasets can only be actioned by a curator with write access.

fix: Private collections must not display "No datasets uploaded ... Add Dataset from Dropbox" to submitters (#4491)

---

frontend/tests/utils/helpers.ts

we're going to try doubling the timeout to see if it helps with e2e tests timing out. currently, about half of recent push tests have failed due to e2e tests timing out
doubles timeout from 60 seconds to 120 seconds
🤷‍♀️ going to see if the push tests for this PR pass

chore: double timeout to 120 seconds

---

backend/curation/api/v1/curation/collections/common.py
tests/unit/backend/layers/api/test_curation_api.py

- #5113 
- modify response on `GET /collection_versions/{collection_version_id}` and `GET /collections/{collectIon_id}/versions` such that `.datasets[]` becomes `.dataset_versions[]`
- ## Testing steps
unit tests updated

fix: change 'datasets' to 'dataset_versions' in GET /collection_versions

---

.happy/terraform/modules/ecs-stack/main.tf
.happy/terraform/modules/ecs-stack/variables.tf

- The container resources are under utilised. These changes make full use of the container as recommended by flask.
- make the number of works match the number recommended by flask.
- make backend vcpus configurable.

fix(backend): increase number of workers for deployed backend flask app 

---

Makefile
backend/curation/api/v1/curation/collections/common.py
tests/unit/backend/common/test_common.py

This temporary fix addresses a more fundamental bug in the pipeline logic which is resulting in occasional instances of duplicate asset rows in the DatasetArtifact table.
- #5136 
- unit tested

fix: prevent duplicate assets from being returned by Discover API

---

frontend/src/views/CellCards/components/CellCard/components/Description/index.tsx
frontend/src/views/CellCards/components/CellCard/components/MarkerGeneTables/index.tsx
frontend/tests/features/cellCards/cellCards.test.ts

- This applies the same filtering done for FMG in GE.
- Hide organism dropdown for canonical marker genes and tissue dropdown for computational marker genes
- change typo from "in" to "at"

chore(cell-guide): filter genes with <0.5 marker score and hide irrelevant gene dropdowns

---

frontend/src/views/CellCards/components/CellCard/components/MarkerGeneTables/index.tsx

- Gene Info was not working for mouse genes (in computational marker gene table) as the genes are required to be fully capitalized.
- The fix was to simply capitalize the gene symbol prior to setting the gene info gene.

fix(cell-guide): capitalize mouse genes for gene info feature

---

backend/wmg/pipeline/integrated_corpus/job.py

if we fail to extract an h5ad file into an anndata object, we should just skip over it rather than breaking the entire WMG pipeline
n/a

fix: wrap anndata extraction in try/except

---

backend/wmg/api/v2.py

- build_expression_summary is the bottleneck for wmg v2
- rewrote the for loop to iterate through numpy arrays instead of using `pandas.DataFrame.loc`
- Tested locally and confirmed that the results are the same before and after this change

fix(wmg): update build_expression_summary to be faster

---

.happy/terraform/envs/prod/main.tf
backend/wmg/data/query.py
backend/wmg/data/tiledb.py

- #5213 
- Decreasing buffer by 10x
- Using return_incomplete=True and `pd.concat` to avoid query restarts for queries that exceed buffer size.
- add
- remove
- modify

chore: decrease init buffer bytes and use return_incomplete

---

backend/wmg/data/validation/validation.py

- this should now allow you to search the aws logs for "Cube Validation Failed" and find all the reasons why cube validation failed
- this also marks these as `error` level logs instead of `info` level
n/a

fix: make error message more searchable / readable

---

backend/layers/business/business.py
backend/layers/business/business_interface.py
tests/unit/backend/layers/api/test_curation_api.py
tests/unit/backend/layers/business/test_business.py

- #3039 
- modify `BusinessLogic.remove_dataset_version` to accept a `delete_published` boolean parameter, which defaults to `False`
- prevent a published Dataset from being tombstoned unless `delete_published` is `True`.
- Add business tests per @Bento007 's request
- unit tested
- Parameter approach preferred by eng team to previous implementation with env var - #5226

feat: prevent deletion of published Datasets

---

frontend/src/views/CellGuide/components/CellGuideCard/components/MarkerGeneTables/index.tsx
frontend/src/views/CellGuide/components/CellGuideCard/index.tsx

- This was launch blocking
- #5218
- added cellType to the share URL for the open in gene expression feature.

feat(cellguide): open in gene expression now filters to cell card cell type on load

---

frontend/src/views/WheresMyGeneV2/components/GeneSearchBar/components/SaveExport/csvUtils.ts

- #5108
BEFORE:
AFTER:
1. Download a CSV with one tissue expanded, your CSV should have "aggregated" as value for the tissue rows on "Cell Type" column

fix(wmg): 5108 fix csv cellType column for tissue

---

backend/Makefile

fixes
```
[1689971749803][fargate/db/3c25]  =====
[1689971749803][fargate/db/3c25] | starting backend container
[1689971749803][fargate/db/3c25]  =====
[1689971749804][fargate/db/3c25] make: Entering directory '/single-cell-data-portal/backend'
[1689971749806][fargate/db/3c25] /bin/sh: 1: aws: not found
[1689971749838][fargate/db/3c25] # Run utility installation before invoking these commands.
[1689971749839][fargate/db/3c25] pip install awscli -r ../requirements-base.txt
[1689971750244][fargate/db/3c25] ERROR: Could not open requirements file: [Errno 2] No such file or directory: '../requirements-base.txt'
[1689971750303][fargate/db/3c25] make: *** [Makefile:8: db/remote_migration_init] Error 1
[1689971750303][fargate/db/3c25] make: Leaving directory '/single-cell-data-portal/backend' …
```

fix: update requirements for db/remote_migration_init

---

requirements-wmg-pipeline.txt

- #5075 
- modify `requirements-wmg-pipeline.txt` such that package versions are pinned
- Ensure all unit tests pass locally
- `botocore` is not _pinned_ but its version is constrained based on the fact that it is a dependency of `boto3` (which is pinned) and `pipdeptree -packages boto3` requires `botocore` to be within a version range:
```
% pipdeptree --packages boto3    
boto3==1.28.7
├── botocore [required: >=1.31.7,<1.32.0, installed: 1.31.7]
│   ├── jmespath [required: >=0.7.1,<2.0.0, installed: 1.0.1]
│   ├── python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.2]
│   │   └── six [required: >=1.5, installed: 1.16.0]
│   └── urllib3 [required: >=1.25.4,<1.27, installed: 1.26.16]
├── jmespath [required: >=0.7.1,<2.0.0, installed: 1.0.1]
└── s3transfer [required: >=0.6.0,<0.7.0, …
```

chore: Pin python package versions for wmg pipeline

---

frontend/src/views/CellGuide/components/common/OntologyDagView/index.tsx

- #5325 
- added `disableFullScreen()` to the cleanup hook in the ontology component.
https://github.com/chanzuckerberg/single-cell-data-portal/assets/16548075/14333085-f2ee-4858-b54d-9639e9eccb0f

fix(cellguide): disable full screen when cell type id changes

---

backend/wmg/data/snapshot.py
backend/wmg/data/utils.py

- #4928
- cube builder only fetches the latest published dataset version with pinned major schema version 3 (i.e. 3.X.X) for each canonical dataset
- update build_dataset_metadata_dict function to only make 1 API call (all necessary data is in datasets endpoint)
- dev cube run

feat: update cube builder to only fetch datasets from pinned CxG schema version

---

tests/functional/backend/wmg/test_wmg_api.py

- A couple of `v1/wmg/api` functional tests are being skipped because the V1 API is deprecated and adds no value. A future PR will clean up the dead code and modify functional tests that target `v2/wmg/api`
- add a `@unittest.skip` decorator to the functional tests that should be skipped
Ran the functional tests _locally_ and check that the appropriate tests are _skipped_ :
```
% AWS_PROFILE=single-cell-dev DEPLOYMENT_STAGE=dev pytest -v tests/functional/backend/wmg/test_wmg_api.py
```
```
================================================================================================================ test session starts ================================================================================================================
platform darwin -- Python 3.10.12, pytest-7.4.0, …
```

test: Skip failing WMG V1 functional tests

---

frontend/tests/utils/helpers.ts

We're now getting `Invalid URL TypeError` when trying to login, turned out that when I upgraded FE packages last week, a minor version upgrade for `@aws-sdk/client-secrets-manager` actually was a breaking change that it no longer accepts empty string 😮‍💨 
https://github.com/chanzuckerberg/single-cell-data-portal/pull/5222

test: fix login invalid URL error

---

frontend/tests/common/playwright.global.setup.ts
frontend/tests/utils/helpers.ts

1. Skip login for GHA PR tests that are NOT against `dev` or `staging`, so we save time and avoid unnecessary error

test: Fix wmg e2e test login

---

.happy/terraform/modules/schema_migration/main.tf

- Previously, we were using an Job Definition ARN for schema-migration that pinned to a particular version. This would cause the step function to start failing during runs if a new version was deployed mid-run (as the pinned version would get marked as inactive). We should use the same model the [upload sfn uses](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/.happy/terraform/modules/batch/outputs.tf#L6), which is pulling the latest job definition at run-time so that the sfn will persist across deployments, which always trigger new job definitions. 
- define job definition arn without the revision number as a local var in schema_migration sfn definition file
- replace in sfn definition 
- [In-progress] Created an rdev and validated a schema migration works, even after …

fix: pull latest schema-migration batch job definition in sfn

---

backend/wmg/api/__init__.py
backend/wmg/api/v2.py
backend/wmg/api/wmg_api_config.py
backend/wmg/data/snapshot.py
backend/wmg/pipeline/summary_cubes/calculate_markers.py

- #5165 
- The entry point function `load_snapshot()` accepts a snapshot schema version and an optional snapshot id to enable loading snapshots are a particular snapshot schema version.
- refactor the interface to `load_snapshot()` and the functions it calls to accept a snapshot schema version to load and an optional snapshot id to force load in the case the latest snapshot at a particular schema version is not needed
- **NOTE**: This change is merely a change to the interface. There are no changes to the behavior (ie output and side effects) of the functions being refactored. That change will come when we address #5166 and #5167 
- Run unit tests locally and ensure that they all pass
- The following `rdev` functionally shows that the snapshot can be uploaded when you go to the gene …

refactor: Change snapshot loading interface

---

requirements-processing.txt

unpin before prod deployment. This was original set to test the schema-migration pipeline on the dev data corpus.

feat(schema-migration): unpin cellxgene-schema-cli

---

frontend/src/common/API.ts
frontend/src/common/queries/wheresMyGene.ts

- https://github.com/chanzuckerberg/single-cell-data-portal/pull/5377
- Make the WMG frontend call `/v2/markers` instead of `/v1/markers`
- modify call sites on the frontend to call hit `/v2/markers`
- Manually tested by starting the frontend server locally and checking that adding marker genes calls `/v2/markers` and returns `http 200 OK`

fix: Make WMG frontend call v2 version of the /markers endpoint

---

README.md

- Added to the README to highlight notebooks added in #5376

chore: add callout for example_dev_notebooks to the README

---

frontend/src/views/WheresMyGene/components/CellInfoSideBar/index.tsx

1. Use relative path, so the user will get the cell guide from the same domain instead of always from prod
- add
- remove
- modify
1. Open in Cell Guide link should now open a new tab from the same domain. E.g., localhost if open from localhost, staging if open from staging

fix: cross link relative path

---

frontend/playwright.config.ts
frontend/tests/README.md
frontend/tests/common/constants.ts

1. Add e2e test fail fast when there's already 2 tests failing. This should prevent e2e tests from timing out due to too many test failures, so engineers at least get to see the 2 test errors in the GHA report
2. Add a `Playwright Cheat Sheet` section to document efficient ways to debug and write e2e tests ([PREVIEW](https://github.com/chanzuckerberg/single-cell-data-portal/tree/thuang-improve-e2e/frontend/tests#playwright-cheat-sheet))
4. Add new test flag `LOGIN=false` to skip login. A complement to `SKIP_LOGIN=true`, which has too many chars to type
1. `LOGIN=false npm run e2e` should skip login step

test: Improve e2e tests

---

frontend/src/views/CellGuide/components/CellGuideCard/style.ts

- per SEO Jackie, we need to use h1! [Slack](https://czi-sci.slack.com/archives/C04CP2N7XC5/p1691605196636249)
1. Change header from `div` to `h1`
Like this:

fix: CellGuide header to h1

---

backend/layers/business/business.py
backend/layers/persistence/persistence.py
backend/layers/persistence/persistence_interface.py
backend/layers/persistence/persistence_mock.py
tests/unit/backend/layers/business/test_business.py

Change relevant db provider methods to strictly rely on datasets associated with latest CollectionVersion as the 'active' DatasetVersion for a given DatasetId. This fixes a bug introduced by #5355 which allows rollback to previous DatasetVersions without deleting the most-recently-created DatasetVersion row.
- #4811 
- replace usage of `get_all_versions_for_dataset` to find latest (active) DatasetVersion with a new db provider method `get_most_recent_active_dataset_version`.
- unit tested

fix: do not assume latest DatasetVersion is active

---

backend/layers/persistence/persistence.py
tests/unit/backend/layers/business/test_business.py

Fixes #5424 
- Enforces a stricter transaction isolation level for some database operations. This should hopefully mitigate a race condition where the two pipelines (RDS and CXG) can update the same database record concurrently if they complete at the same time.
- TODO: this will only cause one of the transactions to fail. This will at least mark the dataset as failed, and not yield a silent failure like today. A better alternative is to add retries [as recommended by the PostgreSQL docs](https://www.postgresql.org/docs/current/transaction-iso.html). This can be done as part of this PR or as a follow up.
- Added a unit test that simulates the concurrency via threading. I tried the unit test it main and it doesn't pass (as it should)
- For what it's worth, I tested this in rdev to make …

feat: add Serializable isolation for select db operations

---

backend/wmg/data/load_cube.py
backend/wmg/data/snapshot.py
tests/unit/wmg_processing/test_cube_pipeline.py

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5167
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4691
- marker genes is already reading versioned snapshots, this PR will update `load_snapshot` so that all clients (including the WMG API) read versioned snapshot paths
- adds more logging for when we write the snapshots
- adds a test verifying that we're reading / writing to versioned paths

feat: update load_snapshot to by default read versioned paths

---

frontend/src/pages/cellguide/tissues/[tissueId].tsx
frontend/src/views/CellGuide/components/CellGuideCard/index.tsx
frontend/src/views/CellGuide/components/TissueCard/index.tsx
frontend/src/views/CellGuide/components/common/OntologyDagView/index.tsx

- #5037  
- The goal is to remove branches with 0 cells in the tissue.
- A secondary goal of this PR is to prep the `OntologyDagView` component for the situation where a tissue AND a cell type is specified. This will be used in the case where users can set a global tissue filter on each CellGuideCard (see #5368 for details). In this case, the expanded nodes will be the intersection of the expanded nodes in the specified tissue and the specified cell type. The "hidden" nodes when a parent is expanded will be the _union_ of those in the specified tissue and the specified cell type.
- No functional behavior changes expected in this PR except for the content that is displayed in tissue ontology views. Therefore, no tests added. When the global tissue filter is added, then E2E tests will be …

feat(cellguide): remove nodes from tissue ontology view that are not found in the tissue

---

.github/workflows/build-images-and-create-deployment.yml
.github/workflows/push-tests.yml

Submit `codecov` reports when merging a commit to main. We're currently submitting them on PRs (push-tests.yml), but since we do squash and merge, the commit that ends up in main will be different. This is causing codecov not to record all the commits.

fix: add codecov reports on merges to main

---

backend/layers/processing/schema_migration.py

Add more logging to make debugging easier in the event a report is not created or an error occurs during publish. The function to delete artifact was moved before publish to make sure artifact are deleted even if publish fails.
- add logging for the error message for each dataset during publish
- Move delete datasets artifact before publish. This is to ensure the migrated files get cleanup.

fix(schema-migration): add more logging

---

backend/layers/processing/schema_migration.py
tests/unit/processing/schema_migration/test_publish_and_cleanup.py

- #5555 
- Issue with cleanup of temp migrated.h5ad files created during schema-migration; wrong IDs were used for comparison to determine whether cleanup + error reporting occurred. As a result, files were not cleaned up. 
- compare canonical dataset IDs to determine whether a dataset in a collection was processed by schema migration (rather than version ID, which creates a new dataset version ID when you do dataset replacement ingestion but keeps the stable canonical dataset ID) 
- rdev migration

fix(schema-migration): migrated.h5ad file cleanup

---

.happy/terraform/envs/stage/main.tf
backend/layers/processing/schema_migration.py
tests/unit/processing/schema_migration/test_publish_and_cleanup.py

- #5555 
- Lowering batch container memory limit for staging job
- Fix post-migration migrated.h5ad file cleanup error (wasn't properly cleaning up migrated.h5ad files)
- batch container memory limit for upload jobs 635600 -> 63500 (matches prod)
- Functional Tests (they caught the batch container error last time)
- rdev migration run

fix: staging batch container memory limit + file cleanup

---

frontend/src/views/WheresMyGene/components/HeatMap/components/Chart/index.tsx
frontend/tests/features/wheresMyGene/cellTooltip.test.ts

- #5559
- add
-  Adds logic fork for tissue tooltips, uses `celltype.name` instead of celltype.cellTypeName` if the `name` contains `"UBERON"`
-  ~Adds test to ensure UBERON isn't present in the tooltip text~

fix(wmg): add correct tooltip cell type for tissue rows and add test coverage

---

.github/workflows/close-inactive-issues.yml

The default setting for the Github Action to automatically mark PRs as stale sets issues as `stale` after 60 days. This PR fixes that by overriding the default to -1 which ensures that issues are never marked as stale.
#560 
None.
None.
The `close-inactive-prs` Github Action has been modified to never set issues as stale.
Not tested.
None.

fix: override default so that issues are not marked as stale

---

backend/common/constants.py
backend/wmg/data/utils.py

- To avoid needing to set two environment variables when running the cellguide pipeline, add a mapping of DEPLOYMENT_STAGE to API_URL. Now, only DEPLOYMENT_STAGE is required when running the CellGuide pipeline.

chore(cellguide): update to infer API URL from DEPLOYMENT_STAGE

---

.github/workflows/build-images-and-create-deployment.yml

- Upload the CellGuide pipeline image to ECR.
- remove 'push-prod-images' as all prod deployments are using dev images

fix(cellguide): add cellguide_pipeline to ecr upload

---

Dockerfile.cellguide_pipeline

- Missing modules for the pipeline to run inside the CellGuide container
- RDEV pipeline running successfully (logs to be added)

fix(cellguide): add wmg api backend to cellguide image (DO NOT MERGE)

---

backend/wmg/data/snapshot.py

- [Slack context](https://czi-sci.slack.com/archives/C023Q1APASK/p1693329070018309)
- disentangle dataset_dict building from snapshot loading. Even if the snapshot exists, if dataset_dict does not exist as an attribute, it should be rebuilt.

chore(wmg): rebuild dataset dict if previous load_snapshot failed to do so

---

scripts/cxg_admin.py

- #4828 
- modify CloudfrontProvider import to be after path assignment in the cxg_admin.py file
- tested in dev/staging

fix: perform import after path assignment for cxg script

---

backend/cellguide/pipeline/__init__.py
backend/cellguide/pipeline/gpt_descriptions/gpt_description_generator.py
backend/cellguide/pipeline/providers/s3_provider.py
backend/cellguide/pipeline/utils.py
scripts/populate_rdev_with_cellguide_data.sh

- added helper functions to get the bucket path and object keys for different deployments (namely rdev vs everything else)
- Pipeline successfully completed, uploaded data to the right location, and created cloudfront invalidation
- Logs [here](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/%2Fdp%2Frdev%2Fcellguide-pipeline%2Fcg-pipeline/log-events/cg-rdev-cellguide-pipeline-cg-pipeline%2Fdefault%2F12d766f7563e4ca196167e39ed29379f)

chore(cellguide): handle s3 upload and file checking for rdevs

---

frontend/src/views/CellGuide/components/common/OntologyDagView/index.tsx

- Previously, when selecting a tissue, we were filtering the DAG in a CellGuide Card by taking the intersection of the expanded nodes in the Tissue tree and the expanded nodes in the Cell tree. This led to invalid tree states with the target cell type being collapsed for certain tissues.
- In retrospect, there was no justification for choosing to intersect the expanded nodes in the tree DAG and the cell type DAG.
- The correct approach is to use the cell tree state but inject tissue counts into the tree state. This activates logic used for pruning subtrees that do not belong in the tissue (which was previously only being used in the tissue card DAGs).

feat(cellguide): improve DAG filtering by tissue

---

tests/functional/backend/corpora/test_api.py

- This test is failing as deployed_version is not working. Skipping it to unblock deployments. [It should be re-added once the feature is fixed](https://github.com/chanzuckerberg/single-cell-data-portal/issues/5664).

chore: skip failing functional test

---

frontend/src/common/hooks/useCategoryFilter/common/selectUtils.ts
frontend/src/components/common/Filter/common/entities.ts
frontend/src/components/common/Filter/components/FilterContent/components/FilterMenu/index.tsx
frontend/src/components/common/Filter/components/FilterContent/index.tsx

- [#556](https://github.com/chanzuckerberg/single-cell/issues/556)
- Modified filter menu to position "pinned" values to the bottom of the list.

feat: updated publication filter ui (#556)

---

frontend/src/views/WheresMyGene/components/HeatMap/style.ts
frontend/src/views/WheresMyGene/components/HeatMap/utils.ts
frontend/src/views/WheresMyGeneV2/components/HeatMap/index.tsx
frontend/src/views/WheresMyGeneV2/components/HeatMap/style.ts

1. Add divider
1. No divider in PNG/SVG
PNG:
SVG:

feat: heatmap divider

---

frontend/src/common/analytics/index.ts

- [Context](https://czi-sci.slack.com/archives/C0244PQK934/p1694004494357189?thread_ts=1693949072.510159&cid=C0244PQK934)
Not sure why window.plausible started erroring with the "not a function" TypeError during playwright tests..But this should fix it.

fix(e2e): add try-catch to ignore plausible errors in playwright tests

---

.happy/config.json

When cleaning up an rdev environment sometime the ECS task would be left running. This will get expensive as we mmake more rdev environments.
This work is related to https://github.com/chanzuckerberg/single-cell-data-portal/issues/5439
- add enable_dynamo_locking to prevent race conditions when cleaning up rdev environments
- create an rdev and break it down.

fix(happy): prevent orphaned ECS tasks

---

frontend/src/components/common/SideBar/index.tsx
frontend/src/views/WheresMyGene/common/store/reducer.ts
frontend/src/views/WheresMyGene/components/HeatMap/components/XAxisChart/index.tsx
frontend/src/views/WheresMyGene/components/HeatMap/components/XAxisChart/style.ts
frontend/src/views/WheresMyGene/components/HeatMap/index.tsx
frontend/src/views/WheresMyGene/components/Main/index.tsx
frontend/src/views/WheresMyGeneV2/common/constants.ts
frontend/src/views/WheresMyGeneV2/components/GeneSearchBar/index.tsx
frontend/src/views/WheresMyGeneV2/components/GeneSearchBar/style.ts
frontend/src/views/WheresMyGeneV2/components/HeatMap/index.tsx
frontend/src/views/WheresMyGeneV2/components/Main/index.tsx

- #5703 
1. Update GeneSearchBar to be `position: fixed`, so it can be sticky even when we scroll the x axis
1. To support fixed position, we actually need to pass the expand/collapse sidebar width to the search bar, so it can update the `left: px` value dynamically
1.  Go to: https://localhost:3000/gene-expression?genes=TSPAN6%2CTNMD%2CDPM1%2CSCYL3%2CC1orf112%2CFGR%2CCFH%2CFUCA2%2CGCLC%2CNFYA%2CSTPG1%2CNIPAL3%2CLAS1L%2CENPP4%2CSEMA3F%2CCFTR%2CANKIB1%2CCYP51A1%2CKRIT1%2CRAD52%2CMYH16%2CBAD%2CLAP3%2CCD99%2CHS3ST1%2CAOC1%2CWNT16%2CHECW1%2CMAD1L1%2CLASP1%2CSNX11%2CTMEM176A%2CM6PR%2CKLHL13%2CCYP26B1%2CICA1%2CDBNDD1%2CALS2%2CCASP10%2CCFLAR%2CTFPI%2CNDUFAF7%2CRBM5%2CMTMR7%2CSLC7A2%2CARF5%2CPOLDIP2%2CAK2%2CCD38%2CFKBP4%2CKDM1A%2CRBM6%2CCAMKK1%2CRECQL%2CVPS50%2CHSPB6%2CARHGAP33%2CNDUFAB1&ver=2
2. …

fix: 5703 XAxis label overflow

---

frontend/src/components/Collections/common/utils.ts
frontend/src/views/Collection/index.tsx

- #5004
- Updated redirect on view of withdrawn collection to collections page (instead of home page).
- Updated toast text.
1. Delete collection
1. View deleted collection
1. Confirm browser redirects to collections page and pops toast with updated text

fix: redirect withdrawn collection to collections

---

backend/curation/api/curation-api.yml
backend/curation/api/v1/curation/collections/common.py
backend/layers/common/entities.py
backend/layers/processing/process_download_validate.py
backend/portal/api/portal-api.yml
backend/portal/api/portal_api.py
tests/unit/backend/layers/api/test_curation_api.py
tests/unit/backend/layers/api/test_portal_api.py
tests/unit/backend/layers/business/test_business.py
tests/unit/backend/layers/common/base_test.py
tests/unit/processing/test_extract_metadata.py

- [this is part of the work to automate the hero numbers on the landing page](https://docs.google.com/document/d/1UIw-nyNmRF6ob46WLOnxXhyT46J-jcEglzJ9bxGV2BU/edit).
- add primary cell count field to curation and data portal apis
- update extract metadata with primary cell count
- tests pass
- @brianraymor to check [rdev](https://primary-cell-count-backend.rdev.single-cell.czi.technology/)

feat(dp): add primary cell count to dataset metadata

---

frontend/src/common/queries/filter.ts
frontend/src/views/Landing/index.tsx

- The primary cell counts were added to the DB and exposed in datasets/index.
- Future work will move this logic into a backend endpoint.
- This work hooks up the landing page to the datasets/index and aggregates the required hero numbers

feat(landing): hook up hero numbers to datasets/index

---

frontend/src/views/CellGuide/components/CellGuideCard/components/MarkerGeneTables/constants.ts
frontend/src/views/CellGuide/components/CellGuideCard/components/MarkerGeneTables/hooks/canonical_markers.ts
frontend/src/views/CellGuide/components/CellGuideCard/components/MarkerGeneTables/hooks/computational_markers.ts
frontend/src/views/CellGuide/components/CellGuideCard/components/MarkerGeneTables/index.tsx
frontend/src/views/CellGuide/components/CellGuideCard/components/SourceDataTable/hooks/useDataSourceFilter.ts
frontend/src/views/CellGuide/components/CellGuideCard/components/SourceDataTable/index.tsx
frontend/src/views/CellGuide/components/CellGuideCard/index.tsx

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5671
updates only the view layer mapping `organsMap` to `sdsOrgansList`, which we use for display in the dropdown. also adds some logic to `handleChangeOrgan` to make sure we're mapping back from "tissue agnostic" to "all tissues" for setting the selected organ id + tracking the analytics event
checked T cell which actually has canonical/computational markers now!

feat: use the string "tissue agnostic" instead of "all tissues"

---

frontend/src/views/CellGuide/components/CellGuideCard/style.ts

Some overflow scrolling was breaking the sticky (fixed) header in cellguide card pages.
Fixed by changing `width` to max-width and updating the left position of the sticky header in accordance.

fix(cellguide): fix mobile view tooltip and sticky header

---

frontend/src/views/CellGuide/components/common/OntologyDagView/index.tsx

- #5671 
Tooltip now reads as before the regression:

fix(cellguide): update tooltip to read "in all tissues" instead of "in tissue agnostic"

---

frontend/src/common/queries/wheresMyGene.ts
frontend/src/views/WheresMyGene/common/store/actions.ts
frontend/src/views/WheresMyGene/common/store/reducer.ts
frontend/src/views/WheresMyGeneV2/components/HeatMap/index.tsx

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5716
adds a new field filteredCellTypeIds to the state, which we then pass in to WMG under `cell_type_ontology_ids`
https://github.com/chanzuckerberg/single-cell-data-portal/assets/5653616/6327a7a0-ccf3-4c24-b470-546fef7b9053

fix: secondary filters in gene expression

---

frontend/src/views/WheresMyGene/common/constants.ts
frontend/src/views/WheresMyGeneV2/components/GeneSearchBar/components/SaveExport/index.tsx
frontend/src/views/WheresMyGeneV2/components/GeneSearchBar/components/SaveExport/svgUtils.ts

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5656
- added constant for svg spacing
- added font weight attribute
- slight indentation for expanded cell types
- select genes, click the download button, select svg
https://github.com/chanzuckerberg/single-cell-data-portal/assets/7976579/95643b85-44b1-4992-8b54-79d5c91f9b15

fix: spacing and styling for svg

---

frontend/src/views/CellGuide/components/common/OntologyDagView/components/Legend/index.tsx
frontend/src/views/CellGuide/components/common/OntologyDagView/components/Legend/style.ts
frontend/src/views/CellGuide/components/common/OntologyDagView/components/Node/components/RectOrCircle/style.ts

foreignObject is apparently broken in safari ([context](https://stackoverflow.com/questions/51313873/svg-foreignobject-not-working-properly-on-safari)). It breaks when one of its child elements has `position` set. See screenshot
This fixes that bug by removing `position: relative` from `NodeWrapper` (which is unnecessary in the SVG) and adding back it for the legend!

fix(cellguide): work around foreignObject bug in safari

---

frontend/tests/features/wheresMyGene/landingPageFilter.test.ts

- bug: https://github.com/chanzuckerberg/single-cell-data-portal/issues/5716
- fix: https://github.com/chanzuckerberg/single-cell-data-portal/issues/5725
- ticket: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5761
- added test to ensure that cell type filter cross-filters with the left side bar filters

test(WMG): test cell type filter cross-filters with secondary filters

---

frontend/tests/features/wheresMyGene/wheresMyGene.test.ts

- We have a couple failing e2e tests in main. This PR fixes them.
- `dev` only has one FE/BE task now, so it is slower. The compare test originally cycled through all the compare options, but this takes too long and the test times out (especially now that queries take longer after WMGv2). The solution for now is to only test one of the compare options as the risk of the other options not working if the tested one does is low as they all operate through the same code path.
- The CSV download test fails because the download triggers before the heatmap finishes rendering. I think?
- Green checkmark!

fix(wmg): fix failing wmg e2e tests in main branch

---

tests/functional/backend/corpora/test_revisions.py

- check the status of the request response before parsing it.
- Modify test_revision_flow subtest to verify the status before parsing the response
- This is modifying a tests to give more useful information than before. The test is already failing. This will help us figure out why.

fix(functional tests): check status before parsing

---

.github/workflows/deploy-happy-stack.yml
Makefile

- smoke tests needs AWS secrets to run. Install chamber in GHA to retrieve secrets.
- Add make recipe to make it easier to verify backend smoke-tests work.
- Ran `$ DEPLOYMENT_STAGE=dev make backend-smoke-test`

fix(cicd): Use chamber to pass secrets to the smoke test

---

.github/workflows/rdev-update-for-pr.yml

- There are cases where the rdev is not created when a PR is opened. Subsequent commits will fail to update the rdev because it doesn't exists. The deployment summary will never be applied because that happens when the PR is first opened. This ticket addresses these issues.
- rename "create rdev" to "deploy rdev". This makes it easier to find in the list of GHA and describes both creation and update operations.
- use `create-or-update` in fromt he Deploy-happy GHA. This will update or create an happy environment depending on if it exists or not.

 fix(cicd): Use create-or-update operation from happy to manage rdev

---

.github/workflows/push-rdev.yml

- push-rdev.yml is running out of space during build. This is the same [issue](https://github.com/chanzuckerberg/single-cell-data-portal/pull/5759) that was affecting the deployment of dev.
- build the image using the matrix build strategy
- look at the Push Remote Dev/ build-push-images GHA job

fix(rdev): Parallel build for push-rdev.yml

---

.github/workflows/lint-pr.yml

- The default has more options and reduce the configuration we need to manager.
- allow all conventional commit types

feat(cicd): allow all conventional commit types

---

backend/curation/api/v1/curation/collections/common.py
backend/layers/business/business.py
backend/layers/business/business_interface.py
backend/layers/business/entities.py
backend/portal/api/portal-api.yml
backend/portal/api/portal_api.py
tests/unit/backend/layers/api/test_portal_api.py
tests/unit/backend/layers/business/test_business.py

- #5758
- Added GET dataset asset endpoint that reuses existing Discover API functionality to calculate file size and permanent URL. (Supersedes POST dataset asset endpoint that generates pre-signed URL.)
- Modified Discover API's `extract_dataset_assets`: moved permanent URL builder code to business layer for reuse.
- Added unit tests to `test_portal_api` and `test_business` test suites.
- Tested in rdev by hitting new GET endpoint and:
- confirming file size matches existing POST file size for same asset, and,
- confirming permanent URL yields download.

feat: added get asset with permanent url.

---

tests/unit/cellguide_pipeline/test_ontology_tree.py

- Accidentally merged in a debugging line added to one of the cellguide pipeline unit tests in #5825

fix: remove debugging line in ontology tree unit test

---

frontend/src/common/queries/cellGuide.ts
frontend/src/pages/cellguide/[cellTypeId].tsx

- CellGuide pipeline was updated to generate SEO descriptions as strings, not dictionaries. Because SEO descriptions are only generated when new cell types are added, most of the SEO descriptions are still dictionaries. Newer cell types (like [this one](https://cellxgene.cziscience.com/cellguide/CL_4030026)) store the SEO descriptions as strings, leading to an error in parsing the server side props and undefined names.
- This PR updates the frontend server to get the cell type names from the `celltype_metadata.json` and updates the CellGuide query module to expect strings for the GPT SEO description.
- Once this is deployed, the old GPT SEO descriptions will be migrated to the correct format (strings).

fix(cellguide): server side props for seo description

---

frontend/src/common/queries/cellGuide.ts
frontend/src/pages/cellguide/[cellTypeId].tsx

- CellGuide pipeline was updated to generate SEO descriptions as strings, not dictionaries. Because SEO descriptions are only generated when new cell types are added, most of the SEO descriptions are still dictionaries. Newer cell types (like [this
one](https://cellxgene.cziscience.com/cellguide/CL_4030026)) store the SEO descriptions as strings, leading to an error in parsing the server side props and undefined names.
- This PR updates the frontend server to get the cell type names from the `celltype_metadata.json` and updates the CellGuide query module to expect strings for the GPT SEO description.
- Once this is deployed, the old GPT SEO descriptions will be migrated to the correct format (strings).
- If the reason for this PR's code changes are not clear in the issue, …

fix(cellguide): server side props for seo description (#5832)

---

frontend/tests/features/wheresMyGene/landingPageFilter.test.ts

1. Update locator to use `page.getByRole("option")`, since `page.locator("option")` was getting 3 local development only React Query tool elements

test: Fix e2e filter test

---

.happy/terraform/modules/ecs-stack/main.tf
.happy/terraform/modules/service/main.tf
Dockerfile.backend
backend/api_server/app.py
backend/wmg/api/v2.py
container_init.sh
requirements-backend.txt
tests/unit/backend/layers/common/test_auth0_manager.py

The purpose of this PR is to integrate datadog for APM. When this PR is merged, we should be able to see the most essential APM metrics in datadog dashboards. **NOTE**: Deploying this PR will automatically enable datadog metrics collection for `staging`, `prod`.
- This PR builds on earlier work. A POC specified in #5297 with a [draft PR](https://github.com/chanzuckerberg/single-cell-data-portal/pull/3610)
- This PR will emit metrics for WMG API endpoints as stated in #1965 
- add terraform to integrate datadog agent
- start `gunicorn` server in docker with datadog integration
- add decoration of WMG api functions with datadog tracer
- Manual testing by verifying that metrics get displayed in datadog dashboards:
- RDEV to invoke API calls to the backend and collect datadog metrics: …

feat: Integrate datadog for APM

---

.happy/terraform/envs/dev/main.tf

Tentatively fixes test load issues by scaling up to 2 backend containers.

chore: scale dev backend instances to 2

---

.happy/terraform/envs/dev/main.tf

Unblock e2e tests with even more resources.

chore: scale dev backend instances to 4

---

.github/workflows/rdev-delete-for-pr.yml
.github/workflows/rdev-update-for-pr.yml
backend/layers/processing/h5ad_data_file.py

-  There is a chance the rdev environment can get into an unknown state if multiple happy updates are run on the same environment concurrently. This PR adds some locking to prevent happy from running for the same rdev in different GHA at the same time. 
- add concurrency locking of the happy update/delete jobs to prevent concurrent happy modification.
- Created an rdev using a PR. Adding additional commits and check that the GHA triggered by the latest commit waited for the previous GHA to finish.

fix: Add concurrency to rdev managing GHAs

---

requirements-processing.txt

- #5907
- modify scanpy version in processing requirements. 1.6.0 -> 1.9.3
- Processing tests are no longer broken

fix: bump processing scanpy version 1.6.0 -> 1.9.3

---

frontend/tests/features/wheresMyGene/tissueAutoExpand.test.ts

This PR is Part 2 of Tissue Auto Expand test coverage. Part 1 was merged [here](https://github.com/chanzuckerberg/single-cell-data-portal/pull/5884).
[Add extensive test coverage for tissue expansion 5827
](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5827)

test(wmg): additional test coverage for tissue auto expand 5827

---

backend/portal/api/portal_api.py
tests/unit/backend/layers/api/test_portal_api.py

- #5858
- Added `consortia` to collections index and user collections index responses.
- Updated unit tests.
- Tested manually in [rdev](https://mim-consortia-e2e-i-frontend.rdev.single-cell.czi.technology/collections).

feat: added consortia to collections index.

---

.github/workflows/build-images-and-create-deployment.yml
.github/workflows/deploy-happy-stack.yml
.github/workflows/merge-main-into-staging.yml
.github/workflows/trigger-release-candidate-build-and-deploy.yml

- #5461
The idea is that we can leverage our existing workflow where a commit to `staging` branch creates a deployment to the `stage` environment. So, whenever new commits to `main` come in, we merge the commit to `staging` thus kicking off a deployment to `stage` environment.
Additionally, github action's [concurrency group feature is utilized](https://docs.github.com/en/actions/using-jobs/using-concurrency) to eliminate race conditions involving multiple builds and deployments run at the same time. Here, we cancel scheduled builds and deployments as well as currently running builds and deployments in favor of the newest build/deployment job.
- add merging `main` branch to `staging` branch on new commits to `main`
- add GHA concurrency group feature
- The following workflow was used to …

feat: Auto merge and deploy to staging branch

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/CreateCollectionModal/components/Content/index.tsx

- #5950
- ~Modified the consortia dropdown `onChange` function `handleConsortiaChange` to a memoized function.~
- Updated `czi-sds` package to `v18.1.2`.
*Background*
Currently, editing a collection is unavailable due to a bug that causes the page to freeze or return an error: "Application error: a client-side exception has occurred (see the browser console for more information)".
The bug was introduced with an upgrade of `czi-sds` package version; specifically the package upgrade introduced a defect in the consortia dropdown functionality in the [create / edit collection](https://github.com/chanzuckerberg/single-cell-data-portal/blob/fe226f5f20ef7ff5690ddf47e3add9bae082a040/frontend/src/components/CreateCollectionModal/components/Content/index.tsx#L217) component.
Between versions …

fix: Edit collection is broken (#5950)

---

frontend/src/common/networkGuard.ts
frontend/src/pages/_app.tsx
frontend/src/views/WheresMyGene/components/Filters/components/Compare/connect.ts
frontend/tests/README.md
frontend/tests/common/playwright.global.preSetup.ts
frontend/tests/common/test.ts
frontend/tests/features/cellGuide/cellGuide.test.ts
frontend/tests/features/collection/util.test.ts
frontend/tests/features/filter/filter.test.ts
frontend/tests/features/filter/selectUtils.test.ts
frontend/tests/features/filter/useCategoryFilter.test.ts
frontend/tests/features/filter/utils.test.ts
frontend/tests/features/home/homePage.test.ts
frontend/tests/features/terms/tosAndPrivacy.test.ts
frontend/tests/features/wheresMyGene/cellTooltip.test.ts
frontend/tests/features/wheresMyGene/downloadCsv.test.ts
frontend/tests/features/wheresMyGene/landingPage.test.ts
frontend/tests/features/wheresMyGene/manageGene.test.ts
frontend/tests/features/wheresMyGene/rightSideBar.test.ts
frontend/tests/features/wheresMyGene/shareLink.test.ts
frontend/tests/features/wheresMyGene/tissueAutoExpand.test.ts
frontend/tests/features/wheresMyGene/wheresMyGene.test.ts

- #5940
1. Add a network guard in `window.fetch()` to catch excessive API calls
2. Add network guard in every e2e test to detect excessive API calls, so we're aware of it in test logs
1. Temporarily change `handleChange()` in frontend/src/views/WheresMyGene/components/Filters/components/Compare/connect.ts to depend on `optionLabel`, which will generate a new `handleChange` function every time `optionLabel` changes. Which is the crux of the infinite loop
2. Navigate to https://localhost:3000/gene-expression?compare=disease&sexes=PATO%3A0000383&tissues=blood%2Clung&genes=DPM1%2CTNMD%2CTSPAN6&ver=2
3. Observe console that it will now throw many "Too many API calls" errors, but the `network` tab will stop making requests

feat: Add network guard

---

.github/workflows/push-rdev.yml
.github/workflows/push-tests.yml
.github/workflows/rdev-update-for-pr.yml

- #5971 
- Delete previous image version from ECR for a given PR/stack, for all ECR repos, after successful happy push of a new image version.
- Reintroduce unique sha-based image tags for all images.

fix: failing rdev updates

---

.github/workflows/rdev-update-for-pr.yml
frontend/tests/features/collection/revision.test.ts
scripts/smoke_tests/setup.py
tests/functional/backend/common.py

This commit modifies the BaseFunctionalTestCase class to allow the caller to specify a `smoke_tests` flag. If True, the class will initialized (seed) the data using the test account for smoke tests, which is user@example.com, instead of the test account for functional tests, which is functest@example.com
- #5666 
- Use the test user account `user@example.com` (rather than the functional test user account `functest@example.com`) to seed the database ahead of smoke tests
- Reinstate the e2e tests that are dependent on the seeded Collections being created with the test user account `user@example.com`
- Describe how you made sure to know that your changes worked. Should allow someone else to go verify your code without in depth …

test: use smoke test account to seed db for smoke tests

---

.github/workflows/rdev-update-for-pr.yml

- Forgot to include AWS credentials 
- Was referencing a job output incorrectly
- verified that ECR images are deleted on subsequent pushes ✅

chore: fix 'deletion of previous images' GHA

---

.github/workflows/build-images-and-create-deployment.yml

To freeze the dev environment while pentesting happens.
- only deploy staging and prod in GHA
This will be reverted after pentesting concludes

chore: Disable redeploying the dev environment for pentest

---

frontend/src/common/constants/routes.ts
frontend/src/pages/api/deployed_version.ts
frontend/tests/features/api/deployedVersion.test.ts

- #5848 
1. Add `COMMIT_SHA` to `/api/deployed_version`, so we can query it like so: https://pr-6002-frontend.rdev.single-cell.czi.technology/api/deployed_version
2. Add e2e test for this
1. Navigate to https://pr-6002-frontend.rdev.single-cell.czi.technology/api/deployed_version, you should see something like: `{"Data Portal":"0d27c97a65ef30d8afa8df3920f4c75a8aff0c43"}`

feat: 5848 FE add deployed version

---

frontend/tests/features/wheresMyGene/wheresMyGene.test.ts

revert temp fix for newsletter validate email from 
`emailInput.fill(" ")`  to `emailInput.fill("")`

fix(wmg): newsletter test revert to empty string

---

.github/workflows/test-receiving-repository-dispatch.yml
.github/workflows/test-sending-repository-dispatch.yml

- This to test `repository_dispatch` call
- Manual testing by pushing to another feature branch `psridharan/trigger-stage-deploy` and seeing that the `repository_dispatch` event gets sent by the `psridharan/trigger-stage-deploy` branch

feat: Test repository_dispatch call for github actions

---

.github/workflows/test-sending-repository-dispatch.yml

Testing `repository_dispatch` invocation by pushing to `main`
- add
- remove
- modify
- On merge to `main` we should see the sending and receiving of `repository_dispatch` call on the `Actions` page

chore: Test repository_dispatch trigger on push to main

---

.github/workflows/build-images-and-create-deployment.yml
.github/workflows/deploy-happy-stack.yml
.github/workflows/push-tests.yml
.github/workflows/trigger-release-candidate-build-and-deploy.yml

- #5461 
- Use `repository_dispatch` to trigger a `stage` environment deploy after `main` is auto-merged to `staging` branch
- add `repository_dispatch` calls to workflow
- Manually done on this PR branch or `main`

feat: Trigger staging deployment on auto-merge to staging branch

---

.github/workflows/build-images-and-create-deployment.yml

When `repository_dispatch` event is sent for event `build-images`, the `build-images-and-create-deployment.yml` file has a step to checkout the current `${{ github.ref }}`. This turns out the be the `main` branch because it is the branch _that emitted the `repository_dispatch` event_. 
_That is not what we want!_. For the `build-images` event, the `payload` contains a `ref`. This `ref` turns out to be `staging` because the event is emitted in workflow that is the starting point for a `stage` deploy.
Manually test in `main`

fix: Get the ref to checkout from repository_dispatch payload

---

backend/common/utils/color_conversion_utils.py
tests/unit/backend/layers/utils/test_color_conversion_utils.py

- https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-explorer/643
- we want to update the colors to use label fields instead of term fields. when i started working on this in explorer, i found that the colors API would return the left side for term fields, and the right side for label fields
- so instead of changing how we load colors in explorer, the correct fix is to alter how we set the colors metadata when we do the CXG conversion
- i wrote the following python notebook to generate all necessary fixtures. `liver.h5ad` is just the [smallest dataset we have in prod](https://cellxgene.cziscience.com/collections/44531dd9-1388-4416-a117-af0a99de2294) that contains liver cells.
```
import anndata
import numpy as np
from …
```

feat: update cxg conversion to use label colors

---

backend/wmg/pipeline/constants.py
backend/wmg/pipeline/expression_summary.py

feat(wmg): implement gene length normalization

---

.github/workflows/test-workflow-run-after-push-tests-pass.yml

- Pertains to #5461 
Test that a workflow only runs on `main` branch after `push_tests.yml` runs `main` branch
- add
- remove
- modify
Manual testing on `main` branch

chore: TEST workflow_run trigger on push_tests

---

frontend/src/views/WheresMyGene/components/HeatMap/components/YAxisChart/style.ts
frontend/src/views/WheresMyGene/components/HeatMap/style.ts
frontend/src/views/WheresMyGeneV2/components/HeatMap/components/YAxisChart/index.tsx
frontend/tests/features/wheresMyGene/tissueAutoExpand.test.ts
frontend/tests/utils/wmgUtils.ts

- #5416 
1. Use `TagFilter` for cell type filter tag
2. Update tissue label font weight based on `expanded`
1. Go to rdev
2. Select some cell types and see the new styled tags
3. Collapse a tissue, the tissue name should no longer be bold

fix: 5416 GE quick fixes

---

.github/workflows/build-images-and-create-deployment.yml
.github/workflows/trigger-release-candidate-build-and-deploy.yml

- Pertains to #5461 
Remove `staging` branch as a trigger to `build-images-and-create-deployment.yml` because `trigger-release-candidate-build-and-deploy.yml` will invoke a _staging deploy_ through continous deployment mechanism
Manual testing in `main` branch

chore: Remove staging branch trigger to build images

---

frontend/src/common/queries/wheresMyGene.ts
frontend/src/common/utils/removeParams.ts
frontend/src/components/Collections/common/utils.ts
frontend/src/components/CreateCollectionModal/index.tsx
frontend/src/views/Collection/index.tsx
frontend/src/views/WheresMyGene/common/store/reducer.ts
frontend/src/views/WheresMyGeneV2/components/GeneSearchBar/components/ShareButton/index.tsx
frontend/src/views/WheresMyGeneV2/components/GeneSearchBar/components/ShareButton/utils.tsx
frontend/src/views/WheresMyGeneV2/components/HeatMap/connect.ts
frontend/src/views/WheresMyGeneV2/components/HeatMap/hooks.ts
frontend/src/views/WheresMyGeneV2/components/HeatMap/index.tsx
frontend/src/views/WheresMyGeneV2/components/HeatMap/types.ts
frontend/tests/features/wheresMyGene/downloadCsv.test.ts
frontend/tests/features/wheresMyGene/shareLink.test.ts
frontend/tests/features/wheresMyGene/tissueAutoExpand.test.ts
frontend/tests/utils/wmgUtils.ts

- #5936 
1. CellTypes in share link will now auto expand tissues
2. BONUS: Fix extra bug that cellTypes in share link doesn't result in cellTypeIds in `/filters` API request
3. Add corresponding tests to cover both bugs above
4. EXTRA BONUS: Refactor Heatmap component to use Ronen Pattern™️ 
1. Visit https://pr-6050-frontend.rdev.single-cell.czi.technology/gene-expression?genes=TSPAN6%2CTNMD%2CDPM1&ver=2&cellTypes=B+cell%2CB-1a+B+cell
2. The tissues should be expanded like so:
3. API call should include cellTypeIds too

fix: 5936 cell type share link auto expand

---

backend/wmg/data/schemas/cube_schema_default.py
scripts/populate_rdev_with_cellguide_data.sh
scripts/populate_rdev_with_wmg_data.sh

- Using hilbert ordering for the expression summary default cube was bad for performance once after the WMGv2 changes to the backend. This reverts the schema to be row-ordered like the full expression summary cube.

chore(wmg): improve default wmg cube schema

---

frontend/tests/features/collection/revision.test.ts

1. e2e collection revision test was timing out at 30 mins, because there's a bug in the waitUntil block logic that triggers a 5 min wait every time it can't find a suitable collection

test: Update collection revision e2e test timeout

---

.github/workflows/clean_happy_rdev.yml

This PR fixes a broken JSON field when trying to get the stacks using jq. This was fixed in the latest version of this action, so we are just updating the action. Here is the fix notes: https://github.com/chanzuckerberg/github-actions/pull/212. The action will still print an error about validations, but this is just a print statement and shouldn't affect anything.
- https://czi-tech.atlassian.net/browse/ONCALL-635?atlOrigin=eyJpIjoiNWE3YzUyZmVhMTNjNGE1OTliOGE3MGMyYTY1NGQyMWMiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
- The cleanup aciton stopped working
* Used a local ubuntu image to test the `jq` string does what we expect. Looks like with this update, there are at least 4 stacks that should be cleaned.

fix: happy validating terraform that doesn't exist for single-cell

---

backend/common/utils/rollup.py
backend/wmg/api/common/rollup.py
backend/wmg/api/v2.py
backend/wmg/data/snapshot.py
tests/unit/backend/wmg/api/common/test_rollup.py
tests/unit/backend/wmg/api/test_v2.py
tests/unit/backend/wmg/fixtures/test_snapshot.py

There are two performance improvements included in this PR.
- Update build_ordered_cell_types_by_tissue to iterative over numpy arrays instead of pandas DataFrame rows.
- This reduces runtime from 8s to 50ms for large queries.
- Re-write the gene expression rollup function. Instead of rolling up a tidy pandas dataframe, the dataframe is reshaped into a 2D numpy array per numeric column, where the rows correspond to groups excluding gene and the columns correspond to genes. Rollup is performed on this 2D array and then reshaped into a pandas dataframe.
- This also includes a performance optimization to find_descendants_per_cell_type where a hash table is used to store descendants for cell types so that the operation does not need to be needlessly repeated.
- This reduces runtime for …

feat(wmg): performance improvements

---

frontend/src/common/queries/wheresMyGene.ts
frontend/src/views/WheresMyGene/components/InfoPanel/components/RelativeGeneExpression/index.tsx
frontend/src/views/WheresMyGeneV2/components/CellInfoSideBar/index.tsx
frontend/tests/features/wheresMyGene/rightSideBar.test.ts

- When splitting up #5999, I forgot to port over changes in the FE for the new response from the marker genes endpoint. 
- E2E tests pass
- Confirmed fix in rdev

fix(wmg): update marker gene sidebar to match new endpoint response

---

backend/curation/api/v1/curation/collections/collection_id/s3_upload_credentials.py

The UploadKeyPrefix that is returned in response to GET /s3-upload-credentials needed to be reconfigured specifically for the rdev use-case, because in order to satisfy IAM permissions, the user must come before the stack name:
- old prefix format: {rdev_prefix}/{user}/{collection_id}
- new prefix format: {user}/{rdev_prefix}/{collection_id}
- #6010 
- modify `UploadKeyPrefix` attribute in response for s3 upload credentials request

fix: reconfigure s3 upload key prefix to work for rdev

---

frontend/src/common/theme.ts
frontend/src/components/common/Button/index.tsx
frontend/src/views/WheresMyGene/common/store/reducer.ts
frontend/src/views/WheresMyGene/common/store/selectors.ts
frontend/src/views/WheresMyGeneV2/components/Filters/components/Organism/components/Dialog/index.tsx
frontend/src/views/WheresMyGeneV2/components/Filters/components/Organism/components/Dialog/style.ts
frontend/src/views/WheresMyGeneV2/components/Filters/components/Organism/connect.ts
frontend/src/views/WheresMyGeneV2/components/Filters/components/Organism/index.tsx
frontend/tests/common/constants.ts
frontend/tests/features/wheresMyGene/selectOrganism.test.ts
frontend/tests/features/wheresMyGene/tissueAutoExpand.test.ts
frontend/tests/features/wheresMyGene/wheresMyGene.test.ts

- #5777
1. Add a few more design token functions in `frontend/src/common/theme.ts`
2. Add SC Button in `frontend/src/components/common/Button/index.tsx`
3. Update `selectOrganism` reducer to fix bug (same fix as in Seve's PR)
4. Add a new selector `selectHasCustomFiltersOrGenesSelected` to detect when the redux state is dirty and need to pop the confirm modal
5. Add Confirm Dialog (frontend/src/views/WheresMyGeneV2/components/Filters/components/Organism/components/Dialog/index.tsx)
6. Update `Organism/connect.ts` to use a new state `pendingOrganism` as a placeholder, so if the user cancel the confirm dialog, it won't dispatch an action to update the organism in the store
7. BONUS: Extract more test constants `frontend/tests/common/constants.ts`
8. Add 10 e2e tests for this feature
The …

fix: 5777 switch organism bug

---

.github/workflows/rdev-update-for-pr.yml

- We always want the summary to print out when a PR is created even if deployment fails
- remove depending con deploy-rdev for summary.

fix: always print summary for PR rdev

---

backend/common/feature_flag.py
backend/curation/api/v1/curation/collections/common.py
backend/layers/processing/process_download_validate.py
backend/portal/api/portal_api.py
tests/functional/backend/common.py
tests/unit/backend/common/test_feature_flag.py
tests/unit/processing/test_extract_metadata.py
tests/unit/processing/test_h5ad_data_file.py

The goal of this is to provide a lightweight layer for us to access feature flags set up in `CorporaConfig`. This will allow us to, if we ever desire to, swap out the underlying implementation of feature flags. I provided some basic documentation within `feature_flag.py` for how to use this.
Feature flags use a design pattern called string literals. String literals use the `Literal` provided in Python typing to ensure type strictness similar to enums. Since `FeatureFlagService.is_enabled` requires passing in a `FeatureFlag` type, we can ensure that only strings that exist within this `Literal` are allowed. Since they're simply strings, they can be easily passed into functions like `getattr(CorporaConfig(), feature_flag)` without needing to convert between strings and enums.
- Adds the …

feat: Add lightweight FeatureFlagService

---

backend/wmg/api/v2.py
backend/wmg/data/utils.py
tests/unit/backend/wmg/api/common/test_wmg_api_helpers.py
tests/unit/backend/wmg/api/test_v2.py
tests/unit/backend/wmg/fixtures/test_snapshot.py

- https://github.com/chanzuckerberg/single-cell/issues/596
A consequence of including comma-delimited ontology term ID values for `self_reported_ethnicity_ontology_term_id` to encode mixed ethnicities is that _data including such ethnicity values must be excluded when filtering or grouping by `self_reported_ethnicity_ontology_term_id`_. This is the functional requirement indicated in the ticket above.
- Add functions to filter input datastructures that might be associated with `self_reported_ethnicity_ontology_term_id` values that contain comma-delimited values
- Unit tests

feat(schema4): Filter out comma-delimited ethnicity term IDs from input datastructures

---

backend/wmg/pipeline/expression_summary_and_cell_counts.py
tests/test_utils/mocks.py

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/526
updates the census parameters to filter on `tissue_type == tissue`, and also filters out the system-level UBERON terms
We can't test the `tissue_type` filter until schema 4 is in census, so the best we can do is hide the logic behind a feature flag and test in staging once we start the schema 4 migration there. I was able to verify that the tissue portion of the filter worked by running this script locally:
```
import cellxgene_census
import tiledbsoma as soma
def main():
with cellxgene_census.open_soma() as census:
human = census["census_data"]["homo_sapiens"]
with human.axis_query(
measurement_name="RNA",
obs_query=soma.AxisQuery(
value_filter="is_primary_data == True"
)
) as …
```

feat: remove non-tissues from WMG

---

.happy/terraform/modules/schema_migration/main.tf
backend/layers/processing/schema_migration.py

- Make it easier to limit a migration by passing it in as a parameter to the step function
- using one variable LIMIT_MIGRATION to indicate how many collection to process in a migration
- accept limit_migration as a parameter to the step function to limit how many collections are migrated.
- tested by running a schema_migration SFN with
```
{
"limit_migration": "10"
}
```

fix: Make it easier to limit a migration by passing as parameter

---

frontend/src/views/CensusDirectory/index.tsx

The spotlight page had the tier filter inverted for maintained + community projects

fix(spotlight): fix tiers on directory

---

frontend/src/components/Datasets/components/DownloadDataset/style.ts

- #6175
- Added a minimum height to the download dataset modal to prevent jiggle between download state (i.e. toggle between selection of format type).
- Use feature flag `dux=true`.

feat: Update dataset download modal height to prevent jiggle (#6175)

---

frontend/src/views/WheresMyGeneV2/components/HeatMap/connect.ts

- #6006
How to test:
- cell types with count < 10 should be omitted from the list/heatmap

chore(wmg): GE hide cells with under 10 count

---

frontend/src/views/WheresMyGeneV2/components/HeatMap/hooks/useSortedCellTypesByTissueName.ts

- #6110 
- modify
- unshift instead of push tissue labels when sorting rows

fix(wmg): fix tissue labels for hierarchical sort

---

backend/layers/processing/process_validate.py

- https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/579
- Missing compression arg here resulted in h5ad exploding in size after adding citation; we want to save our h5ads with gzip compression
- add compression='gzip' to adata.write call after adding citation post-validation add-labels.
- N/A

fix: use gzip compression after writing citation to h5ad

---

backend/layers/processing/upload_failures/app.py
tests/unit/processing/test_handle_error.py

- We recently changed the SFN to use collection version ID instead of collection ID. We missed swapping the env var name in the slack failure notification module, therefore failures were being reported with collection version ID as None.

fix: slack dataset failure notification reports collection version ID

---

frontend/src/views/WheresMyGeneV2/common/constants.ts
frontend/src/views/WheresMyGeneV2/components/Filters/components/ColorScale/index.tsx
frontend/src/views/WheresMyGeneV2/components/GeneSearchBar/style.ts
frontend/src/views/WheresMyGeneV2/components/HeatMap/components/XAxisChart/style.ts
frontend/src/views/WheresMyGeneV2/components/HeatMap/components/YAxisChart/style.ts
frontend/src/views/WheresMyGeneV2/components/HeatMap/index.tsx
frontend/src/views/WheresMyGeneV2/components/HeatMap/style.ts
frontend/src/views/WheresMyGeneV2/components/HeatMap/utils.ts

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5837
adds the proposed changes to [gene expression spacing](https://github-production-user-asset-6210df.s3.amazonaws.com/87047537/280899356-bda34806-f8b3-43cd-bae8-35108dcb9e05.png). note that as @karenliang0 notes in the ticket, the changes to shift the alignment of the cell type search bar would be in a separate ticket, so that's not in this PR.
static screenshot to verify pixel padding
easiest way to review would be to just look at the rdev: https://pr-6214-frontend.rdev.single-cell.czi.technology/gene-expression
TODO
i don't think e2e tests are necessary for moving stuff 4 pixels here and there

feat: fix spacing in gene expression

---

.happy/terraform/modules/sfn/main.tf
backend/layers/processing/process_cxg.py

- #6215 
- Recent changes to handling errors in the parallel step caused error handling to only be configured for Seurat failures but not for cxg failures
- add
- remove
- modify

fix: pass cxg errors to be handled in HandleSuccess

---

backend/layers/processing/schema_migration.py

- Test-only bug; previous implementation to run random subset of corpus did not account for filtering out published collections with active revisions. This change moves the subsetting to only sample from the set of collections AFTER filtering out ineligible collections (published w/ active revisions)

fix: option to test schema migration with random subset of corpus

---

backend/common/corpora_config.py
backend/layers/processing/process_download.py
tests/unit/processing/test_process_download.py

- The memory settings for the ingest process are dynamic and can sometimes be off. This results in fail upload. To make it easier to fine tune and adjust the memory setting for ingest, the values have been move into the CorporaConfig. This allow us to quickly change the memory setting for ingest using the corpora config secret. This saves us the need to redeploy prod.
- move ingest memory configuration secret to corpora config
- set default values for the ingest memory configuration
- make all memory calculation based on the number of VCPUs allocated.
- updated tests

feat: quickly modify ingest memory configuration without redeploying,

---

frontend/src/pages/_app.tsx

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/6167
follows the instructions [here](https://plausible.io/docs/proxy/guides/cloudfront) to proxy the plausible script. this is done by setting the script src to be `/js/script.js` and routing `/js/script.js` within cloudfront to plausible. cloudfront distribution is set up:
- in dev https://us-east-1.console.aws.amazon.com/cloudfront/v4/home?region=us-west-2#/distributions/E2AI5EG7QRYE6E/behaviors
- in staging https://us-east-1.console.aws.amazon.com/cloudfront/v4/home?region=us-west-2#/distributions/E1KICGZMYV4YWQ/behaviors
hitting https://pr-6197-frontend.rdev.single-cell.czi.technology/js/script.js will 404, but not sure if the cloudfront things apply to rdevs? it's …

feat: proxy plausible script

---

backend/common/feature_flag.py
tests/unit/backend/common/test_feature_flag.py
tests/unit/backend/layers/api/test_gene_info.py
tests/unit/backend/layers/business/test_business.py
tests/unit/backend/layers/common/base_api_test.py
tests/unit/backend/layers/common/base_test.py
tests/unit/processing/base_processing_test.py
tests/unit/processing/test_extract_metadata.py
tests/unit/processing/test_h5ad_data_file.py
tests/unit/processing/test_process_download.py
tests/unit/processing/test_process_validate.py
tests/unit/processing/test_processing.py

- Fixes tests that are failing because of how CorporaConfig is mocked
- This simplifies how configuration setting are mocked.
- modify how SecretConfig classes are mocked

fix: Use built in set and reset in SecretConfig for testing

---

.happy/terraform/modules/sfn/main.tf
backend/layers/processing/process_download.py

- Retrying seurat, cxg, and validate have never resulted in a passing job. Removing to reveal error sooner.
- Keeping the retry bon download because sometimes the download source is flakey.
- remove try from seurat, cxg, and validate
- Add logging of memory settings. This will help in the future with looking down memory usuage

fix(ingest): Don't retry cxg, seurat, and validate

---

tests/unit/cellguide_pipeline/test_computational_marker_genes.py

- This test passes locally but fails in GHA. Skip this test until it is fixed (#6240)
- add
- remove
- modify

chore: skip failing cg unit test

---

frontend/src/pages/_app.tsx

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/6167
I verified the Plausible script is working as expected in staging and prod. This PR removes the original script which links out to Plausible directly, rather than to the proxy.
See test steps in the Zenhub ticket

feat: removes the original plausible script

---

frontend/src/views/WheresMyGeneV2/components/Main/connect.ts
frontend/src/views/WheresMyGeneV2/components/Main/hooks.ts
frontend/src/views/WheresMyGeneV2/components/Main/index.tsx

- #6054
1. Extract hooks into `connect.ts`
2. Extract `useScaledMeanExpression()` in `hooks.ts`, since it's too damn long 😂 
3. Remove explicit version 2 passing to function argument. Like `useCellTypesByTissueName(2)` to just `useCellTypesByTissueName()`
1. App should work as before

refactor: 6054 Update WMGv2 Main

---

frontend/src/views/WheresMyGeneV2/components/Filters/connect.ts
frontend/tests/features/wheresMyGene/tissueAutoExpand.test.ts

- #5352
- this code is creating a sorted version of publication_citations where any object with a name of "No Publication" is moved to the end, and the rest are sorted alphabetically by name. The sorted array is memoized, so it will only be recomputed when publication_citations changes.

chore: pin no publication to the bottom of publication filter

---

backend/layers/processing/schema_migration.py
tests/unit/processing/schema_migration/test_dataset_migrate.py

- This will make it easier to find datasets that failed during migration.
- modify the sfn name to use the new dataset_version_id
- updated tests

fix: The name of the sfn created uses the new dataset version id

---

frontend/src/views/WheresMyGeneV2/components/Filters/components/Compare/index.tsx
frontend/src/views/WheresMyGeneV2/components/Filters/components/Compare/style.ts
frontend/src/views/WheresMyGeneV2/components/GeneSearchBar/components/SourceDataButton/style.ts
frontend/src/views/WheresMyGeneV2/components/HeatMap/components/YAxisChart/index.tsx
frontend/src/views/WheresMyGeneV2/components/InfoPanel/components/ExpressedInCells/index.tsx
frontend/src/views/WheresMyGeneV2/components/InfoPanel/components/ExpressedInCells/style.ts
frontend/src/views/WheresMyGeneV2/components/InfoPanel/components/Legend/style.ts
frontend/src/views/WheresMyGeneV2/components/InfoPanel/components/RelativeGeneExpression/index.tsx
frontend/src/views/WheresMyGeneV2/components/InfoPanel/components/RelativeGeneExpression/style.ts

- #5838
- Change chevron color from rgb(153, 153, 153) to colors.gray[300]
- Remove “New” tag from “Group By” (P2 since performance is so bad, maybe users will be more understanding)
- Labels for color scale and dot size legends should be aligned with the labels for download, share, and source data.
- check changes in UI

chore: ge style updates

---

frontend/src/components/common/Filter/common/constants.ts

Related to https://github.com/chanzuckerberg/single-cell-curation/pull/698

feat: Update hand-curated list of Cell Classes and Subclasses

---

backend/wmg/pipeline/validation/validation.py

as a result of the changes to exclude system-level tissues from WMG, our expected number of tissues in the corpus should now be 49. therefore, we need to reduce the min tissue count validation from 53 to 49 so that we won't fail to publish a new cube because of this validation error
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/6307
lowers min tissue count to 49
after merging this, i'll deploy to dev and re-run WMG

chore: lower min tissue count

---

frontend/doc-site/04__Analyze Public Data/4_2__Gene Expression Documentation/4_2_6__Gene Expression Source Data.mdx

We got an email from a user flagging a data integrity issue. I've filed a separate bug to update these and populate the correct links asap. For now, this PR just removes the download links to the incorrect data.

fix(wmg): Remove links to outdated data downloads

---

frontend/src/common/queries/collections.ts

- #6280
- Added handling of Schema 4.0.0 tissue_type to collection detail page.
- Tested locally pointing to dev:

feat: collection detail page Schema 4.0.0

---

frontend/src/common/queries/filter.ts
frontend/tests/features/filter/filter.test.ts

- #6301
- Added handling of Schema 4.0.0 multiethnicity values.
- Tested locally pointing to dev (4.0.0):
- Tested locally pointing to staging (3.x.x):
- Tested on rdev.
- Added unit tests.

feat: Schema 4.0.0 self reported ethnicity

---

tests/unit/backend/layers/api/test_portal_api.py

- #6341 
- Updated enrichment test data to match 4.0.0 data.
- Ran BE tests locally.

fix: 4.0.0 enrichment test data

---

.happy/terraform/modules/batch/main.tf
backend/layers/business/business.py
backend/layers/processing/reprocess_dataset_metadata.py

- #6345
- Proposed solution, built off of proposed approach in https://github.com/chanzuckerberg/single-cell-data-portal/pull/6350/files#diff-df36ae23a2a7f265486f5569606db86dbd40811ca8b99fda3aafb293d1b1d379
- new batch job for reprocessing dataset citations modeled after dataset_metadata_update (i.e. 'light' reprocessing by doing point updates of our artifacts' metadata where necessary, rather than re-validating, re-converting our datasets)
- 1 batch job per dataset
- old files are not overwritten as part of job, new artifacts will be created in a new file in the same directory as existing datasets in corpora-data-prod. Then validated and then copied to replace old artifacts with a bulk cp job [This approach is To Be Finalized]
- Does not create new dataset versions, to retain existing …

feat: reprocess dataset citations in-place

---

frontend/runtime_configs/dev.env

Solves a config bug that only exists in dev and prevents CellGuide from working.

fix: wrong CellGuide data link in dev

---

frontend/.eslintrc.js

1. Somehow some machines don't use `__dirname` as root when finding `tsconfig.json` file, so we need to explicitly set this!

chore: Explicitly set eslint tsconfigRootDir

---

backend/common/providers/crossref_provider.py
backend/layers/thirdparty/crossref_provider.py
tests/unit/backend/layers/thirdparty/test_crossref_provider.py

- #6268
- Added unescape to journal value returned from CrossRef.
- 
- Tested in rdev ([collection list](https://mim-unescape-journal-frontend.rdev.single-cell.czi.technology/collections), [collection detail page](https://mim-unescape-journal-frontend.rdev.single-cell.czi.technology/collections/14f0683e-bcd0-42af-8ff2-5579850c0c0d)).
- Added unit test.

fix: unescape CrossRef journal

---

frontend/src/views/WheresMyGeneV2/components/GeneSearchBar/components/SaveExport/style.ts
frontend/src/views/WheresMyGeneV2/components/GeneSearchBar/components/SourceDataButton/style.ts

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/6379
fixes the z-index of the download modal and the source data badge to make sure the source data badge does not overlap the download modal
- not necessary for this imo

fix: source data badge overlapping download modal

---

frontend/src/views/WheresMyGeneV2/components/GeneSearchBar/components/ShareButton/utils.tsx
frontend/tests/features/wheresMyGene/shareLink.test.ts

- #6131
1. Bug fix - share link using tissue name was broken. It's now fixed
2. Added back test to test the bug above
1. Go to https://localhost:3000/gene-expression?compare=disease&diseases=MONDO%3A0100096&ethnicities=unknown&publications=Ren+et+al.+Cell+2021&sexes=PATO%3A0000383%2CPATO%3A0000384&tissues=UBERON%3A0000178%2CUBERON%3A0002048&genes=DPM1%2CTNMD%2CTSPAN6&cellTypes=natural+killer+cell&ver=2
2. Alternatively, in rdev (https://pr-6385-frontend.rdev.single-cell.czi.technology/gene-expression?compare=disease&diseases=MONDO%3A0100096&ethnicities=unknown&publications=Ren+et+al.+Cell+2021&sexes=PATO%3A0000383%2CPATO%3A0000384&tissues=UBERON%3A0000178%2CUBERON%3A0002048&genes=DPM1%2CTNMD%2CTSPAN6&cellTypes=natural+killer+cell&ver=2)
3. You should see this app state. Note, there should …

fix: share link and test

---

requirements-wmg-pipeline.txt

- Latest census builds require updates to the census dependencies to be read.
- updated census and tiledbsoma dependencies
- Unit tested only

fix: update dependencies to be able to read latest census version

---

frontend/src/views/CellGuide/components/common/OntologyDagView/constants.ts
frontend/src/views/CellGuide/components/common/OntologyDagView/index.tsx
frontend/tests/features/cellGuide/cellGuide.test.ts

The test is failing right now because the node is half hidden and not hoverable
1. Update test to zoom out of the tree view, so more nodes are in the view
All tests should pass now!

test: Fix CellGuide tree view e2e test

---

.github/workflows/deploy-happy-stack.yml

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/6100
three things this changes:
1. notifies @sc-eng if there are issues with any happy deploy
2. notifies @sc-eng and @sc-pm for all prod deploys, regardless of status
3. notifies @sc-eng for all other deploys that fail
the [documentation](https://action-slack.netlify.app/usage/with/) isn't 100% clear, but i believe we need to specify `if_mention` if we want any of the things specified in `mention` to work. i'm pretty sure this is why our existing slack alerts are not notifying @here. regardless, i think @sc-eng is better than @here 
note that (2) notifies #cell-science-ops, which is where we currently do the manual notification, so that seems right to me.
not sure how …

feat: notify @sc-pm and @sc-eng with each deploy

---

.github/workflows/deploy-happy-stack.yml

previously, we intended to use `@here` for failed deploys, but i changed it to use `@sc-eng` because that seemed better than notifying everyone in that channel. based on feedback, it doesn't seem necessary to @-message anyone, so i'm just removing the @-mention for this job entirely.
removes notifying `@sc-eng` when a non-prod deploy fails. note that we will still notify `@sc-eng` and `@sc-pm` for all prod deploys (success and failure), to automate a process that we do manually now.
testing after merge seems fine to me

feat: remove notifying @sc-eng for failed non-prod deploys

---

.github/workflows/deploy-happy-stack.yml

i discovered we had a group for single cell oncall, `@sc-oncall-eng`.
now instead of:
1. notifying nobody when a non-prod deploy fails
2. notifying `@sc-eng` when there are errors with the build
for both of these failures, we'll notify `@sc-oncall-eng`
merge and test : )

feat: notify oncall engineer for failed non-prod deploys

---

backend/Makefile

- fixing the make recipe db/remote_migration_init
- the break was caused by https://github.com/chanzuckerberg/single-cell-data-portal/pull/6425

fix: db/remote_migration_init

---

.github/workflows/build-images-and-create-deployment.yml
.github/workflows/build-images.yml
.github/workflows/push-rdev.yml
.github/workflows/rdev-update-for-pr.yml

Make building docker images DRY for easier to maintain.
- add build-images.yml to build docker images
- call build-images.yml in areas where building docker images is required
- testing in rdev

chore: Reuse build images to simplify GHAs, 1 of 3

---

.github/workflows/rdev-delete-for-pr.yml
.github/workflows/rdev-tests.yml
.github/workflows/rdev-update-for-pr.yml

- https://github.com/chanzuckerberg/single-cell-data-portal/issues/5895
- related to https://github.com/chanzuckerberg/single-cell-data-portal/issues/6169
- This will improve the rdev testing development cycle by stopping GHA jobs from running when newer commits come in.
- add specific concurrency group to .github/workflows/rdev-update-for-pr.yml. 
- Cancel build-images if a new one is in progress. This will interrupt upload docker build and upload which is not a problem
- cancel e2e and functional tests if a new commit comes in.
- rdev deployments are not interrupted if they are started.
- running the github action and interrupting with new commits.
- updates workflow

chore: Adjust concurrency of rdev create to cancel if it's safe. 2 of 3

---

.github/workflows/build-images-and-create-deployment.yml
.github/workflows/promote-staging-to-prod.yml
.github/workflows/trigger-release-candidate-build-and-deploy.yml

- #5482
- Reusable workflow implementation not working with staging / prod deploys, reverting to repository dispatch implementation since there is only a relatively small advantage of reusable workflow approach (keeps gha logs for triggering a deployment in two actions rather than split across three)
- Use repository dispatch rather than reusable workflow to deploy to staging / prod

fix: re-add repository dispatch when triggering deployment

---

frontend/next.config.js
frontend/package-lock.json
frontend/package.json
frontend/src/pages/_app.tsx

- #6555 
For posterity:
- this reverses the changes made on the frontend for Datadog in this [PR](https://github.com/chanzuckerberg/single-cell-data-portal/pull/6140)
- this [PR](https://github.com/chanzuckerberg/single-cell-data-portal/pull/6217) (that was never merged) shows the steps it takes to combine RUM (frontend user monitoring) with Traces (backend tracing)

chore: remove Datadog tracing from frontend

---

backend/wmg/data/ontology_labels.py
tests/unit/wmg_processing/test_ontology_labels.py

For schema-4 tissue term IDs with suffixes like `(orgonoid)` are invalid. Therefore, this PR removes the handling of such term IDs when determining the term label associated with a given tissue term ID.
https://github.com/chanzuckerberg/single-cell/issues/525
- modify `ontology_term_label()` by removing the suffix logic and updating unit tests.
- Passing unit tests

chore: Remove suffix logic for tissue term Ids that don't exist in schema-4

---

.github/workflows/rdev-tests.yml
.github/workflows/rdev-update-for-pr.yml
frontend/src/views/CellGuide/components/CellGuideCard/components/Description/index.tsx
frontend/src/views/WheresMyGeneV2/components/CellInfoSideBar/index.tsx
frontend/tests/features/wheresMyGene/wheresMyGene.test.ts

- #6133
- added cellguide descriptions to marker gene panel. this component mirrors what is shown in the cellguide sidebar that pops up when you click on a cell type in the ontology tree.
- updated gha workflow to seed data before rdev deployment
- E2E test added
- tested in rdev

feat: add cellguide descriptions to fmg sidebar panel

---

backend/wmg/pipeline/cell_type_ordering.py
frontend/src/common/queries/wheresMyGene.ts

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/527
removes the named frontend + backend code that explicitly filters out root CL terms
no-op on list of tissues on gene expression and tissue filter dropdown
- [n/a] Add product, design, and eng as reviewers for rdev review
- [n/a] For UI changes, add e2e tests to prevent regressions

feat: remove redundant code for dealing with root CL terms

---

frontend/doc-site/032__Contribute and Publish Data.mdx

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/3685
Adds the proposed copy changes, with a few minor tweaks:
- Sets the maximum dataset size to 30GB instead of 50GB, since that is what the [code](https://github.com/chanzuckerberg/single-cell-data-portal/blob/75c648e8b277d23c4ff0fe198754e660dfd981d9/frontend/src/components/DropboxChooser/index.tsx#L29) appears to say
- Removes "in 2023" since we're doing this after 2023
- [n/a] For UI changes, add e2e tests to prevent regressions

feat: Update copy for scale constraints

---

frontend/tests/features/wheresMyGene/wheresMyGene.test.ts

this e2e test for verifying the copy of the effect size + specificity tooltip started to fail after merging a seemingly unrelated PR: https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/7630357037/job/20787018226
looking at the playwright trace, i believe the failure is due to a race condition of:
- we hover onto the tooltip
- gpt description loads, pushing the tooltip further down the page
- we aren't able to find the tooltip
updates this e2e test to wait for the GPT description element to load before doing anything else with the marker genes table in the test
i ran this locally with `npm run e2e -- -- tests/features/wheresMyGene/wheresMyGene.test.ts` and it passed, but since the test passed locally but not in the staging deploy, hard to know for sure until we merge …

fix: await gpt description generation

---

backend/database/versions/05_67c4015bce73_add_custom_dataset_order.py
backend/database/versions/05_67c4015bce73_add_datasets_custom_ordered_to_.py
backend/layers/business/business.py
backend/layers/common/entities.py
backend/layers/common/helpers.py
backend/layers/persistence/orm.py
backend/layers/persistence/persistence.py
backend/layers/persistence/persistence_interface.py
backend/layers/persistence/persistence_mock.py
backend/portal/api/portal-api.yml
backend/portal/api/portal_api.py
tests/unit/backend/layers/api/test_portal_api.py
tests/unit/backend/layers/business/test_business.py

- #6484
- Added database migration to add `datasets_custom_ordered` column.
- Added `datasets_custom_ordered` to CollectionVersion
- Added `order-datasets` endpoint.
- Added tests to [test_portal_api.py](https://github.com/chanzuckerberg/single-cell-data-portal/compare/mim/6484-save-dataset-order?expand=1#diff-09a58764042645262735c766e7d4656104dcab6eda35bc3d82f641fe42efe581) and [test_business.py](https://github.com/chanzuckerberg/single-cell-data-portal/compare/mim/6484-save-dataset-order?expand=1#diff-98efcfe189db84e8fdd45833310cbcf9bcd4debb00f0e1aa2e89581034980fed).
- Tested in rdev
- **Valid reorder:** `curl -X PUT --cookie _oauth2_proxy=${oauth2_proxy} --cookie cxguser=${cxguser} -H 'Content-Type: application/json' -d '{"datasets":["30362c1c-96e1-44ef-b0dd-6a783ae9a40d", …

feat: order-datasets DP API endpoint

---

.happy/terraform/modules/deletion/main.tf
.happy/terraform/modules/migration/main.tf
.happy/terraform/modules/service/main.tf
container_init.sh

Ensure that db migration ECS tasks do not download WMG data snapshot to Fargate instance disk. This is done so that deployments aren't slowed by an unnecessary 27 GB data download of WMG cube
- add
- remove
- modify
- Manual testing on rdev and staging

fix: Skip downloading WMG snapshot for db fargate tasks

---

.github/workflows/rdev-update-for-pr.yml

The GHA rdev-update-for-pr.yml randomly fails when a multiple jobs are running in parallel. The error is `Error: The operation was canceled.` This PR reduces the level of parallelism to reduce the change of that error. The suspected it cause is out of memory.
- build-image depends on push-test
- remove seed-wmg-cellguide-rdev dependencies
new workflow

fix(PR tests): GHA flow randomly fails

---

backend/wmg/pipeline/expression_summary.py
python_dependencies/wmg/requirements.txt

In order for WMG pipeline to properly work with the latest version of `cellxgene-census` and `tiledbsoma`, we have to do 2 things:
1. Unpin `numba` so that the dependency versions are properly resolved such that WMG is using the latest versions of `cellxgene-census` and `tiledbsoma`
2. Fix the failure between WMG pipeline and `cellxgene-census` by having WMG pipeline code use SOMA blockwise iterators instead of`cellxgene_census.experimental.util.X_sparse_iter` [due to this backward incompatible change in cellxgene-census](https://github.com/chanzuckerberg/cellxgene-census/pull/962)
- Passing WMG pipeline unit tests
- Passing run of WMG pipeline in rdev and staging

fix: Use soma blockwise iterator for WMG Pipeline

---

frontend/tests/features/wheresMyGene/tissueAutoExpand.test.ts

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/6706
alters the test setup to reflect that we have influenza brain cells in our corpus
e2e test now pass

fix: auto expand disease e2e test

---

backend/layers/processing/process_seurat.py
backend/layers/processing/utils.py
tests/unit/processing/test_processing.py

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/6671
- modifies the anndata of the `local.h5ad` that we pull down from S3 before doing the seurat RDS conversion
- i chose this approach so that i don't have to learn R lol
1. i downloaded an RDS dataset from the rdev generated by this PR
2. i sent the `.rds` file to @brianraymor, who has RStudio up and running, and verified the citation field has `.rds` instead of `.h5ad`
i isolated this logic to `utils.rds_citation_from_h5ad` and added some tests in `test_utils.py`

fix: update RDS citation to use .rds instead of .h5ad

---

.github/workflows/build-images-and-create-deployment.yml

to freeze dev deploys while we run the schema 5.0 migration in dev
freezes dev deploys with merges to main
this will be reverted after dev migration concludes

chore: freeze dev deploys

---

scripts/smoke_tests/setup.py

- #6688 
- Updated seed collections to contain three datasets each.
- Verify PR tests run clean.
- Verify dev and staging merge tests run clean.

test: seed collections contain three datasets each

---

.happy/terraform/modules/schema_migration/main.tf

so that we don't have to change this manually with each run
changes to `DISTRIBUTED` mode

feat: persist distributed mode in schema migration script

---

.github/workflows/build-images.yml
.github/workflows/rdev-tests.yml

- reducing the chance that the GHA will terminated by reducing parallelism in workflows
- run-e2e-tests depends  on seed-database-e2e-tests and functional-test
- verifying GHA passes

fix: reduce GHA parallelism to reduce canceled jobs

---

frontend/src/views/CellGuide/components/CellGuideCardSearchBar/index.tsx
frontend/tests/features/cellGuide/cellGuide.test.ts

This PR lets you search by CL or UBERON ontology term ID
Testing steps:
- Added e2e tests

feat(cellguide): enable search by ontology term ID

---

frontend/tests/features/collection/revision.test.ts

The fix is simply removing the `tryUntil()` block around the assertion:
```ts
expect(await collectionRows.count()).toBeGreaterThan(
MIN_USABLE_COLLECTION_COUNT - 1
);
```
so the `catch()` block can delete revision and recheck the assertion!

test: fix revision deletion

---

frontend/src/views/CellGuide/components/CellGuideCard/components/MarkerGeneTables/hooks/common.ts
frontend/src/views/CellGuide/components/CellGuideCard/components/common/HelpTooltip/style.ts
frontend/src/views/CellGuide/components/common/OntologyDagView/index.tsx
frontend/src/views/CellGuide/components/common/OntologyDagView/style.ts
frontend/tests/features/cellGuide/cellGuide.test.ts

- Changing organisms on a cell type with no cells for the new organism crashed the page.
- Allowed `tissues` to be undefined.
- Tooltip for open integrated embedding button was using an incorrect warning icon
- Used design-approved icon
- Tooltip was placed in an orientation that was not compatible with mobile layouts
- Placed the tooltip on top, instead
- "Open Integrated Embedding" text wrap on mobile layouts looked ugly
- Turned off text wrap
- Added e2e test for the primary bug

chore(cg): a couple bug fixes and tooltip update

---

backend/wmg/api/v2.py

[Slack context](https://czi-sci.slack.com/archives/C0247APK621/p1710178286312599)
- `cell` ancestor node in lung is not showing any data, even though it's the root of the tree. The reason for this was because there was an extraneous filtering step where we were filtering out cell type IDs from the gene expression dataframe that wasn't included in the ORIGINAL, UNROLLED cell counts dataframe. This was a mistake as we should have been comparing against the POST-ROLLUP cell counts dataframe.
- Also, after empirical testing, this filtering step rarely (if ever) actually filters out any entries, so we can safely remove it.
- remove extraneous filtering step
- Tested in rdev.

chore: fix wmg rollup by removing extraneous filtering step

---

python_dependencies/processing/requirements.txt

- [bug in pytest 8.1.0+](https://github.com/pytest-dev/pytest/issues/12069) is causing failures in processing unit tests

fix: pin pytest 8.0.2

---

frontend/src/views/CellGuide/components/common/OntologyDagView/index.tsx

chore: update cellguide embedding tooltip to indicate LTS support only

---

.github/workflows/build-images-and-create-deployment.yml

- sometime deployment to dev needs to be pause for testing or migrations
- add comments on how to enable and disable deployment of an environment
- remove dev from deployed environments
- verified if logic works https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/8270321903/job/22627569180
`${{ }}` were used incorrectly. According to [GHA docs](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution#overview):
> When you use expressions in an if conditional, you can, optionally, omit the ${{ }} expression syntax because GitHub Actions automatically evaluates the if conditional as an expression. However, this exception does not apply everywhere.
So either the whole expression should be in `${{ }}`, or none of it of `if`s.

feat: block dev deployment

---

.github/workflows/deploy-happy-stack.yml
.github/workflows/rdev-tests.yml

Lower e2e shard count from 10 to 5 to hopefully relieve the GHA cancelling jobs issue

chore: decrease e2e shards

---

.github/dependabot.yml

- disable dependabot from making new PR. This might help reduce the issue of cancel jobs in GHA.
- set open-pull-requests-limit: 0 for all dependency files/

fix: disable new dependabot PRs

---

frontend/src/common/featureFlags/features.ts
frontend/src/views/Collection/components/CollectionActions/components/MoreDropdown/components/Menu/index.tsx
frontend/src/views/Collection/hooks/useReorder/useReorder.ts

- #6493.
- Removed `reorder` feature flag.
- Curator may only reorder datasets while collection is private collection, or private revision collection.
- Curator may reorder datasets - without the feature flag `reorder` (now removed).

feat: Remove reorder feature flag (#6493)

---

backend/common/constants.py
backend/database/versions/06_8bced1b1470b_add_data_submission_policy_version.py
backend/layers/business/business.py
backend/layers/business/business_interface.py
backend/layers/common/entities.py
backend/layers/persistence/orm.py
backend/layers/persistence/persistence.py
backend/layers/persistence/persistence_interface.py
backend/layers/persistence/persistence_mock.py
backend/portal/api/portal-api.yml
backend/portal/api/portal_api.py
python_dependencies/backend/requirements.txt
scripts/smoke_tests/setup.py
tests/functional/backend/corpora/test_api.py
tests/functional/backend/corpora/test_revisions.py
tests/unit/backend/layers/api/test_portal_api.py
tests/unit/backend/layers/business/test_business.py

- #6202
- Updated publish of collection to save data submission policy version to DB.
- Updated read of collection to return saved data submission policy version. 
- Updated controller and business-layer tests.
- Tested in rdev.

fix: data submission policy version

---

backend/layers/processing/publish_revisions.py
scripts/smoke_tests/setup.py
tests/functional/backend/common.py
tests/unit/processing/schema_migration/test_publish_revisions.py

- For migrations, we support a bulk revision publish job. Currently, it publishes all open revisions where all datasets are 1) in a successful processing state and 2) migrated to the latest schema version release. However, there are some cases where we would like to hold on publish for certain, pinpointed revisions. This adds the ability to pass a 'deny_list' to the bulk publish batch job.
- fetch do_not_publish_list from env var, optionally defined in container overrides for a batch job. If set, skips publish of collections with collection_version_id in the input list. 
- do_not_publish_list is set as a comma-delimited string with collection_version_ids with "DO_NOT_PUBLISH_LIST" as the expected env var name.
- use 5.0.0 test dataset for post-deploy tests
- rdev + unit tests

feat: add publishing denylist to mass  revision publish batch job

---

.happy/terraform/modules/schema_migration/main.tf

The SFN will fail if a single subtask fails unless we add these values. We'll fail after 20% of Collections fail (20); a Collection fails if any single Dataset fails, but all Datasets will be processed for a given Collection (100).
- add
- remove
- modify

fix: add appropriate failure tolerances to schema migration sfn

---

.github/workflows/rebuild-processing-image.yml

- This is to facilitate scenarios (such as the present migration) where it is useful to trigger the processing image rebuild manually in the Github console _without also triggering a schema migration sfn run_
- add
- remove
- modify

feat: allow rebuild of processing image GHA to be triggered manually

---

.github/workflows/build-images.yml
.github/workflows/rdev-tests.yml
.github/workflows/rdev-update-for-pr.yml

When calling a workflow from another workflow with a `concurreny.group` containing dynamic values ( `${{}}` ), the group name is not constructed properly. For example:
Give the job
```
job:
job-1:
uses: ./.github/workflows/build-images.yml
concurrency:
group: ${{ github.event.number }}-test
```
The group would be `-test`. An example can be seen in [this](https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/8382082600?pr=6835) workflow summary
This is causing workflows to be cancelled prematurely and interfere with other workflow.
- move concurrency group into the called workflow
- remove concurrency group from the caller workflow
- remove the `stack_name` workflow.
- running multiple PR with this workflow 
- ran …

fix: GHA concurrency collisions

---

.github/workflows/build-images.yml

The recent change to [concurrency groups ](https://github.com/chanzuckerberg/single-cell-data-portal/pull/6840)has caused [build-image jobs](https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/8396464523) on main to be canceled. To fix this we are using `github.sha` when `github.event.number` is not availible. This means when a pull_requests triggers the workflow `github.event.number` should be used. If this workflow was not triggered by a pull_request, then `github.sha` will be used. The likely hood of a concurrency group name collision using `github.sha` is very low.

fix: use github.sha to avoid concurrency collisions when building images on main

---

backend/layers/processing/upload_failures/app.py
tests/unit/processing/test_handle_error.py

suppresses the slack message from being sent out if the dataset failure to process comes from a schema migration
when running a schema migration, we prefix the SFN with `migrate` here: https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/backend/layers/processing/schema_migration.py#L126
we can then use this naming convention to determine if the individual dataset failure we're handling in `handle_failure` comes from a migration or not.
it may be slightly better / more correct to pass in the metadata of "is from migration or not" more explicitly, but after looking at the terraform declarations for the dataset processing step function and the schema migration step function i'm not entirely sure how that would work tbh. if that's a similar level of lift i'm happy to change …

feat: suppress slack notification in wrangling channel for migration failures

---

.happy/terraform/modules/ecs-stack/main.tf

- To solve failing deployments. health check is timing out due to longer snapshot downloading time.

chore: bump health check timeout to 60s

---

.github/workflows/build-images-and-create-deployment.yml

This reverts commit e7e9651ef3708e612c36eb8ad16d7a97be2da21f.
- Isolating dev environment for testing integration with cellxgene-ontology-guide using deployed env + prod data. 
- stop auto-deploys to dev from merges to main. deploys to staging off of merges to main will continue.

chore: stop auto-deploys to dev

---

tests/test_utils/mocks.py

- Tests are failing because the WMG pipeline is currently forbidden from reading the latest Census 2.0 build.
- This will be reverted once the pipeline has been updated

chore: switch mock census version parameter to stable

---

frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/DownloadLink/components/CopyCaption/index.tsx

https://github.com/chanzuckerberg/single-cell-data-portal/issues/6629
Updates to the 5.0.0 schema in this modal
Went to the rdev build and:
1. Navigate to https://cellxgene.cziscience.com/datasets
2. Press one of the Download buttons.
3. Select h5ad format.
4. Click the "dataset schema" text
5. Verify that this links to a 5.0.0 URL

feat: update schema version on discover UX download modal

---

backend/common/utils/json.py
backend/curation/api/curation-api.yml
tests/unit/backend/layers/api/test_curation_api.py
tests/unit/backend/layers/utils/test_json.py

- #5203 
- #5202 
- Updated JSON encoder to format dates to a timestamp without milliseconds.
- Updated existing unit tests.
- Tested on rdev.

feat: timestamp format without milliseconds

---

Dockerfile.processing
python_dependencies/processing/requirements.txt

- Processing docker image was only installing PyPI package versions with python requirements <=3.8 when calling pip install, this should configure python3.10 + pip3.10 completely and set-up a virtual env for easier dependency management within the dockerfile in the future.
- Removing unused dependencies
- refactored Dockerfile.processing
- removed louvain, python-igraph, packaging dependencies
- use PyPi packages with python requirements >=3.10 if available (required for 5.1 cellxgene-schema release)
- images build and post-deploy tests pass

chore: clean-up processing docker image

---

frontend/src/views/WheresMyGeneV2/components/InfoPanel/components/SourceData/index.tsx
frontend/src/views/WheresMyGeneV2/components/InfoPanel/components/SourceData/style.ts

#6852 
There's an edge case where collection metadata fails to load for a number of datasets. This adds a render state for that case instead of just rendering an empty row in the source data sidebar.

fix: create render state for failed collection metadata fetching

---

backend/wmg/pipeline/cell_counts.py
backend/wmg/pipeline/expression_summary.py
python_dependencies/wmg/requirements.txt

- Categorical encoding in census obs df broke things
- Update pandas to >2 and convert categorical dtypes to strings
- Previously failing tests now pass

chore: update wmg pipeline to handle categorical data types in Census

---

frontend/src/views/CensusDirectory/components/Project/ProjectButtons/components/EmbeddingButton/connect.ts
frontend/src/views/CensusDirectory/components/Project/ProjectButtons/components/EmbeddingButton/index.tsx
frontend/src/views/CensusDirectory/components/Project/ProjectButtons/components/EmbeddingButton/style.ts

Add support for the new Census embedding API.
- Modify collaborations embeddings to use the `obs_embedding` field 
- Modify hosted embeddings to also use the `obs_embedding`/`var_embedding` field
- Remove R support 
- Add callout to use the latest version of the census API.
- Manual QA

feat: Add support for the new Census embeddings API

---

.github/workflows/deploy-happy-stack.yml

fixes https://github.com/chanzuckerberg/single-cell-data-portal/issues/6201
The previous tag was not fetched when releasing prod. This results in a [release](https://github.com/chanzuckerberg/single-cell-data-portal/releases/tag/sha-5d992477) with no change log.
This GHA job step:
https://github.com/chanzuckerberg/single-cell-data-portal/blob/d8f4a8bce2c76c0e13c6bdad8f31894d38a3b92a/.github/workflows/deploy-happy-stack.yml#L108-L113
is[ failing silently](https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/8559629696/job/23457114380) with `fatal: No names found, cannot describe anything.`
- upgrade checkout to v4
- add fetch-tags
- print `$GITHUB_OUTPUT` to make debugging in the future easier.
- verified using this simplified …

chore: previous tag was not fetched when releasing prod

---

backend/cellguide/pipeline/__init__.py

- CellGuide cannot run in staging as it does not have access to the prod `s3://hosted-cellxgene-prod/cellguide-cxgs/` bucket/key.
- add a try except to unblock pipeline from running in staging temporarily while the appropriate permissions are added asynchronously

chore: temporarily skip valid explorer cxg pipeline if permissions issues

---

.github/dependabot.yml
.github/workflows/push-tests.yml
Dockerfile.backend
Dockerfile.cellguide_pipeline
Dockerfile.processing
Dockerfile.wmg_pipeline
Makefile
docker-compose.yml
python_dependencies/backend/requirements.txt
python_dependencies/cellguide_pipeline/requirements.txt
python_dependencies/common/requirements-dev.txt
python_dependencies/processing/requirements.txt
python_dependencies/wmg/requirements.txt

- Inflated docker image sizes due to installing dev-specific packages (i.e. pytest, coverage) in deployed images
- Easier to manage dev-specific dependencies if we consolidate versions + group them in one file
- extract dev-specific dependencies into python_dependencies/common/requirements-dev.txt, removing them from other requirements.txt
- add new build arg INSTALL_DEV to Dockerfiles for backend, processing, wmg-processing, and cellguide that only installs dev-specific packages if docker build is incurred with INSTALL_DEV=true 
- only call INSTALL_DEV=true to build images during push-tests.yml
- update push-tests.yml to check for whether to rebuild images for unit-test steps that were checking for changed files but not using that value anywhere
- unit tests + inspecting docker image …

chore: extract test + lint requirements into requirements-dev.txt

---

frontend/src/views/CellGuide/components/common/OntologyDagView/components/AnimatedNodes/index.tsx
frontend/src/views/CellGuide/components/common/OntologyDagView/index.tsx
frontend/src/views/CellGuide/components/common/OntologyDagView/style.ts
frontend/tests/features/cellGuide/cellGuide.test.ts

- This PR fixes node centering when nodes are collapsed and expanded, which should reduce test flakiness.
- This PR also fixes failing e2e tests related to node collapse. Hidden nodes were still visible by the locator as they were hidden with opacity 0, so now we added logic to filter out nodes that had 0 opacity in the tests.
- tests pass

feat(cellguide): fix zoom centering when interacting with nodes in OntologyDagView

---

frontend/src/views/CellGuide/components/common/OntologyDagView/index.tsx

- Node centering logic was prioritizing nodes that had children but even non-expanded nodes in the DAG technically had children. This PR fixes this to center on nodes that are _expanded_
- use `isExpanded` property to determine which node to center on

chore: fix node centering to be on expanded node on page load

---

backend/curation/api/v1/curation/collections/common.py
backend/layers/business/business.py
tests/unit/backend/layers/api/test_curation_api.py
tests/unit/backend/layers/business/test_business.py

- #6942 
- Updated business logic to exclude public revision datasets from the `datasets?visibility=PRIVATE` response.
- Unit tests covering business layer and controller
The following test data is set up on [rdev](https://pr-6982-frontend.rdev.single-cell.czi.technology)https://pr-6982-frontend.rdev.single-cell.czi.technology/:
1. Public collection, never revised ([Link](https://pr-6982-frontend.rdev.single-cell.czi.technology/collections/a467ca3c-9a8c-49b7-91c2-fe480f6e2939))
1. Public collection, revised and published
1. Public collection, revision in progress ([Link](https://pr-6982-frontend.rdev.single-cell.czi.technology/collections/991c1744-8a98-4699-9de9-76c7ce2edc87))
1. Revision (of 3), three datasets: one new, one updated and one unchanged …

fix: exclude public revision datasets from private datasets endpoint

---

frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/DataFormat/constants.ts

- #6752 
- Updated ".rds unavailable" tooltip text.
- Tested locally and in rdev.

feat: generalized .rds unavailable messaging

---

.happy/terraform/modules/schema_migration/main.tf
backend/layers/processing/schema_migration.py
tests/unit/processing/schema_migration/test_collection_migrate.py
tests/unit/processing/schema_migration/test_gather_collections.py

- #6917 
- Passing execution_id to mapped async step functions steps. This is to allow logs message to be stored under the same s3 to suffix for schema migration reporting purposes.
- run a small migration and verify all of the expected log messages are returned. The reporter now returns errors for failed jobs 
```json
{
"errors": [
[
{
"collection_id": "45f0f67d-4b69-4a3c-a4e8-a63b962e843f",
"collection_version_id": "104a13bf-bb4e-41af-971b-2d5fc3c48c17",
"dataset_id": "28c696bb-9549-434b-9340-dc745a846f9a",
"dataset_status": {
"cxg_status": null,
"h5ad_status": "UPLOADED",
"processing_status": "FAILURE",
"rds_status": null,
"upload_status": "UPLOADED",
"validation_message": "ERROR: Column 'schema_version' is a reserved column name of 'uns'. Remove it from h5ad and try again.\nERROR: …
```

fix: schema migration error reporting

---

backend/layers/processing/process_validate.py
tests/unit/processing/test_extract_metadata.py

- Bug caught when processing a Slide-Seq-v2 dataset that has is_single: True and no library_id in uns['spatial']. Expected behavior: Should be valid, Actual Behavior: IndexError due to missing a library_id
- modify check in extract_metadata step of DownloadValidate to account for cases where there are no library_ids, removed 1 bit of logic that was making (inaccurate) assumption about the uns shape post-validation
- added unit test to cover case

fix: case where uns['spatial']['is_single'] is True and no library_id key

---

.github/workflows/rebuild-processing-image.yml
Dockerfile.processing
docker-compose.yml

- we depend on the processing image rebuilder to install the latest release of cellxgene-schema, which is unpinned in requirements.txt, as part of the migration automation workflow. However, the rebuild workflow we call after a new PyPI release will cache the install step since we are not committing changes to the processing container. 
- however, we do want to keep caching processing images in all other scenarios when the container is not explicitly updated (push tests, deploys, etc.) 
- add CACHEBUST arg to the processing dockerfile + docker-compose, and only pass a new value (date) when running the rebuild workflow triggered as part of a schema migration after a new cellxgene-schema CLI release.
- running workflows, ensuring it is cached as expected in push tests + deploys and not …

fix: bust cache on processing image rebuild workflow only

---

backend/de/api/v1.py
tests/unit/backend/de/api/test_v1.py

- We need two-sided p-values so that negative effect sizes have non-1 p-values.
- updated p-value calculation to be 2-sided
- updated unit test expected values

chore: calculate 2-sided p-values for DE

---

DEV_ENV_WITHOUT_DOCKER.md
python_dependencies/wmg/requirements.txt

`PyMySQL 0.9.3` was [reported as a security vulnerability by dependabot](https://github.com/chanzuckerberg/single-cell-data-portal/security/dependabot/95). However, WMG application has no need for the package and therefore this PR removes it.
- remove `PyMySQL` python package from `python_depenedencies/wmg/requirements.txt` file
- update docs
- Check that CI passes

chore: Remove PyMySQL python package from WMG

---

backend/layers/processing/h5ad_data_file.py
backend/layers/processing/process_cxg.py
backend/layers/processing/process_logic.py
backend/layers/processing/process_seurat.py
backend/layers/processing/utils/cxg_generation_utils.py
backend/layers/processing/utils/spatial.py
tests/unit/processing/test_h5ad_data_file.py
tests/unit/processing/test_spatial_assets_utils.py

- Bug found while testing https://github.com/chanzuckerberg/single-cell-data-portal/pull/7023 
- uses "local" as directory name for all assets across all datasets, meaning assets are overwritten rather than appropriately distinguished by a unique ID
- use dataset_version_id as unique directory identifier when uploading spatial assets to deep zoom bucket in s3
- unit tests + integration tests (TBD)

fix: use dataset_version_id as deep-zoom spatial bucket directory name for spatial assets

---

.github/workflows/push-tests.yml
.github/workflows/rdev-delete-for-pr.yml
.github/workflows/rdev-update-for-pr.yml

- Renovate is building rdevs and running tests every time they get rebased (which is often), which is a no-no since they're only used as reference PRs.

chore: forbid renovate from running GHA

---

frontend/src/components/common/Filter/common/style.ts
frontend/src/components/common/Filter/components/FilterLabel/index.tsx
frontend/src/components/common/Filter/components/FilterLabel/style.ts
frontend/src/components/common/Filter/components/FilterTags/index.tsx
frontend/src/components/common/Filter/components/FilterTags/style.ts
frontend/src/components/common/SideBar/index.tsx
frontend/src/components/common/SideBar/style.ts
frontend/src/views/Collections/index.tsx
frontend/src/views/Collections/style.ts
frontend/src/views/Datasets/index.tsx
frontend/src/views/Datasets/style.ts
frontend/src/views/WheresMyGeneV2/style_old.ts

- See https://clevercanary.slack.com/archives/C023Q1APASK/p1717534645840959?thread_ts=1715623480.846529&cid=C023Q1APASK and [mocks](https://www.figma.com/design/jEv0ZWQd0Q53aFl9nNRbBy/Portal?node-id=1274-2358&t=J7LP4mZ8oRZiycxw-1), resolved on behalf of https://github.com/chanzuckerberg/single-cell-data-portal/issues/6999.
- Updated `SideBar` component styles (the toggle button) and also update `FilterLabel` component to use SDS library `InputDropdown` as per slack [thread](https://clevercanary.slack.com/archives/C023Q1APASK/p1717534645840959?thread_ts=1715623480.846529&cid=C023Q1APASK).

fix: collections and datasets sidebar sds components and associated styles

---

.happy/terraform/envs/prod/main.tf

- Prod CPU count was improperly configured for fargate. This PR cherry-picks the hotfix applied directly to prod back into main

chore(hotfix cherrypick): proper CPU configuration

---

.happy/terraform/modules/schema_migration/main.tf

- this avoid us spamming the batch queue with jobs that will state in runnable stable for days.
- It also reduces the chance of us running into rate limiting from AWS on batch API requests. 
- adjust the compute resources for dataset_migration to make better use compute.
- modify SpanCollection Concurrency from 40 to 10
- modify SpanDataset Concurrency from 32 to 10
- reduce the memory and VCPUs used by dataset_migrate to 64000MB and 8 VCPUs.
- Add 300000MB of swap to dataset_migrate.

fix: reduce schema-migration span concurrency

---

python_dependencies/processing/requirements.txt
tests/unit/processing/test_h5ad_data_file.py
tests/unit/processing/test_spatial_assets_utils.py

- cellxgene-schema 5.1.0 requires the following dependency version pin updates to numba, numpy, and scanpy
- bump versions for numba, numpy, and scanpy to allow install for cellxgene-schema 5.1.0

chore: bump cellxgene-schema 5.1.0 related pinned versions

---

backend/layers/processing/publish_revisions.py

- Small bug where passing in do_not_publish_list as None for a publish-revisions job caused an error; workaround is to pass in an empty string but we want to support None.
- support publish-revision batch job submission without a DO_NOT_PUBLISH_LIST env var being set.

fix: accept NoneType do_not_publish_list

---

backend/common/utils/timer.py
backend/layers/persistence/persistence.py

- ServerTiming is a library that depend on flask being installed. It is being removed from the persistence layer and mvoed into a utility function where ServerTimer is imported if it exists. Otherwise it's a nop 
- add a nop function if sever_timing is not installed
- send server timing metric back to API if server_timing is installed
- modify
- verified unit tests work
- verified server time is returned in the response for Get curation/v1/collections

fix: remove ServerTiming from persistence layer

---

.happy/terraform/modules/ecs-stack/main.tf

- partial fix for https://github.com/chanzuckerberg/single-cell-data-portal/issues/7190
- some endpoint in the backend are slow and exceed our configured timeouts.
- endpoint `/curation/v1/collections` is showing requests take as long as 78 seconds:
```
FAILED
Gateway Time-out
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>504 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.
We can't connect to the server for this app …
```

fix: cloudfront 504 error for long backend requests.

---

frontend/src/views/CensusDirectory/components/Project/ProjectButtons/index.tsx

These keys will be added to contributions.json and they don't need to show up here.
In the future, it would be better to switch to an allow list model, since the contributions.json file isn't uniquely used by this page anymore.

fix: add more ignored keys in the Census Models page

---

scripts/cxg_admin.py
scripts/cxg_admin_scripts/request_logs.py

- this saves developers a trip to AWS to see the request logs when they have the request_id in hand. 
- add cxg_admin command to get backend logs from a request_id
- verified the script works on dev using cxg_admin
- verified the script works on it's own using rdev.

feat(cxg_admin): add command to get backend logs based on a request id.

---

backend/layers/processing/dataset_metadata_update.py
tests/unit/processing/test_dataset_metadata_update.py

- Currently, the raw.h5ad is not updated on a dataset_metadata_update batch job. This is reasonable for updates to citation or schema_version, which are not fields on the raw H5AD (only labeled), but now that we support updates to dataset title (which is on the raw.h5ad as well), we need to update the dataset title on the raw.h5ad. This is because we use the raw.h5ad as the object to migrate during a migration; in the current state, we would accidentally roll back dataset title changes done since the last schema version bump.
- add raw_h5ad_update function 
- only trigger raw_h5ad_update if a field being updated is contained in the raw h5ad (currently, of fields on the raw h5ad, we only support updating "title")
- otherwise, retain previous behavior (that is, copy existing raw_h5ad_uri to …

fix: update raw h5ad when editing dataset title

---

backend/curation/api/v1/curation/auth/token.py
tests/unit/backend/layers/api/test_curation_api.py

- Add a helpful error when the curation API token has expired. The current response is an unhelpful 500.
- add an additional 401 response if **not** the latest generated curation/discover API key is used to get an access token.
- add unit tests to simulate a 403 from the auth0 endpoint for generating access tokens.

fix: api token expired error

---

backend/layers/persistence/persistence.py

- functional tests were failing because the backend was trying to add tombstoned datasets to a collection because the dataset version was in the list of datasets in the collection
- filter out datasets that were not returned by `get_dataset_versions_by_id` due to being tombstoned.
- modify variable names for readability

fix: account for tombstoned datasets when getting all versions of a collection

---

frontend/tests/features/collection/revision.test.ts

- #7061 
- Added e2e tests.
- `RDEV_LINK=https://pr-7234-frontend.rdev.single-cell.czi.technology/ TEST_ACCOUNT_PASS=x HEADFUL=true RETRY=false npm run e2e-rdev -- -- tests/features/collection/revision.test.ts`

feat: rename dataset e2e

---

frontend/src/views/DifferentialExpression/common/store/actions.ts
frontend/src/views/DifferentialExpression/common/store/reducer.ts
frontend/src/views/DifferentialExpression/components/Main/components/DeResults/components/DifferentialExpressionResults/components/QueryGroupTags/index.tsx
frontend/src/views/DifferentialExpression/components/Main/components/DeResults/components/DifferentialExpressionResults/connect.ts
frontend/src/views/DifferentialExpression/components/Main/components/DeResults/components/DifferentialExpressionResults/index.tsx
frontend/src/views/DifferentialExpression/components/Main/components/DeResults/utils.ts
frontend/src/views/DifferentialExpression/components/Main/components/Filters/components/CopyButton/connect.ts
frontend/src/views/DifferentialExpression/components/Main/components/Filters/components/FilterDropdown/connect.ts
frontend/src/views/DifferentialExpression/components/Main/components/Filters/components/FilterDropdown/index.tsx
frontend/src/views/DifferentialExpression/components/Main/components/Filters/components/FilterDropdown/style.ts
frontend/src/views/DifferentialExpression/components/Main/components/Filters/components/FilterDropdown/types.ts
frontend/src/views/DifferentialExpression/components/Main/components/Filters/components/FilterDropdown/utils.ts
frontend/src/views/DifferentialExpression/components/Main/components/Filters/connect.ts
frontend/src/views/DifferentialExpression/components/Main/components/Filters/index.tsx
frontend/src/views/DifferentialExpression/components/Main/components/Filters/types.ts
frontend/src/views/DifferentialExpression/components/Main/components/common/query_group_filter_dimensions.ts
frontend/tests/features/differentialExpression/differentialExpression.test.ts
scripts/cxg_admin.py

- Addresses the last couple UI/UX items from the DE changes needed for MVP.
- Unavailable (gray) tags that were cross-filtered out are not included in the filter tags on the results panel.
- Whitespace is now trimmed out prior to regex parsing for the results table expression filter input fields
- added reducer state required to track which tags are available or not
- Local QA
- E2E test added

chore(de): remove unavailable tags from query group boxes

---

backend/layers/processing/utils/spatial.py
tests/unit/processing/test_spatial_assets_utils.py

- #7124 
- removed hires image from cxg
- converted locally and tested dataset in explorer

chore: remove mvp related fields from cxg conversion

---

scripts/smoke_tests/setup.py

- use threads when uploading datasets to speed up rdev database seeding.

chore: speed up rdev seeding

---

frontend/src/common/queries/collections.ts

- #7296 
- Updated DELETE success handler to not refetch on invalidate of revision in cache.
- Manually create and cancel revision.
- Confirm edit dataset title E2E test passes.
- A refetch of the canceled revision causes the collection actions button component to unmount, preventing a [redirect to the published collection](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/frontend/src/views/Collection/components/CollectionActions/index.tsx#L94).

fix: invalidate cache without refetch on cancel revision

---

backend/layers/business/business.py
tests/unit/backend/layers/business/test_business.py

- New Citations must be generated whenever a new DatasetVersionId is generated; edit dataset titles represented a use-case where this was not happening
- add path to generate a new citation when a dataset title is updated, and persist that update to artifact updates
- unit + rdev

fix: update citation when updating dataset title

---

frontend/tests/features/wheresMyGene/selectOrganism.test.ts
frontend/tests/features/wheresMyGene/shareLink.test.ts
frontend/tests/features/wheresMyGene/tissueAutoExpand.test.ts

1. BE recently updated the publication citation format and the WMG cube was updated last Sunday
2. BE only downloads the latest WMG cubes at server start time, which is why even though the cubes were updated last Sunday, the runtime error only shows up in staging BE when I did a staging deployment earlier today
3. The fix is to update the e2e tests with publication to use the new citation format
- "Unit tested only", "tested in rdev by a, b, c, verifying feature worked by... ", …

test: Update test

---

frontend/src/common/queries/wheresMyGene.ts
frontend/src/common/utils/formatCitation.ts
frontend/src/views/WheresMyGeneV2/components/HeatMap/components/YAxisChart/index.tsx

1. BE now serves the correct publication title format, so FE no longer needs to format the string anymore, which actually caused a formatting bug
BEFORE:
AFTER:

fix: Update WMG publication format

---

frontend/tests/features/differentialExpression/differentialExpression.test.ts

Context [here](https://czi-sci.slack.com/archives/C0247APK621/p1724427880326249)
- Added click to sort by negative effect size 
- Replaced hardcoded test value of `SAA1` with first gene returned in results table
- Added another click to sort by positive effect size to ensure subsequent assertions won't fail

fix: top DE gene result for e2e test

---

backend/Makefile

Replace makefile rules for connecting to Postgres through the new SSM-enabled machines.
Note: due to how awscli works, it is not possible to launch the tunnel in the background without resorting to bash shenanigans (forking the process via `&`, killing the process via `kill`). Therefore, I made the following changes:
1. `make db/tunnel/up` now needs to be launched on a separate shell, and will not fork the process
1. `make db/connect` will need to be called after the tunnel is up
1. Instead of running `make db/tunnel/down`, it is sufficient to shut down the tunnel via CTRL-C.

feat: bastion replacement

---

.github/workflows/rdev-tests.yml
backend/Makefile
backend/scripts/mirror_env_data.sh
backend/scripts/mirror_rds_data.sh
backend/scripts/mirror_s3_data.sh
backend/scripts/set_src_dest_envs.sh
python_dependencies/wmg_processing/requirements.txt

- Infra team recently deprecated bastions, breaking our data mirroring and PostgreSQL ssh connection make commands
- ebezzi replaced the bastions with accessing our DBs via SSM-enabled [machines](https://github.com/chanzuckerberg/single-cell-data-portal/pull/7328)
- This PR uses those changes to fix our data mirroring script and updating its instructions, so we can continue to mirror prod data to dev/staging for testing purposes.
- require running  `make db/tunnel/up` for both SRC and DEST env, with a different local port number forwarding to the SSM-enabled machine for each DB env.
- add port number as argument for mirroring script and tunneling command
- update 'make db/dump' to also take PORT as an arg and remove `make db/connect` call, which is now interactive-only and replaced by the …

chore: Fix data mirroring script and instructions

---

backend/curation/api/curation-api.yml
frontend/doc-site/032__Contribute and Publish Data.mdx
frontend/doc-site/03__Download Published Data.mdx
frontend/doc-site/04__Analyze Public Data/4_2__Gene Expression Documentation/4_2_2__Cell Type and Gene Ordering.mdx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/DataFormat/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/DownloadLink/components/CopyCaption/index.tsx

- #7329
- use new github-pages based "latest" schema.md redirect rather than link out to a specific version and require updating every migration
- bump references to anndata 0.8 in docs/FE modals to anndata 0.10

chore: update schema reference urls to use 'latest-schema' redirect url

---

backend/common/corpora_config.py
backend/portal/api/app/v1/authentication.py

- Remove sever metadata field from oauth.register()

chore: remove sever metadata field from oauth.register()

---

frontend/src/views/CellGuide/components/CellGuideCard/components/Description/constants.ts
frontend/src/views/CellGuide/components/CellGuideCard/components/Description/index.tsx
frontend/src/views/WheresMyGeneV2/components/CellInfoSideBar/index.tsx

- When a user tries to click on a cell type in GE that doesn't exist in CG, the app would crash for missing `clDescription`
- Context: [here](https://czi.atlassian.net/jira/software/c/projects/SCE/list?selectedIssue=SCE-22)
- Added default values for missing `clDescription` and `rawDescriptionGpt`
- Hide `Open in Cell Guide `link when a cell type is missing in Cell Guide
- In GE, filter by `chondroblast` - click on info icon

fix: add default values for cell guide description (SCE-22)

---

backend/layers/processing/upload_failures/app.py
tests/unit/processing/test_handle_error.py

context: https://czi-sci.slack.com/archives/C024HCSH9PT/p1728939906110759
- removes the oncall slack tag
- minor copy change to remove the attempt to hyperlink out to the triage steps since that doesn't work
- updated unit tests

feat: remove oncall page from slack message about failed dataset validation

---

frontend/doc-site/05__Annotate and Analyze Your Data/5_3__Preparing Data.mdx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/DataFormat/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/Details/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/Details/style.ts
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/index.tsx

- [Ticket](https://czi.atlassian.net/browse/SCE-32)
- Notify users of upcoming Seurat deprecation
- Add deprecation warning banner
- Add relevant docs
- Visual QA for content and design
- rdev -> [here](https://pr-7365-frontend.rdev.single-cell.czi.technology/datasets)
- Docs -> [here](https://pr-7365-frontend.rdev.single-cell.czi.technology/docs/05__Annotate%20and%20Analyze%20Your%20Data/5_3__Preparing%20Data#seurat-deprecated)

chore: seurat deprecation notice (SCE-32)

---

frontend/doc-site/032__Contribute and Publish Data.mdx

[This page](https://cellxgene.cziscience.com/docs/032__Contribute%20and%20Publish%20Data) should reflect an overview of the submission requirements, but has yet to be updated to reflect Visium & Slide-seq requirements.

docs: add spatial standards to Contribute documentation

---

DEV_ENV_WITHOUT_DOCKER.md
backend/layers/processing/h5ad_data_file.py

https://czi.atlassian.net/browse/VC-1333
Reverts the change to use backed mode when reading in anndata. The most time intensive part of CXG conversion is writing tiledb arrays from the anndata, and needing to read anndata in from disk instead of memory is almost certainly the cause of the performance degradation we saw.
This change will increase our memory usage, which will require us to beef up our machines to use more memory to avoid OOM errors. But it should decrease our overall time spent on CXG conversion.
I also added some documentation changes because I had to spend some time fiddling around with my local environment before I could get this to work.
I wrote a very simple Jupyter notebook to time CXG conversion locally:
```
import time
from backend.layers.processing.h5ad_data_file …
```

feat: Do not use backed mode when reading in anndata for CXG conversion

---

frontend/container_init.sh
frontend/package-lock.json

- Fix staging frontend errors following nextjs version bump (to avoid high already security vulnerability)
- npm run start invocation no longer needs extra --, this is causing the frontend task to fail despite the build succeeding
- bump some dependencies to correspond with the nextjs bump

fix: nextjs 14.2.12 dependencies + npm start invocation

---

.github/workflows/deploy-happy-stack.yml
.github/workflows/push-tests.yml
.github/workflows/rdev-tests.yml

- V3 was deprecated on Nov 30thm 2024.
- upgrade actions/download-artifact to V4
- upgrade actions/upload-artifact to V4
- use unique names to upload artifacts.
- verify allure report is generated
- verify code coverage is submitted

fix(gha): upgrade GHA upload & download to major version 4.

---

.github/workflows/deploy-happy-stack.yml

Happy Deploy fails on upload artifact
- Added dynamic name per shard for blob reports

fix: Happy upload-artifact blob name

---

.github/workflows/deploy-happy-stack.yml

- prod deployment fails because playwrite repots are not found for e2e-logged-in-test. Otherwise these test run and pass. 
- remove requirements that artifacts are uploaded.

fix: e2e-logged-in-test failing on upload artifacts in prod

---

backend/wmg/pipeline/validation/validation.py

- WMG pipeline fails on AQP5 validation test. Recent additions to the corpus caused an already borderline test to fail due to changing `sum` averages
- Disabled test, captured [here](https://github.com/chanzuckerberg/single-cell-data-portal/issues/7421)

fix: disable AQP5 validation test

---

backend/common/census_cube/data/criteria.py
python_dependencies/backend/de/requirements.txt
python_dependencies/backend/requirements.txt
python_dependencies/backend/wmg/requirements.txt
python_dependencies/cellguide_pipeline/requirements.txt
python_dependencies/processing/requirements.txt
python_dependencies/wmg_processing/requirements.txt

- There are some model validation and conversion function that are in pydantic V2 that would be helpful in the new manifest schema.
- Update pydantic version to be < 3
- Update deprecated pydantic terms.
- Verified unit test pass

fix: upgrade pydantic to <3

---

tests/unit/backend/layers/api/test_curation_api.py

These tests were not running due to an indentation error, this should fix that.

fix: curation api tests now run

---

backend/curation/api/curation-api.yml
backend/curation/api/v1/curation/collections/collection_id/datasets/dataset_id/actions.py
backend/curation/api/v1/curation/collections/collection_id/datasets/dataset_id/manifest/actions.py
backend/curation/api/v1/curation/collections/common.py
backend/layers/business/business.py
tests/unit/backend/layers/api/test_curation_api.py
tests/unit/backend/layers/business/test_business.py

- https://github.com/chanzuckerberg/single-cell/issues/738
- ~[ ] Submit ATAC to SFN~
I think it would be better if `ingest_dataset` ONLY took a manifest, and that the routing layer above it had to account for transforming the JSON. But the method is called in really a lot of tests, so changing it would touch a lot of code.
- Added a PUT endpoint for manifest files

feat: PUT for manifest files

---

frontend/src/views/CensusDirectory/components/Project/connect.ts

Several of the "Last Updated" dates on the [Census Models](https://cellxgene.cziscience.com/census-models) page show as December 31, 1969. I tracked it down to this comparison.

fix: Census Models last-updated dates

---

backend/curation/api/curation-api.yml
backend/curation/api/v1/curation/collections/collection_id/datasets/dataset_id/manifest/actions.py
backend/curation/api/v1/curation/collections/common.py
backend/layers/business/business.py
backend/layers/common/entities.py
tests/unit/backend/layers/api/test_curation_api.py

- https://github.com/chanzuckerberg/single-cell/issues/741
- added FRAGMENT_INDEX artifact type
- modified permanent url resolution code to account for URI for fragment indices
- added tests checking that atac artifacts are returned by the API
In the specification doc there is some inconsistency around what the index artifact is called. I went with `FRAGMENT_INDEX` but `FRAGMENT_TABIX` is also used in the spec.

feat: Check other endpoints for ATAC artifacts

---

backend/layers/business/business.py
backend/layers/business/business_interface.py
backend/layers/common/entities.py
backend/layers/processing/dataset_metadata_update.py
backend/portal/api/portal-api.yml
backend/portal/api/portal_api.py
tests/functional/backend/utils.py
tests/unit/backend/layers/api/test_portal_api.py
tests/unit/processing/test_dataset_metadata_update.py
tests/unit/processing/test_handle_error.py

- atac_status will be used to communicate the status of atac dataset processing to the end users.
- add DatasetStatus.atac_status and default to skipped during ingestion
- Update test cases to reflect changes

feat: Add DatasetStatus.atac_status and default to skipped

---

.happy/terraform/modules/sfn/main.tf

- errors not passed correctly to error handler
- errors not passed correctly to error handler, causing the error handler to not be invoked.
- fix how parameters are passed to the error handler

fix: ingestion error handler

---

backend/database/versions/92c817dddc7d_new_atac_artifact_enums.py
backend/layers/persistence/orm.py

- Changing `DatasetArtifact.type` from enum to String will make it easier to add new artifact types in the future without doing a database migration. This is safe because only the backend code has access to the database and will handle enforment. 
- add database migration to change `DatasetArtifact.type` from an enum to a string
- update `orm.py` to make `DatasetArtifact.type`
- tested the migration locally
- Ran the migration on dev and verified existing datasets could be retrieved and that new datasets can be created.

feat: Change DatasetArtifact.type from enum to String

---

backend/database/versions/92c817dddc7d_new_atac_artifact_enums.py
backend/layers/persistence/orm.py
backend/portal/api/portal-api.yml
tests/unit/backend/layers/api/test_portal_api.py

- This allows the portal to retrieve datasets with atac assets.
- update portal-api.yaml
- update related tests.
- updated related test

fix: add new artifact types to portal API

---

backend/common/corpora_config.py
backend/common/utils/dl_sources/uri.py
tests/unit/backend/layers/utils/test_uri.py

- support uploading file using a public cellxgene url
- add CXGPublicURL to parse public cellxgene urls
- remove import side effects when importing `backend.common.utils.dl_sources.uri` by moving `RegisteredSources.add` calls to inside `from_uri` if `RegisteredSources` has no sources.
- renamed `_registered` to `_sources` in `RegisteredSources`.
- To help with testing the `dataset_assets_base_url` is defined in `CorporaConfig` when `DEPLOYMENT_STAGE == test`
- Added unit tests for `S3URL` and `CXGPublicURL`

fix:  support uploading files from a cellxgene public url

---

frontend/src/views/Collection/index.tsx

- [VC-2245 Private Collection is currently public via Google indexing](https://czi.atlassian.net/browse/VC-2245)
- Ensure private collections are not being indexed by search engines
- Added `noindex` meta tag to Collection page if `collection.visibility == "PRIVATE"`
- In `rdev` - inspect page source while viewing a private collecation

fix: Add noindex meta tag for private collections (VC-2245)

---

scripts/smoke_tests/setup.py
tests/functional/backend/conftest.py
tests/functional/backend/constants.py
tests/functional/backend/utils.py

- Updating the rdev database seed to include visium and atac datasets. This is to allow frontend developer to test their changes in an rdev without uploading additional files. It also improves our ability to test changes as the types of data we ingest continues to evolve.
- Use the curation API to upload datasets using the manifest endpoint to the rdev database.
- make `create_and_publish_collection` reusuable
- seed db creates a collection with a visium datasets if it does not exist
- seed db creates a collection with a atac dataset if it does not exist.
verified the datasets exist in the rdev environment

fix: update rdev db seed to include visium and atac datasets

---

.happy/terraform/modules/batch/main.tf
.happy/terraform/modules/schema_migration/main.tf

- Need more resources for some datasets' validation, add labels, etc.
- Need resources for dataset migration step as well, but not for other steps in migration
- bump resource allocation for ingestion batch jobs from 1vcpu, 8 gb --> 2 vcpu, 16 gb (includes both validate steps, add labels)
- refactor migration batch job allocation to have a separate batch job definition for dataset migration job, which requires more resources than other steps

feat: bump ingestion batch job resources + dataset migration step resources

---

frontend/src/components/BottomBanner/components/ModalContent/connect.ts
frontend/src/components/BottomBanner/constants.ts

- Newsletter `Subscribe` was not displaying success message upon signup
- The script was checking for a hidden success message returned from HubSpot - since the copy of that message has changed by the provider over time, the logic that displays the success message to the user was skipped
- Updated the logic to look for `submitted-message` class name in the hidden form node upon submission instead of looking for the hidden text, as it is less likely to change over time
- Click subscribe from the bottom banner - and enter a valid email

fix: Newsletter Subscribe VC-2285

---

python_dependencies/processing/requirements.txt

- The anndata version used by the processing conrtainer follow cellxgene-schema requirements
- unpin the anndata version for the processing container. Now it'll use the version required by cellxgene-schema.
- verify tests pass.

chore: anndata version follow cellxgene-schema requirements

---

.github/workflows/deploy-happy-stack.yml
.github/workflows/push-tests.yml
.github/workflows/rdev-tests.yml
.github/workflows/rebuild-processing-image.yml

We changed how to manage self-hosted runner scalesets and in doing so have a programatically generated scaleset name. This new scaleset has the same specs as the old runner scaleset.

chore: update runners with new drop-in replacement

---

.happy/terraform/envs/stage/main.tf

- Staging wmg api becomes non-responsive during e2e test run
- Increase resources for staging

fix: staging wmg backend resources

---

backend/layers/processing/dataset_metadata_update.py
backend/layers/processing/process_validate_atac.py
backend/portal/api/portal-api.yml
frontend/doc-site/032__Contribute and Publish Data.mdx
tests/functional/backend/conftest.py
tests/functional/backend/corpora/test_api.py
tests/functional/backend/utils.py
tests/unit/processing/test_dataset_metadata_update.py
tests/unit/processing/test_process_validate_atac.py

- Issue reported by Jenny in slack, when attempting a metadata update for datasets (non-multiome)
- Evan dug and diagnosed error as stemming from the atac status not being updated, and thus failing the check for a valid set of artifact statuses
- further investigation by me suggests that, in addition to not copying over the atac status when atac validation is skipped, when datasets with valid fragment files are updated, we were also failing to point the new dataset version produced by the metadata update job to the fragment files. No impact in prod, as the error above found by Evan would've blocked this from occurring anyway.
- https://czi-sci.slack.com/archives/C024HCSH9PT/p1744650148839419
- when updating dataset metadata status, check for ATAC_FRAGMENT and ATAC_INDEX artifacts 
- if …

fix: copy atac status/files when running dataset metadata update job

---

backend/curation/api/curation-api.yml
backend/portal/api/portal-api.yml

Report from Jim Chaffer:
> > [@Brian Mott](https://czi-sci.slack.com/team/U064K47JL56)
>  and I have come across an issue with the CXG_API in which trying a call for get_collection of a collection that has data from organisms other than human/mouse/covid/spike results in an error.
> It looks like this is originating from the feature reference value not being accepted.
> Example output:
> 
> ```
> FAILED
> 
> Internal Server Error
> 
> {
>   "detail": "'NCBITaxon:7227' is not one of ['NCBITaxon:9606', 'NCBITaxon:10090', 'NCBITaxon:2697049', 'NCBITaxon:32630']\n\nFailed validating 'enum' in schema['allOf'][0]['properties']['datasets']['items']['properties']['feature_reference']['items']:\n    {'enum': ['NCBITaxon:9606',\n              'NCBITaxon:10090',\n              'NCBITaxon:2697049',\n …
```

fix: remove species enum in curation API swagger spec

---

frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/components/DataFormat/constants.ts
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/index.tsx
frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/utils.ts

- Fall back if download url call fails
- Disable download button when download urls are not available
- Prevent duplicate H5AD urls
- remove hard coding of download url for demonstration purposes.
https://github.com/user-attachments/assets/339ae708-889d-445c-87b8-dcad91bacb33

fix: patch Multiome Download - front end fixes

---

.happy/terraform/modules/batch/main.tf

- this should prevent us from needing to manually rerun the SFN for larger multiome datasets
- ideally, we should not need such high resourcing, but this seems like a good short to medium term solution
- implements the memory + vcpus specified when i needed to manually re-run the SFN for a larger dataset
- n/a
not applicable

chore: increase aws resources of atac job

---

frontend/doc-site/032__Contribute and Publish Data.mdx

- part 2 of #7411 
- Update the Contribute documentation to reflect the updated submission criteria & requirements for schema 5.3
- Additional update to correct the visualization constraint to 4.3M cells (not 4.6)

docs: refactor contribute doc for schema 5.3 cont

---

backend/layers/processing/process_add_labels.py
tests/unit/processing/test_extract_metadata.py

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/1311
- update the `extract_metadata` method in data portal to read the organism terms from `uns`, if available
- this is written to be backwards compatible. so we should be able to merge the change in to data portal before the 6.0 migration. then, when we run the migration, we'll update the `DatasetMetadata` for every dataset. all of the API's should work as expected since they all read from the `DatasetMetadata` object, not from the adata file directly
- wrote a new test in `test_extract_metadata_organism_uns` that is very similar to `test_extract_metadata`, except it sets the organism terms in `uns` instead of `obs`. it is passing in the `processing-unit-test` job
- i …

feat: read organism terms from uns

---

.happy/terraform/modules/sfn/main.tf
backend/layers/processing/h5ad_data_file.py

https://czi.atlassian.net/browse/VC-2370
i found two improvements to CXG conversion, while staying within our current resource allocation of 2 vCPUs and 16GB of memory. these changes are:
1. increase `chunk_size` when reading h5ads to be 15000. i think this was originally set at 7500 when we had memory for this job to be 8GB. doubling this to 15000 still keeps us well within the 16GB of allocated memory and should make this operation a bit faster
2. instead of scheduling 2 workers and 1 thread per worker with 6GB of memory per worker when we write `X`, it should be a better use of memory to have 1 worker with 2 threads per worker. so if one of the threads is working on something that's more memory intensive, instead of each process having its own 6GB bucket of memory, the more memory …

chore: allocate memory for CXG conversion better

---

.happy/terraform/envs/prod/main.tf

- `cg-prod` batch job container has been [failing](https://us-west-2.console.aws.amazon.com/batch/home?region=us-west-2#jobs/ec2/detail/08da5536-8596-4e48-8897-73d357f08cac) on out of memory
- Upped the memory for cg batch job

fix: Up CG batch memory limit

---

.happy/terraform/envs/prod/main.tf

- `wmg-prod` batch job container has been [failing](https://us-west-2.console.aws.amazon.com/batch/home?region=us-west-2#jobs/ec2/detail/08da5536-8596-4e48-8897-73d357f08cac) on out of memory
- Upped the memory for wmg batch job

fix: Up WMG batch memory limit

---

.happy/terraform/modules/sfn/main.tf
backend/layers/processing/process.py
backend/layers/processing/process_cxg.py
backend/layers/processing/process_validate_atac.py

- https://github.com/chanzuckerberg/single-cell-data-portal/pull/7569
- This iterates on the previous implementation where `fragment_artifact_id` is being pulled from the database/artifacts
-  CXG step now queries database directly for fragment artifacts instead of relying on parameter passing
-  Eliminated fragment_artifact_id from process() method signatures and environment variables
-  Updated ATAC validation: No longer returns fragment_artifact_id since it's not needed
-  Cleaned up infrastructure: Removed unused FRAGMENT_ARTIFACT_ID from Terraform Step Function config

fix: ATAC Process updates

---

backend/layers/processing/utils/atac.py

- vc-3630
- fixes an OOM error when processing ATAC fragments into CXG using a function generator instead of preallocating an array. This is slower but will be less memory intensive.
* [`backend/layers/processing/utils/atac.py`](diffhunk://#diff-76e55c365137fb5f4b085debb6488c1800836a335a3becc92444b273973c1caeL389-R408): Replaced pre-allocated arrays for storing intermediate data with a generator function (`generate_coverage_records`) that dynamically yields coverage records. This eliminates the need for large in-memory arrays.
* [`backend/layers/processing/utils/atac.py`](diffhunk://#diff-76e55c365137fb5f4b085debb6488c1800836a335a3becc92444b273973c1caeL389-R408): Introduced `itertools.islice` to process records in chunks, reducing memory usage by writing smaller fragments to TileDB …

fix: use chunked write to tiledb to avoid OOM

---

.happy/terraform/modules/batch/main.tf
.happy/terraform/modules/sfn/main.tf
backend/layers/processing/utils/atac.py

- the 50000  chunk size for writing CXG was low and made writing take hours. Increasing to to about 300MB per chunk.
- fixing https://czi.atlassian.net/browse/VC-3722?atlOrigin=eyJpIjoiNzlkMzAwMDdkMWZkNDg5ZmJjZDU4ZjQwM2U2ZGMxOTAiLCJwIjoiaiJ9
This pull request includes changes to optimize resource configurations and improve error handling across batch job definitions, state machine configurations, and a Python utility function. Key updates include adjustments to memory and CPU allocations, the introduction of retry strategies for state machine tasks, and an increased chunk size for processing data.
* [`.happy/terraform/modules/batch/main.tf`](diffhunk://#diff-79c3e8b861066ac4e8d0ecf50e8c69713501bf03de50a7c314ab02461e07f7eeL62-R62): Reduced memory allocation for `cxg_job_def` from 64,000 to …

fix: OOM in ingestion pipeline

---

README.md
backend/layers/processing/h5ad_data_file.py
backend/layers/processing/utils/atac.py

- VC-3630
-   Dynamically limits process count based on fragment file size to prevent OOM
-   Eliminated redundant double-processing of fragment data, reducing peak memory
-   Stream 500K record chunks on-demand instead of pre-allocating arrays for 200M+ records, preventing memory exhaustion
-   Added missing TileDB consolidation + vacuum for ATAC coverage arrays, reducing multiple fragments to single fragment for optimal read performance

fix: ATAC processing memory optimization VC-3630

---

.happy/terraform/modules/sfn/main.tf

https://czi.atlassian.net/browse/VC-3818
previously, we were not retrying if `ValidateAnndata`, `ValidateAtac`, or `Cxg` failed with `States.TaskFailed`. we would only retry if it failed with `States.Timeout` or some sort of specific AWS issue (and honestly not even 100% sure if those were caught)
n/a

feat: increase to 1 retry for States.TaskFailed

---

backend/layers/processing/process_cxg.py
tests/unit/processing/test_processing.py

- Remove old cxg files from folder on reprocess
- Modified `process_cxg` method to accept is_reprocess parameter
- Added `delete_existing_cxg_files` method that uses the existing delete_prefix functionality from S3Provider
- Updated `copy_cxg_files_to_cxg_bucket` method to accept a `clear_existing` parameter
- Passed the `is_reprocess` flag through the call chain
- Unit test coverage for above
- Unit tests should all pass for processing
- Step function to be tested in staging, prior to deployment

fix: Delete old cxg files on is_reprocess

---

.happy/terraform/modules/batch/main.tf

- Some multiome datasets are raising OOM during processing when fragment is over 40GB. Bump up resources for cxg sfn to be in par with validate atac sfn resources.
- Changed sfn to 64GB 8vCPU

fix: Update resources for cxg

---

backend/layers/processing/process_validate_atac.py
backend/layers/thirdparty/schema_validator_provider.py
tests/functional/backend/corpora/test_api.py
tests/functional/backend/utils.py
tests/unit/processing/test_process_validate_atac.py

- The test was existing early because we were checking the status of the old dataset version. Now we retrieve the dataset version after submitting the manifest which will be the new version if the dataset existed previously. 
- When deduplicating a fragment, the old file was not being replaced with the new file. This lead to error where the file read was empty. Now we are using the deduplicated file directly and not renaming. This was error we were getting.
```{"levelname": "ERROR", "asctime": "2025-09-10T16:14:37.010Z", "name": "cellxgene_schema.atac_seq", "message": "Error Parsing the fragment file. Check that columns match schema definition. Error: Empty CSV file", "lineno": 218, "pathname": "/opt/venv/lib/python3.10/site-packages/cellxgene_schema/atac_seq.py", "exc_info": "Traceback …
```

fix: get the dataset version after submitting manifest
